/**
 * Kontovia Abo-Seite: Wörterbuch Englisch.
 *
 * Die Seite nutzt dieselbe Übersetzungsmaschine wie die App (lib/sprache.js);
 * hier steht nur der Text der Seite: der feste Text aus index.html, die Texte
 * aus config.json (Tarife, Vergleich) und Beispiele, die abo.js setzt.
 * Schlüssel ist der deutsche Text, {0} {1} stehen für eingebettete Elemente.
 * Die Prüfung `webfassung` verlangt für jeden Text der Seite einen Eintrag.
 */

export default {
  // Kopf, Seitentitel
  "Kontovia Preise: Buchhaltung, die bei Ihnen bleibt": "Kontovia pricing: bookkeeping that stays with you",
  "Zum Inhalt": "Skip to content",
  "Testbetrieb": "Test mode",
  "Kontovia ist noch in Entwicklung. Tarife und Preise sind vorläufig, es wird nichts abgerechnet. Keine Haftung und keine Gewährleistung.": "Kontovia is still in development. Plans and prices are provisional and nothing is billed. No liability and no warranty.",
  "Funktionen": "Features",
  "Sicherheit": "Security",
  "Preise": "Pricing",
  "Fragen": "FAQ",
  "Öffnen": "Open",
  "Kostenlos starten": "Start for free",
  "Seitenbereiche": "Page sections",
  "Kontovia, zum Seitenanfang": "Kontovia, back to top",

  // Held
  "Neu": "New",
  "Assistent direkt auf Ihrem Gerät": "Assistant right on your device",
  "Buchhaltung,": "Bookkeeping",
  "die": "that",
  "bei": "stays",
  "Ihnen": "with you.",
  "bleibt.": "",
  "Rechnungen, Belege und Steuer an einem Ort. Kontovia arbeitet auf Ihrem Gerät, verschlüsselt alles mit Ihrem Passwort und funktioniert auch ohne Internet.": "Invoices, receipts and tax in one place. Kontovia works on your device, encrypts everything with your password and works without internet too.",
  "Preise ansehen": "See pricing",
  "Ohne Anmeldung": "No sign-up",
  "Ohne Kreditkarte": "No credit card",
  "Daten jederzeit exportierbar": "Data exportable at any time",

  // Nachbau der Übersicht
  "Strg K": "Ctrl K",
  "Strg J": "Ctrl J",
  "Alle Funktionen vergleichen": "Compare all features",
  "RE-2026-038": "INV-2026-038",
  "RE-2026-033": "INV-2026-033",
  "Suchen": "Search",
  "Neue Buchung": "New transaction",
  "Übersicht": "Overview",
  "Buchungen": "Transactions",
  "Kontoauszug": "Bank statement",
  "Rechnungen": "Invoices",
  "Kalender": "Calendar",
  "Aufgaben": "Tasks",
  "Auswertungen": "Reports",
  "Import & Export": "Import & export",
  "Jahr 2026": "Year 2026",
  "Einnahmen": "Income",
  "Ausgaben": "Expenses",
  "Gewinn": "Profit",
  "Umsatzsteuer": "VAT",
  "Marge 78,8 %": "Margin 78.8 %",
  "bis 10.11.": "by 10 Nov",
  "Verlauf": "Trend",
  "Säulen": "Bars",
  "Linien": "Lines",
  "Offene Posten": "Open items",
  "Ihre Forderungen": "Your receivables",
  "Website-Relaunch": "Website relaunch",
  "Bildrechte": "Image rights",
  "Hochzeitsreportage": "Wedding photography",
  "38 Tage": "38 days",
  "25 Tage": "25 days",
  "21 Tage": "21 days",
  "E-Rechnung erstellt": "E-invoice created",
  "RE-2026-041 · XRechnung": "INV-2026-041 · XRechnung",
  "Verschlüsselt": "Encrypted",
  "nur auf diesem Gerät": "only on this device",
  "Zahlung erkannt": "Payment detected",
  "+ 1.190,00 € · Müller GmbH": "+ €1,190.00 · Müller GmbH",
  "Beispielzahlen": "Sample figures",

  // Formate
  "Unterstützte Formate": "Supported formats",
  "Spricht die Formate, die in Deutschland zählen": "Speaks the formats that matter in Germany",

  // Funktionen
  "Von der Rechnung bis zur Anlage EÜR.": "From the invoice to the annual tax form.",
  "Kontovia nimmt Ihnen die Routine ab und lässt Ihnen die Entscheidungen. Alles in einem Programm, das sich anfühlt wie eine gute App und nicht wie ein Formular.": "Kontovia takes the routine off your hands and leaves the decisions to you. Everything in one program that feels like a good app, not a form.",
  "Rechnung": "Invoice",
  "RE-2026-041": "INV-2026-041",
  "Fotoproduktion, 1 Tag": "Photo production, 1 day",
  "Gesamt inkl. 19 % USt": "Total incl. 19 % VAT",
  "E-Rechnung": "E-invoice",
  "Pflichtangaben vollständig": "All required details present",
  "XRechnung erzeugt": "XRechnung created",
  "ZUGFeRD im PDF": "ZUGFeRD in the PDF",
  "QR-Code zum Bezahlen": "QR code for payment",
  "Rechnungen, die einfach stimmen.": "Invoices that simply get it right.",
  "Gestalten Sie Ihre Rechnung direkt auf dem Blatt. Kontovia achtet auf alle Pflichtangaben, setzt den QR-Code zum Bezahlen und legt die E-Rechnung gleich mit bei.": "Design your invoice right on the page. Kontovia takes care of all required details, adds the QR code for payment and attaches the e-invoice too.",
  "Voranmeldung": "Advance return",
  "Oktober 2026": "October 2026",
  "Umsätze zu 19 %": "Sales at 19 %",
  "Vorsteuer": "Input VAT",
  "Zahllast": "Amount due",
  "ELSTER-Datei bereit": "ELSTER file ready",
  "Steuer ohne Rätselraten.": "Tax without the guesswork.",
  "Umsatzsteuer-Voranmeldung und Anlage EÜR, fertig zum Einlesen in Mein ELSTER.": "VAT advance return and annual profit statement, ready to load into Mein ELSTER.",
  "Müller GmbH": "Müller GmbH",
  "Rechnung bezahlt": "Invoice paid",
  "Cloud-Speicher": "Cloud storage",
  "Abo Oktober": "October subscription",
  "Software": "Software",
  "Bahnfahrt Köln": "Train trip to Cologne",
  "Fahrkarte": "Ticket",
  "Reisekosten?": "Travel costs?",
  "Kontoauszug rein, fertig gebucht.": "Statement in, booked in no time.",
  "Datei aus dem Onlinebanking einlesen. Kontovia erkennt bezahlte Rechnungen, Sie entscheiden, was gebucht wird.": "Load the file from your online banking. Kontovia recognises paid invoices, you decide what gets booked.",
  "Studio Nord": "Studio Nord",
  "Erinnerung": "Reminder",
  "1. Mahnung": "1st dunning letter",
  "Bezahlt": "Paid",
  "Tag 7": "Day 7",
  "Tag 21": "Day 21",
  "Tag 24": "Day 24",
  "Freundlich erinnern.": "A friendly nudge.",
  "Offene Posten im Blick, Erinnerung und Mahnungen mit Frist, höflich formuliert und rechtlich sauber.": "Open items at a glance, reminders and dunning letters with deadlines, politely worded and legally sound.",
  "Wie viel habe ich im September verdient?": "How much did I earn in September?",
  "Im September 8.265 € Gewinn, 1.140 € mehr als im August.": "In September you made €8,265 profit, €1,140 more than in August.",
  "Frage stellen": "Ask a question",
  "Fragen Sie Ihre Zahlen.": "Ask your numbers.",
  "Vorschau": "Preview",
  "Der Assistent rechnet auf Ihrem Gerät. Fragen und Antworten verlassen es nie.": "The assistant calculates on your device. Questions and answers never leave it.",
  "Finanzamt 2026.zip": "Tax office 2026.zip",
  "Alles beisammen, mit Anleitung": "Everything together, with instructions",
  "Bereit für Ihre Kanzlei.": "Ready for your accountant.",
  "DATEV, Excel, Datenträger für die Betriebsprüfung und ein Paket fürs Finanzamt. Ihre Daten gehören Ihnen.": "DATEV, Excel, a data carrier for tax audits and a package for the tax office. Your data belongs to you.",
  "November 2026": "November 2026",
  "Mo": "Mon",
  "Di": "Tue",
  "Mi": "Wed",
  "Do": "Thu",
  "Fr": "Fri",
  "Sa": "Sat",
  "So": "Sun",
  "Umsatzsteuer Oktober": "VAT October",
  "RE-2026-041 fällig": "INV-2026-041 due",
  "Termin Studio Nord": "Appointment Studio Nord",
  "Fristen, die Sie nicht verpassen.": "Deadlines you won't miss.",
  "Steuertermine, Fälligkeiten und Aufgaben in einem Kalender, auf Wunsch abgeglichen mit Google Kalender.": "Tax dates, due dates and tasks in one calendar, synced with Google Calendar if you like.",
  "Und vieles mehr": "And much more",
  "Wiederkehrende Buchungen": "Recurring transactions",
  "Anlagen und Abschreibungen": "Assets and depreciation",
  "Journal nach GoBD": "GoBD-compliant journal",
  "Benutzer mit Rollen": "Users with roles",
  "Private Buchungen ausblenden": "Hide private transactions",
  "Suche über alles": "Search across everything",
  "Zweites Gerät per QR-Code": "Second device via QR code",
  "Jahresvergleich": "Year-over-year comparison",
  "Belege per Ziehen": "Drag and drop receipts",
  "Zusammenfassende Meldung": "EC Sales List",
  "Tastenkürzel": "Keyboard shortcuts",
  "Hell und Dunkel": "Light and dark",

  // Sicherheit
  "Ihre Zahlen gehen niemanden etwas an.": "Your numbers are nobody else's business.",
  "Viele Programme speichern Ihre Buchhaltung lesbar auf ihren Servern. Kontovia verschlüsselt alles auf Ihrem Gerät, bevor irgendetwas es verlässt. Ohne Ihren Schlüssel sind die Daten nur Zeichensalat.": "Many programs store your books in readable form on their servers. Kontovia encrypts everything on your device before anything leaves it. Without your key the data is just gibberish.",
  "Auf Ihrem Gerät": "On your device",
  "Rechnung RE-2026-041": "Invoice INV-2026-041",
  "Müller GmbH, Köln": "Müller GmbH, Cologne",
  "Fällig am 16.11.2026": "Due on 16 Nov 2026",
  "In der Cloud": "In the cloud",
  "Verschlüsselt mit Ihrem Passwort": "Encrypted with your password",
  "Jeder Eintrag und jeder Beleg. Den Schlüssel kennt nur Ihr Gerät.": "Every entry and every receipt. Only your device knows the key.",
  "Funktioniert offline": "Works offline",
  "Im Zug, im Keller, im Funkloch. Internet brauchen Sie nur zum Abgleichen und Senden.": "On the train, in the basement, in a dead zone. You only need the internet to sync and send.",
  "Sicherung in der EU": "Backup in the EU",
  "Auf Wunsch eine verschlüsselte Sicherung, gespeichert in der Europäischen Union.": "An encrypted backup on request, stored in the European Union.",
  "Lückenlos nach GoBD": "Complete under GoBD",
  "Jede Änderung steht im Journal. Festgeschriebene Zeiträume bleiben, wie sie sind.": "Every change is in the journal. Locked periods stay as they are.",
  "automatische Prüfungen vor jeder neuen Version": "automatic checks before every new version",
  "Werbung, Tracking oder Datenhandel": "ads, tracking or data trading",
  "Tage Standard, Pro und Max gratis testen": "days to try Standard, Pro and Max for free",

  // Preise
  "Klein anfangen. Mitwachsen.": "Start small. Grow along.",
  "Kostenlos starten, ganz ohne Anmeldung. Standard, Pro und Max {0} Tage gratis testen.": "Start for free, no sign-up at all. Try Standard, Pro and Max free for {0} days.",
  "Abrechnung": "Billing",
  "Monatlich": "Monthly",
  "Jährlich": "Yearly",
  "Alles auf dieser Seite ist vorläufig. Die Tarife lassen sich noch nicht buchen, Preise und Leistungen können sich bis zum Start ändern, und es wird nichts abgerechnet. Kontovia ist in Entwicklung: Es gibt keine Haftung und keine Gewährleistung für Funktion und Ergebnisse. Bitte sichern Sie Ihre Daten regelmäßig.": "Everything on this page is provisional. The plans cannot be booked yet, prices and features may change before launch, and nothing is billed. Kontovia is in development: there is no liability and no warranty for function or results. Please back up your data regularly.",
  "Für die Preisübersicht wird JavaScript gebraucht.": "JavaScript is needed for the price overview.",

  // Anmelden
  "Lizenz holen": "Get a licence",
  "In zwei Minuten startklar.": "Ready in two minutes.",
  "Tarif wählen": "Choose a plan",
  "Wechseln geht jederzeit, nach oben wie nach unten.": "You can switch at any time, up or down.",
  "Angaben eintragen": "Enter your details",
  "Nur Name und E-Mail-Adresse.": "Just your name and email address.",
  "Loslegen": "Get started",
  "Programm öffnen und Buchhaltung einrichten.": "Open the program and set up your bookkeeping.",
  "Ihre Buchhaltungsdaten gehen dabei nie an uns. Wir erfahren nur, wer eine Lizenz hat.": "Your bookkeeping data never reaches us. We only learn who has a licence.",
  "Erst einmal nur schauen? Für den kostenlosen Tarif brauchen Sie nichts davon.": "Just want to look around? You need none of this for the free plan.",
  "Kontovia direkt öffnen": "Open Kontovia right away",
  "Tarif": "Plan",
  "Name": "Name",
  "E-Mail-Adresse": "Email address",
  "Firma": "Company",
  "(freiwillig)": "(optional)",
  "Ich habe die {0} und die {1} gelesen und bin einverstanden.": "I have read the {0} and the {1} and agree.",
  "Nutzungsbedingungen": "terms of use",
  "Datenschutzhinweise": "privacy notice",
  "Vormerken": "Pre-register",

  // Laden
  "Programm laden": "Get the program",
  "Auf jedem Gerät zu Hause.": "At home on every device.",
  "Kontovia läuft im Browser und lässt sich wie eine normale App installieren. Nichts Schweres zum Herunterladen, Updates nur, wenn Sie es wollen.": "Kontovia runs in the browser and can be installed like a normal app. Nothing heavy to download, updates only when you want them.",
  "Windows, Mac und Linux": "Windows, Mac and Linux",
  "Mit Chrome oder Edge auf „Installieren“ klicken. Kontovia bekommt ein eigenes Fenster und ein Symbol auf dem Desktop.": "In Chrome or Edge, click “Install”. Kontovia gets its own window and an icon on the desktop.",
  "Auf diesem Gerät installieren": "Install on this device",
  "Android": "Android",
  "In Chrome öffnen, oben rechts das Menü antippen und „App installieren“ wählen.": "Open in Chrome, tap the menu at the top right and choose “Install app”.",
  "Kontovia öffnen": "Open Kontovia",
  "iPhone und iPad": "iPhone and iPad",
  "In Safari öffnen, auf „Teilen“ tippen und „Zum Home-Bildschirm“ wählen.": "Open in Safari, tap “Share” and choose “Add to Home Screen”.",

  // Fragen
  "Gut zu wissen.": "Good to know.",
  "Noch etwas offen? Schreiben Sie uns, die Adresse steht im {0}.": "Anything else? Write to us, the address is in the {0}.",
  "Impressum": "legal notice",
  "Kann ich Kontovia schon im Alltag nutzen?": "Can I already use Kontovia day to day?",
  "Kontovia ist im Testbetrieb. Sie können alles ausprobieren, es gibt aber noch keine Haftung und keine Gewährleistung, und Tarife lassen sich noch nicht buchen. Prüfen Sie Ergebnisse, bevor Sie sie ans Finanzamt geben, und sichern Sie Ihre Daten regelmäßig.": "Kontovia is in test mode. You can try everything, but there is no liability and no warranty yet, and plans cannot be booked yet. Check the results before you hand them to the tax office, and back up your data regularly.",
  "Was kann der kostenlose Tarif?": "What does the free plan include?",
  "Buchungen und Belege ohne Grenze, fünf Rechnungen im Monat samt E-Rechnung, die Übersicht und den Export als CSV und Excel. Er läuft auf einem Gerät und braucht keine Anmeldung. Für Umsatzsteuer, Anlage EÜR und Cloud-Sicherung wechseln Sie zu Standard.": "Unlimited transactions and receipts, five invoices a month including e-invoice, the overview and export as CSV and Excel. It runs on one device and needs no sign-up. For VAT, the annual profit statement and cloud backup, switch to Standard.",
  "Wo liegen meine Daten?": "Where is my data?",
  "Auf Ihrem Gerät, verschlüsselt mit Ihrem Passwort. Ab Standard können Sie zusätzlich eine verschlüsselte Sicherung in der Cloud anlegen und mehrere Geräte abgleichen. Die Cloud liegt in der EU und bekommt nur verschlüsselte Daten.": "On your device, encrypted with your password. From Standard you can also create an encrypted backup in the cloud and sync several devices. The cloud is in the EU and only ever receives encrypted data.",
  "Brauche ich Internet?": "Do I need internet?",
  "Nur zum Installieren, zum Abgleich zwischen Geräten und für den E-Mail-Versand. Alles andere funktioniert auch offline.": "Only to install, to sync between devices and to send email. Everything else also works offline.",
  "Muss ich E-Rechnungen schreiben können?": "Do I need to be able to write e-invoices?",
  "Seit 2025 müssen Unternehmen in Deutschland E-Rechnungen empfangen können. Ausstellen müssen sie größere Betriebe ab 2027, die übrigen ab 2028 (Kleinunternehmer ausgenommen). Kontovia kann beides, schon im kostenlosen Tarif.": "Since 2025, businesses in Germany must be able to receive e-invoices. Larger businesses must issue them from 2027, the rest from 2028 (small businesses exempt). Kontovia can do both, even in the free plan.",
  "Kann ich den Tarif wechseln oder kündigen?": "Can I change or cancel my plan?",
  "Ja, jederzeit. Monatliche Tarife enden zum Ende des bezahlten Monats, Jahrestarife zum Ende des bezahlten Jahres. Ihre Daten bleiben bei Ihnen und lassen sich vorher exportieren.": "Yes, at any time. Monthly plans end at the end of the paid month, yearly plans at the end of the paid year. Your data stays with you and can be exported beforehand.",
  "Was passiert nach dem Test?": "What happens after the trial?",
  "Sie entscheiden: Tarif behalten oder kostenlos weitermachen. Es wird nichts abgebucht, solange Sie keine Zahlungsart hinterlegt haben, und Ihre Daten bleiben in jedem Fall bei Ihnen.": "You decide: keep the plan or carry on for free. Nothing is charged as long as you have not added a payment method, and your data stays with you in any case.",
  "Ersetzt Kontovia meine Steuerberatung?": "Does Kontovia replace my tax adviser?",
  "Nein. Kontovia bereitet Ihre Zahlen sauber auf und gibt sie in gängigen Formaten weiter, auch an DATEV. Steuerliche Beratung bleibt Sache Ihrer Beraterin oder Ihres Beraters.": "No. Kontovia prepares your figures cleanly and passes them on in common formats, including DATEV. Tax advice remains a matter for your adviser.",

  // Schluss, Fuß
  "Eine Buchhaltung, die Ihnen gehört.": "Bookkeeping that belongs to you.",
  "In einer Minute eingerichtet. Kostenlos, solange Sie wollen.": "Set up in a minute. Free for as long as you like.",
  "Tarife vergleichen": "Compare plans",
  "Buchhaltung, die auf Ihrem Gerät bleibt.": "Bookkeeping that stays on your device.",
  "Programm": "Program",
  "Installieren": "Install",
  "Rechtliches": "Legal",
  "Datenschutz": "Privacy",
  "Testbetrieb: Kontovia ist in Entwicklung. Alle Angaben auf dieser Seite sind vorläufig, ohne Haftung und ohne Gewährleistung.": "Test mode: Kontovia is in development. All information on this page is provisional, without liability and without warranty.",

  // config.json: Tarife
  "Kostenlos": "Free",
  "Standard": "Standard",
  "Pro": "Pro",
  "Max": "Max",
  "Preise je Betrieb und Monat, inklusive gesetzlicher Umsatzsteuer.": "Prices per business and month, including statutory VAT.",
  "Zum Kennenlernen und für den Nebenerwerb": "To get to know it and for side businesses",
  "Für Selbstständige und Freiberufler": "For self-employed people and freelancers",
  "Für Betriebe mit vielen Kunden": "For businesses with many customers",
  "Für Teams und mehrere Firmen": "For teams and several companies",
  "Alles aus Kostenlos, dazu:": "Everything in Free, plus:",
  "Alles aus Standard, dazu:": "Everything in Standard, plus:",
  "Alles aus Pro, dazu:": "Everything in Pro, plus:",
  "Einnahmen, Ausgaben und Belege ohne Grenze": "Unlimited income, expenses and receipts",
  "5 Rechnungen im Monat, auch als E-Rechnung": "5 invoices a month, also as e-invoice",
  "E-Rechnungen empfangen und lesen": "Receive and read e-invoices",
  "Übersicht, Gewinn und Verlust": "Overview, profit and loss",
  "Export als CSV und Excel": "Export as CSV and Excel",
  "Ein Gerät, verschlüsselt und offline": "One device, encrypted and offline",
  "Unbegrenzt Rechnungen mit eigenem Logo": "Unlimited invoices with your own logo",
  "Umsatzsteuer-Voranmeldung und Anlage EÜR": "VAT advance return and annual profit statement",
  "Kontoauszug einlesen": "Import bank statements",
  "Export für DATEV und das Finanzamt": "Export for DATEV and the tax office",
  "Cloud-Sicherung und zwei Geräte": "Cloud backup and two devices",
  "Mahnwesen mit Erinnerung und Mahnstufen": "Dunning with reminders and dunning levels",
  "Direkt aus Gmail oder Outlook senden": "Send directly from Gmail or Outlook",
  "Assistent auf dem Gerät (Vorschau)": "Assistant on your device (preview)",
  "Google Kalender abgleichen": "Sync Google Calendar",
  "3 Benutzer und 5 Geräte": "3 users and 5 devices",
  "10 Benutzer mit Rollen": "10 users with roles",
  "Bis zu 5 Firmen getrennt führen": "Keep up to 5 companies separate",
  "Unbegrenzt Geräte": "Unlimited devices",
  "Bevorzugte Hilfe per E-Mail": "Priority help by email",

  // config.json: Vergleich
  "Buchen und Belege": "Bookkeeping and receipts",
  "Einnahmen, Ausgaben und Belege": "Income, expenses and receipts",
  "Rechnungen schreiben": "Writing invoices",
  "E-Rechnung (XRechnung, ZUGFeRD)": "E-invoice (XRechnung, ZUGFeRD)",
  "Eigenes Logo und freie Gestaltung": "Your own logo and free design",
  "Produkte und Vorlagen": "Products and templates",
  "Mahnwesen mit Mahnstufen": "Dunning with dunning levels",
  "Steuer und Auswertung": "Tax and reports",
  "Journal und Festschreibung nach GoBD": "Journal and period locking under GoBD",
  "Umsatzsteuer-Voranmeldung als ELSTER-Datei": "VAT advance return as ELSTER file",
  "Anlage EÜR nach amtlichem Vordruck": "Annual profit statement on the official form",
  "Steuertermine und Jahresvergleich": "Tax dates and year-over-year comparison",
  "Zusammenfassende Meldung für EU-Kunden": "EC Sales List for EU customers",
  "Export und Sicherung": "Export and backup",
  "CSV und Excel": "CSV and Excel",
  "Sicherung als Datei": "Backup as a file",
  "DATEV für Ihre Kanzlei": "DATEV for your accountant",
  "Paket fürs Finanzamt": "Package for the tax office",
  "Verschlüsselte Cloud-Sicherung in der EU": "Encrypted cloud backup in the EU",
  "Datenträger für die Betriebsprüfung": "Data carrier for tax audits",
  "Geräte und Team": "Devices and team",
  "Geräte": "Devices",
  "Getrennte Firmen": "Separate companies",
  "Zweites Gerät per QR-Code koppeln": "Pair a second device via QR code",
  "Extras und Hilfe": "Extras and help",
  "Hilfe im Programm": "Help in the program",
  "Hilfe per E-Mail": "Help by email",
  "5 im Monat": "5 per month",
  "unbegrenzt": "unlimited",
  "bevorzugt": "priority"
}
