/** Wörterbuch Englisch, Teil t01. Quellen: app.js, lib/assistent.js, lib/assistentdeutung.js. */

export default {
  "Assistent": "Assistant",
  "Übersicht": "Overview",
  "Buchungen": "Transactions",
  "Kontoauszug": "Bank statement",
  "Kalender": "Calendar",
  "Aufgaben": "Tasks",
  "Rechnungen": "Invoices",
  "Auswertungen": "Reports",
  "Import & Export": "Import & export",
  "Stammdaten": "Master data",
  "Einstellungen": "Settings",
  "Hilfe": "Help",
  "Hell": "Light",
  "Dunkel": "Dark",
  "Auto": "Auto",
  "Wie das Betriebssystem": "Same as the operating system",
  "Erscheinungsbild": "Appearance",
  "Kontovia öffnet sich nur in einem eigenen Fenster": "Kontovia only opens in its own window",
  "Diese Seite wurde in eine andere Website eingebettet. Zum Schutz Ihrer Buchhaltung läuft Kontovia dort nicht.": "This page was embedded in another website. To protect your accounting, Kontovia does not run there.",
  "Kontovia öffnen": "Open Kontovia",
  "Anmeldung bei Google": "Google sign-in",
  "Abgemeldet": "Signed out",
  "Kontovia {0} ist installiert": "Kontovia {0} is installed",
  "Sie werden gleich angemeldet.": "You will be signed in shortly.",
  "Ihr Konto": "Your account",
  "Bei Google angemeldet als {0}. Entsperren Sie Kontovia, um die Verbindung zu speichern.": "Signed in to Google as {0}. Unlock Kontovia to save the connection.",
  "Kontovia wurde aktualisiert. Bitte melden Sie sich dieses eine Mal mit Ihrem Passwort an.": "Kontovia has been updated. Please sign in with your password this one time.",
  "Sie sind weiterhin angemeldet.": "You are still signed in.",
  "Hier klicken für alle Neuigkeiten.": "Click here for all news.",
  "Aktualisierung abgeschlossen: Version": "Update complete: version",
  "Neu in Kontovia": "New in Kontovia",
  "zu kurz": "too short",
  "sehr stark": "very strong",
  "vierteljährlich": "quarterly",
  "Buchhaltung in einem Ordner?": "Accounting in a folder?",
  "Haben Sie Kontovia unter Windows oder schon in einem Ordner auf diesem Gerät benutzt? Öffnen Sie diesen Ordner; Kontovia arbeitet dann direkt darin.": "Have you used Kontovia on Windows or already in a folder on this device? Open that folder; Kontovia then works directly in it.",
  "Ordner öffnen": "Open folder",
  "Dieses Google-Konto ist schon da": "This Google account is already here",
  "Es gehört auf diesem Gerät bereits zu „{0}“. Wechseln Sie zu diesem Konto, statt es ein zweites Mal anzulegen.": "On this device it already belongs to “{0}”. Switch to that account instead of creating it a second time.",
  "Google-Konto": "Google account",
  "Angemeldet als": "Signed in as",
  "Ihre Buchhaltung wird nach dem Anlegen verschlüsselt in Ihrem Konto gesichert und lässt sich auf weiteren Geräten laden.": "After it is created, your accounting is backed up encrypted in your account and can be loaded on other devices.",
  "Abmelden": "Sign out",
  "Weiter zu Google …": "Continue to Google …",
  "Warte auf die Anmeldung …": "Waiting for sign-in …",
  "Nach der Anmeldung kommen Sie hierher zurück.": "After signing in you will come back here.",
  "Geben Sie den angezeigten Code bei Google ein.": "Enter the code shown at Google.",
  "Abbrechen": "Cancel",
  "Melden Sie sich jetzt mit Ihrem Google-Konto an. Danach geht es weiter.": "Now sign in with your Google account. Then you can continue.",
  "Der QR-Code ist angekommen.": "The QR code has arrived.",
  "Klappt nicht? Mit Code anmelden": "Not working? Sign in with a code",
  "Kontovia schon auf einem anderen Gerät?": "Already using Kontovia on another device?",
  "Mit Google anmelden und Ihre Buchhaltung aus der Cloud laden, oder eine neue gleich verschlüsselt in Ihrem Konto sichern. Das geht auch später in den Einstellungen. Ein mit Google verbundenes Gerät bestätigt alle 30 Tage von selbst, dass das Konto noch zugelassen ist; dabei wird nur gelesen.": "Sign in with Google and load your accounting from the cloud, or back up a new one encrypted in your account right away. You can also do this later in the settings. A device connected to Google confirms by itself every 30 days that the account is still approved; this only reads.",
  "Mit Google anmelden": "Sign in with Google",
  "Mit Google angemeldet": "Signed in with Google",
  "Anmeldung fehlgeschlagen": "Sign-in failed",
  "Weiteres Konto hinzufügen": "Add another account",
  "Willkommen bei Kontovia": "Welcome to Kontovia",
  "Jedes Konto hat sein eigenes Passwort und seine eigene Buchhaltung. Die bisherigen Konten bleiben, wie sie sind.": "Each account has its own password and its own accounting. Your existing accounts stay as they are.",
  "Ihre Buchhaltung bleibt auf diesem Gerät, verschlüsselt mit Ihrem Passwort. Es gibt kein Benutzerkonto beim Hersteller und keine Telemetrie; Ihre Buchhaltung verlässt das Gerät nur, wenn Sie den Cloud-Abgleich einschalten. Zuerst ein paar Angaben zu Ihrem Betrieb. Sie lassen sich später ändern.": "Your accounting stays on this device, encrypted with your password. There is no user account with the vendor and no telemetry; your accounting only leaves the device if you turn on cloud sync. First, a few details about your business. You can change them later.",
  "Firma / Name des Betriebs": "Company / business name",
  "Inhaber / Ansprechpartner": "Owner / contact person",
  "Straße und Hausnummer": "Street and number",
  "Ort": "City",
  "Steuernummer": "Tax number",
  "Umsatzsteuer-Identifikationsnummer": "VAT identification number",
  "Zuständiges Finanzamt": "Responsible tax office",
  "jährlich": "yearly",
  "Steuerliche Einstellungen": "Tax settings",
  "Diese Einstellungen bestimmen, wie Kontovia rechnet. Wenn Sie unsicher sind: Die Voreinstellung passt für die meisten Selbstständigen und kleinen Betriebe. Die Anlage EÜR folgt immer dem Zahlungsfluss.": "These settings determine how Kontovia calculates. If you are unsure: the defaults suit most self-employed people and small businesses. The Anlage EÜR always follows cash flow.",
  "Umsatzsteuer": "VAT",
  "Regelbesteuerung (ich weise Umsatzsteuer aus)": "Standard taxation (I charge VAT)",
  "Kleinunternehmer nach § 19 UStG (keine Umsatzsteuer)": "Small business under § 19 UStG (no VAT)",
  "Als Kleinunternehmer rechnet Kontovia durchgehend mit Bruttobeträgen und blendet alle Umsatzsteuerfelder aus.": "As a small business, Kontovia always works with gross amounts and hides all VAT fields.",
  "Umsatzsteuer berechnen nach": "Calculate VAT by",
  "Zahlungseingang (Ist-Versteuerung, § 20 UStG, auf Antrag)": "Payment received (cash basis, § 20 UStG, on application)",
  "Rechnungsdatum (Soll-Versteuerung, gesetzlicher Regelfall)": "Invoice date (accrual basis, the statutory default)",
  "Steht in Ihrem Steuerbescheid oder im Fragebogen zur steuerlichen Erfassung. Selbstständige und Betriebe bis 800.000 € Umsatz bekommen die Ist-Versteuerung meist auf Antrag. Die Anlage EÜR rechnet in beiden Fällen nach Zahlungsfluss (§ 11 EStG).": "This is stated in your tax assessment or in the tax registration questionnaire. Self-employed people and businesses with up to €800,000 turnover usually get cash basis on application. The Anlage EÜR uses cash flow in both cases (§ 11 EStG).",
  "Voreingestellter Steuersatz": "Default tax rate",
  "Voranmeldungszeitraum": "VAT return period",
  "Kontenrahmen für den DATEV-Export": "Chart of accounts for the DATEV export",
  "SKR03 (Prozessgliederung, am weitesten verbreitet)": "SKR03 (process structure, most common)",
  "SKR04 (Abschlussgliederung)": "SKR04 (financial statement structure)",
  "Passwort festlegen": "Set a password",
  "Ihre gesamte Buchhaltung wird mit diesem Passwort verschlüsselt. Ohne das Passwort sind die Daten unwiederbringlich verloren. Es gibt keine Hintertür und keine Zurücksetzfunktion.": "Your entire accounting is encrypted with this password. Without it the data is lost forever. There is no back door and no reset function.",
  "Passwort": "Password",
  "Mindestens 10 Zeichen. Eine Folge aus vier zufälligen Wörtern ist leichter zu merken und sicherer als „Sommer2024!“.": "At least 10 characters. A sequence of four random words is easier to remember and safer than “Summer2024!”.",
  "Passwort wiederholen": "Repeat password",
  "Ein Passwortmanager oder ein Zettel im Safe ist besser, als sich aufs Gedächtnis zu verlassen. Legen Sie außerdem regelmäßig Vollsicherungen an (Einstellungen → Sicherung und Speicherort).": "A password manager or a note in a safe is better than relying on memory. Also create full backups regularly (Settings → Backup and storage location).",
  "Bitte notieren Sie das Passwort an einem sicheren Ort.": "Please write the password down in a safe place.",
  "Soll Kontovia nach neuen Programmversionen suchen?": "Should Kontovia check for new versions?",
  "Ja, beim Start und alle sechs Stunden": "Yes, at startup and every six hours",
  "Nein": "No",
  "Dafür ruft Kontovia eine kleine Versionsdatei ab; der Betreiber des Servers sieht dabei Ihre IP-Adresse, sonst nichts. Installiert wird nur nach Ihrer Bestätigung. Ohne Antwort fragt Kontovia beim ersten Entsperren noch einmal. Jederzeit unter Einstellungen → Programmaktualisierung änderbar.": "For this, Kontovia fetches a small version file; the server operator sees your IP address and nothing else. Updates are only installed after you confirm. Without an answer, Kontovia asks again at the first unlock. You can change this at any time under Settings → Program updates.",
  "Ich habe die {0} und die {1} gelesen und bin einverstanden.": "I have read the {0} and the {1} and agree.",
  "Nutzungsbedingungen": "Terms of use",
  "Datenschutzhinweise": "Privacy notice",
  "Zurück zu „{0}“": "Back to “{0}”",
  "Zurück": "Back",
  "Tresor anlegen": "Create vault",
  "Weiter": "Next",
  "Zurück nicht möglich": "Going back is not possible",
  "Einschätzung:": "Rating:",
  "Mindestens 10 Zeichen.": "At least 10 characters.",
  "Das Passwort muss mindestens 10 Zeichen haben.": "The password must have at least 10 characters.",
  "Die beiden Eingaben stimmen nicht überein.": "The two entries do not match.",
  "Bitte stimmen Sie den Nutzungsbedingungen und den Datenschutzhinweisen zu, um fortzufahren.": "Please agree to the terms of use and the privacy notice to continue.",
  "Verschlüssele …": "Encrypting …",
  "Tresor angelegt": "Vault created",
  "Ihre Daten liegen verschlüsselt in": "Your data is stored encrypted in",
  "Ihrem Benutzerordner": "your user folder",
  "und werden gleich in Ihrem Google-Konto gesichert.": "and will be backed up to your Google account shortly.",
  ", Stand": ", as of",
  "Ohne Passwort laden (Anmeldung bei Google genügt)": "Load without password (Google sign-in is enough)",
  ", außer mit „Ohne Passwort laden“ oben: Für dieses Google-Konto ist „Mit Google entsperren“ eingeschaltet": ", except with “Load without password” above: “Unlock with Google” is turned on for this Google account",
  ", weder von Kontovia noch von Google": ", neither by Kontovia nor by Google",
  "Buchhaltung aus der Cloud laden": "Load accounting from the cloud",
  "Angemeldet als {0}. In Ihrem Konto liegt eine Kontovia-Buchhaltung{1}{2}. Sie ist mit dem Passwort verschlüsselt, das Sie auf Ihrem anderen Gerät festgelegt haben.": "Signed in as {0}. Your account contains a Kontovia accounting{1}{2}. It is encrypted with the password you set on your other device.",
  "Mit QR-Code vom anderen Gerät öffnen": "Open with QR code from the other device",
  "Scannen Sie den QR-Code auf Ihrem anderen Gerät: unter Einstellungen, Sicherheit, „Neues Gerät hinzufügen“. Der Code allein und Ihr Google-Konto allein genügen nicht, beides zusammen öffnet Ihre Buchhaltung.": "Scan the QR code on your other device: under Settings, Security, “Add new device”. The code alone or your Google account alone is not enough; together they open your accounting.",
  "oder mit Passwort": "or with password",
  "Passwort der Buchhaltung": "Accounting password",
  "Laden und entsperren": "Load and unlock",
  "Die Belege kommen danach im Hintergrund nach.": "Receipts will follow in the background.",
  "Passwort vergessen?": "Forgot your password?",
  "Ohne das Passwort lässt sich die Buchhaltung nicht öffnen{0}. Ist sie auf einem anderen Gerät noch entsperrt, ändern Sie dort unter {1} das Passwort und gleichen ab; danach gilt hier das neue.": "Without the password the accounting cannot be opened{0}. If it is still unlocked on another device, change the password there under {1} and sync; after that the new one applies here.",
  "Einstellungen → Sicherheit": "Settings → Security",
  "Stattdessen neu anfangen": "Start fresh instead",
  "Buchhaltung geladen": "Accounting loaded",
  "Dieses Gerät ist jetzt mit Ihrem Google-Konto verbunden. Belege werden im Hintergrund geholt.": "This device is now connected to your Google account. Receipts are being fetched in the background.",
  "Lade und entschlüssele …": "Loading and decrypting …",
  "Das Passwort passt nicht zu dieser Buchhaltung.": "The password does not match this accounting.",
  "Neue Buchhaltung": "New accounting",
  "Die Buchhaltung in Ihrem Google-Konto bleibt unberührt. Wenn Sie dieses Gerät später in den Einstellungen verbinden, fragt Kontovia, welche gelten soll.": "The accounting in your Google account stays untouched. If you connect this device later in the settings, Kontovia will ask which one should apply.",
  "Ordner nicht geöffnet": "Folder not opened",
  "Keine Buchhaltung gefunden": "No accounting found",
  "Im Ordner „{0}“ liegt keine Kontovia-Buchhaltung. Unter Windows liegt sie im Ordner {1}.": "The folder “{0}” contains no Kontovia accounting. On Windows it is in the folder {1}.",
  "Den gibt der Browser nicht direkt frei: Kopieren Sie ihn zum Beispiel in Ihre Dokumente und wählen Sie dann die Kopie.": "The browser does not grant access to it directly: copy it, for example to your documents, and then choose the copy.",
  "Die Buchhaltung im Ordner „{0}“ ist bereit. Entsperren Sie sie mit ihrem Passwort.": "The accounting in the folder “{0}” is ready. Unlock it with its password.",
  "Arbeitet Kontovia unter Windows mit demselben Ordner, öffnen Sie bitte nie beide gleichzeitig.": "If Kontovia on Windows works with the same folder, please never open both at the same time.",
  "Ordner nicht übernommen": "Folder not adopted",
  "Der Zugriff wurde abgelehnt. Ohne ihn kann Kontovia die Buchhaltung nicht öffnen. Erlauben Sie ihn, oder setzen Sie die Berechtigung in den Website-Einstellungen des Browsers zurück.": "Access was denied. Without it Kontovia cannot open the accounting. Allow it, or reset the permission in the browser's site settings.",
  "Zugriff auf Ihren Ordner": "Access to your folder",
  "Ihre Buchhaltung liegt im Ordner {0} auf diesem Gerät. Der Browser fragt nach einem Neustart, ob Kontovia wieder darauf zugreifen darf.": "Your accounting is in the folder {0} on this device. After a restart the browser asks whether Kontovia may access it again.",
  "Zugriff erlauben": "Allow access",
  "Wählen Sie im Browser „Bei jedem Besuch zulassen“, wenn er es anbietet. Dann entfällt die Frage künftig.": "Choose “Allow on every visit” in the browser if it is offered. Then you will not be asked again.",
  "Ordner verschoben oder anderen verwenden?": "Folder moved or use another one?",
  "Wurde der Ordner verschoben oder umbenannt, wählen Sie ihn neu aus.": "If the folder was moved or renamed, select it again.",
  "Ordner neu wählen": "Choose folder again",
  "Ordner nicht mehr verwenden": "Stop using folder",
  "Ohne Zugriff kann Kontovia die Buchhaltung nicht öffnen.": "Without access Kontovia cannot open the accounting.",
  "Buchhaltung nicht gefunden": "Accounting not found",
  "Kontovia speichert Ihre Buchhaltung im Ordner {0}, aber dort liegt sie nicht mehr. Wurde der Ordner verschoben, umbenannt oder geleert?": "Kontovia stores your accounting in the folder {0}, but it is no longer there. Was the folder moved, renamed or emptied?",
  "Ohne Ordner beginnt Kontovia mit dem leeren Speicher dieses Browsers. Dort lässt sich eine Vollsicherung einspielen oder die Buchhaltung aus der Cloud laden.": "Without a folder, Kontovia starts with this browser's empty storage. There you can restore a full backup or load the accounting from the cloud.",
  "Ordner": "Folder",
  "Ordner nicht mehr verwenden?": "Stop using the folder?",
  "Kontovia vergisst den Ordner „{0}“. Die Dateien darin bleiben unberührt; Sie können den Ordner später wieder öffnen.": "Kontovia forgets the folder “{0}”. The files in it stay untouched; you can open the folder again later.",
  "Danach startet Kontovia mit dem Speicher dieses Browsers.": "After that, Kontovia starts with this browser's storage.",
  "Nicht mehr verwenden": "Stop using",
  "Kontovia ist gesperrt": "Kontovia is locked",
  "Geben Sie Ihr Passwort ein, um die Buchhaltung zu entschlüsseln.": "Enter your password to decrypt the accounting.",
  "Entsperren": "Unlock",
  "Das Entschlüsseln dauert etwa eine Sekunde. Das bremst Angreifer, die Passwörter durchprobieren.": "Decrypting takes about a second. This slows down attackers who try out passwords.",
  "Ohne Passwort lässt sich der Tresor nicht öffnen, auch nicht vom Hersteller. Das schützt Ihre Buchhaltung, falls jemand die Datei in die Hände bekommt. Ausnahme: Sie haben „Mit Google entsperren“ eingeschaltet, dann genügt die Anmeldung bei Google.": "Without the password the vault cannot be opened, not even by the vendor. This protects your accounting if someone gets hold of the file. Exception: if you turned on “Unlock with Google”, signing in with Google is enough.",
  "Haben Sie eine {0}, deren Passwort Sie kennen: Unten auf {1} tippen, eine neue Buchhaltung anlegen und die Sicherung dort unter {2} einspielen. Das gesperrte Konto bleibt so lange erhalten, bis Sie es selbst entfernen.": "If you have a {0} whose password you know: tap {1} below, create a new accounting and restore the backup there under {2}. The locked account is kept until you remove it yourself.",
  "Vollsicherung (.kvbak)": "full backup (.kvbak)",
  "Konto hinzufügen": "Add account",
  "Einstellungen → Sicherung wiederherstellen": "Settings → Restore backup",
  "Die automatischen Sicherungen sind mit dem Tresorpasswort verschlüsselt, das zu ihrer Zeit galt.": "The automatic backups are encrypted with the vault password that applied at their time.",
  "Entschlüssele …": "Decrypting …",
  "Stornos korrigiert": "Reversals corrected",
  "EÜR-Zeilen umgestellt": "EÜR lines rearranged",
  "Sonderzeichen wiederhergestellt": "Special characters restored",
  "Ihre Buchhaltung liegt nur in diesem Browser": "Your accounting is only stored in this browser",
  "Verschieben Sie sie in einen Ordner, schalten": "Move it to a folder, turn on",
  "Schalten": "Turn on",
  "Den Speicher darf der Browser bei Platzmangel räumen. {0} Sie die Cloud-Sicherung ein oder legen Sie eine Vollsicherung an. Hier klicken.": "The browser may clear this storage when space runs low. {0} cloud backup or create a full backup. Click here.",
  "Hinweise der Schemapflege:": "Notes from data maintenance:",
  "Cloud-Automatik:": "Cloud automation:",
  "Verbinden nach Weiterleitung:": "Connecting after redirect:",
  "Rückkehr von Google Kalender:": "Returning from Google Calendar:",
  "Kalenderabgleich:": "Calendar sync:",
  "Wiederkehrende Buchungen:": "Recurring transactions:",
  "Nach neuen Versionen suchen?": "Check for new versions?",
  "Kontovia kann Sie darauf hinweisen, wenn eine neue Fassung vorliegt, und sie auf Wunsch direkt installieren. Sie müssen dann nichts im Internet suchen.": "Kontovia can let you know when a new version is available and install it directly if you wish. You then do not have to search the internet.",
  "Dafür wird beim Start und danach alle sechs Stunden eine kleine Versionsdatei abgerufen. Der Betreiber des Servers sieht dabei Ihre IP-Adresse. Angaben zu Ihrem Gerät oder Ihrer Buchhaltung werden nicht mitgesendet, und installiert wird nur nach Ihrer ausdrücklichen Bestätigung.": "For this, a small version file is fetched at startup and every six hours after that. The server operator sees your IP address. No details about your device or your accounting are sent, and updates are only installed after your explicit confirmation.",
  "Jederzeit änderbar unter {0}.": "You can change this at any time under {0}.",
  "Einstellungen → Programmaktualisierung": "Settings → Program updates",
  "Nein, danke": "No, thanks",
  "Ja, danach suchen": "Yes, check for them",
  "Version {0} ist verfügbar": "Version {0} is available",
  "Klicken Sie hier oder auf den Knopf links unten, um sie zu installieren.": "Click here or on the button at the bottom left to install it.",
  "Version {0} verfügbar": "Version {0} available",
  "Seitenleiste ausklappen": "Expand sidebar",
  "Seitenleiste einklappen": "Collapse sidebar",
  "Nur lesen": "Read only",
  "Mit Ihrer Rolle lassen sich keine Buchungen anlegen.": "Your role does not allow creating transactions.",
  "Neue Buchung": "New transaction",
  "Einnahme": "Income",
  "Geld, das Sie erhalten": "Money you receive",
  "Ausgabe": "Expense",
  "Geld, das Sie bezahlen": "Money you pay",
  "Aus Beleg": "From receipt",
  "Rechnung oder Quittung wählen": "Choose an invoice or receipt",
  "Konto wechseln oder hinzufügen": "Switch or add account",
  "Kontovia": "Kontovia",
  "Alles durchsuchen ({0})": "Search everything ({0})",
  "Suchen": "Search",
  "Assistent fragen ({0})": "Ask the assistant ({0})",
  "Hauptnavigation": "Main navigation",
  "Rückmeldung geben, auf Wunsch mit Bildschirmfoto": "Send feedback, with a screenshot if you like",
  "Feedback": "Feedback",
  "Sperren ({0}+L)": "Lock ({0}+L)",
  "Sperren": "Lock",
  "Hilfe zu diesem Bereich": "Help for this section",
  "Alles durchsuchen": "Search everything",
  "Assistent fragen": "Ask the assistant",
  "Cloud-Abgleich": "Cloud sync",
  "Abgleich abgeschlossen": "Sync complete",
  "Abgleich fehlgeschlagen": "Sync failed",
  "speichere …": "saving …",
  "Fehler:": "Error:",
  "ungespeicherte Änderungen": "unsaved changes",
  "Buchhaltung": "Accounting",
  "Buchungen · {0} Termine": "transactions · {0} appointments",
  "offene Aufgabe": "open task",
  "offene Aufgaben": "open tasks",
  "festgeschrieben bis": "locked until",
  "keine Festschreibung": "no period lock",
  "Cloud: Abgleich läuft …": "Cloud: syncing …",
  "Cloud-Sicherung einrichten": "Set up cloud backup",
  "Cloud: bitte neu anmelden": "Cloud: please sign in again",
  "Cloud:": "Cloud:",
  "Die Ansicht konnte nicht dargestellt werden:": "The view could not be displayed:",
  "Kontovia wurde wegen Inaktivität gesperrt.": "Kontovia was locked due to inactivity.",
  "Das Gerät war im Ruhezustand, deshalb wurde Kontovia gesperrt.": "The device was asleep, so Kontovia was locked.",
  "Der Bildschirm wurde gesperrt, deshalb wurde auch Kontovia gesperrt.": "The screen was locked, so Kontovia was locked too.",
  "Kontovia war einige Minuten im Hintergrund und wurde deshalb gesperrt.": "Kontovia was in the background for a few minutes and was therefore locked.",
  "Kontovia wurde in einem anderen Fenster geöffnet und hier gesperrt. Laden Sie diese Seite neu, um hier weiterzuarbeiten.": "Kontovia was opened in another window and locked here. Reload this page to continue working here.",
  "Die neue Fassung wird geladen …": "Loading the new version …",
  "Kontovia muss sich nach längerer Zeit einmal mit dem Internet verbinden, um zu prüfen, ob Ihr Konto noch zugelassen ist. Verbinden Sie das Gerät mit dem Internet und entsperren Sie noch einmal. Ihre Buchhaltung ist unverändert.": "After a longer time, Kontovia needs to connect to the internet once to check whether your account is still approved. Connect the device to the internet and unlock again. Your accounting is unchanged.",
  "Der Stand aus der Cloud ist übernommen. Entsperren Sie ihn mit dem Passwort, das auf Ihrem anderen Gerät gilt.": "The cloud version has been adopted. Unlock it with the password that applies on your other device.",
  "Die Sicherung gehörte zu einer anderen Buchhaltung und ist jetzt geladen. Entsperren Sie sie mit dem Passwort der Sicherung.": "The backup belonged to a different accounting and is now loaded. Unlock it with the backup's password.",
  "Ihre Daten werden für die neue Version vorbereitet.": "Your data is being prepared for the new version.",
  "Das geschieht einmal und dauert meist nur einen Moment. Bitte lassen Sie Kontovia so lange geöffnet.": "This happens once and usually only takes a moment. Please keep Kontovia open until then.",
  "Gespeichert": "Saved",
  "Suche nach neuer Version …": "Checking for a new version …",
  "Update-Prüfung fehlgeschlagen": "Update check failed",
  "Keine Update-Suche möglich": "Update check not possible",
  "In dieser Fassung ist keine Update-Adresse hinterlegt.": "No update address is set in this version.",
  "Update-Server nicht erreichbar": "Update server not reachable",
  "Keine neue Version": "No new version",
  "Sie verwenden bereits die neueste Fassung ({0}).": "You are already using the latest version ({0}).",
  "Über Kontovia": "About Kontovia",
  ": Buchhaltung, die auf Ihrem Rechner bleibt.": ": accounting that stays on your computer.",
  "Datenordner": "Data folder",
  "Verschlüsselung": "Encryption",
  "AES-256, der Schlüssel entsteht aus Ihrem Passwort": "AES-256, the key is derived from your password",
  "Kontovia ersetzt keine Steuerberatung. Die Zuordnungen zu EÜR-Zeilen, Kennzahlen und Konten sind Vorschläge, die Sie prüfen sollten.": "Kontovia does not replace tax advice. The assignments to EÜR lines, boxes and accounts are suggestions you should check.",
  "Neuigkeiten": "News",
  "Rechtliches und Lizenzen": "Legal and licenses",
  "Schließen": "Close",
  "Das habe ich nicht verstanden. Fragen Sie zum Beispiel „Was ist noch offen?“, „Umsatz im März“ oder „Finde Rechnung Müller“.": "I did not understand that. Ask, for example, “What is still open?”, “Revenue in March” or “Find invoice Müller”.",
  "[Geöffnet: {0}]": "[Open: {0}]",
  "Frage:": "Question:",
  "Antwort von Kontovia:": "Answer from Kontovia:",
  "({0}, id {1})": "({0}, id {1})",
  "Antworte jetzt kurz mit dem, was du hast, ohne weitere Werkzeuge.": "Answer briefly now with what you have, without further tools.",
  "Abgebrochen.": "Cancelled.",
  "Die Antwort des Modells enthielt Beträge, die nicht aus Ihren Buchungen stammen. Sie sehen deshalb nur die geprüften Werte.": "The model's answer contained amounts that do not come from your transactions. You therefore only see the verified values.",
  "gesamter Bestand": "all data",
  "Jahr": "Year",
  ". Quartal": ". quarter",
  "dieses Jahr": "this year",
  "Mahnungen": "Reminders",
  "Eingangsrechnungen": "Incoming invoices",
  "Rechnungsvorlagen": "Invoice templates",
  "Produkte": "Products",
  "Rechnungsgestaltung": "Invoice design",
  "Gewinn und Verlust": "Profit and loss",
  "Anlage EÜR": "Anlage EÜR",
  "Vermögen": "Assets",
  "Offene Posten": "Open items",
  "Kontostände": "Account balances",
  "Abschreibungen": "Depreciation",
  "Jahresvergleich": "Year comparison",
  "Daten übernehmen": "Import data",
  "Export": "Export",
  "Kunden und Lieferanten": "Customers and suppliers",
  "Kategorien": "Categories",
  "Zahlungskonten": "Payment accounts",
  "Anlagevermögen": "Fixed assets",
  "Wiederkehrende Buchungen": "Recurring transactions",
  "(netto|zzgl|zuzueglich|plus)|(netto|nettobetrag) (von |aus )?": "(netto|zzgl|zuzueglich|plus)|(netto|nettobetrag) (von |aus )?",
  "(brutto|inkl|inklusive)|(brutto|bruttobetrag) (von |aus )?": "(brutto|inkl|inklusive)|(brutto|bruttobetrag) (von |aus )?",
  "Termin": "Appointment",
  "Leistung": "Service",
  "letztes Jahr": "last year",
  "die letzten 12 Monate": "the last 12 months",
  "die nächsten 60 Tage": "the next 60 days",
};
