/** Wörterbuch Englisch, Teil t02. Quellen: lib/assistentdeutung.js, lib/assistentfenster.js, lib/assistentmodelle.js, lib/assistentwerkzeuge.js. */

export default {
  "dieses Quartal": "this quarter",
  "die nächsten 90 Tage": "the next 90 days",
  "dieser Monat": "this month",
  "die nächsten 14 Tage": "the next 14 days",
  "Was steht heute an?": "What's on today?",
  "Was ist noch offen?": "What is still open?",
  "Wie viel Umsatz hatte ich diesen Monat?": "How much revenue did I have this month?",
  "Wie viel Umsatzsteuer muss ich dieses Quartal zahlen?": "How much VAT do I have to pay this quarter?",
  "Wofür habe ich dieses Jahr am meisten ausgegeben?": "What did I spend the most on this year?",
  "Wie schreibe ich eine Rechnung?": "How do I write an invoice?",
  "Durchsucht den Bestand": "Searching your data",
  "Liest Buchungen": "Reading transactions",
  "Liest Rechnungen": "Reading invoices",
  "Rechnet Einnahmen und Ausgaben": "Calculating income and expenses",
  "Rechnet nach Kategorien": "Calculating by category",
  "Rechnet nach Kunden und Lieferanten": "Calculating by customer and supplier",
  "Vergleicht Zeiträume": "Comparing periods",
  "Rechnet die Umsatzsteuer": "Calculating VAT",
  "Prüft offene Posten": "Checking open items",
  "Liest Kontostände": "Reading account balances",
  "Liest den Kalender": "Reading the calendar",
  "Liest Aufgaben": "Reading tasks",
  "Sucht den Kontakt": "Looking up the contact",
  "Prüft Steuertermine": "Checking tax deadlines",
  "Rechnet": "Calculating",
  "Rechnet netto und brutto": "Calculating net and gross",
  "Öffnet einen Bereich": "Opening a section",
  "Öffnet einen Eintrag": "Opening an entry",
  "Bereitet eine Buchung vor": "Preparing a transaction",
  "Bereitet eine Aufgabe vor": "Preparing a task",
  "Bereitet einen Termin vor": "Preparing an appointment",
  "Bereitet einen Kontakt vor": "Preparing a contact",
  "Bereitet eine Rechnung vor": "Preparing an invoice",
  "Antwortet": "Answering",
  "Liest den Eintrag": "Reading the entry",
  "Sieht nach, was ansteht": "Checking what's coming up",
  "Rechnet Monat für Monat": "Calculating month by month",
  "Prüft das Jahr": "Checking the year",
  "Liest die Anlage EÜR": "Reading the Anlage EÜR",
  "Rechnet die Abschreibungen": "Calculating depreciation",
  "Prüft die Umsatzgrenzen": "Checking the turnover limits",
  "Sucht in der Hilfe": "Searching the help",
  "Sucht den offenen Posten": "Looking up the open item",
  "Bereitet eine Mahnung vor": "Preparing a reminder",
  "Der Grafikchip hat die Antwort abgebrochen und wurde vom Treiber neu gestartet. Das kommt vor, wenn eine Stufe das Gerät stark fordert.": "The graphics chip aborted the answer and was restarted by the driver. This can happen when a level puts heavy load on the device.",
  "Fragen Sie einfach noch einmal, die Stufe startet dann neu. Passiert das öfter, wählen Sie eine kleinere Stufe.": "Just ask again, the level will then restart. If this happens often, choose a smaller level.",
  "Der Assistent ist neu und wird noch erprobt.": "The assistant is new and still being tested.",
  "Test": "Test",
  "Läuft nur auf diesem Gerät": "Runs only on this device",
  "So funktioniert der Assistent": "How the assistant works",
  "Neues Gespräch": "New conversation",
  "Assistent schließen": "Close assistant",
  "Schließen (Esc)": "Close (Esc)",
  "Stufe wählen: wie viel der Assistent versteht": "Choose level: how much the assistant understands",
  "Denkweise wählen: schneller oder gründlicher": "Choose thinking style: faster or more thorough",
  "Wird vorbereitet …": "Preparing …",
  "Modell wird geladen": "Loading model",
  "Gespräch": "Conversation",
  "Fragen Sie etwas zu Ihrer Buchhaltung …": "Ask something about your accounting …",
  "Frage an den Assistenten": "Question for the assistant",
  "Senden": "Send",
  "Senden (Enter)": "Send (Enter)",
  "Der Assistent kann sich irren. Zahlen kommen immer aus Ihren Buchungen.": "The assistant can make mistakes. Figures always come from your transactions.",
  "Wie das funktioniert": "How this works",
  "Die Stufe Basis arbeitet mit festen Regeln und denkt nicht nach.": "The Basic level works with fixed rules and does not think.",
  "Feste Regeln": "Fixed rules",
  "Bereit": "Ready",
  "Auf dem Gerät": "On the device",
  "Stufe wählen": "Choose level",
  "sofort bereit": "ready immediately",
  "auf dem Gerät": "on the device",
  "Download": "Download",
  "nicht auf diesem Gerät": "not on this device",
  "Grafikchip freigeben": "Enable the graphics chip",
  "Schritt für Schritt für diesen Browser": "Step by step for this browser",
  "Stufe: wie viel der Assistent versteht": "Level: how much the assistant understands",
  "Denkweise": "Thinking style",
  "Bei Mini nicht möglich, wirkt wie Ausgewogen": "Not possible with Mini, works like Balanced",
  "Stufe {0} herunterladen?": "Download level {0}?",
  "Frei im Browser": "Free in the browser",
  "Der freie Speicher ist knapp. Der Download kann scheitern.": "Free storage is low. The download may fail.",
  "Entfernen Sie ein anderes Modell unter „So funktioniert der Assistent“ oder wählen Sie eine kleinere Stufe.": "Remove another model under “How the assistant works” or choose a smaller level.",
  "Im Browser ist nicht genug Speicher frei.": "There is not enough free storage in the browser.",
  "Tipp: am besten im WLAN laden.": "Tip: best loaded over Wi-Fi.",
  "Das Sprachmodell für die Stufe {0} wird {1} heruntergeladen und bleibt danach auf diesem Gerät. Ab dann arbeitet der Assistent auch ohne Internet.": "The language model for level {0} is downloaded {1} and then stays on this device. From then on the assistant also works without internet.",
  "Größe": "Size",
  "Speicher auf dem Grafikchip": "Memory on the graphics chip",
  "Quelle": "Source",
  "Hugging Face und GitHub, in genau dieser geprüften Fassung": "Hugging Face and GitHub, in exactly this verified version",
  "Geladen werden nur die Dateien des Modells. Der Anbieter sieht wie bei jedem Download Ihre IP-Adresse. Ihre Fragen und Ihre Buchhaltung bleiben auf dem Gerät.": "Only the model files are loaded. As with any download, the provider sees your IP address. Your questions and your accounting stay on the device.",
  "Ihre Daten werden dabei nicht gesendet.": "Your data is not sent.",
  "Herunterladen und starten": "Download and start",
  "Stufe {0} wird gestartet …": "Starting level {0} …",
  "Stufe {0} wird heruntergeladen …": "Downloading level {0} …",
  "Nur für diese Sitzung geladen": "Loaded for this session only",
  "Der Browser hat die Stufe {0} nicht dauerhaft gespeichert, meist aus Platzmangel. Sie läuft jetzt, muss nach dem nächsten Start aber erneut geladen werden.": "The browser did not store level {0} permanently, usually due to lack of space. It is running now but has to be loaded again after the next start.",
  "Der Grafikchip hat das Modell nicht geschafft. Wählen Sie eine kleinere Stufe.": "The graphics chip could not handle the model. Choose a smaller level.",
  "Keine Verbindung zum Download. Prüfen Sie das Internet und versuchen Sie es erneut.": "No connection for the download. Check your internet connection and try again.",
  "Die geladenen Dateien stimmen nicht mit der geprüften Fassung überein. Aus Sicherheitsgründen startet das Modell nicht.": "The downloaded files do not match the verified version. For security reasons the model will not start.",
  "Modell konnte nicht starten": "Model could not start",
  "Wie kann ich helfen?": "How can I help?",
  "Ich suche, rechne und öffne für Sie, mit Ihrer Buchhaltung. Alles bleibt auf diesem Gerät.": "I search, calculate and open things for you, using your accounting. Everything stays on this device.",
  "Antwort anhalten": "Stop answer",
  "Anhalten (Esc)": "Stop (Esc)",
  "Überlegt …": "Thinking …",
  "Gedanken": "Thoughts",
  "Denkt nach …": "Thinking …",
  "Schreibt …": "Writing …",
  "Arbeitet …": "Working …",
  "Das hat nicht geklappt:": "That did not work:",
  "Antwort einer KI ·": "Answer from an AI ·",
  "Feste Regeln ·": "Fixed rules ·",
  "Basis": "Basic",
  "Das Modell hat keine brauchbare Antwort geliefert. Diese Antwort kommt aus den festen Regeln.": "The model did not give a usable answer. This answer comes from the fixed rules.",
  "feste Regeln": "fixed rules",
  "· {0} s": "· {0} s",
  "Antwort kopieren": "Copy answer",
  "Kopiert": "Copied",
  "Zu {0} wechseln": "Go to {0}",
  "Treffer": "Results",
  "data-ziel=\"{0}\"": "data-ziel=\"{0}\"",
  "Geöffnet:": "Open:",
  "Prüfen und speichern": "Check and save",
  "Mit Ihrer Rolle lässt sich nichts anlegen.": "Your role does not allow creating anything.",
  "Verwerfen": "Discard",
  "Noch nicht gespeichert. Das Fenster öffnet sich ausgefüllt.": "Not saved yet. The window opens filled in.",
  "Nichts gefunden.": "Nothing found.",
  "Verworfen.": "Discarded.",
  "Im Fenster geöffnet. Gespeichert wird dort.": "Opened in the window. You save it there.",
  "Kunde fehlt noch": "Customer still missing",
  "„{0}“ gibt es noch nicht als Kontakt. Tragen Sie den Kunden in der Rechnung ein.": "“{0}” does not exist as a contact yet. Enter the customer in the invoice.",
  "Entfernen": "Remove",
  "Noch kein Modell heruntergeladen.": "No model downloaded yet.",
  "Dieser Browser gibt den Grafikchip nicht frei, darum geht hier nur die Stufe Basis.": "This browser does not make the graphics chip available, so only the Basic level works here.",
  "So geben Sie ihn frei": "How to enable it",
  "Kontovia belegt im Browser zusammen {0}.": "Kontovia uses {0} in total in the browser.",
  "Er beantwortet Fragen zu Ihrer Buchhaltung und zur Bedienung, sagt, was heute ansteht, sucht Einträge, rechnet und öffnet Bereiche. Neue Buchungen, Aufgaben, Termine, Kontakte und Rechnungen bereitet er vor, ebenso Zahlungseingänge und Mahnungen; speichern tun Sie selbst, im gewohnten Fenster.": "It answers questions about your accounting and how to use Kontovia, tells you what's on today, searches entries, calculates and opens sections. It prepares new transactions, tasks, appointments, contacts and invoices, as well as incoming payments and reminders; you save them yourself in the usual window.",
  "Der Assistent ist neu und noch in Erprobung.": "The assistant is new and still being tested.",
  "Sagen Sie „diese Rechnung“ oder „hier“, meint er den Eintrag, den Sie gerade geöffnet haben.": "If you say “this invoice” or “here”, it means the entry you have just opened.",
  "Ihre Daten bleiben hier": "Your data stays here",
  "Das Sprachmodell läuft auf dem Grafikchip {0}. Fragen, Antworten und Ihre Buchhaltung werden nirgendwohin gesendet.": "The language model runs on the graphics chip {0}. Questions, answers and your accounting are not sent anywhere.",
  "dieses Geräts": "of this device",
  "Das Internet braucht es nur einmal, um ein Modell herunterzuladen. Danach geht alles offline.": "The internet is only needed once to download a model. After that everything works offline.",
  "Das Modell lernt nichts dazu und verändert sich nicht. Es ist eine feste, geprüfte Fassung.": "The model does not learn anything and does not change. It is a fixed, verified version.",
  "Das Gespräch steht nur im Arbeitsspeicher. Beim Sperren oder mit „Neues Gespräch“ ist es weg.": "The conversation is only kept in memory. When you lock or start a “New conversation”, it is gone.",
  "Stufen": "Levels",
  "Stufe": "Level",
  "Für": "For",
  "Wo die Grenzen liegen": "Where the limits are",
  "Zahlen rechnet immer Kontovia selbst. Das Modell sucht nur aus, was gerechnet wird. Trotzdem kann es eine Frage falsch verstehen: Unter jeder Antwort steht, was gelaufen ist.": "Kontovia always calculates figures itself. The model only chooses what is calculated. Still, it can misunderstand a question: below each answer you can see what ran.",
  "Steuerberatung ersetzt der Assistent nicht.": "The assistant does not replace tax advice.",
  "Kleine Stufen verwechseln schneller etwas. Klappt eine Antwort nicht, springt die Stufe Basis mit festen Regeln ein.": "Small levels mix things up more easily. If an answer does not work, the Basic level with fixed rules steps in.",
  "Auf diesem Gerät": "On this device",
  "Tastenkürzel: {0} öffnet und schließt den Assistenten.": "Shortcut: {0} opens and closes the assistant.",
  "Verstanden": "Got it",
  "Stufe {0} entfernt": "Level {0} removed",
  "Entfernen fehlgeschlagen": "Removing failed",
  "Ohne Download": "No download",
  "Jedes Gerät": "Any device",
  "Versteht feste Fragen und Befehle wie „Was ist offen?“ oder „Öffne Mahnungen“. Sofort bereit, ohne Download.": "Understands fixed questions and commands like “What is open?” or “Open reminders”. Ready immediately, no download.",
  "Mini": "Mini",
  "0,6 Mrd. Parameter": "0.6 billion parameters",
  "Qwen3-0.6B-q4f16_1-MLC": "Qwen3-0.6B-q4f16_1-MLC",
  "Telefon, Tablet, ältere Rechner": "Phones, tablets, older computers",
  "Versteht freie Formulierungen bei einfachen Fragen. Klein und schnell, aber leicht zu verwirren.": "Understands free wording for simple questions. Small and fast, but easily confused.",
  "Standard": "Standard",
  "1,7 Mrd. Parameter": "1.7 billion parameters",
  "Qwen3-1.7B-q4f16_1-MLC": "Qwen3-1.7B-q4f16_1-MLC",
  "Die meisten Laptops und PCs": "Most laptops and PCs",
  "Der beste Kompromiss: versteht die meisten Fragen, sucht mit eigenen Worten und schreibt kurze Antworten.": "The best compromise: understands most questions, searches in its own words and writes short answers.",
  "Groß": "Large",
  "4 Mrd. Parameter": "4 billion parameters",
  "Qwen3-4B-q4f16_1-MLC": "Qwen3-4B-q4f16_1-MLC",
  "PCs mit eigener Grafikkarte, neuere Macs": "PCs with a dedicated graphics card, newer Macs",
  "Versteht auch verschachtelte Fragen, verbindet mehrere Schritte und erklärt Ergebnisse besser.": "Also understands nested questions, links several steps and explains results better.",
  "Maximal": "Maximum",
  "8 Mrd. Parameter": "8 billion parameters",
  "Qwen3-8B-q4f16_1-MLC": "Qwen3-8B-q4f16_1-MLC",
  "Starke Grafikkarten ab 8 GB": "Strong graphics cards with 8 GB or more",
  "Das gründlichste Modell. Lohnt sich nur auf sehr starken Rechnern, sonst wird es langsam.": "The most thorough model. Only worth it on very powerful computers, otherwise it gets slow.",
  "Automatisch": "Automatic",
  "Entscheidet je Frage: einfache schnell, schwierige gründlich.": "Decides per question: simple ones fast, difficult ones thoroughly.",
  "Schnell": "Fast",
  "Wählt nur das passende Werkzeug. Die Antwort kommt direkt aus Ihren Zahlen.": "Only picks the right tool. The answer comes straight from your figures.",
  "Ausgewogen": "Balanced",
  "Formuliert eine kurze Antwort und darf zwei, drei Schritte gehen.": "Writes a short answer and may take two or three steps.",
  "Gründlich": "Thorough",
  "Denkt vorher nach und geht bis zu sechs Schritte. Langsamer.": "Thinks first and takes up to six steps. Slower.",
  "Dieser Browser gibt den Grafikchip nicht frei. Ein Sprachmodell läuft hier nicht, die Stufe Basis schon.": "This browser does not make the graphics chip available. A language model does not run here, but the Basic level does.",
  "Telefon mit wenig Arbeitsspeicher: Mini passt.": "Phone with little memory: Mini fits.",
  "Auf Telefonen ist Mini am flüssigsten. Standard geht auf neueren Geräten.": "On phones Mini runs most smoothly. Standard works on newer devices.",
  "Wenig Arbeitsspeicher: Mini läuft sicher, Standard mit Glück.": "Little memory: Mini runs reliably, Standard with luck.",
  "Eigene Grafikkarte erkannt: Groß sollte flüssig laufen.": "Dedicated graphics card detected: Large should run smoothly.",
  "Mac mit eigenem Chip: Standard läuft flüssig, Groß meist auch.": "Mac with Apple chip: Standard runs smoothly, Large usually too.",
  "Für die meisten Rechner ist Standard der beste Kompromiss.": "For most computers Standard is the best compromise.",
  "Das Modell schreibt auf diesem Gerät sehr langsam. Eine kleinere Stufe antwortet schneller.": "The model writes very slowly on this device. A smaller level answers faster.",
  "Ihr Gerät hat Reserven. Die Stufe {0} versteht mehr und sollte flüssig laufen.": "Your device has headroom. Level {0} understands more and should run smoothly.",
  "kein Download": "no download",
  "Ohne Kategorie": "No category",
  "offen, seit {0} fällig": "open, due since {0}",
  "Entwurf": "Draft",
  "Eingang": "Incoming",
  "Ausgang": "Outgoing",
  "ohne Text": "no text",
  "„{0}“ vom {1} über": "“{0}” of {1} for",
  "Rechnung {0}{1} über": "Invoice {0}{1} for",
  "Lieferant": "Supplier",
  "Kunde": "Customer",
  "Termin „{0}“ am": "Appointment “{0}” on",
  "Aufgabe „{0}“": "Task “{0}”",
  "Der Ausdruck enthält etwas, das sich nicht rechnen lässt.": "The expression contains something that cannot be calculated.",
  "Durch null lässt sich nicht teilen.": "Cannot divide by zero.",
  "Eine Klammer ist nicht geschlossen.": "A bracket is not closed.",
  "Der Ausdruck ist unvollständig.": "The expression is incomplete.",
  "Kein Rechenausdruck gefunden.": "No calculation found.",
  "Der Ausdruck ist nicht vollständig lesbar.": "The expression is not fully readable.",
  "Das Ergebnis ist keine Zahl.": "The result is not a number.",
  "Sucht Buchungen, Rechnungen, Kontakte, Termine, Aufgaben. Schreibweisen mit | trennen.": "Sucht Buchungen, Rechnungen, Kontakte, Termine, Aufgaben. Schreibweisen mit | trennen.",
  "z. B. \"fotoshooting|shooting garten\"": "z. B. \"fotoshooting|shooting garten\"",
  "Gefunden": "Found",
  "Dazu habe ich nichts gefunden.": "I found nothing on that.",
  "Ich habe {0} zu „{1}“ gefunden.": "I found {0} for “{1}”.",
  "Zu „{0}“ habe ich nichts gefunden. Versuchen Sie es mit einem anderen Wort.": "I found nothing for “{0}”. Try a different word.",
  "Buchungen mit Filtern, mit Summen.": "Buchungen mit Filtern, mit Summen.",
  "Buchungen ohne Beleg": "Transactions without receipt",
  "Einnahmen": "Income",
  "Ausgaben": "Expenses",
  "Anzahl": "Count",
  "Alle {0} in Buchungen zeigen": "Show all {0} in transactions",
  "In Buchungen zeigen": "Show in transactions",
  "Keine passenden Buchungen.": "No matching transactions.",
  "Buchung": "Transaction",
  ", Einnahmen": ", income",
  ", Ausgaben": ", expenses",
  "im Zeitraum {0}{1}{2}.": "in the period {0}{1}{2}.",
  "Im Zeitraum {0} gibt es keine passenden Buchungen.": "There are no matching transactions in the period {0}.",
  "Rechnungen: geschriebene (ausgang) oder erhaltene (eingang).": "Rechnungen: geschriebene (ausgang) oder erhaltene (eingang).",
  "Offene Rechnungen": "Open invoices",
  "Überfällige Rechnungen": "Overdue invoices",
  "Rechnungsentwürfe": "Invoice drafts",
  "Summe": "Total",
  "Rechnungen öffnen": "Show invoices",
  "Keine passenden Rechnungen.": "No matching invoices.",
  "Rechnung": "Invoice",
  ", zusammen {0}.": ", together {0}.",
  "Keine passenden Rechnungen{0}.": "No matching invoices{0}.",
  "Umsatz, Einnahmen, Ausgaben, Gewinn eines Zeitraums.": "Umsatz, Einnahmen, Ausgaben, Gewinn eines Zeitraums.",
  "(netto)": "(net)",
  "Kleinunternehmer: Beträge ohne Umsatzsteuer": "Small business: amounts without VAT",
  "Beträge netto, gezählt am Zahlungstag": "Net amounts, counted on the payment date",
  "Einnahmen und Ausgaben": "Income and expenses",
  "Gewinn": "Profit",
  "Verlust": "Loss",
  "Noch nicht bezahlt": "Not yet paid",
  "Auswertung öffnen": "Show report",
  ", jeweils netto": ", each net",
  ": Einnahmen {0}, Ausgaben {1}, {2} {3}{4}.": ": income {0}, expenses {1}, {2} {3}{4}.",
  "Summen je Kategorie, größte zuerst.": "Summen je Kategorie, größte zuerst.",
  "Einnahmen nach Kategorie": "Income by category",
  "Ausgaben nach Kategorie": "Expenses by category",
  "Im Zeitraum gibt es keine Buchungen dieser Art.": "There are no transactions of this kind in the period.",
  "Größter Posten {0}: {1} mit {2} ({3}).": "Largest item {0}: {1} with {2} ({3}).",
  "Rangliste der Kunden (einnahme) oder Lieferanten (ausgabe) nach Betrag.": "Rangliste der Kunden (einnahme) oder Lieferanten (ausgabe) nach Betrag.",
  "Unbekannt": "Unknown",
  "Kunden": "Customers",
  "Lieferanten": "Suppliers",
  "Kunden nach Umsatz": "Customers by revenue",
  "Lieferanten nach Ausgaben": "Suppliers by expenses",
  "Keine Buchungen mit Kontakt in diesem Zeitraum.": "No transactions with a contact in this period.",
  "Stärkster Kunde": "Top customer",
  "Größter Lieferant": "Largest supplier",
  ": {0} mit {1}.": ": {0} with {1}.",
  "Im Zeitraum gibt es keine Buchungen mit Kontakt.": "There are no transactions with a contact in the period.",
  "Vergleicht zwei Zeiträume.": "Vergleicht zwei Zeiträume.",
  "Vergleich": "Comparison",
  "Gewinn {0}: {1}, {2}: {3}, Unterschied {4}.": "Profit {0}: {1}, {2}: {3}, difference {4}.",
  "Nur die Steuer: Umsatzsteuer, Vorsteuer, Zahllast. Für Umsatz: kennzahlen.": "Nur die Steuer: Umsatzsteuer, Vorsteuer, Zahllast. Für Umsatz: kennzahlen.",
  "Als Kleinunternehmer fällt keine Umsatzsteuer an und es gibt keine Voranmeldung.": "As a small business no VAT is due and there is no VAT return.",
  "Sie sind als Kleinunternehmer eingestellt: Es fällt keine Umsatzsteuer an.": "You are set up as a small business: no VAT is due.",
  "Sie sind als Kleinunternehmer eingestellt. Es fällt keine Umsatzsteuer an, eine Voranmeldung gibt es nicht.": "You are set up as a small business. No VAT is due and there is no VAT return.",
  "an das Finanzamt zu zahlen": "to be paid to the tax office",
  "Erstattung vom Finanzamt": "refund from the tax office",
  "Soll (Rechnungsdatum)": "Accrual (invoice date)",
  "Ist (Zahlungstag)": "Cash (payment date)",
  "Vorsteuer": "Input VAT",
  "Zahllast": "VAT payable",
  "Erstattung": "Refund",
  "Umsatzsteuer öffnen": "Show VAT",
  ": {0} Umsatzsteuer an das Finanzamt ({1} Umsatzsteuer minus {2} Vorsteuer).": ": {0} VAT to the tax office ({1} VAT minus {2} input VAT).",
  ": {0} Erstattung vom Finanzamt, weil die Vorsteuer ({1}) höher ist als die Umsatzsteuer ({2}).": ": {0} refund from the tax office, because the input VAT ({1}) is higher than the VAT ({2}).",
  "Noch nicht bezahlt: was Kunden schulden (forderungen), was der Nutzer schuldet (verbindlichkeiten).": "Noch nicht bezahlt: was Kunden schulden (forderungen), was der Nutzer schuldet (verbindlichkeiten).",
  "Überfällig": "Overdue",
  "Noch offen": "Still open",
  "Forderungen": "Receivables",
  "Verbindlichkeiten": "Payables",
  "Davon überfällig": "Of which overdue",
  "· {0} Tage über der Frist": "· {0} days past the deadline",
  "Offene Posten öffnen": "Show open items",
  "Alles bezahlt.": "Everything paid.",
  "Posten": "items",
  "Kunden schulden Ihnen {0} ({1})": "Customers owe you {0} ({1})",
  "Sie schulden {0} ({1})": "You owe {0} ({1})",
  "Posten ist": "item is",
  "Posten sind": "items are",
  "überfällig.": "overdue.",
  "Es ist nichts offen. Alles bezahlt.": "Nothing is open. Everything paid.",
  "Stand der Bank- und Kassenkonten.": "Stand der Bank- und Kassenkonten.",
  "Es sind keine Zahlungskonten angelegt.": "No payment accounts have been created.",
  "Termine im Kalender.": "Termine im Kalender.",
  "Termine": "Appointments",
  "Kalender öffnen": "Open calendar",
  "Keine Termine in diesem Zeitraum.": "No appointments in this period.",
  "im Zeitraum {0}.": "in the period {0}.",
  "Im Zeitraum {0} stehen keine Termine im Kalender.": "There are no appointments in the calendar in the period {0}.",
  "Aufgaben.": "Aufgaben.",
  "Erledigte Aufgaben": "Completed tasks",
  "Überfällige Aufgaben": "Overdue tasks",
  "(ohne Titel)": "(untitled)",
  ", überfällig": ", overdue",
  "ohne Datum": "no date",
};
