/** Wörterbuch Englisch, Teil t03. Quellen: lib/assistentwerkzeuge.js, lib/aufgaben.js, lib/benutzer.js, lib/bewegung.js, lib/bildschirmfoto.js, lib/calc.js. */

export default {
  "Aufgaben öffnen": "Show tasks",
  "Keine Aufgaben.": "No tasks.",
  "erledigte Aufgabe": "completed task",
  "erledigte Aufgaben": "completed tasks",
  ", als Nächstes fällig: „{0}“ am": ", next due: “{0}” on",
  "Keine Aufgaben in dieser Liste.": "No tasks in this list.",
  "Kunde oder Lieferant mit Angaben, Umsatz, Offenem.": "Kunde oder Lieferant mit Angaben, Umsatz, Offenem.",
  "Kontakt": "Contact",
  "Kein Kontakt „{0}“ gefunden.": "No contact “{0}” found.",
  "Ich finde keinen Kontakt „{0}“.": "I cannot find a contact “{0}”.",
  "Einnahmen 12 Monate": "Income 12 months",
  "Offen": "Open",
  "E-Mail": "Email",
  "Telefon": "Phone",
  "Anschrift": "Address",
  "Kontakt öffnen": "Open contact",
  ", Telefon": ", phone",
  ", offen:": ", open:",
  ". Einnahmen in den letzten 12 Monaten: {0}{1}.": ". Income in the last 12 months: {0}{1}.",
  "Fristen beim Finanzamt.": "Fristen beim Finanzamt.",
  "Steuertermine": "Tax deadlines",
  "Keine Fristen in diesem Zeitraum.": "No deadlines in this period.",
  "Nächste Frist: {0} am {1}.": "Next deadline: {0} on {1}.",
  "Im Zeitraum {0} stehen keine Fristen an.": "There are no deadlines in the period {0}.",
  "Alle Angaben zu einem Eintrag (id aus einem Ergebnis oder dem geöffneten Eintrag).": "Alle Angaben zu einem Eintrag (id aus einem Ergebnis oder dem geöffneten Eintrag).",
  "Diesen Eintrag finde ich nicht.": "I cannot find this entry.",
  "Eintrag": "Entry",
  "Welchen Eintrag meinen Sie? Öffnen Sie ihn oder nennen Sie ihn genauer.": "Which entry do you mean? Open it or describe it more precisely.",
  "Betrag": "Amount",
  ", darin {0} Umsatzsteuer": ", including {0} VAT",
  "Datum": "Date",
  "Bezahlt": "Paid",
  "Kategorie": "Category",
  "Beleg": "Receipt",
  "Nummer": "Number",
  "(netto {0})": "(net {0})",
  "Zustand": "Status",
  "Fällig": "Due",
  "Zuletzt gemahnt": "Last reminded",
  "Zeit": "Time",
  "Erledigt": "Done",
  "Öffnen": "Open",
  "Storniert": "Reversed",
  "Bezahlt am": "Paid on",
  ", fällig am": ", due on",
  ", offen": ", open",
  "Zustand: {0}{1}.": "Status: {0}{1}.",
  "Was heute ansteht.": "Was heute ansteht.",
  "Termin heute oder morgen": "appointment today or tomorrow",
  "Termine heute und morgen": "appointments today and tomorrow",
  "Aufgabe fällig": "task due",
  "Aufgaben fällig": "tasks due",
  "weitere Frist": "more deadline",
  "weitere Fristen": "more deadlines",
  "und {0} in 14 Tagen": "and {0} within 14 days",
  "Frist beim Finanzamt": "tax office deadline",
  "Kundenrechnung überfällig": "customer invoice overdue",
  "Kundenrechnungen überfällig": "customer invoices overdue",
  "Kunden schulden Ihnen Geld": "Customers owe you money",
  "eigene Rechnung zu zahlen": "own invoice to pay",
  "eigene Rechnungen zu zahlen": "own invoices to pay",
  "fällig in den nächsten 7 Tagen oder schon fällig": "due in the next 7 days or already due",
  "wiederkehrende Buchung fällig": "recurring transaction due",
  "wiederkehrende Buchungen fällig": "recurring transactions due",
  "Hinweis zur Buchhaltung": "accounting note",
  "Hinweis": "Note",
  "fällige Aufgabe": "task due",
  "fällige Aufgaben": "tasks due",
  "überfällige Kundenrechnung": "overdue customer invoice",
  "überfällige Kundenrechnungen": "overdue customer invoices",
  "eigene Rechnung": "own invoice",
  "eigene Rechnungen": "own invoices",
  "wiederkehrende Buchung zu buchen": "recurring transaction to book",
  "wiederkehrende Buchungen zu buchen": "recurring transactions to book",
  "Hinweise zur Buchhaltung": "accounting notes",
  "Was ansteht": "Coming up",
  "Heute steht nichts Dringendes an.": "Nothing urgent today.",
  "Heute wichtig: {0}.": "Important today: {0}.",
  "Verlauf Monat für Monat: Einnahmen, Ausgaben oder Gewinn, auch einer Kategorie.": "Verlauf Monat für Monat: Einnahmen, Ausgaben oder Gewinn, auch einer Kategorie.",
  "Verlauf": "Trend",
  "In diesem Zeitraum gibt es keine Buchungen.": "There are no transactions in this period.",
  "Die letzten {0} Monate liegen {1} den {2} davor.": "The last {0} months are {1} the {2} before.",
  "je Monat": "per month",
  "Zusammen": "Total",
  "Schnitt je Monat": "Average per month",
  "Letzte {0} Monate": "Last {0} months",
  "Jahresvergleich öffnen": "Open year comparison",
  ": zusammen {0}, im Schnitt {1} je Monat. Am meisten im {2} ({3}), am wenigsten im {4} ({5}).": ": total {0}, on average {1} per month. Most in {2} ({3}), least in {4} ({5}).",
  "Prüft ein Jahr vor der Steuer: was fehlt oder nicht stimmt.": "Prüft ein Jahr vor der Steuer: was fehlt oder nicht stimmt.",
  "Fehler": "Error",
  "Bitte prüfen": "Please check",
  "Prüfung": "Check",
  "Nichts gefunden, das fehlt oder nicht stimmt.": "Nothing found that is missing or wrong.",
  "Punkt": "issue",
  "Punkte": "issues",
  ", davon": ", of which",
  "Für {0} habe ich {1} gefunden{2}.": "For {0} I found {1}{2}.",
  "Für {0} habe ich nichts gefunden, das fehlt oder nicht stimmt. Offene Rechnungen und Belege aus anderen Jahren sind darin nicht geprüft.": "For {0} I found nothing that is missing or wrong. Open invoices and receipts from other years are not checked here.",
  "Zeilen der Anlage EÜR eines Jahres mit Beträgen.": "Zeilen der Anlage EÜR eines Jahres mit Beträgen.",
  "Zeile {0} ·": "Line {0} ·",
  "Anlage EÜR öffnen": "Open Anlage EÜR",
  "In diesem Jahr gibt es keine Buchungen für die Anlage EÜR.": "There are no transactions for the Anlage EÜR in this year.",
  "Größte Ausgabenzeile: Zeile {0} ({1}) mit {2}.": "Largest expense line: line {0} ({1}) with {2}.",
  "Buchung hat": "transaction has",
  "Buchungen haben": "transactions have",
  "noch keine Kategorie und fehlt darin.": "no category yet and is missing from it.",
  "Anlage EÜR {0}: Betriebseinnahmen {1}, Betriebsausgaben {2}, {3} {4}.": "Anlage EÜR {0}: business income {1}, business expenses {2}, {3} {4}.",
  "Abschreibungen (AfA) der Anlagegüter in einem Zeitraum.": "Abschreibungen (AfA) der Anlagegüter in einem Zeitraum.",
  "Restwert": "Residual value",
  "Anlagevermögen öffnen": "Open fixed assets",
  "Es sind keine Anlagegüter erfasst.": "No fixed assets have been recorded.",
  "Anlagegut": "fixed asset",
  "Anlagegüter": "fixed assets",
  "Am meisten: {0} mit {1}.": "Most: {0} with {1}.",
  "Abschreibungen {0}: {1} für {2}.": "Depreciation {0}: {1} for {2}.",
  "Es sind keine Anlagegüter erfasst, die abgeschrieben werden.": "No fixed assets subject to depreciation have been recorded.",
  "Umsatz im Vergleich zu den Grenzen der Kleinunternehmerregelung.": "Umsatz im Vergleich zu den Grenzen der Kleinunternehmerregelung.",
  "Kleinunternehmerregelung": "Small business rule",
  "Umsatz": "Revenue",
  "Umsatz {0} bisher": "Revenue {0} so far",
  "Grenze für das Vorjahr": "Limit for the previous year",
  "Grenze im laufenden Jahr": "Limit in the current year",
  "Einstellungen öffnen": "Open settings",
  "Sie sind als Kleinunternehmer eingestellt.": "You are set up as a small business.",
  "Sie sind nicht als Kleinunternehmer eingestellt.": "You are not set up as a small business.",
  ", noch {0} Luft": ", {0} headroom left",
  "Umsatz {0}: {1} (Grenze 25.000 €), {2} bisher: {3} (Grenze 100.000 €{4}).": "Revenue {0}: {1} (limit €25,000), {2} so far: {3} (limit €100,000{4}).",
  "Anleitung: wie etwas geht, wo es steht, was ein Begriff heißt.": "Anleitung: wie etwas geht, wo es steht, was ein Begriff heißt.",
  "Die Anleitung ist gerade nicht geladen.": "The guide is not loaded right now.",
  "Ich öffne die Hilfe.": "I am opening the help.",
  "In der Hilfe": "In the help",
  "Hilfe öffnen": "Open help",
  "Dazu steht in der Hilfe nichts.": "The help says nothing about this.",
  "Dazu steht in der Hilfe nichts. Versuchen Sie es mit einem anderen Wort.": "The help says nothing about this. Try a different word.",
  "In der Hilfe unter „{0}“:": "In the help under “{0}”:",
  "Rechnet genau, z. B. \"(120+80)*1,19\", \"19 % von 250\".": "Rechnet genau, z. B. \"(120+80)*1,19\", \"19 % von 250\".",
  "Netto, Steuer, brutto aus einem Betrag.": "Netto, Steuer, brutto aus einem Betrag.",
  "Euro": "Euro",
  "Prozent, meist 19": "Prozent, meist 19",
  "Umsatzsteuer {0} %": "VAT {0}%",
  "Netto": "Net",
  "Brutto": "Gross",
  "Netto {0} + {1} % Umsatzsteuer {2} = brutto {3}.": "Net {0} + {1}% VAT {2} = gross {3}.",
  "Öffnet einen Bereich: {0}. Reiter: rechnungen (ausgang, eingang, mahnwesen, vorlagen, produkte), reports (guv, euer, ust, bilanz, opos, konten, anlagen, vergleich), master (contacts, categories, accounts, assets, recurring), export (export, import).": "Öffnet einen Bereich: {0}. Reiter: rechnungen (ausgang, eingang, mahnwesen, vorlagen, produkte), reports (guv, euer, ust, bilanz, opos, konten, anlagen, vergleich), master (contacts, categories, accounts, assets, recurring), export (export, import).",
  "Bereich „{0}“ gibt es nicht.": "There is no section “{0}”.",
  "Diesen Bereich kenne ich nicht.": "I don't know this section.",
  "Ich öffne {0}.": "Opening {0}.",
  "Öffnet einen Eintrag mit seiner id aus einem Ergebnis.": "Öffnet einen Eintrag mit seiner id aus einem Ergebnis.",
  "Diesen Eintrag gibt es nicht.": "This entry does not exist.",
  "Ich öffne „{0}“.": "Opening “{0}”.",
  "Bereitet eine Einnahme oder Ausgabe vor (Nutzer speichert).": "Bereitet eine Einnahme oder Ausgabe vor (Nutzer speichert).",
  "brutto, Euro": "brutto, Euro",
  "(Vorschlag)": "(suggestion)",
  "Noch nicht gespeichert: Der Nutzer prüft im Fenster und speichert selbst.": "Not saved yet: you check it in the window and save it yourself.",
  "Neue Einnahme": "New income",
  "Neue Ausgabe": "New expense",
  "Beschreibung": "Description",
  ", Vorschlag": ", suggestion",
  "eine Einnahme": "an income",
  "eine Ausgabe": "an expense",
  "Ich habe {0} über {1} vorbereitet. Prüfen Sie die Angaben und speichern Sie.": "I have prepared {0} for {1}. Check the details and save.",
  "Bereitet eine Aufgabe vor.": "Bereitet eine Aufgabe vor.",
  "Noch nicht gespeichert.": "Not saved yet.",
  "Neue Aufgabe": "New task",
  "Aufgabe": "Task",
  "Notiz": "Note",
  "Ich habe die Aufgabe „{0}“{1} vorbereitet.": "I have prepared the task “{0}”{1}.",
  "Bereitet einen Termin vor.": "Bereitet einen Termin vor.",
  "Neuer Termin": "New appointment",
  "Titel": "Title",
  "Ich habe den Termin „{0}“ am {1}{2} vorbereitet.": "I have prepared the appointment “{0}” on {1}{2}.",
  "Bereitet einen Kontakt vor.": "Bereitet einen Kontakt vor.",
  "Neuer Lieferant": "New supplier",
  "Neuer Kunde": "New customer",
  "Name": "Name",
  "Es gibt schon „{0}“.": "“{0}” already exists.",
  "Achtung: „{0}“ gibt es schon. Ich habe den neuen Kontakt trotzdem vorbereitet.": "Note: “{0}” already exists. I prepared the new contact anyway.",
  "Ich habe den Kontakt „{0}“ vorbereitet.": "I have prepared the contact “{0}”.",
  "Bereitet eine Rechnung vor.": "Bereitet eine Rechnung vor.",
  "netto, Euro": "netto, Euro",
  "Ein Entwurf entsteht erst, wenn der Nutzer ihn öffnet und speichert.": "A draft is only created when you open and save it.",
  "Neue Rechnung": "New invoice",
  "Diesen Kunden gibt es noch nicht als Kontakt.": "This customer does not exist as a contact yet.",
  "Ich habe eine Rechnung{0} vorbereitet{1}.": "I have prepared an invoice{0}{1}.",
  "Offener Posten wurde bezahlt (\"X hat bezahlt\"); Nutzer bestätigt.": "Offener Posten wurde bezahlt (\"X hat bezahlt\"); Nutzer bestätigt.",
  "zu „{0}“": "for “{0}”",
  "Ich finde keinen offenen Posten{0}. Vielleicht ist er schon als bezahlt eingetragen.": "I cannot find an open item{0}. Maybe it has already been recorded as paid.",
  "Zahlung": "Payment",
  "Noch nicht eingetragen: Der Nutzer bestätigt im Fenster.": "Not recorded yet: you confirm it in the window.",
  "Zahlung eingegangen": "Payment received",
  "Zahlung geleistet": "Payment made",
  "Prüfen und eintragen": "Check and record",
  "Fällig war": "Was due",
  "Der {0} liegt im festgeschriebenen Zeitraum.": "The {0} is in the locked period.",
  "weiterer offener Posten": "more open item",
  "weitere offene Posten": "more open items",
  "Es passen noch {0}: {1}.": "{0} also match: {1}.",
  "Ich habe die Zahlung zu „{0}“{1} über {2} vorbereitet, bezahlt am {3}. Prüfen und bestätigen Sie im Fenster.": "I have prepared the payment for “{0}”{1} of {2}, paid on {3}. Check and confirm it in the window.",
  "Bereitet eine Mahnung zu einer überfälligen Rechnung vor (Nutzer prüft).": "Bereitet eine Mahnung zu einer überfälligen Rechnung vor (Nutzer prüft).",
  "Rechnungsnummer": "Invoice number",
  "Ich finde keine überfällige Rechnung{0}.": "I cannot find an overdue invoice{0}.",
  "Mahnung": "Reminder",
  "Noch nichts erstellt: Der Nutzer prüft im Mahnungsfenster.": "Nothing created yet: you check it in the reminder window.",
  "Mahnung vorbereiten": "Prepare reminder",
  "({0} Tage)": "({0} days)",
  "Zuletzt": "Last",
  "Die Frist der letzten Mahnung läuft noch bis {0}.": "The deadline of the last reminder runs until {0}.",
  "Außerdem mahnbar: {0}.": "Also due for a reminder: {0}.",
  "Tag": "day",
  "Tagen": "days",
  "Rechnung {0}{1} ist seit {2} überfällig, offen {3}. Ich habe die {4} vorbereitet; prüfen Sie sie im Fenster.": "Invoice {0}{1} has been overdue since {2}, open {3}. I have prepared the {4}; check it in the window.",
  "Was der Assistent kann.": "Was der Assistent kann.",
  "Gern. Fragen Sie jederzeit wieder.": "You're welcome. Ask again any time.",
  "Ich finde Buchungen, Rechnungen, Kontakte, Termine und Aufgaben, rechne Ihre Zahlen aus, erkläre die Bedienung, öffne Bereiche und bereite neue Einträge, Zahlungen und Mahnungen vor. Fragen Sie zum Beispiel: „Was steht heute an?“": "I find transactions, invoices, contacts, appointments and tasks, calculate your figures, explain how things work, open sections and prepare new entries, payments and reminders. Ask, for example: “What's on today?”",
  "Das Werkzeug „{0}“ gibt es nicht.": "The tool “{0}” does not exist.",
  "Das hat nicht geklappt.": "That did not work.",
  "Tage": "days",
  "Woche": "week",
  "Wochen": "weeks",
  "Monat": "month",
  "Monate": "months",
  "Nächster Tag": "Next day",
  "Nächste Woche": "Next week",
  "Nächster Monat": "Next month",
  "Nächste": "Next",
  "Ziel": "Goal",
  "Wiederholt sich": "Repeats",
  "Frist vorbei, es fehlen": "Deadline passed, still missing",
  "noch {0}{1} in {2}: {3}{4} pro Tag": "{0}{1} left in {2}: {3}{4} per day",
  "von {0}{1},": "of {0}{1},",
  "Jahre": "years",
  "jeden Tag": "every day",
  "jede Woche": "every week",
  "jeden Monat": "every month",
  "jedes Jahr": "every year",
  "PIN für": "PIN for",
  "Dieser Benutzer ist mit einer PIN geschützt, damit nicht jemand anderes in seinem Namen arbeitet.": "This user is protected with a PIN so that nobody else works in their name.",
  "Anmelden": "Sign in",
  "Die PIN stimmt nicht.": "The PIN is wrong.",
  "Wer arbeitet jetzt?": "Who is working now?",
  "· mit PIN": "· with PIN",
  "Wählen Sie Ihren Namen. Kontovia vermerkt ihn im Änderungsjournal bei allem, was Sie ändern.": "Choose your name. Kontovia records it in the change log for everything you change.",
  "Benutzer": "User",
  "Benutzer in diesem Konto": "Users in this account",
  "Benutzer verwalten": "Manage users",
  "Benutzer wechseln": "Switch user",
  "Sie sind als „{0}“ mit der Rolle „Nur lesen“ angemeldet: ansehen, auswerten und exportieren geht, ändern nicht.": "You are signed in as “{0}” with the role “Read only”: viewing, reports and exports work, changes do not.",
  "Benutzer einrichten": "Set up users",
  "Benutzer hinzufügen": "Add user",
  "Legen Sie zuerst sich selbst als Inhaber an. Danach können Sie weitere Personen hinzufügen, etwa Mitarbeitende oder die Steuerberatung. Ab dann fragt Kontovia nach dem Entsperren, wer arbeitet, und das Journal vermerkt den Namen.": "First create yourself as the owner. After that you can add more people, such as employees or your tax advisor. From then on Kontovia asks who is working after unlocking, and the log records the name.",
  "Rolle": "Role",
  "leer lassen, um sie zu behalten": "leave empty to keep it",
  "4 bis 8 Ziffern": "4 to 8 digits",
  "PIN entfernen": "Remove PIN",
  "Deaktiviert (taucht bei „Wer arbeitet jetzt?“ nicht mehr auf)": "Deactivated (no longer appears under “Who is working now?”)",
  "PIN (freiwillig)": "PIN (optional)",
  "Mit einer PIN kann niemand ohne sie als dieser Benutzer arbeiten. Sie schützt nicht die Daten: Wer das Passwort des Kontos kennt, kommt ohnehin an alles.": "With a PIN, nobody can work as this user without it. It does not protect the data: anyone who knows the account password can access everything anyway.",
  "Speichern": "Save",
  "Die PIN besteht aus vier bis acht Ziffern.": "The PIN consists of four to eight digits.",
  "Benutzer angelegt": "User created",
  "Benutzer geändert": "User changed",
  "Nicht möglich": "Not possible",
  "Sie sind gerade als dieser Benutzer angemeldet. Wechseln Sie zuerst zu einem anderen.": "You are currently signed in as this user. Switch to another one first.",
  "Es muss mindestens ein Inhaber bleiben.": "At least one owner must remain.",
  "löschen?": "delete?",
  "Der Benutzer verschwindet aus der Liste. Im Änderungsjournal bleibt sein Name bei allem, was er geändert hat, stehen. Das lässt sich nicht rückgängig machen.": "The user disappears from the list. In the change log their name stays with everything they changed. This cannot be undone.",
  "Löschen": "Delete",
  "Benutzer gelöscht:": "User deleted:",
  "Benutzer gelöscht": "User deleted",
  "Nicht gelöscht": "Not deleted",
  "Benutzer abschalten?": "Turn off users?",
  "Alle Benutzer werden gelöscht. Kontovia arbeitet danach wie zuvor: ohne Rollen und ohne Namen im Journal. Die bisherigen Einträge im Journal behalten ihre Namen.": "All users will be deleted. Kontovia then works as before: without roles and without names in the log. Existing log entries keep their names.",
  "Abschalten": "Turn off",
  "Benutzer abgeschaltet": "Users turned off",
  "Nicht abgeschaltet": "Not turned off",
  "Bearbeiten": "Edit",
  "· seit": "· since",
  "Benutzer abschalten": "Turn off users",
  "Benutzer ändern darf nur ein Inhaber.": "Only an owner may change users.",
  "Arbeiten mehrere Personen mit dieser Buchhaltung, oder soll die Steuerberatung nur mitlesen? Mit Benutzern fragt Kontovia nach dem Entsperren, wer arbeitet. Das Änderungsjournal vermerkt dann bei jeder Änderung den Namen (das erwartet die GoBD), und Rollen bestimmen, was jemand ändern darf.": "Do several people work with this accounting, or should your tax advisor only read along? With users, Kontovia asks who is working after unlocking. The change log then records the name for every change (as the GoBD expect), and roles determine what someone may change.",
  "wer was ändern darf und im Journal steht": "who may change what and appears in the log",
  "Wer das Passwort dieses Kontos kennt, besitzt den Schlüssel zu allen Daten. Die Rollen regeln die Bedienung in Kontovia und den Namen im Journal. Wer wirklich getrennte Daten braucht, legt ein eigenes Konto mit eigenem Passwort an (Menü an der Marke links oben).": "Anyone who knows this account's password holds the key to all data. Roles govern how Kontovia is used and the name in the log. If you really need separate data, create your own account with its own password (menu at the logo top left).",
  "Rollen sind keine Zugriffssperre.": "Roles are not an access barrier.",
  "linear(0, 1)": "linear(0, 1)",
  "linear({0})": "linear({0})",
  ":scope > *, .dash > .dash-item, .grid > *, .page-head, .re-editor > *, .todo-group, .set-nav, .set-panel > *": ":scope > *, .dash > .dash-item, .grid > *, .page-head, .re-editor > *, .todo-group, .set-nav, .set-panel > *",
  "scale(1)": "scale(1)",
  "rotate(0) scale(1)": "rotate(0) scale(1)",
  "iframe, object, embed": "iframe, object, embed",
  "input, textarea, select": "input, textarea, select",
  "button, a, input, select, textarea": "button, a, input, select, textarea",
  "circle(0px at {0}px {1}px)": "circle(0px at {0}px {1}px)",
  "circle({0}px at {1}px {2}px)": "circle({0}px at {1}px {2}px)",
  "::view-transition-new(root)": "::view-transition-new(root)",
  "url(\"{0}\")": "url(\"{0}\")",
  "[data-ohne-foto], #toasts": "[data-ohne-foto], #toasts",
  "script, noscript, link, style": "script, noscript, link, style",
  "width:{0}px;height:{1}px;overflow:hidden;position:relative;": "width:{0}px;height:{1}px;overflow:hidden;position:relative;",
  "Bild konnte nicht erzeugt werden.": "The image could not be created.",
  "Die Zeichenfläche lässt sich nicht auslesen.": "The canvas cannot be read.",
  "Bildschirmfoto nicht möglich:": "Screenshot not possible:",
  "degressiv (§ 7 Abs. 2 EStG)": "declining balance (§ 7 (2) EStG)",
  "Nutzungsdauer 1 Jahr (BMF 22.02.2022)": "Useful life 1 year (BMF 22.02.2022)",
  "Kasse": "Cash",
  "Januar": "January",
  "Februar": "February",
  "März": "March",
  "April": "April",
  "Mai": "May",
  "Juni": "June",
  "Juli": "July",
  "August": "August",
  "September": "September",
  "Oktober": "October",
  "November": "November",
  "Dezember": "December",
  "Zeile": "Line",
  "Abschreibungen (AfA)": "Depreciation (AfA)",
  "ohne Kategorie. Voranmeldung und Anlage EÜR stimmen erst, wenn alles zugeordnet ist": "without a category. The VAT return and Anlage EÜR are only correct once everything is assigned",
  "bezahlte Buchung": "paid transaction",
  "bezahlte Buchungen": "paid transactions",
  "ohne Konto, die Kontostände stimmen dadurch nicht": "without an account, so the account balances are not correct",
  "ohne Beleg": "without receipt",
  ", bei denen Netto und Steuer zusammen nicht den Bruttobetrag ergeben": "where net and tax together do not add up to the gross amount",
  "Zahlungen": "Payments",
  "mit Datum in der Zukunft": "dated in the future",
  "mögliche Doppelerfassung": "possible duplicate",
  "mögliche Doppelerfassungen": "possible duplicates",
  "(gleiches Datum, gleicher Betrag, gleicher Text)": "(same date, same amount, same text)",
  "steht am {0} bei {1} €. Eine Kasse kann nicht ins Minus gehen.": "is at {1} € on {0}. A cash account cannot go negative.",
};
