/** Wörterbuch Englisch, Teil t04. Quellen: app.js, lib/assistentfenster.js, lib/calc.js, lib/datenimport.js, lib/datenimportaktionen.js, lib/dokument.js, lib/elster.js, lib/emailversand.js, lib/erechnung.js, lib/euer.js, lib/feedback.js, lib/fristen.js, lib/gcal.js, lib/gcalsync.js, lib/girocode.js, lib/grafikhilfe.js. */

export default {
  "Im Ordner „{0}“ liegt keine Kontovia-Buchhaltung. Unter Windows liegt sie im Ordner {1}. Den gibt der Browser nicht direkt frei: Kopieren Sie ihn zum Beispiel in Ihre Dokumente und wählen Sie dann die Kopie.": "The folder “{0}” contains no Kontovia accounting. On Windows it is in the folder {1}. The browser does not grant access to it directly: copy it, for example to your documents, and then choose the copy.",
  "Die Buchhaltung im Ordner „{0}“ ist bereit. Entsperren Sie sie mit ihrem Passwort. Arbeitet Kontovia unter Windows mit demselben Ordner, öffnen Sie bitte nie beide gleichzeitig.": "The accounting in the folder “{0}” is ready. Unlock it with its password. If Kontovia on Windows works with the same folder, please never open both at the same time.",
  "Der Grafikchip hat die Antwort abgebrochen und wurde vom Treiber neu gestartet. Das kommt vor, wenn eine Stufe das Gerät stark fordert. Fragen Sie einfach noch einmal, die Stufe startet dann neu. Passiert das öfter, wählen Sie eine kleinere Stufe.": "The graphics chip aborted the answer and was restarted by the driver. This can happen when a level puts heavy load on the device. Just ask again, the level will then restart. If this happens often, choose a smaller level.",
  "steht am {0} bei {1} €. Eine Kasse kann nicht ins Minus gehen. Bei einer Betriebsprüfung gilt das als Hinweis auf fehlende Einnahmen. Meist lief eine Ausgabe in Wahrheit über die Bank, oder eine Bareinnahme fehlt.": "is at {1} € on {0}. A cash account cannot go negative. In a tax audit this is seen as a sign of missing income. Usually an expense actually went through the bank, or a cash receipt is missing.",
  "unter 800 € netto: Solche geringwertigen Anschaffungen lassen sich meist sofort voll absetzen": "under €800 net: such low-value purchases can usually be deducted in full right away",
  "Die Rechnungsnummer {0} ist mehrfach vergeben. Jede Nummer darf nur einmal vorkommen. Das passiert meist, wenn auf zwei Geräten ohne Verbindung Rechnungen geschrieben wurden. Stornieren Sie eine der Rechnungen und stellen Sie sie mit neuer Nummer neu aus.": "The invoice number {0} is used more than once. Each number may only occur once. This usually happens when invoices were written on two devices without a connection. Reverse one of the invoices and issue it again with a new number.",
  "Umsatz {0}: {1} € netto, damit über 800.000 €. Nach Zahlungseingang dürfen Sie die Umsatzsteuer dann nur noch als Freiberufler oder mit Erlaubnis des Finanzamts berechnen. Bitte mit der Steuerberatung klären.": "Revenue {0}: {1} € net, which is over €800,000. You may then only calculate VAT on payment received as a freelancer or with permission from the tax office. Please clarify with your tax advisor.",
  "Die Voranmeldung bis {0} ist abgegeben, der Zeitraum aber noch nicht festgeschrieben. Schreiben Sie ihn fest, damit er sich nicht mehr unbemerkt ändert (Einstellungen › Firma & Steuern).": "The VAT return up to {0} has been filed, but the period is not locked yet. Lock it so that it cannot change unnoticed (Settings › Company & taxes).",
  "EÜR-Zeile prüfen: {0}. Diese Zeile ist im Formular": "Check EÜR line: {0}. In the form this line is",
  "„{0}“ (Zeile {1})": "“{0}” (line {1})",
  "EÜR-Zeile prüfen: {0}. Diese Zeile ist im Formular eine Summe oder passt nicht zur Art der Kategorie. Anpassen unter Stammdaten → Kategorien.": "Check EÜR line: {0}. In the form this line is a total or does not match the type of category. Adjust under Master data → Categories.",
  "Umsatz {0}: {1} €, damit über 25.000 €. Die Kleinunternehmerregelung gilt {2} damit nicht; Umsatzsteuer ist auszuweisen. Bitte mit der Steuerberatung klären und unter Einstellungen umstellen.": "Revenue {0}: {1} €, which is over €25,000. The small business rule therefore does not apply in {2}; VAT must be charged. Please clarify with your tax advisor and change it in the settings.",
  "Umsatz {0}: {1} €, damit über 100.000 €. Ab dem Umsatz, mit dem die Grenze überschritten wurde, gilt die Regelbesteuerung (§ 19 Abs. 1 UStG). Bitte umgehend mit der Steuerberatung klären.": "Revenue {0}: {1} €, which is over €100,000. From the sale that exceeded the limit, standard taxation applies (§ 19 (1) UStG). Please clarify with your tax advisor right away.",
  "Umsatz {0}: {1} €, damit über 25.000 €. Im Jahr, in dem die Tätigkeit beginnt, gilt diese Grenze schon im laufenden Jahr: Ab dem Umsatz, mit dem sie überschritten wurde, gilt die Regelbesteuerung (§ 19 UStG). Bitte umgehend mit der Steuerberatung klären.": "Revenue {0}: {1} €, which is over €25,000. In the year the business starts, this limit already applies in the current year: from the sale that exceeded it, standard taxation applies (§ 19 UStG). Please clarify with your tax advisor right away.",
  "Umsatz {0}: {1} €, damit über 25.000 €. Im Jahr {2} gilt die Kleinunternehmerregelung damit nicht mehr.": "Revenue {0}: {1} €, which is over €25,000. The small business rule therefore no longer applies in {2}.",
  "Hat Ihre Tätigkeit erst in diesem Jahr begonnen, gilt die Regelbesteuerung schon ab dem Umsatz, mit dem die 25.000 € überschritten wurden. Den Beginn tragen Sie in den Einstellungen ein.": "If your business only started this year, standard taxation already applies from the sale that exceeded €25,000. Enter the start date in the settings.",
  "Die DATEV-Datei ist leer.": "The DATEV file is empty.",
  "Die Datei beginnt nicht mit einem DATEV-Kopf (EXTF).": "The file does not start with a DATEV header (EXTF).",
  "Die Datei hat mehr als {0} Zeilen; gelesen wurden die ersten.": "The file has more than {0} rows; the first ones were read.",
  "Diese DATEV-Datei enthält {0}. Eingelesen werden Buchungsstapel sowie Debitoren und Kreditoren.": "This DATEV file contains {0}. Booking batches as well as debtors and creditors are imported.",
  "andere Daten": "other data",
  "In der DATEV-Datei fehlen die Spalten Umsatz, Konto oder Gegenkonto.": "The DATEV file is missing the columns Umsatz, Konto or Gegenkonto.",
  "Zeile {0}: Belegdatum „{1}“ ist nicht lesbar und wurde übersprungen.": "Row {0}: document date “{1}” is not readable and was skipped.",
  "Zeile {0}: Betrag in {1} wurde übersprungen; übernommen werden Euro-Beträge.": "Row {0}: amount in {1} was skipped; only euro amounts are imported.",
  "Konto oder Gegenkonto fehlt.": "Account or contra account missing.",
  "Umbuchung zwischen zwei Geldkonten; sie ändert kein Ergebnis.": "Transfer between two money accounts; it does not change any result.",
  "Umbuchung zwischen zwei Personenkonten.": "Transfer between two personal accounts.",
  "Umbuchung zwischen Sachkonten, etwa Abschreibung oder Abgrenzung. Bitte von Hand prüfen.": "Transfer between general ledger accounts, such as depreciation or accruals. Please check manually.",
  "Gegenbuchung auf Konto {0} ({1}), etwa eine Gutschrift. Bitte von Hand als Storno erfassen.": "Contra entry on account {0} ({1}), such as a credit note. Please record it manually as a reversal.",
  "Konto": "Account",
  "Konto {0} gehört zu keiner Kategorie; die Buchung kommt ohne Kategorie.": "Account {0} does not belong to any category; the transaction is imported without a category.",
  "Steckt als Zahlungsdatum in der Rechnung {0} (Zeile {1}).": "Contained as the payment date in invoice {0} (row {1}).",
  "Zahlung zur vorhandenen Buchung „{0}“ ({1}).": "Payment for the existing transaction “{0}” ({1}).",
  "Zahlung ohne passende Rechnung in der Datei oder im Bestand.": "Payment without a matching invoice in the file or in your data.",
  "In der Tabelle fehlen erkennbare Überschriften wie Datum, Betrag und Beschreibung.": "The table lacks recognizable headings such as date, amount and description.",
  "In der Tabelle fehlt die Spalte {0}.": "The table is missing the column {0}.",
  "Zeile {0}: kein lesbares Datum, übersprungen.": "Row {0}: no readable date, skipped.",
  "Zeile {0}: kein Betrag, übersprungen.": "Row {0}: no amount, skipped.",
  "In der Tabelle als „{0}“ markiert; Storno und Gegenbuchung bleiben draußen.": "Marked as “{0}” in the table; reversal and contra entry are left out.",
  "Tabelle": "Table",
  "Kategorie „{0}“ gibt es nicht; die Buchung kommt ohne Kategorie.": "Category “{0}” does not exist; the transaction is imported without a category.",
  "Ohne Kategorie.": "No category.",
  "Noch nicht bezahlt.": "Not yet paid.",
  "Mögliche Dublette: Am selben Tag gibt es schon „{0}“ über denselben Betrag.": "Possible duplicate: on the same day there is already “{0}” with the same amount.",
  "eine Buchung": "one transaction",
  "Ansprechperson:": "Contact person:",
  "vereinigtes koenigreich": "vereinigtes koenigreich",
  "united kingdom": "united kingdom",
  "united states": "united states",
  "In der Tabelle fehlt eine Spalte mit dem Namen oder der Firma.": "The table is missing a column with the name or company.",
  "In der Tabelle fehlt die Spalte Bezeichnung oder Name.": "The table is missing the column description or name.",
  "Stk.": "pcs.",
  "Gibt es schon.": "Already exists.",
  "Steht mehrfach in der Datei.": "Appears several times in the file.",
  "-Import": "-import",
  "Die Buchung ist inzwischen bezahlt oder gelöscht.": "The transaction has since been paid or deleted.",
  "Der {0} ist festgeschrieben.": "The {0} is locked.",
  "Bezahlt am {0}: {1}, {2} ({3})": "Paid on {0}: {1}, {2} ({3})",
  "Diese Zeile wurde schon übernommen.": "This row has already been imported.",
  ": {0} Buchungen übernommen": ": {0} transactions imported",
  ", {0} Zahlungen zugeordnet": ", {0} payments matched",
  ", {0} Kontakte angelegt": ", {0} contacts created",
  ", {0} nicht übernommen": ", {0} not imported",
  "(aus {0})": "(from {0})",
  "Umsatzsteuer-Voranmeldung {0}/{1} aus {2}, Kennzahl 83:": "VAT return {0}/{1} from {2}, box 83:",
  "Überschuss": "Surplus",
  "Erstellt am {0} mit Kontovia, berechnet aus den erfassten Buchungen nach festen Rechenregeln; an der Berechnung wirkt keine künstliche Intelligenz mit. Eine Arbeitshilfe, bitte vor der Übernahme prüfen.": "Created on {0} with Kontovia, calculated from the recorded transactions using fixed rules; no artificial intelligence is involved in the calculation. A working aid, please check before using it.",
  "Steuernummer:": "Tax number:",
  "USt-IdNr.:": "VAT ID:",
  "Ohne Firmenangabe": "No company details",
  "Jahresunterlagen": "Annual documents",
  "Erstellt mit Kontovia": "Created with Kontovia",
  "Seite {0} von": "Page {0} of",
  "Baden-Württemberg": "Baden-Württemberg",
  "Bayern": "Bavaria",
  "Berlin": "Berlin",
  "Brandenburg": "Brandenburg",
  "Bremen": "Bremen",
  "Hamburg": "Hamburg",
  "Hessen": "Hesse",
  "Mecklenburg-Vorpommern": "Mecklenburg-Western Pomerania",
  "Niedersachsen": "Lower Saxony",
  "Nordrhein-Westfalen": "North Rhine-Westphalia",
  "Rheinland-Pfalz": "Rhineland-Palatinate",
  "Saarland": "Saarland",
  "Sachsen": "Saxony",
  "Sachsen-Anhalt": "Saxony-Anhalt",
  "Schleswig-Holstein": "Schleswig-Holstein",
  "Thüringen": "Thuringia",
  "Eine Voranmeldung gilt für einen Monat oder ein Quartal. Bitte den Zeitraum entsprechend wählen.": "A VAT return covers one month or one quarter. Please choose the period accordingly.",
  "Für ELSTER wird die Steuernummer im 13-stelligen Format gebraucht.": "ELSTER needs the tax number in the 13-digit format.",
  "Als Kleinunternehmer geben Sie keine Voranmeldung ab.": "As a small business you do not file VAT returns.",
  "Im Zeitraum {0} ohne Kategorie. Ohne Kategorie ist nicht klar, ob und wie hoch Umsatzsteuer anfällt; die Voranmeldung wäre unvollständig.": "In the period {0} without a category. Without a category it is unclear whether and how much VAT is due; the VAT return would be incomplete.",
  "liegt eine Buchung": "there is one transaction",
  "liegen {0} Buchungen": "there are {0} transactions",
  "Kz10": "Kz10",
  "Kz": "Box",
  "Unternehmen": "Company",
  "Die Datei ist kein lesbares XML:": "The file is not readable XML:",
  "Umsatzsteuervoranmeldung": "Umsatzsteuervoranmeldung",
  "Lohnsteueranmeldung": "Lohnsteueranmeldung",
  "Umsatzsteuererklaerung": "Umsatzsteuererklaerung",
  "Einkommensteuererklaerung": "Einkommensteuererklaerung",
  "Zusammenfassende_Meldung": "Zusammenfassende_Meldung",
  "Diese ELSTER-Datei enthält keine Umsatzsteuer-Voranmeldung. Eingelesen werden derzeit nur Voranmeldungen.": "This ELSTER file contains no VAT return. Currently only VAT returns are imported.",
  "In der Datei steht keine Umsatzsteuer-Voranmeldung im ELSTER-Format.": "The file contains no VAT return in ELSTER format.",
  "Zeitraum": "Period",
  "Eine Voranmeldung ohne gültigen Zeitraum wurde übersprungen ({0}/{1}).": "A VAT return without a valid period was skipped ({0}/{1}).",
  "Kennzahl {0} hat keinen lesbaren Betrag und fehlt.": "Box {0} has no readable amount and is missing.",
  ": Kennzahl 83 fehlte und wurde nachgerechnet.": ": box 83 was missing and was recalculated.",
  "Keine der Voranmeldungen in der Datei ließ sich lesen.": "None of the VAT returns in the file could be read.",
  "Umsätze 19 % (Bemessungsgrundlage)": "Sales at 19% (tax base)",
  "Umsätze 7 % (Bemessungsgrundlage)": "Sales at 7% (tax base)",
  "Umsätze zu anderen Steuersätzen": "Sales at other tax rates",
  "Steuer zu anderen Steuersätzen": "Tax at other tax rates",
  "Innergemeinschaftliche Lieferungen": "Intra-community supplies",
  "Nicht steuerbare Leistungen ins EU-Ausland": "Non-taxable services to other EU countries",
  "Steuerfreie Umsätze mit Vorsteuerabzug (Ausfuhr)": "Tax-exempt sales with input tax deduction (export)",
  "Nicht steuerbare Leistungen außerhalb der EU": "Non-taxable services outside the EU",
  "Steuerfreie Umsätze ohne Vorsteuerabzug": "Tax-exempt sales without input tax deduction",
  "Umsätze, für die der Kunde die Steuer schuldet": "Sales for which the customer owes the tax",
  "Innergemeinschaftliche Erwerbe 19 %": "Intra-community acquisitions 19%",
  "Innergemeinschaftliche Erwerbe 7 %": "Intra-community acquisitions 7%",
  "Leistungen nach § 13b aus der EU (Bemessungsgrundlage)": "Services under § 13b from the EU (tax base)",
  "Steuer nach § 13b (EU)": "Tax under § 13b (EU)",
  "Andere Leistungen nach § 13b (Bemessungsgrundlage)": "Other services under § 13b (tax base)",
  "Steuer auf andere Leistungen nach § 13b": "Tax on other services under § 13b",
  "Vorsteuer aus Rechnungen": "Input VAT from invoices",
  "Vorsteuer aus innergemeinschaftlichen Erwerben": "Input VAT from intra-community acquisitions",
  "Vorsteuer aus Leistungen nach § 13b": "Input VAT from services under § 13b",
  "Sondervorauszahlung": "Special advance payment",
  "Verbleibende Vorauszahlung (oder Überschuss)": "Remaining advance payment (or surplus)",
  "Art": "Type",
  "Rechnung, Gutschrift oder Stornorechnung": "Invoice, credit note or cancellation invoice",
  "Rechnungsdatum": "Invoice date",
  "Gesamtbetrag": "Total amount",
  "Zahlungshinweis": "Payment note",
  "Satz mit Betrag und Frist, fällt bei bezahlten Rechnungen weg": "Sentence with amount and deadline, omitted for paid invoices",
  "Name des Kunden": "Customer name",
  "Absender": "Sender",
  "Ihr Name oder Ihre Firma": "Your name or company",
  "{Art} {Nummer} von {Absender}": "{Art} {Nummer} from {Absender}",
  "Guten Tag,": "Hello,",
  "anbei erhalten Sie unsere {Art} {Nummer} vom {Datum} über {Betrag}.": "please find attached our {Art} {Nummer} of {Datum} for {Betrag}.",
  "{Zahlungshinweis}": "{Zahlungshinweis}",
  "Die {Art} liegt als PDF bei. Die Rechnungsdaten sind darin auch maschinenlesbar enthalten (E-Rechnung).": "The {Art} is attached as a PDF. The invoice data is also included in machine-readable form (e-invoice).",
  "Mit freundlichen Grüßen": "Kind regards",
  "{Absender}": "{Absender}",
  "Bitte zahlen Sie {0} bis zum {1}.": "Please pay {0} by {1}.",
  "den offenen Betrag von": "the open amount of",
  "den Betrag": "the amount",
  "Bitte zahlen Sie den Betrag ohne Abzug.": "Please pay the amount without deduction.",
  "&body=": "&body=",
  "=?UTF-8?B?{0}?=": "=?UTF-8?B?{0}?=",
  "filename=\"{0}\"; filename*=UTF-8''": "filename=\"{0}\"; filename*=UTF-8''",
  "To:": "To:",
  "Subject:": "Subject:",
  "Dies ist eine E-Mail im MIME-Format.": "This is an email in MIME format.",
  "Content-Type: {0}; name=\"{1}\"": "Content-Type: {0}; name=\"{1}\"",
  "Text": "Text",
  "Die XML-Datei ist zu groß.": "The XML file is too large.",
  "Die XML-Datei ist unvollständig.": "The XML file is incomplete.",
  "Die XML-Datei ist fehlerhaft.": "The XML file is faulty.",
  "Die Datei enthält kein XML.": "The file contains no XML.",
  "Stück": "pcs.",
  "Std.": "hrs",
  "Min.": "min",
  "m²": "m²",
  "m³": "m³",
  "Satz": "set",
  "XRechnung": "XRechnung",
  "ZUGFeRD / Factur-X": "ZUGFeRD / Factur-X",
  "E-Rechnung (UBL)": "E-invoice (UBL)",
  "E-Rechnung (CII)": "E-invoice (CII)",
  "Party": "Party",
  "Country": "Country",
  "Contact": "Contact",
  "Percent": "Percent",
  "Item": "Item",
  "Description": "Description",
  "Price": "Price",
  "Note": "Note",
  "URIUniversalCommunication": "URIUniversalCommunication",
  "Content": "Content",
  "Invoice": "Invoice",
  "Betriebseinnahmen als umsatzsteuerlicher Kleinunternehmer (§ 19 UStG)": "Business income as a small business for VAT (§ 19 UStG)",
  "davon nicht steuerbare Umsätze sowie Umsätze nach § 19 Abs. 2 UStG": "of which non-taxable sales and sales under § 19 (2) UStG",
  "Umsatzsteuerpflichtige Betriebseinnahmen": "Business income subject to VAT",
  "Umsatzsteuerfreie, nicht steuerbare und § 13b-Betriebseinnahmen": "VAT-exempt, non-taxable and § 13b business income",
  "Vereinnahmte Umsatzsteuer": "VAT collected",
  "Vom Finanzamt erstattete Umsatzsteuer": "VAT refunded by the tax office",
  "Veräußerung oder Entnahme von Anlagevermögen": "Sale or withdrawal of fixed assets",
  "Private Kfz-Nutzung": "Private use of company car",
  "Sonstige Sach-, Nutzungs- und Leistungsentnahmen": "Other withdrawals of goods, use and services",
  "Auflösung von Rücklagen und Ausgleichsposten": "Release of reserves and adjustment items",
  "Summe Betriebseinnahmen": "Total business income",
  "Betriebsausgabenpauschale für bestimmte Berufsgruppen": "Flat-rate business expenses for certain professions",
  "Waren, Rohstoffe und Hilfsstoffe": "Goods, raw materials and supplies",
  "Bezogene Fremdleistungen": "Purchased third-party services",
  "Ausgaben für eigenes Personal": "Expenses for own staff",
  "AfA auf Grundstücke und grundstücksgleiche Rechte": "Depreciation on land and equivalent rights",
  "AfA auf immaterielle Wirtschaftsgüter": "Depreciation on intangible assets",
  "AfA auf bewegliche Wirtschaftsgüter": "Depreciation on movable assets",
  "Geringwertige Wirtschaftsgüter (§ 6 Abs. 2 EStG)": "Low-value assets (§ 6 (2) EStG)",
  "Auflösung Sammelposten (§ 6 Abs. 2a EStG)": "Release of pooled items (§ 6 (2a) EStG)",
  "Restbuchwerte ausgeschiedener Anlagegüter": "Residual book values of disposed fixed assets",
  "Miete/Pacht für Geschäftsräume": "Rent/lease for business premises",
  "Aufwendungen für doppelte Haushaltsführung": "Expenses for double housekeeping",
  "Sonstige Aufwendungen für betrieblich genutzte Grundstücke": "Other expenses for business properties",
  "Aufwendungen für Telekommunikation": "Telecommunication expenses",
  "Übernachtungs- und Reisenebenkosten bei Geschäftsreisen": "Accommodation and incidental travel costs on business trips",
  "Fortbildungskosten": "Training costs",
  "Rechts- und Steuerberatung, Buchführung": "Legal and tax advice, bookkeeping",
  "Miete/Leasing für bewegliche Wirtschaftsgüter (ohne Kfz)": "Rent/leasing for movable assets (excluding cars)",
  "Erhaltungsaufwendungen (ohne Gebäude und Kfz)": "Maintenance expenses (excluding buildings and cars)",
  "Beiträge, Gebühren, Abgaben und Versicherungen": "Contributions, fees, levies and insurance",
  "Laufende EDV-Kosten": "Ongoing IT costs",
  "Arbeitsmittel (Bürobedarf, Porto, Fachliteratur)": "Work equipment (office supplies, postage, specialist literature)",
  "Abfallbeseitigung und Entsorgung": "Waste removal and disposal",
  "Verpackung und Transport": "Packaging and transport",
  "Werbekosten": "Advertising costs",
  "Schuldzinsen für Anschaffungen des Anlagevermögens": "Interest on loans for fixed asset purchases",
  "Übrige Schuldzinsen": "Other interest on debt",
  "Gezahlte Vorsteuerbeträge": "Input VAT paid",
  "An das Finanzamt gezahlte Umsatzsteuer": "VAT paid to the tax office",
  "Übrige unbeschränkt abziehbare Betriebsausgaben": "Other fully deductible business expenses",
  "Geschenke": "Gifts",
  "Bewirtungsaufwendungen": "Entertainment expenses",
  "Verpflegungsmehraufwendungen": "Additional meal allowances",
  "Häusliches Arbeitszimmer": "Home office",
  "Tagespauschale für die Tätigkeit in der häuslichen Wohnung": "Daily allowance for working at home",
  "Sonstige beschränkt abziehbare Betriebsausgaben": "Other partially deductible business expenses",
  "Kfz: Steuern, Versicherungen und Maut": "Car: taxes, insurance and tolls",
  "Kfz und Fahrten: sonstige tatsächliche Kosten (Treibstoff, Reparaturen, ÖPNV)": "Car and trips: other actual costs (fuel, repairs, public transport)",
  "Fahrtkosten für nicht zum Betrieb gehörende Fahrzeuge": "Travel costs for vehicles not belonging to the business",
  "Summe Betriebsausgaben": "Total business expenses",
  "Gewinn/Verlust": "Profit/loss",
  "Idee": "Idea",
  "Frage": "Question",
  "Lob": "Praise",
  "feedback-{0}.jpg": "feedback-{0}.jpg",
  "Rückmeldung ({0}) gespeichert": "Feedback ({0}) saved",
  "Rückmeldung geben": "Give feedback",
  "Was ist Ihnen aufgefallen, was fehlt, was hat Ihnen gefallen? Schreiben Sie einfach los.": "What did you notice, what is missing, what did you like? Just start writing.",
  "Worum geht es?": "What is it about?",
  "Ihre Nachricht": "Your message",
  "Ihre Gedanken in eigenen Worten": "Your thoughts in your own words",
  "Lesen können sie nur wir, nicht andere Nutzer. Übertragen werden Art, Text, Name der Seite, Programmversion und Fenstergröße (und das Foto, wenn Sie es ankreuzen), nichts sonst aus Ihrer Buchhaltung, kein Name und keine E-Mail-Adresse. Bitte schreiben Sie keine Passwörter, Kontonummern, Kundennamen oder anderes hinein, das nicht öffentlich sein soll. Eine Kopie bleibt verschlüsselt auf diesem Gerät.": "Only we can read it, not other users. What is sent: type, text, page name, program version and window size (and the photo if you tick it), nothing else from your accounting, no name and no email address. Please do not write passwords, account numbers, customer names or anything else that should not be public. A copy stays encrypted on this device.",
  "Ihre Rückmeldung geht unverschlüsselt an uns.": "Your feedback is sent to us unencrypted.",
  "Bildschirmfoto der Seite mitsenden": "Include a screenshot of the page",
  "Bildschirmfoto der Seite, auf der Sie waren": "Screenshot of the page you were on",
  "Das Foto zeigt die Seite so, wie Sie sie eben gesehen haben, ohne dieses Fenster. Es kann Zahlen aus Ihrer Buchhaltung zeigen. Es geht nur mit, wenn Sie den Haken setzen, und ist dann für uns sichtbar.": "The photo shows the page as you just saw it, without this window. It may show figures from your accounting. It is only sent if you tick the box, and is then visible to us.",
  "Ein Bildschirmfoto ließ sich in diesem Browser nicht erstellen. Ihre Nachricht können Sie trotzdem abschicken.": "A screenshot could not be created in this browser. You can still send your message.",
  "Sende …": "Sending …",
  "Danke für Ihre Rückmeldung": "Thank you for your feedback",
  "Sie ist bei uns angekommen.": "It has reached us.",
  "Rückmeldung gespeichert": "Feedback saved",
  "Das Senden hat gerade nicht geklappt. Kontovia versucht es später noch einmal.": "Sending did not work just now. Kontovia will try again later.",
  "Nicht gespeichert": "Not saved",
  "text/plain;charset=utf-8": "text/plain;charset=utf-8",
  "Entwicklermenü": "Developer menu",
  "Eingegangen (online)": "Received (online)",
  "gesamt, {0} offen": "total, {0} open",
  "Neu laden": "Reload",
  "Seite:": "Page:",
  "· Version": "· version",
  "Wieder öffnen": "Reopen",
  "Bildschirmfoto zur Rückmeldung": "Screenshot for the feedback",
  "Noch nichts eingegangen.": "Nothing received yet.",
  "small muted": "small muted",
  "Foto nicht verfügbar": "Photo not available",
  "Lade …": "Loading …",
  "Noch einmal versuchen": "Try again",
  "Rückmeldungen gehen beim Absenden online; eine Kopie bleibt auf dem Gerät der Person. Hier sehen und löschen Sie alle. Version {0}.": "Feedback goes online when sent; a copy stays on the person's device. Here you can view and delete all of it. Version {0}.",
  "Alle als Textdatei sichern": "Save all as a text file",
  "nicht gesendet": "not sent",
  "wartet auf Senden": "waiting to be sent",
  "nur hier": "only here",
  "Foto öffnen": "Open photo",
  "Noch keine Rückmeldungen. Sie entstehen über „Feedback“ in der Seitenleiste.": "No feedback yet. It is created via “Feedback” in the sidebar.",
  "Rückmeldung löschen?": "Delete feedback?",
  "Sie wird online samt Foto entfernt, für alle.": "It will be removed online including the photo, for everyone.",
  "Textdatei (JSON)": "Text file (JSON)",
  "Nicht gesichert": "Not saved",
  "Rückmeldung abgehakt": "Feedback ticked off",
  "Sie wird samt Foto entfernt.": "It will be removed including the photo.",
  "Rückmeldung gelöscht": "Feedback deleted",
  "rueckmeldung-{0}.jpg": "rueckmeldung-{0}.jpg",
  "Foto": "Photo",
  "Umsatzsteuer-Voranmeldung": "VAT return",
  "mit Dauerfristverlängerung (§ 46 UStDV)": "with permanent extension (§ 46 UStDV)",
  "bis zum 10. nach Ablauf des Zeitraums (§ 18 UStG)": "by the 10th after the end of the period (§ 18 UStG)",
  "Sondervorauszahlung {0} und Antrag auf Dauerfristverlängerung": "Special advance payment {0} and application for permanent extension",
  "ein Elftel der Vorauszahlungen des Vorjahres (§ 47 UStDV)": "one eleventh of the previous year's advance payments (§ 47 UStDV)",
  "Einkommensteuer-Vorauszahlung": "Income tax prepayment",
  "laut Vorauszahlungsbescheid (§ 37 EStG)": "according to the prepayment notice (§ 37 EStG)",
  "Gewerbesteuer-Vorauszahlung": "Trade tax prepayment",
  "laut Bescheid der Gemeinde (§ 19 GewStG)": "according to the municipality's notice (§ 19 GewStG)",
  "Zusammenfassende Meldung": "EC sales list",
  "Lieferungen und Leistungen an Unternehmen in der EU, beim Bundeszentralamt für Steuern (§ 18a UStG)": "Supplies and services to businesses in the EU, filed with the Federal Central Tax Office (§ 18a UStG)",
  "Einkommensteuer mit Anlage EÜR": "Income tax with Anlage EÜR",
  "Steuererklärungen": "Tax returns",
  ", mit Steuerberatung bis": ", with a tax advisor by",
  "FREQ=WEEKLY": "FREQ=WEEKLY",
  "FREQ=WEEKLY;INTERVAL=2": "FREQ=WEEKLY;INTERVAL=2",
  "FREQ=MONTHLY": "FREQ=MONTHLY",
  "FREQ=YEARLY": "FREQ=YEARLY",
  ";UNTIL=": ";UNTIL=",
  "RRULE:": "RRULE:",
  "Europe/Berlin": "Europe/Berlin",
  "T{0}:00": "T{0}:00",
  "Zahlungseingang erwartet": "Payment expected",
  "Zahlung fällig": "Payment due",
  "Aus Kontovia: Fälligkeit einer offenen Rechnung. Wird aus der Buchung gepflegt.": "From Kontovia: due date of an open invoice. Maintained from the transaction.",
  "Aus Kontovia: Termin der Veranstaltung zu einer Anzahlung. Wird aus der Buchung gepflegt.": "From Kontovia: date of the event for a down payment. Maintained from the transaction.",
  "läuft-bereits": "läuft-bereits",
  "nicht-verfügbar": "nicht-verfügbar",
  "Der Abgleich würde {0} Termine löschen, das sind ungewöhnlich viele. Er wurde deshalb angehalten. Bitte prüfen Sie den Kalender „Kontovia“ in Google; zum Neuanfang Google Kalender trennen und neu verbinden.": "The sync would delete {0} appointments, which is unusually many. It was therefore stopped. Please check the “Kontovia” calendar in Google; to start over, disconnect Google Calendar and connect it again.",
  "Der Abgleich würde in Ihren weiteren Google-Kalendern {0} Termine löschen, das sind ungewöhnlich viele. Er wurde deshalb angehalten. Bitte prüfen Sie die Kalender; zum Neuanfang die Auswahl unter Einstellungen → Kalender-Abgleich ändern.": "The sync would delete {0} appointments in your other Google calendars, which is unusually many. It was therefore stopped. Please check the calendars; to start over, change the selection under Settings → Calendar sync.",
  "neu aus Google": "new from Google",
  "aus Google geändert": "changed from Google",
  "in Google gelöscht": "deleted in Google",
  "nach Google übertragen": "transferred to Google",
  "alles auf dem gleichen Stand": "everything up to date",
  "Google Kalender:": "Google Calendar:",
  "unbekannter Fehler": "unknown error",
  "Termin(e) nicht übertragen:": "appointment(s) not transferred:",
  "Es fehlt die IBAN.": "The IBAN is missing.",
  "Die IBAN ist ungültig.": "The IBAN is invalid.",
  "Es fehlt der Name des Empfängers.": "The recipient's name is missing.",
  "Der Betrag muss größer als null sein.": "The amount must be greater than zero.",
  "Der Betrag ist zu hoch.": "The amount is too high.",
  "Die BIC ist ungültig.": "The BIC is invalid.",
  "Die Angaben sind zu lang für den GiroCode.": "The details are too long for the GiroCode.",
  "Chrome": "Chrome",
  "Edge": "Edge",
  "Opera": "Opera",
  "Brave": "Brave",
  "Vivaldi": "Vivaldi",
  "Samsung Internet": "Samsung Internet",
};
