/** Wörterbuch Englisch, Teil t05. Quellen: lib/grafikhilfe.js, lib/hinweisblase.js, lib/ics.js, lib/importaktionen.js, lib/kategorisierung.js, lib/kontoauszug.js, lib/koppeln.js, lib/mahnungsaktionen.js, lib/mahnwesen.js. */

export default {
  "Chromium": "Chromium",
  "Firefox": "Firefox",
  "Safari": "Safari",
  "Ihr Browser": "Your browser",
  "microsoft edge": "microsoft edge",
  "google chrome": "google chrome",
  "Die Adressen öffnen Sie in einem normalen Fenster von {0}, nicht im Fenster von Kontovia.": "Open the addresses in a normal {0} window, not in the Kontovia window.",
  "gibt den Grafikchip auf diesem Gerät noch nicht für Webseiten frei. Die Stufen ab Mini brauchen ihn.": "does not yet make the graphics chip on this device available to websites. The levels from Mini upwards need it.",
  "hält den Grafikchip zurück, meist weil die Grafikbeschleunigung aus ist oder der Chip auf seiner Sperrliste steht. Die Stufen ab Mini brauchen ihn.": "is holding back the graphics chip, usually because hardware acceleration is off or the chip is on its block list. The levels from Mini upwards need it.",
  "rechnet hier nur mit einem Ersatz ohne Grafikchip, meist weil die Grafikbeschleunigung aus ist. Die Stufen ab Mini brauchen den echten Chip.": "is only using a software substitute without the graphics chip here, usually because hardware acceleration is off. The levels from Mini upwards need the real chip.",
  "Der Grafikchip hat das Modell nicht geschafft. Meist hilft eine kleinere Stufe. Bremst der Browser den Chip aus, helfen diese Schritte.": "The graphics chip could not handle the model. A smaller level usually helps. If the browser is slowing the chip down, these steps help.",
  "Das Modell lief nicht": "The model did not run",
  "Der Grafikchip ist aus": "The graphics chip is off",
  "Kontovia darf das nicht selbst umstellen, mit ein paar Klicks geht es aber.": "Kontovia is not allowed to change this itself, but it only takes a few clicks.",
  "Adresse kopieren, in einem neuen Tab in die Adresszeile einfügen und Enter drücken.": "Copy the address, paste it into the address bar in a new tab and press Enter.",
  "neu starten": "restart",
  "Alle Fenster von {0} schließen, auch das von Kontovia, und neu öffnen.{1} Danach entsperren Sie Kontovia wie gewohnt, und der Assistent prüft den Grafikchip neu.": "Close all {0} windows, including the Kontovia one, and open it again.{1} Then unlock Kontovia as usual, and the assistant checks the graphics chip again.",
  "Grafikbeschleunigung einschalten": "Turn on hardware acceleration",
  "Dort den Schalter „Grafikbeschleunigung verwenden …“ einschalten (in manchen Fassungen heißt er „Hardwarebeschleunigung“).": "Turn on the switch “Use graphics acceleration …” there (in some versions it is called “hardware acceleration”).",
  "In den Einstellungen des Browsers nach „Beschleunigung“ suchen und den Schalter „Grafikbeschleunigung“ oder „Hardwarebeschleunigung“ einschalten.": "Search the browser settings for “acceleration” and turn on the switch “Graphics acceleration” or “Hardware acceleration”.",
  "Sperrliste übergehen": "Override the block list",
  "Der Browser schaltet den Chip auf manchen Geräten vorsichtshalber ab. {0} Beim markierten Eintrag rechts den angegebenen Wert wählen.": "On some devices the browser turns off the chip as a precaution. {0} Choose the given value on the right of the highlighted entry.",
  "Override software rendering list": "Override software rendering list",
  "Enabled": "Enabled",
  "Grafikchip für Webseiten freigeben": "Enable the graphics chip for websites",
  "Beim markierten Eintrag den angegebenen Wert wählen. „Unsafe“ heißt hier: Der Browser erprobt die Funktion auf diesem System noch. Sie gilt dann für alle Webseiten.": "Choose the given value for the highlighted entry. “Unsafe” here means the browser is still testing the feature on this system. It then applies to all websites.",
  "Unsafe WebGPU Support": "Unsafe WebGPU Support",
  "Unter Linux zusätzlich": "Additionally on Linux",
  "Unter Linux braucht {0} dafür noch diesen Eintrag.": "On Linux, {0} also needs this entry.",
  "Vulkan": "Vulkan",
  "Auf der Seite mit den Einträgen geht das auch mit „Relaunch“ unten rechts.": "On the page with the entries you can also use “Relaunch” at the bottom right.",
  "Läuft der Browser im Hintergrund weiter, beenden Sie ihn über sein Symbol unten rechts in der Taskleiste.": "If the browser keeps running in the background, quit it via its icon at the bottom right of the taskbar.",
  "Klappt es noch nicht?": "Still not working?",
  "Rechtsklick auf die Verknüpfung von Kontovia oder von {0}, dann „Eigenschaften“. Im Feld „Ziel“ ganz ans Ende, nach einem Leerzeichen, diesen Zusatz einfügen und mit „OK“ bestätigen. Danach {1} ganz schließen und über diese Verknüpfung starten.": "Right-click the shortcut of Kontovia or of {0}, then “Properties”. In the “Target” field go to the very end and, after a space, add this addition and confirm with “OK”. Then close {1} completely and start it via this shortcut.",
  "Nachsehen, ob es läuft": "Check whether it works",
  "Unter „Graphics Feature Status“ sollte bei „WebGPU“ „Hardware accelerated“ stehen. Steht dort etwas anderes, schafft der Chip die Modelle nicht. Die Stufe Basis funktioniert trotzdem, ganz ohne Grafikchip.": "Under “Graphics Feature Status”, “WebGPU” should say “Hardware accelerated”. If it says something else, the chip cannot handle the models. The Basic level still works, without any graphics chip.",
  "Hardwarebeschleunigung einschalten": "Turn on hardware acceleration",
  "Unter „Leistung“ das Häkchen bei „Empfohlene Leistungseinstellungen verwenden“ entfernen und „Hardwarebeschleunigung verwenden, wenn verfügbar“ anhaken.": "Under “Performance”, untick “Use recommended performance settings” and tick “Use hardware acceleration when available”.",
  "Die Warnung mit „Risiko akzeptieren und fortfahren“ bestätigen, oben nach dem Eintrag suchen und ihn mit einem Doppelklick auf den angegebenen Wert stellen.": "Confirm the warning with “Accept the risk and continue”, search for the entry at the top and set it to the given value by double-clicking.",
  "Auf derselben Seite auch diesen Eintrag suchen und auf den angegebenen Wert stellen.": "On the same page, also search for this entry and set it to the given value.",
  "iOS aktualisieren": "Update iOS",
  "macOS aktualisieren": "Update macOS",
  "Ab iOS 26 gibt Safari den Grafikchip von selbst frei. Aktualisieren unter Einstellungen › Allgemein › Softwareupdate.": "From iOS 26, Safari makes the graphics chip available by itself. Update under Settings › General › Software Update.",
  "Ab macOS 26 gibt Safari den Grafikchip von selbst frei. Aktualisieren unter Systemeinstellungen › Allgemein › Softwareupdate.": "From macOS 26, Safari makes the graphics chip available by itself. Update under System Settings › General › Software Update.",
  "Oder in Safari einschalten": "Or turn it on in Safari",
  "Einstellungen › Apps › Safari › Erweitert › Funktionsflags (auf älteren Geräten „Experimentelle Funktionen“), dort den Eintrag einschalten.": "Settings › Apps › Safari › Advanced › Feature Flags (on older devices “Experimental Features”), turn on the entry there.",
  "In Safari unter Einstellungen › Erweitert „Funktionen für Webentwickler anzeigen“ anhaken. Dann in der Menüleiste Entwickler › Funktionsflags, dort den Eintrag anhaken.": "In Safari, under Settings › Advanced, tick “Show features for web developers”. Then in the menu bar Develop › Feature Flags, tick the entry there.",
  "Auf dem iPhone oder iPad dazu Safari aus der App-Übersicht nach oben wischen.": "On iPhone or iPad, swipe Safari up out of the app switcher.",
  "Auf dem Mac dazu Safari mit Befehl+Q beenden.": "On a Mac, quit Safari with Command+Q.",
  "Einen anderen Browser nehmen": "Use another browser",
  "Am zuverlässigsten läuft der Assistent in einem aktuellen Chrome oder Edge{0}. Ihre Daten nehmen Sie über die Cloud oder eine Vollsicherung mit. Die Stufe Basis funktioniert auch hier, ganz ohne Grafikchip.": "The assistant runs most reliably in a current Chrome or Edge{0}. Take your data with you via the cloud or a full backup. The Basic level also works here, without any graphics chip.",
  "auf Android": "on Android",
  "Anleitung": "Guide",
  "Kopieren": "Copy",
  "Wert:": "Value:",
  "Anleitung schließen": "Close guide",
  "Schritt {0} von": "Step {0} of",
  "Adresse": "Address",
  "Zusatz": "Addition",
  "Fertig": "Done",
  "Markiert": "Highlighted",
  "Mit Strg+C oder Befehl+C kopieren.": "Copy with Ctrl+C or Command+C.",
  "\\n": "\\n",
  "PRODID:-//Kontovia//Buchhaltung//DE": "PRODID:-//Kontovia//Buchhaltung//DE",
  "X-WR-CALNAME:": "X-WR-CALNAME:",
  "UID:": "UID:",
  "DTSTAMP:": "DTSTAMP:",
  "DTSTART;VALUE=DATE:": "DTSTART;VALUE=DATE:",
  "DTEND;VALUE=DATE:": "DTEND;VALUE=DATE:",
  "DTSTART:{0}T": "DTSTART:{0}T",
  "DTEND:{0}T": "DTEND:{0}T",
  "SUMMARY:": "SUMMARY:",
  "LOCATION:": "LOCATION:",
  "DESCRIPTION:": "DESCRIPTION:",
  "RECURRENCE-ID": "RECURRENCE-ID",
  "Bitte ein Zahlungskonto wählen.": "Please choose a payment account.",
  "Dieser Umsatz ist schon importiert.": "This transaction has already been imported.",
  "Die Währung {0} lässt sich nicht buchen, nur Euro.": "The currency {0} cannot be booked, only euro.",
  "Das Datum liegt im festgeschriebenen Zeitraum.": "The date is in the locked period.",
  "Es ist keine Rechnung gewählt.": "No invoice is selected.",
  "Die Rechnung gibt es nicht mehr.": "The invoice no longer exists.",
  "Rechnung {0} hat nichts mehr offen.": "Invoice {0} has nothing left open.",
  "Die Mahnkosten sind höher als offen.": "The reminder costs are higher than the open amount.",
  "Teilzahlung nicht möglich: Die Rechnung liegt im festgeschriebenen Zeitraum.": "Partial payment not possible: the invoice is in the locked period.",
  "Teilzahlung nicht möglich: Die Rechnung hat mehrere offene Buchungen (mehrere Steuersätze). Bitte die Zahlung in der Rechnung vermerken.": "Partial payment not possible: the invoice has several open transactions (several tax rates). Please record the payment in the invoice.",
  "Der Betrag {0} passt nicht zu den offenen {1}.": "The amount {0} does not match the open {1}.",
  "Die offene Buchung gibt es nicht mehr oder ist schon bezahlt.": "The open transaction no longer exists or has already been paid.",
  "Der Betrag {0} passt nicht zu {1}.": "The amount {0} does not match {1}.",
  "Die wiederkehrende Buchung gibt es nicht mehr.": "The recurring transaction no longer exists.",
  "Zu diesem Termin gibt es die Buchung schon.": "The transaction for this date already exists.",
  "Der Termin liegt im festgeschriebenen Zeitraum.": "The date is in the locked period.",
  "Bitte eine Kategorie wählen.": "Please choose a category.",
  "Die Kategorie passt nicht: {0}.": "The category does not fit: {0}.",
  "Eingänge brauchen eine Einnahme-Kategorie": "incoming payments need an income category",
  "Ausgänge brauchen eine Ausgaben-Kategorie": "outgoing payments need an expense category",
  "Bitte zuordnen oder eine Kategorie wählen.": "Please match it or choose a category.",
  "Zahlungseingang": "Payment received",
  "Zahlungsausgang": "Payment sent",
  "Kontoauszug-Import": "Bank statement import",
  "(Teilzahlung)": "(partial payment)",
  "(Rest)": "(remainder)",
  "Teilzahlung {0} zu Rechnung {1} am {2}, offen bleiben {3} ({4})": "Partial payment {0} for invoice {1} on {2}, {3} remains open ({4})",
  "Rechnung {0} bezahlt am {1}, {2} ({3})": "Invoice {0} paid on {1}, {2} ({3})",
  "bezahlt am {0} ({1})": "paid on {0} ({1})",
  "Mahnkosten {0} zu Rechnung {1}, eingegangen am {2} ({3})": "Reminder costs {0} for invoice {1}, received on {2} ({3})",
  "Ausgabe bezahlt am {0}: {1}, {2} ({3})": "Expense paid on {0}: {1}, {2} ({3})",
  "Wiederkehrende Buchung {0} vom {1}, bezahlt am {2}, {3} ({4})": "Recurring transaction {0} of {1}, paid on {2}, {3} ({4})",
  "Kontoauszug {0} ({1}): {2} neue Buchungen, {3} Zahlungen zugeordnet": "Bank statement {0} ({1}): {2} new transactions, {3} payments matched",
  ", {0} nicht gebucht": ", {0} not booked",
  "Bitte einen Suchtext eintragen.": "Please enter a search text.",
  "Regel „{0}“: {1} enthält „{2}“": "Rule “{0}”: {1} contains “{2}”",
  "Regel gelöscht": "Rule deleted",
  "Vorlage „{0}“ für Kontoauszüge": "Template “{0}” for bank statements",
  "Vorlage gelöscht": "Template deleted",
  "Bankgebühren": "Bank fees",
  "Zinsen": "Interest",
  "Finanzamt": "Tax office",
  "Bargeld": "Cash",
  "Software und Cloud": "Software and cloud",
  "Werbung": "Advertising",
  "Porto und Versand": "Postage and shipping",
  "Telefon und Internet": "Phone and internet",
  "Beratung": "Consulting",
  "Fortbildung": "Training",
  "Versicherungen": "Insurance",
  "Abonnements": "Subscriptions",
  "Unterhaltung": "Entertainment",
  "Essen und Trinken außer Haus": "Eating out",
  "Mobilität": "Mobility",
  "Reisen und Bahn": "Travel and rail",
  "Wohnen": "Housing",
  "Lebensunterhalt": "Living costs",
  "Wie bei Ihren früheren Buchungen mit „{0}“ ({1}-mal {2})": "As with your earlier transactions with “{0}” ({1} times {2})",
  "Erkannt als {0} („{1}“); Vorschlag:": "Recognized as {0} (“{1}”); suggestion:",
  "UTF-8 mit BOM": "UTF-8 with BOM",
  "UTF-16": "UTF-16",
  "UTF-8": "UTF-8",
  "ISO-8859-1": "ISO-8859-1",
  "Windows-1252": "Windows-1252",
  "Buchungstag": "Booking date",
  "Wertstellung": "Value date",
  "Soll (Ausgang)": "Debit (outgoing)",
  "Haben (Eingang)": "Credit (incoming)",
  "Name der Gegenseite": "Counterparty name",
  "Name bei Eingängen (Zahlungspflichtiger)": "Name for incoming payments (payer)",
  "Name bei Ausgängen (Empfänger)": "Name for outgoing payments (payee)",
  "IBAN der Gegenseite": "Counterparty IBAN",
  "BIC der Gegenseite": "Counterparty BIC",
  "Verwendungszweck": "Payment reference",
  "Buchungstext": "Booking text",
  "Referenz": "Reference",
  "Währung": "Currency",
  "Saldo": "Balance",
  "Status (nur „gebucht“ zählt)": "Status (only “booked” counts)",
  "Eigenes Konto (IBAN)": "Own account (IBAN)",
  "kein Datum": "no date",
  "kein Betrag": "no amount",
  "Status „{0}“, noch nicht gebucht": "Status “{0}”, not yet booked",
  "Dt": "Dt",
  "Document": "Document",
  "Das ist keine CAMT-Datei.": "This is not a CAMT file.",
  "Stmt": "Stmt",
  "Rpt": "Rpt",
  "Ntfctn": "Ntfctn",
  "Acct": "Acct",
  "Id": "Id",
  "Othr": "Othr",
  "Ntry": "Ntry",
  "Sts": "Sts",
  "Cd": "Cd",
  "Status": "Status",
  "Amt": "Amt",
  "Prtry": "Prtry",
  "Domn": "Domn",
  "Fmly": "Fmly",
  "Dbtr": "Dbtr",
  "Cdtr": "Cdtr",
  "Ustrd": "Ustrd",
  "Strd": "Strd",
  "Ref": "Ref",
  "Nm": "Nm",
  "Pty": "Pty",
  "Ultmt": "Ultmt",
  "Refs": "Refs",
  "Zeile :61: nicht lesbar": "Line :61: not readable",
  "In der MT940-Datei stehen keine Umsätze.": "The MT940 file contains no transactions.",
  "Kontovia darf die Kamera nicht benutzen. Erlauben Sie es in den Einstellungen Ihres Browsers, oder geben Sie den Code von Hand ein.": "Kontovia is not allowed to use the camera. Allow it in your browser settings, or enter the code manually.",
  "Dieses Gerät hat keine Kamera, die Kontovia öffnen kann. Geben Sie den Code von Hand ein.": "This device has no camera that Kontovia can open. Enter the code manually.",
  "Die Kamera wird gerade von einer anderen App benutzt. Schließen Sie diese und versuchen Sie es noch einmal, oder geben Sie den Code von Hand ein.": "The camera is currently being used by another app. Close it and try again, or enter the code manually.",
  "Die Kamera lässt sich nicht öffnen. Geben Sie den Code von Hand ein.": "The camera cannot be opened. Enter the code manually.",
  "Dieser Code stimmt nicht. Bitte prüfen Sie ihn oder scannen Sie den QR-Code noch einmal.": "This code is not correct. Please check it or scan the QR code again.",
  "Dieser Code wurde schon benutzt. Zeigen Sie auf dem anderen Gerät einen neuen an.": "This code has already been used. Show a new one on the other device.",
  "Auf dem anderen Gerät wurde nichts bestätigt, und der Code ist abgelaufen. Prüfen Sie, dass Sie sich auf beiden Geräten mit demselben Google-Konto angemeldet haben und dass das andere Gerät entsperrt ist und Internet hat. Dann zeigen Sie dort einen neuen Code an.": "Nothing was confirmed on the other device and the code has expired. Check that you signed in with the same Google account on both devices and that the other device is unlocked and online. Then show a new code there.",
  "Die Antwort des anderen Geräts passt nicht zu diesem Code. Zeigen Sie dort einen neuen Code an und scannen Sie ihn noch einmal.": "The other device's answer does not match this code. Show a new code there and scan it again.",
  "Die Anmeldung bei Google gilt nicht mehr. Melden Sie sich bitte neu an; Ihre Daten bleiben dabei, wie sie sind.": "The Google sign-in is no longer valid. Please sign in again; your data stays as it is.",
  "Das Verbinden hat nicht geklappt.": "Connecting did not work.",
  "Nicht erlaubt": "Not allowed",
  "Noch nicht mit Google verbunden": "Not connected to Google yet",
  "Verbinden Sie Kontovia zuerst in den Einstellungen unter Cloud mit Ihrem Google-Konto.": "First connect Kontovia to your Google account in the settings under Cloud.",
  "Neues Gerät hinzufügen": "Add new device",
  "Einen Moment …": "One moment …",
  "Neuen Code anzeigen": "Show new code",
  "Öffnen Sie Kontovia auf dem neuen Gerät und melden Sie sich mit demselben Google-Konto an{0}.": "Open Kontovia on the new device and sign in with the same Google account{0}.",
  "Scannen Sie dort diesen Code mit der Kamera, in Kontovia über „QR-Code scannen“ oder mit der Kamera-App Ihres Handys.": "Scan this code there with the camera, in Kontovia via “Scan QR code” or with your phone's camera app.",
  "Oder den Code von Hand eingeben:": "Or enter the code manually:",
  "Der Code gilt noch {0}. Zeigen Sie ihn niemandem und fotografieren Sie ihn nicht.": "The code is valid for {0} more. Do not show it to anyone and do not photograph it.",
  "Warte auf das neue Gerät.": "Waiting for the new device.",
  "QR-Code zum Verbinden eines neuen Geräts. Alternativ der Code": "QR code for connecting a new device. Alternatively the code",
  "Der Code ist abgelaufen. Zeigen Sie einen neuen an.": "The code has expired. Show a new one.",
  "Die Verbindung wurde unterbrochen, zum Beispiel weil Kontovia zwischendurch gesperrt war. Zeigen Sie einen neuen Code an.": "The connection was interrupted, for example because Kontovia was locked in the meantime. Show a new code.",
  "Eine Anfrage passte nicht zu diesem Code. Zur Sicherheit wurde alles gelöscht. Prüfen Sie auch Datum und Uhrzeit beider Geräte und zeigen Sie dann einen neuen Code an.": "A request did not match this code. For safety, everything was deleted. Also check the date and time on both devices and then show a new code.",
  "Kontovia konnte nicht sicher feststellen, ob es geklappt hat.": "Kontovia could not reliably determine whether it worked.",
  "Sehen Sie auf dem neuen Gerät nach. Zeigt es Ihre Buchhaltung, ist es verbunden, und Sie können es hier in die Liste aufnehmen. Zeigt es sie nicht, zeigen Sie einen neuen Code an.": "Look at the new device. If it shows your accounting, it is connected and you can add it to the list here. If not, show a new code.",
  "Ja, es ist verbunden": "Yes, it is connected",
  "Neues Gerät": "New device",
  "Ein Gerät möchte sich mit Ihrer Buchhaltung verbinden:": "A device wants to connect to your accounting:",
  "meldet sich seit": "has been signing in since",
  "Ist das Ihr Gerät, das Sie gerade in der Hand haben? Dann bestätigen Sie. Das Gerät kann danach Ihre gesamte Buchhaltung öffnen. Kennen Sie es nicht, wählen Sie „Das bin nicht ich“.": "Is this your device that you are holding right now? Then confirm. The device can then open your entire accounting. If you don't recognize it, choose “That's not me”.",
  "Ein Gerät möchte sich verbinden:": "A device wants to connect:",
  "Das bin nicht ich": "That's not me",
  "Ja, verbinden": "Yes, connect",
  "Bestätigt. Das neue Gerät lädt jetzt Ihre Buchhaltung …": "Confirmed. The new device is now loading your accounting …",
  "Bestätigt. Das neue Gerät lädt.": "Confirmed. The new device is loading.",
  "Gerät „{0}“ verbunden": "Device “{0}” connected",
  "Das Gerät hat Ihre Buchhaltung geladen. Künftig gleichen beide Geräte über Ihr Google-Konto ab.": "The device has loaded your accounting. From now on both devices sync via your Google account.",
  "Fertig, „{0}“ ist verbunden.": "Done, “{0}” is connected.",
  "Bedenken Sie: Ein verbundenes Gerät kann Ihre Buchhaltung dauerhaft öffnen, solange es entsperrt ist. Schützen Sie es mit einer Bildschirmsperre. Geht es verloren, lässt sich sein Zugang derzeit nicht einzeln zurückrufen.": "Keep in mind: a connected device can open your accounting permanently as long as it is unlocked. Protect it with a screen lock. If it gets lost, its access currently cannot be revoked individually.",
  "Mit Ihrem anderen Gerät verbinden": "Connect with your other device",
  "Stattdessen Passwort eingeben": "Enter password instead",
  ", dass sich „{0}“ verbinden darf.": "that “{0}” may connect.",
  "Bestätigen Sie jetzt auf Ihrem anderen Gerät": "Now confirm on your other device",
  "Das dauert höchstens ein paar Minuten. Das andere Gerät muss entsperrt sein und Internet haben.": "This takes a few minutes at most. The other device must be unlocked and online.",
  "Warte auf die Bestätigung am anderen Gerät.": "Waiting for confirmation on the other device.",
  "Auf Ihrem anderen Gerät, auf dem Kontovia schon läuft: {0}. Dort erscheint ein QR-Code.": "On your other device where Kontovia is already running: {0}. A QR code appears there.",
  "Einstellungen, Sicherheit, „Neues Gerät hinzufügen“": "Settings, Security, “Add new device”",
  "Name dieses Geräts": "Name of this device",
  "Damit erkennen Sie dieses Gerät auf dem anderen wieder. Er wird nur verschlüsselt übertragen.": "This lets you recognize this device on the other one. It is only transferred encrypted.",
  "Code von Hand eingeben": "Enter code manually",
  "Code vom anderen Gerät": "Code from the other device",
  "ABCD-EFGH-JKLM-NPQR-STUV-WX": "ABCD-EFGH-JKLM-NPQR-STUV-WX",
  "Verbinden": "Connect",
  "Ihre Kamera-App hat ihn an Kontovia übergeben.": "Your camera app passed it to Kontovia.",
  "Der Code liegt bereit.": "The code is ready.",
  "Jetzt verbinden": "Connect now",
  "QR-Code scannen": "Scan QR code",
  "Dieser Browser kann den QR-Code nicht selbst lesen. Öffnen Sie die {0} Ihres Handys und halten Sie sie auf den Code: Sie öffnet Kontovia mit dem Code. Oder geben Sie den Code unten von Hand ein.": "This browser cannot read the QR code itself. Open your phone's {0} and point it at the code: it opens Kontovia with the code. Or enter the code manually below.",
  "Kamera-App": "camera app",
  "Kamerabild zum Scannen des QR-Codes": "Camera image for scanning the QR code",
  "Halten Sie die Kamera auf den QR-Code auf Ihrem anderen Gerät.": "Point the camera at the QR code on your other device.",
  "Fertig, dieses Gerät ist verbunden": "Done, this device is connected",
  "Ihre Buchhaltung liegt jetzt auf diesem Gerät. Sie müssen den Code nicht noch einmal scannen.": "Your accounting is now on this device. You do not need to scan the code again.",
  "Beim nächsten Start können Sie Kontovia mit Fingerabdruck oder Gesicht öffnen, wenn Sie das jetzt einschalten. Sonst geben Sie das Passwort ein.": "Next time you can open Kontovia with your fingerprint or face if you turn it on now. Otherwise you enter the password.",
  "Beim nächsten Start geben Sie das Passwort Ihrer Buchhaltung ein.": "Next time you enter your accounting password.",
  "Später": "Later",
  "Mit Fingerabdruck oder Gesicht öffnen": "Open with fingerprint or face",
  "Eingeschaltet": "Turned on",
  "Beim nächsten Sperren können Sie mit Fingerabdruck oder Gesicht entsperren.": "The next time it locks you can unlock with your fingerprint or face.",
  "Nicht geklappt": "Did not work",
  "Das Passwort funktioniert weiterhin.": "The password still works.",
  "Weitere Geräte": "Other devices",
  "Handy, Tablet oder zweiter Rechner": "Phone, tablet or second computer",
  "Ein verbundenes Gerät kann Ihre Buchhaltung dauerhaft öffnen, solange es entsperrt ist. Auch wenn Sie es hier aus der Liste nehmen: Das Gerät behält, was es schon geladen hat. Einen einzelnen Zugang zurückrufen kann Kontovia derzeit nicht. Schützen Sie Ihre Geräte deshalb mit einer Bildschirmsperre. Die Liste zeigt nur Geräte, die Sie von diesem Gerät aus verbunden haben.": "A connected device can open your accounting permanently as long as it is unlocked. Even if you remove it from the list here, the device keeps what it has already loaded. Kontovia currently cannot revoke a single access. So protect your devices with a screen lock. The list only shows devices you connected from this device.",
  "Gut zu wissen.": "Good to know.",
  "Öffnen Sie Ihre Buchhaltung auch auf einem anderen Gerät: Dort melden Sie sich mit demselben Google-Konto an und scannen einen QR-Code, den Sie hier anzeigen. Weder wir noch Google können Ihre Buchhaltung dabei lesen.": "Open your accounting on another device too: there you sign in with the same Google account and scan a QR code that you show here. Neither we nor Google can read your accounting in the process.",
  "Dafür muss Kontovia zuerst mit Ihrem Google-Konto verbunden sein, unter Daten & Cloud. Danach können Sie hier weitere Geräte hinzufügen.": "For this, Kontovia must first be connected to your Google account, under Data & cloud. After that you can add more devices here.",
  "verbunden am": "connected on",
  "Aus der Liste entfernen": "Remove from list",
  "Gerät „{0}“ aus der Liste entfernt": "Device “{0}” removed from the list",
  "Aus der Liste entfernt": "Removed from the list",
  "Nicht entfernt": "Not removed",
  "„{0}“ aus der Liste entfernen?": "Remove “{0}” from the list?",
  "Das Gerät verschwindet nur aus dieser Liste. Es kann seine geladene Buchhaltung weiter öffnen und sich weiter mit Ihrem Google-Konto abgleichen.": "The device only disappears from this list. It can still open its loaded accounting and keep syncing with your Google account.",
  "Ist das Gerät verloren oder gestohlen, schützt es nur seine eigene Sperre (Passwort, Fingerabdruck, Bildschirmsperre). Einen einzelnen Zugang zurückrufen kann Kontovia derzeit nicht.": "If the device is lost or stolen, only its own lock protects it (password, fingerprint, screen lock). Kontovia currently cannot revoke a single access.",
  "Mahngebühren und Verzugsaufschlag": "Reminder fees and late payment surcharge",
  "Diese Rechnung gibt es nicht mehr.": "This invoice no longer exists.",
  "Diese Rechnung lässt sich nicht mahnen.": "This invoice cannot be reminded.",
  "Es ist nichts mehr offen.": "Nothing is open anymore.",
  "Die Zahlungsfrist liegt nicht": "The payment deadline is not",
  "Die Zahlungsfrist muss nach dem Datum des Schreibens liegen.": "The payment deadline must be after the date of the letter.",
  "zu {0} {1}, {2} €, Gebühr {3} €, Verzugsaufschlag {4} €": "for {0} {1}, {2} €, fee {3} €, late payment surcharge {4} €",
  "Diese Mahnung gibt es nicht mehr.": "This reminder no longer exists.",
  "Zu dieser Mahnung sind schon Mahnkosten gebucht. Bitte zuerst die Buchung stornieren.": "Reminder costs have already been booked for this reminder. Please reverse that transaction first.",
  "zu {0} verworfen": "for {0} discarded",
  "Mahnkosten zu Rechnung": "Reminder costs for invoice",
  "Mahngebühr und Verzugsaufschlag: kein Entgelt für eine Leistung, deshalb ohne Umsatzsteuer.": "Reminder fee and late payment surcharge: not a payment for a service, therefore without VAT.",
  "Es stehen keine Mahnkosten mehr offen.": "There are no more open reminder costs.",
  "Der Betrag passt nicht zu den offenen Mahnkosten.": "The amount does not match the open reminder costs.",
  "Das Zahlungsdatum liegt im festgeschriebenen Zeitraum.": "The payment date is in the locked period.",
  "Zahlungserinnerung": "Payment reminder",
  "Erinnerung": "Reminder",
  "1. Mahnung": "1st reminder",
  "Mahnung_1": "Mahnung_1",
  "2. Mahnung (letzte Frist)": "2nd reminder (final deadline)",
  "2. Mahnung": "2nd reminder",
  "Mahnung_2": "Mahnung_2",
  "Kein Verzugsaufschlag": "No late payment surcharge",
  "Prozent pro Jahr": "Percent per year",
  "Feste Pauschale": "Fixed lump sum",
  "Beides zusammen": "Both together",
  "Privatperson (Verbraucher)": "Private person (consumer)",
  "Ab der ersten Erinnerung oder 30 Tage nach Fälligkeit (gesetzliche Regel)": "From the first reminder or 30 days after the due date (statutory rule)",
  "Ab Fälligkeit (das Zahlungsziel ist mit dem Kunden fest vereinbart)": "From the due date (the payment term is firmly agreed with the customer)",
  "Nur eigene Rechnungen werden gemahnt.": "Only your own invoices can be reminded.",
  "Ein Entwurf wird nicht gemahnt.": "A draft cannot be reminded.",
  "Eine Gutschrift wird nicht gemahnt.": "A credit note cannot be reminded.",
  "Eine Stornorechnung wird nicht gemahnt.": "A cancellation invoice cannot be reminded.",
  "Die Rechnung ist storniert.": "The invoice is reversed.",
  "Die Rechnung ist bezahlt.": "The invoice is paid.",
  "Eine Barzahlung wird nicht gemahnt.": "A cash payment cannot be reminded.",
  "Noch nicht fällig (fällig am {0}).": "Not yet due (due on {0}).",
  "Es ist keine Fälligkeit angegeben.": "No due date is given.",
  "Die Verzugspauschale gibt es nur gegenüber Unternehmen (§ 288 Abs. 5 BGB). Bei einer Privatperson wird sie nicht berechnet.": "The late payment lump sum only applies to businesses (§ 288 (5) BGB). It is not charged to a private person.",
  "Gegenüber Privatpersonen gilt der Basiszinssatz plus 5 Prozentpunkte (§ 288 Abs. 1 BGB). {0} % wirken zu hoch; prüfen Sie den Satz.": "For private persons the base rate plus 5 percentage points applies (§ 288 (1) BGB). {0}% seems too high; check the rate.",
  "Gegenüber Unternehmen gilt der Basiszinssatz plus 9 Prozentpunkte (§ 288 Abs. 2 BGB). {0} % wirken zu hoch; prüfen Sie den Satz.": "For businesses the base rate plus 9 percentage points applies (§ 288 (2) BGB). {0}% seems too high; check the rate.",
  "Gegenüber Privatpersonen darf eine Mahngebühr nur den tatsächlich entstandenen Aufwand abdecken. Pauschalen über wenige Euro sind häufig unwirksam.": "For private persons a reminder fee may only cover the costs actually incurred. Lump sums above a few euros are often invalid.",
  "Erst dieses Schreiben bringt den Kunden in Verzug, wenn kein fester Zahlungstermin vereinbart ist. Seine Kosten lassen sich dann in der Regel nicht verlangen.": "If no fixed payment date was agreed, only this letter puts the customer in default. Its costs can then usually not be claimed.",
  "Der Kunde ist noch nicht in Verzug: Das geschieht mit diesem Schreiben. Ein Aufschlag in Prozent fällt deshalb erst ab jetzt an.": "The customer is not in default yet: that happens with this letter. A percentage surcharge therefore only applies from now on.",
  "Für den Verzugsaufschlag in Prozent ist kein Satz eingestellt.": "No rate is set for the percentage late payment surcharge.",
  "Der Verzugsaufschlag in Prozent ist so klein, dass er auf null Cent rundet.": "The percentage late payment surcharge is so small that it rounds to zero cents.",
  "Die Zahlungsfrist liegt nicht nach dem Datum des Schreibens.": "The payment deadline is not after the date of the letter.",
  "Sehr geehrte Damen und Herren, bei der Durchsicht unserer Buchhaltung ist uns aufgefallen, dass die unten genannte Rechnung noch nicht bezahlt ist. Vielleicht ist die Zahlung nur untergegangen. Wir bitten Sie, {betrag} bis zum {frist} zu überweisen.": "Dear Sir or Madam, while reviewing our accounts we noticed that the invoice below has not yet been paid. Perhaps the payment was simply overlooked. Please transfer {betrag} by {frist}.",
  "Sollten Sie inzwischen gezahlt haben, betrachten Sie dieses Schreiben bitte als gegenstandslos. Mit freundlichen Grüßen": "If you have paid in the meantime, please disregard this letter. Kind regards",
  "Sehr geehrte Damen und Herren, den Betrag der unten genannten Rechnung haben wir trotz Fälligkeit bisher nicht erhalten. Wir bitten Sie, {betrag} bis zum {frist} zu überweisen.": "Dear Sir or Madam, despite being due, we have not yet received the amount of the invoice below. Please transfer {betrag} by {frist}.",
  "Sehr geehrte Damen und Herren, unsere bisherigen Schreiben blieben ohne Zahlung. Wir setzen Ihnen deshalb eine letzte Frist: Bitte überweisen Sie {betrag} bis zum {frist}.": "Dear Sir or Madam, our previous letters have not resulted in payment. We are therefore setting you a final deadline: please transfer {betrag} by {frist}.",
  "Nach Ablauf der Frist behalten wir uns vor, die Forderung gerichtlich geltend zu machen. Dadurch entstehen Ihnen weitere Kosten. Sollten Sie inzwischen gezahlt haben, betrachten Sie dieses Schreiben bitte als gegenstandslos. Mit freundlichen Grüßen": "After the deadline has passed, we reserve the right to take legal action to recover the claim. This will result in further costs for you. If you have paid in the meantime, please disregard this letter. Kind regards",
  "Rechnung {0} vom {1}, fällig am": "Invoice {0} of {1}, due on",
  "abzüglich bereits gezahlt": "less amount already paid",
  "Offener Rechnungsbetrag": "Open invoice amount",
  "Mahngebühren früherer Schreiben": "Reminder fees from earlier letters",
  "Mahngebühr ({0})": "Reminder fee ({0})",
};
