/** Wörterbuch Englisch, Teil t06. Quellen: lib/mahnwesen.js, lib/merge.js, lib/pdf.js, lib/pdfausgabe.js, lib/pdfvorschau.js, lib/period.js, lib/popover.js, lib/prefs.js, lib/qr.js, lib/qrlesen.js, lib/rechnung.js, lib/rechnungsaktionen.js, lib/rechnungsdateien.js, lib/rechnungsdruck.js, lib/recht.js. */

export default {
  "Verzugsaufschlag: {0} % pro Jahr auf {1} vom {2} bis {3} ({4})": "Late payment surcharge: {0}% per year on {1} from {2} to {3} ({4})",
  "Verzugsaufschlag (Pauschale)": "Late payment surcharge (lump sum)",
  "Verzugsaufschlag (Pauschale, bereits früher berechnet)": "Late payment surcharge (lump sum, already charged earlier)",
  "abzüglich Mahngebühren, auf die Pauschale angerechnet (§ 288 Abs. 5 BGB)": "less reminder fees, credited against the lump sum (§ 288 (5) BGB)",
  "abzüglich bereits gezahlter Mahnkosten": "less reminder costs already paid",
  "Zu zahlen bis": "Payable by",
  "den Gesamtbetrag von": "the total amount of",
  "Rechnung {0} vom": "Invoice {0} of",
  "Gebühr": "Fee",
  "Aufschlag": "Surcharge",
  "Festschreibung": "Period lock",
  "Wiederkehrende Buchung": "Recurring transaction",
  "Produkt": "Product",
  "Rechnungsvorlage": "Invoice template",
  "Rückmeldung": "Feedback",
  "Regel für Kontoauszüge": "Bank statement rule",
  "Vorlage für Kontoauszüge": "Bank statement template",
  "ELSTER-Meldung": "ELSTER return",
  "· Mahnung Stufe": "· reminder level",
  "· {0} Umsätze": "· {0} transactions",
  "Voranmeldung {0}/": "VAT return {0}/",
  "Auf dem anderen Gerät gelöscht, hier aber geändert. Der Datensatz bleibt erhalten.": "Deleted on the other device but changed here. The record is kept.",
  "Hier gelöscht, auf dem anderen Gerät aber geändert. Der Datensatz kommt zurück.": "Deleted here but changed on the other device. The record comes back.",
  "Firmendaten oder steuerliche Einstellungen": "Company details or tax settings",
  "Von einem Gerät mit älterer Fassung von Kontovia.": "From a device with an older version of Kontovia.",
  "aus der Cloud übernommen": "adopted from the cloud",
  "lokale Änderungen behalten": "local changes kept",
  "gelöscht": "deleted",
  "Konflikt": "Conflict",
  "nichts zu tun": "nothing to do",
  "BT /{0} {1} Tf {2} rg 1 0 0 1 {3} {4} Tm {5} Tj ET": "BT /{0} {1} Tf {2} rg 1 0 0 1 {3} {4} Tm {5} Tj ET",
  "w {0} RG {1} {2} m {3} {4} l S": "w {0} RG {1} {2} m {3} {4} l S",
  "rg {0} w {1} RG {2} B": "rg {0} w {1} RG {2} B",
  "rg {0} f": "rg {0} f",
  "w {0} RG {1} S": "w {0} RG {1} S",
  "D:{0}{1}{2}{3}{4}{5}{6}{7}'{8}'": "D:{0}{1}{2}{3}{4}{5}{6}{7}'{8}'",
  "Helvetica": "Helvetica",
  "Helvetica-Bold": "Helvetica-Bold",
  "Helvetica-Oblique": "Helvetica-Oblique",
  "<< /Type /Font /Subtype /Type1 /BaseFont /{0} /Encoding /WinAnsiEncoding /FirstChar 32 /LastChar 255 /Widths [{1}] >>": "<< /Type /Font /Subtype /Type1 /BaseFont /{0} /Encoding /WinAnsiEncoding /FirstChar 32 /LastChar 255 /Widths [{1}] >>",
  "<< /Font << /F1 {0} 0 R /F2 {1} 0 R /F3 {2} 0 R >> >>": "<< /Font << /F1 {0} 0 R /F2 {1} 0 R /F3 {2} 0 R >> >>",
  "<< /Type /Page /Parent {0} 0 R /MediaBox [0 0 {1} {2}] /Resources {3} /Contents {4} 0 R >>": "<< /Type /Page /Parent {0} 0 R /MediaBox [0 0 {1} {2}] /Resources {3} /Contents {4} 0 R >>",
  "<< /Length {0}{1} >>": "<< /Length {0}{1} >>",
  "/Filter /FlateDecode": "/Filter /FlateDecode",
  "<< /Type /Catalog /Pages {0} 0 R >>": "<< /Type /Catalog /Pages {0} 0 R >>",
  "<< /Type /Pages /Kids [{0}] /Count {1} >>": "<< /Type /Pages /Kids [{0}] /Count {1} >>",
  "0 R": "0 R",
  "<< /Title {0} /Author {1} /Subject {2} /Creator {3} /Producer {4} /CreationDate ({5}) >>": "<< /Title {0} /Author {1} /Subject {2} /Creator {3} /Producer {4} /CreationDate ({5}) >>",
  "%PDF-1.4 %âãÏÓ": "%PDF-1.4 %âãÏÓ",
  "0 obj": "0 obj",
  "0000000000 65535 f": "0000000000 65535 f",
  "00000 n": "00000 n",
  "<< /Size {0} /Root {1} 0 R /Info {2} 0 R /ID [<{3}> <{4}>] >>": "<< /Size {0} /Root {1} 0 R /Info {2} 0 R /ID [<{3}> <{4}>] >>",
  "%%EOF": "%%EOF",
  "PDF-Dokument": "PDF document",
  "stroke=\"{0}\" stroke-width=\"{1}\"": "stroke=\"{0}\" stroke-width=\"{1}\"",
  "Seitenvorschau": "Page preview",
  "Dieser Monat": "This month",
  "Letzter Monat": "Last month",
  "Dieses Quartal": "This quarter",
  "Letztes Quartal": "Last quarter",
  "Dieses Jahr": "This year",
  "Letztes Jahr": "Last year",
  "Gesamter Bestand": "All data",
  "Eigener Zeitraum": "Custom period",
  "Zeitraum wählen:": "Choose period:",
  "Vorheriger Zeitraum:": "Previous period:",
  "Vorheriger Zeitraum": "Previous period",
  "Nächster Zeitraum:": "Next period:",
  "Nächster Zeitraum": "Next period",
  "[data-step=\"{0}\"]": "[data-step=\"{0}\"]",
  "Ganzes Jahr": "Whole year",
  "Zeitraum wählen": "Choose period",
  "Schnellwahl": "Quick choice",
  "Jahr, Quartal oder Monat": "Year, quarter or month",
  "Übernehmen": "Apply",
  "[data-year=\"{0}\"]": "[data-year=\"{0}\"]",
  "[aria-pressed=\"true\"][data-nav], .active[data-nav]": "[aria-pressed=\"true\"][data-nav], .active[data-nav]",
  "[data-nav], button, input": "[data-nav], button, input",
  "Suchen …": "Search …",
  "weitere ohne Treffer": "more without results",
  ", über die Suche erreichbar": ", reachable via search",
  "im Zeitraum": "in the period",
  "1 private Buchung": "1 private transaction",
  "im Zeitraum (Einnahmen {0} €, Ausgaben {1} €).": "in the period (income {0} €, expenses {1} €).",
  "Im Zeitraum gibt es keine privaten Buchungen.": "There are no private transactions in the period.",
  "Die Zahlen enthalten sie jetzt, in Exporte für Finanzamt und Steuerkanzlei gehen sie trotzdem nie.": "The figures now include them; they still never go into exports for the tax office and tax firm.",
  "Sie sind in den Zahlen nicht enthalten.": "They are not included in the figures.",
  "Private einbezogen": "Private included",
  "Private einbeziehen": "Include private",
  "Säulen": "Columns",
  "Linien": "Lines",
  "Aufgelaufen": "Cumulative",
  "Balken": "Bars",
  "Torte": "Pie",
  "Darstellung des Verlaufs": "Trend display",
  "Durchschnitt je Monat als gestrichelte Linie": "Monthly average as a dashed line",
  "Durchschnitt": "Average",
  "Keine Daten": "No data",
  "Für diesen Zeitraum gibt es keine Buchungen.": "There are no transactions for this period.",
  "amount pos": "amount pos",
  "amount neg": "amount neg",
  "data compact": "data compact",
  "neueste zuerst": "newest first",
  "Ergebnis": "Result",
  "Durchschnitt je Monat": "Average per month",
  "({0} Monate)": "({0} months)",
  "Darstellung der Anteile": "Share display",
  "Unbekannte Fehlerkorrekturstufe.": "Unknown error correction level.",
  "Die Daten sind für den QR-Code zu lang.": "The data is too long for the QR code.",
  "Die Kamera lässt sich nicht öffnen.": "The camera cannot be opened.",
  "stück": "piece",
  "Stunde": "Hour",
  "Minute": "Minute",
  "Arbeitstag": "Working day",
  "Pauschale": "Lump sum",
  "sätze": "sets",
  "Paar": "Pair",
  "Packung": "Pack",
  "Pck.": "pk.",
  "Kilogramm": "Kilogram",
  "Gramm": "Gram",
  "Tonne": "Tonne",
  "Meter": "Metre",
  "Kilometer": "Kilometre",
  "Quadratmeter": "Square metre",
  "Kubikmeter": "Cubic metre",
  "Liter": "Litre",
  "Kilowattstunde": "Kilowatt hour",
  "Prozent": "Percent",
  "Teilrechnung": "Partial invoice",
  "Korrekturrechnung": "Corrective invoice",
  "Gutschrift": "Credit note",
  "Mit Umsatzsteuer": "With VAT",
  "Kleinunternehmer (§ 19 UStG)": "Small business (§ 19 UStG)",
  "Steuerbefreiung für Kleinunternehmer nach § 19 UStG: Es wird keine Umsatzsteuer berechnet.": "VAT exemption for small businesses under § 19 UStG: no VAT is charged.",
  "Leistung an Unternehmen in der EU (Steuerschuld beim Kunden)": "Service to a business in the EU (reverse charge)",
  "VATEX-EU-AE": "VATEX-EU-AE",
  "Steuerschuldnerschaft des Leistungsempfängers (Reverse Charge, § 13b UStG).": "Reverse charge: the recipient of the service is liable for the tax (§ 13b UStG).",
  "Leistung an Unternehmen außerhalb der EU": "Service to a business outside the EU",
  "VATEX-EU-O": "VATEX-EU-O",
  "Im Inland nicht steuerbare Leistung (Leistungsort beim Empfänger, § 3a Abs. 2 UStG).": "Service not taxable in Germany (place of supply at the recipient, § 3a (2) UStG).",
  "Steuerschuld beim Kunden im Inland (§ 13b UStG, etwa Bauleistungen)": "Reverse charge within Germany (§ 13b UStG, e.g. construction services)",
  "Steuerschuldnerschaft des Leistungsempfängers (§ 13b UStG).": "Reverse charge: the recipient of the service is liable for the tax (§ 13b UStG).",
  "Innergemeinschaftliche Lieferung (EU)": "Intra-community supply (EU)",
  "VATEX-EU-IC": "VATEX-EU-IC",
  "Steuerfreie innergemeinschaftliche Lieferung (§ 4 Nr. 1b UStG).": "Tax-exempt intra-community supply (§ 4 No. 1b UStG).",
  "Ausfuhr außerhalb der EU": "Export outside the EU",
  "VATEX-EU-G": "VATEX-EU-G",
  "Steuerfreie Ausfuhrlieferung (§ 4 Nr. 1a UStG).": "Tax-exempt export supply (§ 4 No. 1a UStG).",
  "Steuerfrei aus anderem Grund": "Tax-exempt for another reason",
  "Versteuerung nach vereinnahmten Entgelten.": "Taxation based on payments received.",
  "Zahlen Sie nicht innerhalb von 30 Tagen nach Fälligkeit und Zugang dieser Rechnung, kommen Sie ohne weitere Mahnung in Verzug (§ 286 Abs. 3 BGB).": "If you do not pay within 30 days after the due date and receipt of this invoice, you will be in default without further reminder (§ 286 (3) BGB).",
  "Überweisung": "Bank transfer",
  "Bar": "Cash",
  "Karte": "Card",
  "Online-Zahlung (etwa PayPal)": "Online payment (e.g. PayPal)",
  "Deutschland": "Germany",
  "Österreich": "Austria",
  "Schweiz": "Switzerland",
  "Belgien": "Belgium",
  "Bulgarien": "Bulgaria",
  "Zypern": "Cyprus",
  "Tschechien": "Czech Republic",
  "Dänemark": "Denmark",
  "Estland": "Estonia",
  "Spanien": "Spain",
  "Finnland": "Finland",
  "Frankreich": "France",
  "Griechenland": "Greece",
  "Kroatien": "Croatia",
  "Ungarn": "Hungary",
  "Irland": "Ireland",
  "Italien": "Italy",
  "Litauen": "Lithuania",
  "Luxemburg": "Luxembourg",
  "Lettland": "Latvia",
  "Malta": "Malta",
  "Niederlande": "Netherlands",
  "Polen": "Poland",
  "Portugal": "Portugal",
  "Rumänien": "Romania",
  "Schweden": "Sweden",
  "Slowenien": "Slovenia",
  "Slowakei": "Slovakia",
  "Vereinigtes Königreich": "United Kingdom",
  "Norwegen": "Norway",
  "Liechtenstein": "Liechtenstein",
  "Vereinigte Staaten": "United States",
  "Türkei": "Turkey",
  "Sehr geehrte Damen und Herren, vielen Dank für Ihren Auftrag. Wir berechnen Ihnen folgende Leistungen:": "Dear Sir or Madam, thank you for your order. We are invoicing you for the following services:",
  "Bitte überweisen Sie den Betrag unter Angabe der Rechnungsnummer. Mit freundlichen Grüßen": "Please transfer the amount quoting the invoice number. Kind regards",
  "Text vor den Positionen": "Text before the items",
  "Positionen und Summen": "Items and totals",
  "Zahlung, Bank und Steuerhinweise": "Payment, bank and tax notes",
  "Text am Ende": "Text at the end",
  "Bilder der Rechnung": "Invoice images",
  "Zusätzliches Bild": "Additional image",
  "Ihr Text": "Your text",
  "Fälligkeit": "Due date",
  "Ihr Firmenname": "Your company name",
  "Seitenzahl": "Page number",
  "Sie sind gesetzlich verpflichtet, diese Rechnung zwei Jahre lang aufzubewahren (§ 14b Abs. 1 Satz 5 UStG).": "You are legally obliged to keep this invoice for two years (§ 14b (1) sentence 5 UStG).",
  "Den Betrag überweisen wir Ihnen oder verrechnen ihn mit offenen Rechnungen.": "We will transfer the amount to you or offset it against open invoices.",
  "Bei Zahlung innerhalb von {0} Tagen{1} gewähren wir {2} % Skonto.": "If paid within {0} days{1}, we grant a {2}% early payment discount.",
  "(bis {0})": "(by {0})",
  "Der Betrag wurde bar bezahlt.": "The amount was paid in cash.",
  "Zahlbar sofort ohne Abzug.": "Payable immediately without deduction.",
  "Zahlbar ohne Abzug bis zum {0}.": "Payable without deduction by {0}.",
  ". Tag nach Rechnungsdatum": ". day after invoice date",
  "Stornorechnung": "Cancellation invoice",
  "Name Ihres Betriebs fehlt.": "Your business name is missing.",
  "Anschrift Ihres Betriebs ist unvollständig (Straße, PLZ, Ort).": "Your business address is incomplete (street, postcode, city).",
  "Steuernummer oder USt-IdNr. Ihres Betriebs fehlt.": "Your business tax number or VAT ID is missing.",
  "Ihre USt-IdNr. muss mit dem Länderkürzel beginnen, etwa „DE“.": "Your VAT ID must start with the country code, such as “DE”.",
  "Ihre USt-IdNr.:": "Your VAT ID:",
  "Für „{0}“ braucht es Ihre USt-IdNr.": "“{0}” requires your VAT ID.",
  "E-Mail-Adresse Ihres Betriebs fehlt.": "Your business email address is missing.",
  "Telefonnummer Ihres Betriebs fehlt.": "Your business phone number is missing.",
  "Ansprechpartner fehlt.": "Contact person is missing.",
  "Bei Rechnungen bis 250 € nicht vorgeschrieben, die eingebettete E-Rechnung ist dann aber unvollständig.": "Not required for invoices up to €250, but the embedded e-invoice is then incomplete.",
  "Name des Kunden fehlt.": "Customer name is missing.",
  "Straße des Kunden fehlt.": "Customer street is missing.",
  "PLZ und Ort des Kunden fehlen.": "Customer postcode and city are missing.",
  "Land des Kunden fehlt.": "Customer country is missing.",
  "Die E-Mail-Adresse des Kunden sieht unvollständig aus.": "The customer's email address looks incomplete.",
  "E-Mail-Adresse des Kunden fehlt.": "Customer email address is missing.",
  "Leitweg-ID des Kunden fehlt (bei Behörden Pflicht).": "Customer routing ID (Leitweg-ID) is missing (mandatory for public authorities).",
  "Die USt-IdNr. des Kunden muss mit dem Länderkürzel beginnen, etwa „DE“.": "The customer's VAT ID must start with the country code, such as “DE”.",
  "USt-IdNr. des Kunden:": "Customer VAT ID:",
  "Rechnungsdatum fehlt.": "Invoice date is missing.",
  "Leistungszeitraum ist unvollständig.": "Service period is incomplete.",
  "Der Leistungszeitraum endet vor seinem Beginn.": "The service period ends before it starts.",
  "Leistungsdatum fehlt.": "Service date is missing.",
  "Die Rechnungsnummer {0} ist schon vergeben.": "The invoice number {0} is already taken.",
  "Bei einer Korrektur oder Gutschrift sollte die ursprüngliche Rechnung angegeben sein.": "For a correction or credit note, the original invoice should be stated.",
  "Die Rechnung hat noch keine Position.": "The invoice has no items yet.",
  "Position {0}: Bezeichnung fehlt.": "Item {0}: description missing.",
  "Position {0}: Menge fehlt.": "Item {0}: quantity missing.",
  "Position {0}: negativer Preis. Für Nachlässe ist eine negative Menge üblicher.": "Item {0}: negative price. For discounts a negative quantity is more common.",
  "Position {0}: Die Einheit „{1}“ steht in der E-Rechnung als Stück.": "Item {0}: the unit “{1}” appears as piece in the e-invoice.",
  "Position {0}: ungewöhnlicher Steuersatz {1} %.": "Item {0}: unusual tax rate {1}%.",
  "Sie sind als Kleinunternehmer eingestellt, die Rechnung weist aber Umsatzsteuer aus.": "You are set up as a small business, but the invoice shows VAT.",
  "Die Rechnung ist als Kleinunternehmer-Rechnung angelegt, Ihre Einstellungen sagen Regelbesteuerung.": "The invoice was created as a small business invoice, but your settings say standard taxation.",
  "Bei einer steuerfreien Leistung muss der Grund auf der Rechnung stehen.": "For a tax-exempt service the reason must be stated on the invoice.",
  "Bei Steuerschuld des Kunden braucht es seine USt-IdNr.": "For reverse charge the customer's VAT ID is required.",
  "Der Kunde sitzt im Inland. Wählen Sie „Mit Umsatzsteuer“ oder, etwa bei Bauleistungen, „Steuerschuld beim Kunden im Inland“.": "The customer is based in Germany. Choose “With VAT” or, for construction services for example, “Reverse charge within Germany”.",
  "Der Kunde sitzt außerhalb der EU. Wählen Sie „Leistung an Unternehmen außerhalb der EU“.": "The customer is based outside the EU. Choose “Service to a business outside the EU”.",
  "Diese Leistung geht an ein Unternehmen außerhalb der EU. Für Kunden in der EU wählen Sie „Leistung an Unternehmen in der EU“.": "This service goes to a business outside the EU. For customers in the EU choose “Service to a business in the EU”.",
  "Für eine Leistung außerhalb der EU braucht die E-Rechnung Ihre Steuernummer; die USt-IdNr. darf dort nicht stehen.": "For a service outside the EU the e-invoice needs your tax number; the VAT ID must not appear there.",
  "Steuerschuld beim Kunden im Inland gilt nur für Kunden in Deutschland.": "Reverse charge within Germany only applies to customers in Germany.",
  "Für die E-Rechnung braucht es die USt-IdNr. des Kunden.": "The e-invoice requires the customer's VAT ID.",
  "Für eine innergemeinschaftliche Lieferung braucht es die USt-IdNr. des Kunden.": "An intra-community supply requires the customer's VAT ID.",
  "Eine innergemeinschaftliche Lieferung geht in ein anderes EU-Land.": "An intra-community supply goes to another EU country.",
  "Eine Ausfuhrlieferung geht in ein Land außerhalb der EU.": "An export supply goes to a country outside the EU.",
  "Für die Zahlung per Überweisung fehlt Ihre IBAN.": "Your IBAN is missing for payment by bank transfer.",
  "Ihre IBAN ist ungültig. Bitte auf Zahlendreher prüfen.": "Your IBAN is invalid. Please check for transposed digits.",
  "Fälligkeit oder Zahlungsbedingungen fehlen.": "Due date or payment terms are missing.",
  "Für das Skonto fehlt die Frist in Tagen.": "The deadline in days is missing for the early payment discount.",
  "Es ist mehr bezahlt, als die Rechnung ausmacht.": "More has been paid than the invoice amount.",
  "Eine Gutschrift hat normalerweise keine Anzahlung.": "A credit note normally has no down payment.",
  "österreich": "österreich",
  "Storno": "Reversal",
  "Eine ausgestellte Rechnung lässt sich nicht löschen, nur stornieren.": "An issued invoice cannot be deleted, only reversed.",
  "Das Rechnungsdatum liegt im festgeschriebenen Zeitraum. Bitte ein späteres Datum wählen.": "The invoice date is in the locked period. Please choose a later date.",
  "ausgestellt, {0} €,": "issued, {0} €,",
  "Nur eine ausgestellte Rechnung lässt sich stornieren.": "Only an issued invoice can be reversed.",
  "Eine Stornorechnung lässt sich nicht stornieren.": "A cancellation invoice cannot be reversed.",
  "Diese Rechnung ist bereits storniert.": "This invoice has already been reversed.",
  "Storno der Rechnung": "Reversal of invoice",
  "Hiermit stornieren wir die Rechnung {0} vom {1} in voller Höhe.": "We hereby cancel invoice {0} of {1} in full.",
  "Der Betrag wird mit der ursprünglichen Rechnung verrechnet.": "The amount is offset against the original invoice.",
  "Storno durch Rechnung": "Reversed by invoice",
  "bezahlt am": "paid on",
  "Versand vermerkt ({0})": "Sending recorded ({0})",
  "Vorlage": "Template",
  "Das Bild ließ sich nicht umwandeln.": "The image could not be converted.",
  "image/png,image/jpeg,image/webp,image/gif,image/svg+xml": "image/png,image/jpeg,image/webp,image/gif,image/svg+xml",
  "E-Rechnung (XML)": "E-invoice (XML)",
  "Logo": "Logo",
  "Bild": "Image",
  "Briefpapier": "Letterhead",
  "Factur-X/ZUGFeRD-Rechnung": "Factur-X/ZUGFeRD invoice",
  "Alternative": "Alternative",
  "EN 16931": "EN 16931",
  "(Entwurf)": "(draft)",
  "USt-IdNr.": "VAT ID",
  "Rechnungsnr.": "Invoice no.",
  "Kundennr.": "Customer no.",
  "Ihre Bestellung": "Your order",
  "Zahlbar bis": "Payable by",
  "Storno-Nr.": "Cancellation no.",
  "Gutschrift-Nr.": "Credit note no.",
  "Leistungszeitraum": "Service period",
  "Leistungsdatum": "Service date",
  "Leitweg-ID": "Routing ID",
  "Ihre USt-IdNr.": "Your VAT ID",
  "Storno zur": "Cancellation of",
  "Bezug:": "Reference:",
  "Pos.": "Item",
  "Bezeichnung": "Description",
  "Menge": "Qty",
  "Einheit": "Unit",
  "Einzelpreis": "Unit price",
  "USt": "VAT",
  "Gesamt netto": "Total net",
  "Gesamt": "Total",
  "Noch keine Positionen.": "No items yet.",
  "Summe netto": "Subtotal net",
  "zzgl. USt {0} auf": "plus VAT {0} on",
  "USt 0 % auf": "VAT 0% on",
  "Gutschriftbetrag": "Credit amount",
  "abzüglich Anzahlung netto": "less down payment net",
  "abzüglich USt {0} auf die Anzahlung": "less VAT {0} on the down payment",
  "Guthaben": "Credit balance",
  "Noch zu zahlen": "Amount due",
  "Position": "Item",
  "Bankverbindung:": "Bank details:",
  "Mit der Banking-App scannen: Empfänger, IBAN, Betrag und Verwendungszweck sind schon ausgefüllt.": "Scan with your banking app: recipient, IBAN, amount and reference are already filled in.",
  "Zahlungsart:": "Payment method:",
  "Den Betrag von {0} erstatten wir Ihnen.": "We will refund the amount of {0} to you.",
  "Diese Rechnung enthält ihre Daten zusätzlich maschinenlesbar als E-Rechnung ({0}).": "This invoice also contains its data in machine-readable form as an e-invoice ({0}).",
  "ZUGFeRD / Factur-X, Profil EN 16931": "ZUGFeRD / Factur-X, profile EN 16931",
  "Steuernr.": "Tax no.",
  "Geschäftsführung:": "Management:",
  "Tel.": "Tel.",
  "GF:": "MD:",
  "Kontovia ist noch in Entwicklung": "Kontovia is still in development",
  "Diese Fassung ist eine Testversion. Für Ihre Daten, für Datenverlust und für die Richtigkeit von Berechnungen, Auswertungen und Meldungen ans Finanzamt übernehmen wir, soweit gesetzlich zulässig, keine Haftung und keine Gewährleistung. Bewahren Sie Belege und Unterlagen zusätzlich auf, legen Sie regelmäßig Sicherungen an und prüfen Sie Ergebnisse, bevor Sie sie verwenden.": "This version is a test version. To the extent permitted by law, we accept no liability and give no warranty for your data, for data loss or for the correctness of calculations, reports and filings to the tax office. Keep receipts and documents separately as well, create backups regularly and check results before using them.",
  "Testversion ohne Haftung und Gewährleistung für Ihre Daten. Bitte Sicherungen anlegen und Ergebnisse prüfen.": "Test version without liability or warranty for your data. Please create backups and check results.",
  "Mehr dazu": "Learn more",
  "Impressum": "Legal notice",
  "Lizenz der Schrift Geist": "License of the Geist font",
  "Rechtliches": "Legal",
  "Datenschutz": "Privacy",
  "Nutzungsbedingungen, Fassung {0}, zugestimmt": "Terms of use, version {0}, agreed",
  "Die wichtigsten Punkte: Kontovia ersetzt keine Steuerberatung; Sie sind für Ihre Angaben, Ihr Passwort und Ihre Sicherungen verantwortlich; Ihre Daten bleiben verschlüsselt bei Ihnen. Auch die {0} stehen zur Ansicht bereit.": "The key points: Kontovia does not replace tax advice; you are responsible for your details, your password and your backups; your data stays encrypted with you. The {0} are also available to view.",
  "Die Nutzungsbedingungen haben sich geändert.": "The terms of use have changed.",
  "Bitte lesen Sie die Nutzungsbedingungen, bevor Sie Kontovia weiter verwenden.": "Please read the terms of use before you continue using Kontovia.",
  "Ablehnen und sperren": "Decline and lock",
};
