/** Wörterbuch Englisch, Teil t07. Quellen: lib/recht.js, lib/reports.js, lib/richeditor.js, lib/rollen.js, lib/seitenleiste.js, lib/store.js, lib/suche.js, lib/suchindex.js, lib/sync.js, lib/table.js, lib/textbearbeiten.js, lib/ui.js. */

export default {
  "Einverstanden": "Agree",
  "Zufluss-/Abflussprinzip (§ 11 EStG)": "Cash principle (§ 11 EStG)",
  "Zufluss-/Abflussprinzip (§ 11 EStG); die noch offene Zahllast folgt der Soll-Versteuerung (Rechnungsdatum)": "Cash principle (§ 11 EStG); the VAT still payable follows accrual taxation (invoice date)",
  "Keine Einnahmen im Zeitraum": "No income in the period",
  "Keine Ausgaben im Zeitraum": "No expenses in the period",
  "Betriebseinnahmen": "Business income",
  "abzüglich Betriebsausgaben": "less business expenses",
  "vor Steuern": "before taxes",
  "Steuerlich abziehbare Ausgaben (nach Kürzung, z. B. Bewirtung 70 %)": "Tax-deductible expenses (after reduction, e.g. entertainment 70%)",
  "Steuerliches Ergebnis": "Taxable result",
  "Betriebsausgaben": "Business expenses",
  "Privateinlagen": "Private contributions",
  "Privatentnahmen": "Private withdrawals",
  "Nachrichtlich: Umsatzsteuer-Verrechnung mit dem Finanzamt": "For information: VAT settlement with the tax office",
  "Im Zeitraum an das Finanzamt gezahlt": "Paid to the tax office in the period",
  "Vom Finanzamt erstattet": "Refunded by the tax office",
  "Danach noch offene Zahllast des Zeitraums": "VAT still payable for the period afterwards",
  "Diese Zahlungen gleichen nur das Umsatzsteuerkonto aus und sind in der Nettobetrachtung weder Ertrag noch Aufwand. In der Anlage EÜR erscheinen sie dagegen in eigenen Zeilen ({0} und {1}).": "These payments only balance the VAT account and are neither income nor expense in the net view. In the Anlage EÜR, however, they appear in their own lines ({0} and {1}).",
  "Wie diese Zahlen zustande kommen.": "How these figures are calculated.",
  "Grundlage ist das {0}.": "The basis is the {0}.",
  "Als Kleinunternehmer nach § 19 UStG wird durchgehend mit Bruttobeträgen gerechnet; ein Vorsteuerabzug findet nicht statt.": "As a small business under § 19 UStG, gross amounts are used throughout; there is no input VAT deduction.",
  "Einnahmen und Ausgaben sind netto ausgewiesen. Die Umsatzsteuer ist ein durchlaufender Posten und in der Umsatzsteuer-Voranmeldung abgebildet.": "Income and expenses are shown net. VAT is a transitory item and is shown in the VAT return.",
  "Anschaffungen über 800 € netto gehen nicht sofort, sondern über die Abschreibung in das Ergebnis ein.": "Purchases over €800 net are not included in the result immediately but via depreciation.",
  "Gewinn- und Verlustrechnung": "Profit and loss statement",
  "Diese Aufstellung ist eine betriebswirtschaftliche Auswertung und ersetzt keine Steuererklärung.": "This statement is a business evaluation and does not replace a tax return.",
  "Monatsübersicht": "Monthly overview",
  "Betrag in €": "Amount in €",
  "abziehbarer Teil; nicht abziehbar: {0} € (linke Spalte im Formular)": "deductible part; not deductible: {0} € (left column in the form)",
  "So übertragen Sie die Werte.": "How to transfer the values.",
  "Die linke Spalte nennt die Zeilennummer der amtlichen Anlage EÜR (Vordruck {0}). Öffnen Sie in „Mein ELSTER“ das Formular „Einnahmenüberschussrechnung (Anlage EÜR)“ und tragen Sie die Beträge in die gleichnamigen Zeilen ein. Die Beträge folgen dem Zahlungsfluss (§ 11 EStG). Prüfen Sie die Zeilennummern gegen das Formular des jeweiligen Jahres. Sie ändern sich fast jährlich.": "The left column shows the line number of the official Anlage EÜR (form {0}). In “Mein ELSTER”, open the form “Einnahmenüberschussrechnung (Anlage EÜR)” and enter the amounts in the lines of the same name. The amounts follow cash flow (§ 11 EStG). Check the line numbers against the form for the respective year. They change almost every year.",
  "(Zeile {0} abzüglich Zeile {1};": "(line {0} minus line {1};",
  "(Zeile {0} abzüglich Zeile {1}; ohne Korrekturen der Zeilen {2} bis {3})": "(line {0} minus line {1}; without corrections of lines {2} to {3})",
  "Überleitung zum Ergebnis der Gewinn- und Verlustrechnung": "Reconciliation to the profit and loss result",
  "Ergebnis ohne Umsatzsteuer (Nettobetrachtung)": "Result without VAT (net view)",
  "zuzüglich vereinnahmte Umsatzsteuer (Zeile {0})": "plus VAT collected (line {0})",
  "zuzüglich Erstattung vom Finanzamt (Zeile {0})": "plus refund from the tax office (line {0})",
  "abzüglich gezahlte Vorsteuer (Zeile {0})": "less input VAT paid (line {0})",
  "abzüglich an das Finanzamt gezahlte Umsatzsteuer (Zeile {0})": "less VAT paid to the tax office (line {0})",
  "Gewinn laut Anlage EÜR": "Profit according to Anlage EÜR",
  "In der Einnahmen-Überschuss-Rechnung ist die Umsatzsteuer ein durchlaufender Posten, der zeitversetzt wirkt: Sie erhöht den Gewinn, bis die Zahllast an das Finanzamt überwiesen und als Betriebsausgabe erfasst ist. Über mehrere Jahre gleicht sich das aus; die Vorauszahlung für Dezember, gezahlt bis zum 10. Januar, zählt noch im alten Jahr (10-Tage-Regel).": "In the cash-basis income statement, VAT is a transitory item with a time lag: it increases profit until the VAT payable is transferred to the tax office and recorded as a business expense. Over several years this evens out; the advance payment for December, paid by 10 January, still counts in the old year (10-day rule).",
  "10-Tage-Regel.": "10-day rule.",
  "regelmäßig wiederkehrende": "regularly recurring",
  "Zahlung zählt": "payment counts",
  "regelmäßig wiederkehrende {0} im Jahr, zu dem sie gehören, nicht im Jahr der Zahlung (§ 11 EStG):": "regularly recurring {0} in the year they belong to, not in the year of payment (§ 11 EStG):",
  "Buchung steht": "transaction is",
  "vorläufig in Zeile {0} bzw. {1}. Ordnen Sie sie einer Kategorie zu, bevor Sie die Zahlen übernehmen.": "temporarily in line {0} or {1}. Assign it to a category before you use the figures.",
  "Anlage EÜR: Zeilenzuordnung": "Anlage EÜR: line assignment",
  "Kontovia übermittelt nichts an die Finanzverwaltung. Die Übertragung nach ELSTER nehmen Sie selbst vor.": "Kontovia does not transmit anything to the tax authorities. You make the transfer to ELSTER yourself.",
  "Kein Anlagevermögen erfasst.": "No fixed assets recorded.",
  "Anlagenverzeichnis": "Asset register",
  "Lineare Abschreibung monatsgenau ab dem Anschaffungsmonat (§ 7 Abs. 1 Satz 4 EStG); degressiv vom Restwert nach § 7 Abs. 2 EStG (Anschaffung 2020 bis 2022 höchstens 25 %, 04/2024 bis 12/2024 höchstens 20 %, 07/2025 bis 12/2027 höchstens 30 %); Computerhardware und Software auf Wunsch mit einem Jahr Nutzungsdauer voll im Anschaffungsjahr (BMF-Schreiben vom 22.02.2022). Ausgeschiedene Güter werden bis zum Monat des Abgangs abgeschrieben, der Rest ist Restbuchwert. Maßgeblich sind die amtlichen AfA-Tabellen.": "Straight-line depreciation by month from the month of purchase (§ 7 (1) sentence 4 EStG); declining balance on the residual value under § 7 (2) EStG (purchases 2020 to 2022 at most 25%, 04/2024 to 12/2024 at most 20%, 07/2025 to 12/2027 at most 30%); computer hardware and software optionally with a useful life of one year, fully in the year of purchase (BMF letter of 22.02.2022). Disposed assets are depreciated up to the month of disposal, the rest is the residual book value. The official depreciation tables are authoritative.",
  "({0} am {1})": "({0} on {1})",
  "J.": "yrs",
  "Anlagenverzeichnis (§ 4 Abs. 3 Satz 5 EStG)": "Asset register (§ 4 (3) sentence 5 EStG)",
  "Wirtschaftsgut": "Asset",
  "Anschaffung": "Purchase",
  "Kosten": "Cost",
  "Nutzungsdauer": "Useful life",
  "Methode": "Method",
  "AfA im Zeitraum": "Depreciation in period",
  "Restbuchwert": "Residual book value",
  "Kleinunternehmerregelung.": "Small business rule.",
  "Sie führen nach § 19 UStG keine Umsatzsteuer ab und melden keine Voranmeldungen. In Ihren Rechnungen darf keine Umsatzsteuer ausgewiesen sein.": "Under § 19 UStG you do not pay VAT and do not file VAT returns. Your invoices must not show VAT.",
  "Übertragung nach ELSTER.": "Transfer to ELSTER.",
  "Die Nummern links sind die amtlichen Kennzahlen des Formulars „Umsatzsteuer-Voranmeldung“. Tragen Sie die Beträge in die gleichnamigen Felder ein. Bemessungsgrundlagen werden ohne Nachkommastellen abgerundet erwartet, Steuerbeträge mit zwei Nachkommastellen.": "The numbers on the left are the official boxes of the form “Umsatzsteuer-Voranmeldung”. Enter the amounts in the fields of the same name. Tax bases are expected rounded down without decimals, tax amounts with two decimals.",
  "Steuerpflichtige Umsätze (Bemessungsgrundlagen)": "Taxable sales (tax bases)",
  "Umsätze zum Steuersatz von 19 %": "Sales at the 19% tax rate",
  "Umsätze zum Steuersatz von 7 %": "Sales at the 7% tax rate",
  "Innergemeinschaftliche Lieferungen an Abnehmer mit USt-IdNr.": "Intra-community supplies to customers with a VAT ID",
  "Nicht steuerbare sonstige Leistungen (§ 18b Satz 1 Nr. 2 UStG)": "Non-taxable other services (§ 18b sentence 1 No. 2 UStG)",
  "Steuerfreie Umsätze mit Vorsteuerabzug (Ausfuhrlieferungen u. a.)": "Tax-exempt sales with input tax deduction (export supplies etc.)",
  "Nicht steuerbare Umsätze (Leistungsort nicht im Inland)": "Non-taxable sales (place of supply not in Germany)",
  "Steuerpflichtige Umsätze, für die der Leistungsempfänger die Steuer schuldet (§ 13b)": "Taxable sales for which the recipient owes the tax (§ 13b)",
  "Innergemeinschaftliche Erwerbe zum Steuersatz von 19 %": "Intra-community acquisitions at the 19% tax rate",
  "Innergemeinschaftliche Erwerbe zum Steuersatz von 7 %": "Intra-community acquisitions at the 7% tax rate",
  "Sonstige Leistungen aus dem übrigen EU-Gebiet, Steuer schulden Sie (§ 13b Abs. 1)": "Other services from the rest of the EU, you owe the tax (§ 13b (1))",
  "Andere Leistungen, für die Sie die Steuer schulden (§ 13b)": "Other services for which you owe the tax (§ 13b)",
  "Kennzahl 50:": "Box 50:",
  "Davon Minderung wegen Forderungsausfall {0} € (in den Umsätzen oben schon enthalten). Bitte in Mein ELSTER in Kennzahl 50 eintragen; die XML-Datei enthält sie nicht.": "Of which reduction due to bad debt {0} € (already included in the sales above). Please enter it in box 50 in Mein ELSTER; the XML file does not contain it.",
  "Unvollständig:": "Incomplete:",
  "ohne Kategorie": "without a category",
  "ohne Kategorie fehlen in den Kennzahlen. Ordnen Sie sie zu, bevor Sie die Voranmeldung abgeben.": "without a category are missing from the boxes. Assign them before you file the VAT return.",
  "Steuerbeträge": "Tax amounts",
  "Umsatzsteuer auf Umsätze 19 %": "VAT on sales at 19%",
  "Umsatzsteuer auf Umsätze 7 %": "VAT on sales at 7%",
  "Umsatzsteuer zu anderen Steuersätzen": "VAT at other tax rates",
  "Umsatzsteuer aus innergemeinschaftlichen Erwerben": "VAT from intra-community acquisitions",
  "Umsatzsteuer aus Leistungen nach § 13b Abs. 1": "VAT from services under § 13b (1)",
  "Umsatzsteuer aus anderen Leistungen nach § 13b": "VAT from other services under § 13b",
  "Umsatzsteuer gesamt": "Total VAT",
  "Abziehbare Vorsteuer": "Deductible input VAT",
  "Vorsteuerbeträge aus Rechnungen von anderen Unternehmern": "Input VAT amounts from invoices of other businesses",
  "Vorsteuer gesamt": "Total input VAT",
  "Abzug der festgesetzten Sondervorauszahlung (Dauerfristverlängerung)": "Deduction of the assessed special advance payment (permanent extension)",
  "Verbleibende Umsatzsteuer-Vorauszahlung (an das Finanzamt)": "Remaining VAT advance payment (to the tax office)",
  "Verbleibender Überschuss (Erstattung durch das Finanzamt)": "Remaining surplus (refund from the tax office)",
  "In ELSTER:": "In ELSTER:",
  "Kennzahl 83 ergibt dort {0} €, weil ELSTER die Steuer aus den Bemessungsgrundlagen in vollen Euro rechnet. Der Unterschied von {1} € ist gewollt und gleicht sich in der Jahreserklärung aus.": "Box 83 shows {0} € there, because ELSTER calculates the tax from the tax bases in whole euros. The difference of {1} € is intended and evens out in the annual return.",
  "Berechnet nach dem {0};": "Calculated using the {0};",
  "Ist-Prinzip (Besteuerung nach vereinnahmten Entgelten, § 20 UStG)": "cash principle (taxation based on payments received, § 20 UStG)",
  "Berechnet nach dem {0}; die Vorsteuer zählt mit dem Datum der Rechnung. Die Voranmeldung ist bis zum 10. Tag nach Ablauf des Voranmeldungszeitraums zu übermitteln; bei genehmigter Dauerfristverlängerung einen Monat später.": "Calculated using the {0}; input VAT counts with the invoice date. The VAT return must be submitted by the 10th day after the end of the return period; with an approved permanent extension one month later.",
  "(Anschaffung {0})": "(purchase {0})",
  "Vermögensübersicht": "Statement of assets",
  "Stichtag": "Reporting date",
  "Schulden": "Liabilities",
  "Reinvermögen": "Net assets",
  "Vermögen (Aktiva)": "Assets",
  "Kein Anlagevermögen erfasst": "No fixed assets recorded",
  "Summe Anlagevermögen": "Total fixed assets",
  "Umlaufvermögen": "Current assets",
  "Forderungen aus Lieferungen und Leistungen": "Trade receivables",
  "Summe Umlaufvermögen": "Total current assets",
  "Summe Vermögen": "Total assets",
  "Schulden und Reinvermögen (Passiva)": "Liabilities and net assets",
  "Verbindlichkeiten aus Lieferungen und Leistungen": "Trade payables",
  "Umsatzsteuer-Zahllast (laufendes Jahr)": "VAT payable (current year)",
  "Summe Schulden": "Total liabilities",
  "Reinvermögen (Eigenkapital)": "Net assets (equity)",
  "Summe Passiva": "Total liabilities and equity",
  "Entwicklung des Eigenkapitals im laufenden Jahr": "Development of equity in the current year",
  "Ergebnis seit Jahresbeginn": "Result since start of year",
  "Veränderung": "Change",
  "Was diese Übersicht ist und was nicht.": "What this overview is and what it is not.",
  "Bei einer Einnahmen-Überschuss-Rechnung besteht keine Pflicht zur Bilanzierung. Diese Gegenüberstellung zeigt, was dem Betrieb zum Stichtag gehört und was er schuldet. Sie folgt nicht der Gliederung des § 266 HGB und ersetzt keine handelsrechtliche Bilanz. Das Reinvermögen ergibt sich rechnerisch als Vermögen abzüglich Schulden.": "With a cash-basis income statement there is no obligation to prepare a balance sheet. This comparison shows what the business owns and owes on the reporting date. It does not follow the structure of § 266 HGB and does not replace a commercial balance sheet. Net assets are calculated as assets minus liabilities.",
  "Anzahlung {0} %": "Down payment {0}%",
  ", Termin": ", date",
  "[Beleg]": "[Receipt]",
  "Keine Buchungen im Zeitraum": "No transactions in the period",
  "Summe Einnahmen {0} € · Summe Ausgaben {1} €": "Total income {0} € · Total expenses {1} €",
  "Buchungsjournal": "Transaction journal",
  "Beleg-Nr.": "Receipt no.",
  "Vollständige Auflistung aller Geschäftsvorfälle im Zeitraum in zeitlicher Reihenfolge (Grundbuchfunktion). Stornierte Buchungen sind durchgestrichen dargestellt und bleiben zusammen mit ihrer Gegenbuchung nachvollziehbar erhalten.": "Complete list of all business transactions in the period in chronological order (journal function). Reversed transactions are shown struck through and remain traceable together with their contra entry.",
  "Nichts offen": "Nothing open",
  "nicht fällig": "not due",
  "1 bis 30 Tage überfällig": "1 to 30 days overdue",
  "31 bis 60 Tage überfällig": "31 to 60 days overdue",
  "61 bis 90 Tage überfällig": "61 to 90 days overdue",
  "über 90 Tage überfällig": "over 90 days overdue",
  "Forderungen: von Kunden noch nicht bezahlt": "Receivables: not yet paid by customers",
  "Altersstruktur der Forderungen": "Ageing of receivables",
  "Verbindlichkeiten: von Ihnen noch nicht bezahlt": "Payables: not yet paid by you",
  "Altersstruktur der Verbindlichkeiten": "Ageing of payables",
  "Jan": "Jan",
  "Feb": "Feb",
  "Mär": "Mar",
  "Apr": "Apr",
  "Jun": "Jun",
  "Jul": "Jul",
  "Aug": "Aug",
  "Sep": "Sep",
  "Okt": "Oct",
  "Nov": "Nov",
  "Dez": "Dec",
  "Keine {0} in diesen Jahren": "No {0} in these years",
  "Alle": "All",
  ", jeweils vom 1.1. bis": ", each from 1 Jan to",
  ", ganze Jahre": ", whole years",
  "Verlauf über das Jahr:": "Trend over the year:",
  "Die Veränderung vergleicht {0} mit {1}.": "The change compares {0} with {1}.",
  "dem Vorjahr": "the previous year",
  "Mehr Ausgaben sind rot, weniger grün.": "More expenses are red, fewer green.",
  "Die Veränderung vergleicht {0} mit {1}. {2} Gezählt wird wie in der Gewinn- und Verlustrechnung: am Zahlungstag{3}, einschließlich Abschreibungen.": "The change compares {0} with {1}. {2} Counted as in the profit and loss statement: on the payment date{3}, including depreciation.",
  ", brutto (Kleinunternehmer)": ", gross (small business)",
  ", netto": ", net",
  "Bankkonto": "Bank account",
  "Vorgang": "Transaction",
  "Anfangsbestand am": "Opening balance on",
  "Endbestand am": "Closing balance on",
  "Kontenblätter": "Account sheets",
  "Keine Konten angelegt.": "No accounts created.",
  "Bild nicht verfügbar": "Image not available",
  "Das Bild liegt nicht auf diesem Gerät. Nach dem nächsten Abgleich erscheint es hier.": "The image is not on this device. It will appear here after the next sync.",
  "Fett (Strg+B)": "Bold (Ctrl+B)",
  "Kursiv (Strg+I)": "Italic (Ctrl+I)",
  "Unterstrichen (Strg+U)": "Underline (Ctrl+U)",
  "Überschrift": "Heading",
  "Zwischenüberschrift": "Subheading",
  "Liste": "List",
  "Aufzählung": "Bullet list",
  "Nummerierte Liste": "Numbered list",
  "Link": "Link",
  "Link einfügen": "Insert link",
  "Bild einfügen (auch per Strg+V oder Ziehen ins Feld)": "Insert image (also with Ctrl+V or by dragging into the field)",
  "Tx": "Tx",
  "Formatierung entfernen": "Remove formatting",
  "Beschreibung, Notizen, Links, Bilder …": "Description, notes, links, images …",
  "Textformat": "Text format",
  "Adresse des Links": "Link address",
  "Link entfernen": "Remove link",
  "[data-cmd=\"{0}\"]": "[data-cmd=\"{0}\"]",
  "Bild nicht übernommen": "Image not added",
  "Files": "Files",
  "Inhaber": "Owner",
  "Alles": "Everything",
  "Darf alles: Buchungen, Einstellungen, Festschreibung, Sicherungen und die Benutzer verwalten.": "May do everything: transactions, settings, period lock, backups and managing users.",
  "Mitarbeit": "Staff",
  "Buchen": "Bookkeeping",
  "Darf Buchungen, Rechnungen, Kontakte, Termine und Aufgaben bearbeiten. Keine Einstellungen, keine Festschreibung, keine Benutzerverwaltung.": "May edit transactions, invoices, contacts, appointments and tasks. No settings, no period lock, no user management.",
  "Ansehen": "View",
  "Darf alles ansehen, auswerten und exportieren, aber nichts ändern. Gedacht für die Steuerberatung.": "May view, evaluate and export everything, but change nothing. Intended for the tax advisor.",
  "Sie sind als „Nur lesen“ angemeldet und können nichts ändern. Wechseln Sie den Benutzer, wenn Sie etwas ändern möchten.": "You are signed in as “Read only” and cannot change anything. Switch user if you want to change something.",
  "Das darf Ihre Rolle nicht. Einstellungen, Festschreibung, Sicherungen und Benutzer ändert nur ein Inhaber.": "Your role is not allowed to do this. Only an owner changes settings, the period lock, backups and users.",
  "Bitte einen Namen eingeben.": "Please enter a name.",
  "Der Name ist zu lang (höchstens 60 Zeichen).": "The name is too long (at most 60 characters).",
  "Bitte eine Rolle wählen.": "Please choose a role.",
  "Diesen Namen gibt es schon. Bitte einen anderen wählen, damit das Journal die Personen auseinanderhält.": "This name already exists. Please choose another one so the log can tell people apart.",
  "SHA-256": "SHA-256",
  "Seitenleiste anpassen": "Customize sidebar",
  "Nach oben": "Move up",
  "Nach unten": "Move down",
  "Ausblenden": "Hide",
  "Ausgeblendet": "Hidden",
  "Leiste zurücksetzen": "Reset sidebar",
  "Listener-Fehler": "Listener error",
  "Sperr-Haken:": "Lock hook:",
  "Leerer Datenbestand.": "Empty data set.",
  "Die EÜR-Zeilen folgen jetzt den amtlichen Vordrucken 2025 und 2026{0}.": "The EÜR lines now follow the official forms 2025 and 2026{0}.",
  "({0} Kategorien umgestellt)": "({0} categories changed)",
  "Bitte die eigene Zuordnung prüfen: {0}.": "Please check your own assignment: {0}.",
  "Sonderzeichen wie ' & \" < > wurden bis Fassung 1.6 beim Bearbeiten mehrfach umgeschrieben (etwa &amp;#39; statt '). {0} wiederhergestellt.": "Special characters such as ' & \" < > were rewritten several times when editing up to version 1.6 (e.g. &amp;#39; instead of '). {0} restored.",
  "Ein Eintrag ist": "One entry is",
  "Einträge sind": "entries are",
  "unverändert.": "unchanged.",
  "Eine festgeschriebene oder stornierte Buchung bleibt": "A locked or reversed transaction remains",
  "festgeschriebene oder stornierte Buchungen bleiben": "locked or reversed transactions remain",
  "aus einem Storno trägt jetzt das Datum": "from a reversal now carries the date",
  "Eine Gegenbuchung": "A contra entry",
  "aus einem Storno trägt jetzt das Datum der stornierten Buchung. Bisher zählte ein Storno doppelt, die Auswertungen stimmen jetzt.": "from a reversal now carries the date of the reversed transaction. Previously a reversal counted twice; the reports are now correct.",
  "Beleg (Name nicht mehr bekannt)": "Receipt (name no longer known)",
  "Speichern fehlgeschlagen": "Saving failed",
  "Kein Datenbestand geladen.": "No data loaded.",
  "Private Buchung": "Private transaction",
  "Das Datum liegt im festgeschriebenen Zeitraum (bis {0}). Bitte ein späteres Datum wählen.": "The date is in the locked period (until {0}). Please choose a later date.",
  "Die Buchung liegt im festgeschriebenen Zeitraum und lässt sich nur noch stornieren.": "The transaction is in the locked period and can only be reversed.",
  "Die Zahlung lässt sich mit einem Datum nach der Festschreibung eintragen.": "The payment can be recorded with a date after the period lock.",
  "Eine stornierte Buchung und ihre Gegenbuchung lassen sich nicht löschen.": "A reversed transaction and its contra entry cannot be deleted.",
  "Private Buchung gelöscht": "Private transaction deleted",
  "Gelöscht: {0} {1} €,": "Deleted: {0} {1} €,",
  "Diese Buchung ist bereits Teil eines Stornos.": "This transaction is already part of a reversal.",
  "Storno:": "Reversal:",
  "Private Buchung storniert": "Private transaction reversed",
  "Storniert: {0} ({1})": "Reversed: {0} ({1})",
  "ohne Angabe": "not specified",
  "Skonto": "Early payment discount",
  "Forderungsausfall": "Bad debt",
  "Unbekannter Grund zum Ausbuchen.": "Unknown reason for writing off.",
  "Ausbuchen lässt sich nur eine offene Einnahme.": "Only an open income can be written off.",
  "Das Datum liegt im festgeschriebenen Zeitraum. Bitte ein späteres Datum wählen.": "The date is in the locked period. Please choose a later date.",
  "Ausbuchen lässt sich erst ab dem Rechnungsdatum.": "Writing off is only possible from the invoice date.",
  "Private Buchung ausgebucht": "Private transaction written off",
  "ausgebucht: {0}, {1} € am": "written off: {0}, {1} € on",
  "Aufgaben am Termin: {0} gespeichert, {1} entfernt": "Tasks for the appointment: {0} saved, {1} removed",
  "Kalenderabgleich: {0} übernommen, {1} entfernt": "Calendar sync: {0} adopted, {1} removed",
  "wiederkehrende Buchungen angelegt, {0} übersprungen": "recurring transactions created, {0} skipped",
  "Suche": "Search",
  "Buchungen, Rechnungen, Kontakte, Termine, Aufgaben …": "Transactions, invoices, contacts, appointments, tasks …",
  "Esc": "Esc",
  "wählen": "select",
  "öffnen": "open",
  "Mehrere Wörter grenzen ein, auch Beträge und Datum": "Several words narrow it down, amounts and dates too",
  "Nichts gefunden für „{0}“.": "Nothing found for “{0}”.",
  "Den Assistenten fragen": "Ask the assistant",
  "Gehe zu": "Go to",
  "und {0} weitere. Mit mehr Wörtern wird die Liste kürzer.": "and {0} more. More words make the list shorter.",
  "Privat: erscheint nicht in Unterlagen fürs Finanzamt": "Private: does not appear in documents for the tax office",
  "Aktionen": "Actions",
  "Seiten": "Pages",
  "Kontakte": "Contacts",
  "Kontoauszug einlesen": "Import bank statement",
  "Export für Finanzamt und Kanzlei": "Export for tax office and tax firm",
  "Daten übernehmen (Import)": "Import data",
  "Neuer Kontakt": "New contact",
  "Mahnung · {0} · {1} €": "Reminder · {0} · {1} €",
  "Kontovia wurde gesperrt, der Abgleich ist abgebrochen.": "Kontovia was locked, the sync was aborted.",
  "schon auf dem gleichen Stand": "already up to date",
  "Der Abgleich ist mehrfach mit einem anderen Gerät zusammengetroffen. Bitte später erneut versuchen.": "The sync collided with another device several times. Please try again later.",
  "nach-änderung": "nach-änderung",
  "kleinste zuerst": "smallest first",
  "größte zuerst": "largest first",
  "älteste zuerst": "oldest first",
  "A bis Z": "A to Z",
  "Z bis A": "Z to A",
  "Sortieren": "Sort",
  "Nach {0} sortieren": "Sort by {0}",
  ", jetzt": ", currently",
  "Nach {0} filtern": "Filter by {0}",
  "(aktiv)": "(active)",
  "Einträge": "entries",
  "Sortierung wählen": "Choose sorting",
  "Filter": "Filter",
  "Gesetzte Filter": "Active filters",
  "Gefiltert:": "Filtered:",
  "Filter „{0}“ entfernen": "Remove filter “{0}”",
  "Filter entfernen": "Remove filter",
  "Alle Filter zurücksetzen": "Reset all filters",
  "Keine Treffer": "No results",
  "Keine Einträge": "No entries",
  "Keine Zeile passt zu Suche und Filtern.": "No row matches the search and filters.",
  "Filter zurücksetzen": "Reset filters",
  "von {0} Zeilen": "of {0} rows",
  "Weitere {0} zeigen": "Show {0} more",
  "Alle zeigen": "Show all",
  "[data-filter=\"{0}\"]": "[data-filter=\"{0}\"]",
  "Sortieren nach": "Sort by",
  "Reihenfolge": "Order",
  "[data-sort=\"{0}\"]": "[data-sort=\"{0}\"]",
  "th button": "th button",
  "button, a, input, select, label": "button, a, input, select, label",
  ": direkt bearbeiten. Strg+Enter oder Klick daneben beendet, Escape verwirft.": ": edit directly. Ctrl+Enter or clicking elsewhere finishes, Escape discards.",
  "Änderungen verwerfen?": "Discard changes?",
  "Die Eingaben in diesem Fenster wurden noch nicht gespeichert.": "The entries in this window have not been saved yet.",
  "Weiter bearbeiten": "Keep editing",
  "Bestätigen": "Confirm",
  "Wiederholen": "Repeat",
  "Die Eingaben stimmen nicht überein.": "The entries do not match.",
  "Passwort anzeigen": "Show password",
  "Feststelltaste ist aktiv": "Caps Lock is on",
  "input, select, textarea": "input, select, textarea",
  "Passwort verbergen": "Hide password",
  "zum Vorzeitraum": "vs. previous period",
  "Verglichen mit {0} –": "Compared with {0}:",
  ", beide Zeiträume bis zum gleichen Stand (heute: {0})": ", both periods up to the same point (today: {0})",
  "Einnahmen {0} €": "Income {0} €",
  "Ausgaben {0} €": "Expenses {0} €",
  "Ergebnis {0} €": "Result {0} €",
  "Einnahmen, Ausgaben und Ergebnis je Monat": "Income, expenses and result per month",
  "Durchschnitt je Monat ({0} Monate)": "Monthly average ({0} months)",
  "M{0},{1} V{2} Q{3},{4} {5},{6} H{7} Q{8},{9} {10},{11} V{12} Z": "M{0},{1} V{2} Q{3},{4} {5},{6} H{7} Q{8},{9} {10},{11} V{12} Z",
  "Verlauf von Einnahmen, Ausgaben und Ergebnis": "Trend of income, expenses and result",
  "Aufgelaufene Einnahmen, Ausgaben und Ergebnis": "Cumulative income, expenses and result",
  "bis einschließlich": "up to and including",
  "Einnahmen aufgelaufen": "Income cumulative",
  "Ausgaben aufgelaufen": "Expenses cumulative",
  "Ergebnis aufgelaufen": "Result cumulative",
  "Sonstige ({0})": "Other ({0})",
  "Keine Daten vorhanden.": "No data available.",
  "% von {0} €": "% of {0} €",
  "data-pick=\"kat:{0}\" role=\"button\" tabindex=\"0\" title=\"Buchungen dieser Kategorie ansehen\"": "data-pick=\"kat:{0}\" role=\"button\" tabindex=\"0\" title=\"View transactions in this category\"",
  "Anteile": "Shares",
  "M{0} A{1},{2} 0 {3} 1 {4} L{5} A{6},{7} 0 {8} 0 {9} Z": "M{0} A{1},{2} 0 {3} 1 {4} L{5} A{6},{7} 0 {8} 0 {9} Z",
};
