/** Wörterbuch Englisch, Teil t08. Quellen: lib/ui.js, lib/updates.js, lib/util.js, lib/versionen.js. */

export default {
  "M{0},{1} a{2},{3} 0 1 0 {4},0 a{5},{6} 0 1 0 {7},0 Z M{8},{9} a{10},{11} 0 1 1 {12},0 a{13},{14} 0 1 1 {15},0 Z": "M{0},{1} a{2},{3} 0 1 0 {4},0 a{5},{6} 0 1 0 {7},0 Z M{8},{9} a{10},{11} 0 1 1 {12},0 a{13},{14} 0 1 1 {15},0 Z",
  "[data-seg=\"{0}\"] [data-val]": "[data-seg=\"{0}\"] [data-val]",
  "Mio": "M",
  "Update-Hinweis:": "Update notice:",
  "Mehr als zwei Stellen nach dem Komma: gelesen als {0} €. Tausender trennen Sie mit einem Punkt, etwa 1.234,00.": "More than two decimal places: read as {0} €. Separate thousands with a comma, for example 1,234.00.",
  "Mo": "Mon",
  "Di": "Tue",
  "Mi": "Wed",
  "Do": "Thu",
  "Fr": "Fri",
  "Sa": "Sat",
  "So": "Sun",
  "January": "January",
  "February": "February",
  "March": "March",
  "May": "May",
  "June": "June",
  "July": "July",
  "October": "October",
  "December": "December",
  "Mar": "Mar",
  "Oct": "Oct",
  "Dec": "Dec",
  "Mon": "Mon",
  "Tue": "Tue",
  "Wed": "Wed",
  "Thu": "Thu",
  "Fri": "Fri",
  "Sat": "Sat",
  "Sun": "Sun",
  "Ctrl": "Ctrl",
  "Strg": "Ctrl",
  "in {0} Tagen": "in {0} days",
  "vor {0} Tagen": "{0} days ago",
  "Eine deutsche USt-IdNr. besteht aus „DE“ und neun Ziffern.": "A German VAT ID consists of “DE” and nine digits.",
  "Die Prüfziffer passt nicht. Bitte auf Zahlendreher prüfen.": "The check digit does not match. Please check for transposed digits.",
  "Eine USt-IdNr. beginnt mit dem Länderkürzel, etwa „DE“.": "A VAT ID starts with the country code, such as “DE”.",
  "Eine Steuernummer enthält nur Ziffern und Trennzeichen wie / oder Leerzeichen.": "A tax number only contains digits and separators such as / or spaces.",
  "Eine Steuernummer hat zehn bis dreizehn Ziffern.": "A tax number has ten to thirteen digits.",
  "Textcursor in Fenstern": "Text cursor in windows",
  "Behoben: In manchen Fenstern, etwa bei der Sicherung, war der blinkende Textcursor nicht zu sehen.": "Fixed: in some windows, such as the backup, the blinking text cursor was not visible.",
  "Neue Seite mit Tarifen": "New page with plans",
  "Neu: Eine eigene Seite stellt Kontovia vor und zeigt die geplanten Tarife Kostenlos, Standard, Pro und Max.": "New: a separate page introduces Kontovia and shows the planned plans Free, Standard, Pro and Max.",
  "Alles läuft noch im Testbetrieb. Tarife lassen sich noch nicht buchen, und es wird nichts abgerechnet.": "Everything is still in test mode. Plans cannot be booked yet, and nothing is billed.",
  "Der Assistent wird schneller und hilft mehr": "The assistant gets faster and more helpful",
  "Der Assistent antwortet spürbar schneller, weil er im Gespräch nichts doppelt liest. Bricht der Grafikchip ab, startet er bei der nächsten Frage neu.": "The assistant answers noticeably faster because it does not read anything twice in a conversation. If the graphics chip aborts, it restarts with the next question.",
  "Neu: „Was steht heute an?“ zeigt Termine, fällige Aufgaben, Fristen und überfällige Rechnungen auf einen Blick.": "New: “What's on today?” shows appointments, due tasks, deadlines and overdue invoices at a glance.",
  "Fragen zur Bedienung wie „Wie schreibe ich eine Rechnung?“ beantwortet er aus der Hilfe.": "It answers questions about using Kontovia, such as “How do I write an invoice?”, from the help.",
  "„Müller hat bezahlt“ trägt die Zahlung ein, „Mahne das Weingut“ bereitet die Mahnung vor. Gespeichert wird erst, wenn Sie bestätigen.": "“Müller has paid” records the payment, “Send a reminder to the winery” prepares the reminder. Nothing is saved until you confirm.",
  "Er versteht „diese Rechnung“, zeigt Verläufe Monat für Monat, prüft ein Jahr vor der Steuer und liest Anlage EÜR und Abschreibungen.": "It understands “this invoice”, shows trends month by month, checks a year before taxes and reads the Anlage EÜR and depreciation.",
  "Steuer genauer, Rückmeldungen geschützt": "More precise taxes, protected feedback",
  "Wechseln Sie etwa von Kleinunternehmer zu Regelbesteuerung, fragt Kontovia, ab wann. Frühere Jahre bleiben, wie sie waren.": "If you switch, for example, from small business to standard taxation, Kontovia asks from when. Earlier years stay as they were.",
  "Kunden außerhalb der EU, Bauleistungen an deutsche Firmen und Buchungen ohne Kategorie stehen in der Voranmeldung jetzt richtig. Ohne Kategorie fragt Kontovia vor der ELSTER-Datei nach.": "Customers outside the EU, construction services to German companies and transactions without a category now appear correctly in the VAT return. Without a category, Kontovia asks before creating the ELSTER file.",
  "Neu: Skonto und ausgefallene Rechnungen ausbuchen, verkaufte Anlagegüter eintragen, Zahlungen um den Jahreswechsel richtig zuordnen.": "New: write off early payment discounts and bad debts, record sold fixed assets, assign payments around the turn of the year correctly.",
  "Mahnungen rechnen den Verzug erst ab der ersten Erinnerung und ziehen Gebühren von der Pauschale ab. Rechnungen an Privatkunden nennen die 30-Tage-Frist.": "Reminders only calculate default from the first reminder and deduct fees from the lump sum. Invoices to private customers state the 30-day deadline.",
  "Ihre Rückmeldungen und Bildschirmfotos können nur noch wir lesen, nicht andere Nutzer.": "Only we can read your feedback and screenshots now, not other users.",
  "Neuer Speicher für Ihre Buchhaltung": "New storage for your accounting",
  "Ihre Buchhaltung liegt jetzt in einer verschlüsselten Datenbank auf dem Gerät. Gespeichert wird nur noch, was sich geändert hat; so bleibt auch ein großer Bestand flüssig.": "Your accounting is now stored in an encrypted database on the device. Only what has changed is saved; this keeps even large data sets smooth.",
  "Beim ersten Öffnen werden Ihre Daten einmal übernommen und Eintrag für Eintrag geprüft. Der bisherige Stand bleibt als Sicherung erhalten.": "When you first open it, your data is taken over once and checked entry by entry. The previous version is kept as a backup.",
  "Die Cloud bekommt beim ersten Abgleich das neue Format. Die alte Datei geht erst, wenn die neue geprüft angekommen ist, und bleibt als Sicherung. Bitte bald auch die anderen Geräte aktualisieren.": "The cloud gets the new format at the first sync. The old file is only removed once the new one has arrived and been checked, and it is kept as a backup. Please update your other devices soon too.",
  "Das Änderungsjournal verliert keinen Eintrag mehr. Ältere Einträge liegen im Archiv und stehen in jeder Sicherung und in den Unterlagen fürs Finanzamt.": "The change log no longer loses any entries. Older entries are in the archive and are included in every backup and in the documents for the tax office.",
  "Neu unter Einstellungen › Daten & Cloud: Sicherungen auf diesem Gerät ansehen und zurückholen.": "New under Settings › Data & cloud: view and restore backups on this device.",
  "Mit Google entsperren: klarer und sicherer": "Unlock with Google: clearer and safer",
  "„Mit Google entsperren“ schalten Sie jetzt unter Einstellungen › Daten & Cloud ein und aus, direkt bei der Verbindung zu Google.": "You now turn “Unlock with Google” on and off under Settings › Data & cloud, right next to the Google connection.",
  "Dort steht deutlich, dass das ein großes Sicherheitsrisiko ist: Ihre Buchhaltung ist dann nur noch durch das Passwort Ihres Google-Kontos geschützt. Einschalten geht nur mit Bestätigung.": "It clearly states that this is a major security risk: your accounting is then only protected by your Google account password. Turning it on requires confirmation.",
  "Der Sperrbildschirm bietet „Mit Google entsperren“ nur noch dort an, wo es eingeschaltet ist. Geräte, die den Weg schon nutzen, behalten ihn.": "The lock screen only offers “Unlock with Google” where it is turned on. Devices that already use it keep it.",
  "Behoben: Wer den Weg auf einem Gerät ausschaltete, bekam ihn von einem anderen Gerät unbemerkt wieder eingeschaltet.": "Fixed: anyone who turned it off on one device had it turned back on unnoticed by another device.",
  "Hilfe, wenn der Assistent nur Basis anbietet": "Help when the assistant only offers Basic",
  "Gibt Ihr Browser den Grafikchip nicht frei, zeigt der Assistent Schritt für Schritt, wie Sie ihn in genau diesem Browser einschalten.": "If your browser does not make the graphics chip available, the assistant shows step by step how to turn it on in exactly this browser.",
  "Adressen und Einstellungen stehen in der Anleitung zum Kopieren bereit, denn umstellen können Sie sie nur selbst.": "Addresses and settings are ready to copy in the guide, because only you can change them.",
  "Die Anleitung erscheint einmal von selbst. Danach finden Sie sie im Assistenten unter Stufe › Grafikchip freigeben und unter „So funktioniert der Assistent“.": "The guide appears once by itself. After that you find it in the assistant under Level › Enable the graphics chip and under “How the assistant works”.",
  "Umsatzsteuer und Fristen genauer": "More precise VAT and deadlines",
  "Ausfuhren in Länder außerhalb der EU haben beim Buchen einen eigenen Steuerfall und stehen in der Umsatzsteuer-Voranmeldung in der passenden Zeile.": "Exports to countries outside the EU have their own tax case when booking and appear in the right line of the VAT return.",
  "Behoben: Steuerfreie Rechnungen ins Ausland landeten in der Voranmeldung alle in derselben Zeile. Lieferungen in die EU, Ausfuhren und Leistungen, für die der Kunde die Steuer zahlt, stehen jetzt jeweils richtig.": "Fixed: tax-exempt invoices abroad all ended up in the same line of the VAT return. Supplies to the EU, exports and services for which the customer pays the tax now each appear correctly.",
  "Die Fristen der Jahreserklärungen stimmen jetzt auch für die Jahre 2020 bis 2025, mit und ohne Steuerberatung.": "The deadlines for annual returns are now also correct for the years 2020 to 2025, with and without a tax advisor.",
  "Rechnungen als Kleinunternehmer nennen die Steuerbefreiung so, wie es seit 2025 vorgeschrieben ist.": "Invoices as a small business state the tax exemption as required since 2025.",
  "Die Nutzungsbedingungen beschreiben jetzt auch den Assistenten, darum fragt Kontovia einmal neu nach Ihrer Zustimmung. Kleine Knöpfe und Verweise sind leichter zu treffen.": "The terms of use now also describe the assistant, so Kontovia asks for your consent once more. Small buttons and links are easier to hit.",
  "Der Assistent versteht Rückfragen": "The assistant understands follow-up questions",
  "Kurze Rückfragen wie „Und 2023?“ oder „Und im April?“ beantwortet der Assistent jetzt mit der Frage davor und dem neuen Zeitraum.": "The assistant now answers short follow-up questions like “And 2023?” or “And in April?” using the previous question and the new period.",
  "Behoben: Nach „Neues Gespräch“ während einer laufenden Antwort konnte der Assistent nur noch Fehler melden. Er startet sich jetzt selbst neu.": "Fixed: after “New conversation” during a running answer, the assistant could only report errors. It now restarts itself.",
  "Der Assistent, der nur auf Ihrem Gerät rechnet": "The assistant that only calculates on your device",
  "Neu: der Assistent. Fragen Sie in Ihren Worten nach offenen Rechnungen, Umsatz, Umsatzsteuer oder Terminen, oder lassen Sie Buchungen, Aufgaben und Termine vorbereiten. Öffnen mit Strg+J oder über die Seitenleiste.": "New: the assistant. Ask in your own words about open invoices, revenue, VAT or appointments, or have it prepare transactions, tasks and appointments. Open it with Ctrl+J or via the sidebar.",
  "Alles bleibt auf Ihrem Gerät: Fragen und Buchhaltung werden nirgendwohin gesendet. Die Stufe Basis braucht keinen Download, größere Stufen laden ein Sprachmodell einmalig nach Ihrer Zustimmung.": "Everything stays on your device: questions and accounting are not sent anywhere. The Basic level needs no download; larger levels download a language model once after your consent.",
  "Zahlen rechnet immer Kontovia selbst. Unter jeder Antwort sehen Sie, was gesucht und gerechnet wurde. Gespeichert wird erst, wenn Sie im gewohnten Fenster bestätigen.": "Kontovia always calculates figures itself. Below each answer you can see what was searched and calculated. Nothing is saved until you confirm in the usual window.",
  "Der Assistent ist noch in Erprobung und kann eine Frage falsch verstehen.": "The assistant is still being tested and can misunderstand a question.",
  "Hinweis zur Testphase": "Note on the test phase",
  "Kontovia ist noch in Entwicklung. Ein Hinweis auf dem Startbildschirm und eine Leiste über jeder Ansicht erinnern daran, dass es für Ihre Daten noch keine Haftung und keine Gewährleistung gibt.": "Kontovia is still in development. A note on the start screen and a bar above every view remind you that there is no liability and no warranty for your data yet.",
  "Legen Sie bitte regelmäßig Sicherungen an und prüfen Sie Ergebnisse, bevor Sie sie verwenden.": "Please create backups regularly and check results before using them.",
  "Schneller startklar, leichter zu bedienen": "Ready faster, easier to use",
  "Kontovia startet schneller: Die einzelnen Bereiche werden erst geladen, wenn Sie sie öffnen.": "Kontovia starts faster: the individual sections are only loaded when you open them.",
  "Besser mit Tastatur und Bildschirmleser bedienbar: Jedes Eingabefeld trägt seinen Namen, Überschriften sind sauber gegliedert, und kleine Links und Knöpfe sind leichter zu treffen.": "Better to use with keyboard and screen reader: every input field carries its name, headings are cleanly structured, and small links and buttons are easier to hit.",
  "Das Buchungsfenster ist aufgeräumt: Beleg oben, zuletzt verwendete Kategorien zuerst, Kontakte nach Kunden und Lieferanten getrennt. Über „Neue Buchung“ legen Sie eine Buchung auch direkt aus einem Beleg an.": "The transaction window is tidier: receipt at the top, recently used categories first, contacts split into customers and suppliers. Via “New transaction” you can also create a transaction directly from a receipt.",
  "„Von diesem Gerät entfernen“ finden Sie jetzt im Kontomenü oben links, und die Hilfe hat eine Suche.": "“Remove from this device” is now in the account menu at the top left, and the help has a search.",
  "Im Kalender sind Termine in eigenen Farben und die Tage der Nachbarmonate besser lesbar.": "In the calendar, appointments in their own colors and the days of neighboring months are easier to read.",
  "Import und Export an einem Ort, Kacheln schneller verschieben": "Import and export in one place, move tiles faster",
  "Import und Export sind jetzt ein Bereich in der Seitenleiste, mit je einem Reiter.": "Import and export are now one section in the sidebar, each with its own tab.",
  "Halten Sie eine Kachel der Übersicht gedrückt, haben Sie sie sofort in der Hand und können sie an ihren neuen Platz ziehen. Das geht auch am Telefon.": "Press and hold a tile on the overview and you have it in hand right away and can drag it to its new place. This also works on the phone.",
  "Einträge der Seitenleiste lassen sich nach kürzerem Halten verschieben.": "Sidebar entries can be moved after a shorter hold.",
  "Bei Zielen in den Aufgaben steht in einer eigenen Zeile, wann Sie bei Ihrem bisherigen Tempo fertig sind oder wie viele Tage Sie in Verzug wären.": "For goals in tasks, a separate line shows when you will be done at your current pace or how many days you would be behind.",
  "Seitenleiste mit Knopf am Rand, Reiter mit Bewegung": "Sidebar with a button on the edge, tabs with motion",
  "Die Seitenleiste klappen Sie jetzt mit einem kleinen runden Knopf auf ihrer Kante ein und aus. Auch ein Klick auf die Kante selbst genügt.": "You now collapse and expand the sidebar with a small round button on its edge. A click on the edge itself also works.",
  "Beim Ein- und Ausklappen gleitet die Leiste weich auf ihre neue Breite.": "When collapsing and expanding, the bar glides smoothly to its new width.",
  "In der Auswertung, der Hilfe, den Rechnungen, den Aufgaben und überall sonst mit Reitern gleitet die Markierung zum gewählten Reiter.": "In reports, help, invoices, tasks and everywhere else with tabs, the highlight glides to the selected tab.",
  "Auch die kleinen Umschalter, etwa für Einnahme und Ausgabe oder Hell und Dunkel, wechseln jetzt mit Bewegung.": "The small toggles too, such as for income and expense or light and dark, now switch with motion.",
  "In den Einstellungen gleitet der Strich unter dem gewählten Bereich mit.": "In the settings, the line under the selected section glides along.",
  "Kleine Verbesserungen": "Small improvements",
  "Der Knopf zum Einklappen der Seitenleiste sitzt jetzt neben der Suche.": "The button for collapsing the sidebar now sits next to the search.",
  "Die Reiter in den Stammdaten wechseln mit einer gleitenden Markierung.": "The tabs in master data switch with a gliding highlight.",
  "Über den Reitern der Einstellungen scheint beim Scrollen nichts mehr durch.": "Nothing shows through above the settings tabs when scrolling anymore.",
  "Die Zahlen in der Übersicht springen am Ende nicht mehr ein Stück nach unten.": "The figures on the overview no longer jump down a little at the end.",
  "Die Belegquote passt jetzt auch in die kleine Kachel, und die Karten für Einnahmen und Ausgaben haben jeweils ihre eigene Höhe.": "The receipt ratio now also fits in the small tile, and the cards for income and expenses each have their own height.",
  "Seitenleiste nach Ihrem Geschmack": "Sidebar to your taste",
  "Die Seitenleiste lässt sich einklappen: Dann bleiben nur die Symbole, und ein Klick klappt sie wieder aus.": "The sidebar can be collapsed: then only the icons remain, and a click expands it again.",
  "Bereiche lassen sich per Rechtsklick (am Telefon langes Drücken) aus- und einblenden und verschieben. Auch ziehen geht, wenn Sie einen Eintrag kurz halten.": "Sections can be hidden, shown and moved by right-clicking (long press on the phone). Dragging also works if you hold an entry briefly.",
  "Die Einstellungen brauchen weniger Platz: Die Bereiche stehen jetzt als Reiter oben statt in einer breiten Spalte.": "The settings take up less space: the sections are now tabs at the top instead of a wide column.",
  "In der Übersicht zeichnet sich beim Umschalten einer Diagrammart nur noch diese Karte neu. Einnahmen und Ausgaben zeigen weniger Text.": "On the overview, switching a chart type only redraws that card. Income and expenses show less text.",
  "Aufgaben mit Ziel zeigen den Stand als Zahl: eintippen und Enter drücken oder mit den Pfeilen ändern.": "Tasks with a goal show the progress as a number: type it and press Enter or change it with the arrows.",
  "Aufgeräumter: Aufgaben, Einstellungen und Menü am Telefon": "Tidier: tasks, settings and menu on the phone",
  "Die Aufgaben sind übersichtlicher: Jede Gruppe hat ihre eigene Karte, und die Fälligkeit steht immer rechts.": "Tasks are clearer: each group has its own card, and the due date is always on the right.",
  "Die Einstellungen sind in vier Bereiche geteilt. Ein Punkt zeigt, wo noch etwas nicht übernommen ist.": "The settings are split into four sections. A dot shows where something has not been applied yet.",
  "Am Telefon öffnet „Mehr“ jetzt ein Menü von unten statt von links. Ein Wisch nach unten schließt es.": "On the phone, “More” now opens a menu from the bottom instead of from the left. A swipe down closes it.",
  "Kleine Bewegungen helfen beim Orientieren: Abgehakte Aufgaben gleiten aus der Liste, Bereiche blenden sanft ein.": "Small animations help with orientation: completed tasks glide out of the list, sections fade in gently.",
  "Ziele und wiederkehrende Aufgaben": "Goals and recurring tasks",
  "Neue Art von Aufgabe: ein Ziel. Zum Beispiel 20 Seiten in 10 Tagen. Sie tragen ein, was Sie geschafft haben, und sehen, wie viel pro Tag noch nötig ist.": "New type of task: a goal. For example 20 pages in 10 days. You enter what you have done and see how much is still needed per day.",
  "Kontovia zeigt, ob Sie im Plan oder im Rückstand sind, und was bei Ihrem bisherigen Tempo am Ende herauskommt.": "Kontovia shows whether you are on track or behind, and what the result will be at your current pace.",
  "Aufgaben können sich wiederholen, zum Beispiel jede Woche oder jeden Monat. Nach dem Abhaken kommt die nächste von selbst.": "Tasks can repeat, for example every week or every month. After ticking one off, the next one comes by itself.",
  "Senden mit Gmail repariert": "Sending with Gmail fixed",
  "Senden mit Gmail klappt jetzt. Bisher kam nach der Anmeldung „Keine Verbindung zum Server“.": "Sending with Gmail now works. Previously “No connection to the server” appeared after signing in.",
  "Rechnungen direkt mit Gmail oder Outlook senden": "Send invoices directly with Gmail or Outlook",
  "Neu: Rechnungen direkt aus Kontovia senden, über Ihr Gmail- oder Outlook-Konto. Die E-Mail steht danach bei Ihnen unter „Gesendet“.": "New: send invoices directly from Kontovia via your Gmail or Outlook account. The email then appears under “Sent” in your account.",
  "Beim ersten Mal fragt Google oder Microsoft, ob Kontovia in Ihrem Namen senden darf. Lesen kann Kontovia Ihre E-Mails nicht.": "The first time, Google or Microsoft asks whether Kontovia may send in your name. Kontovia cannot read your emails.",
  "Die E-Mail für Ihr E-Mail-Programm landet jetzt gleich im Download-Ordner. Ein Klick darauf öffnet sie.": "The email for your email program now lands straight in the download folder. A click opens it.",
  "Rechnungen per E-Mail senden": "Send invoices by email",
  "Neu: Rechnungen per E-Mail senden. Kontovia schreibt die E-Mail mit Text und PDF, abgeschickt wird sie mit Ihrem eigenen E-Mail-Programm.": "New: send invoices by email. Kontovia writes the email with text and PDF; it is sent with your own email program.",
  "Am Rechner öffnet sich die fertige E-Mail in Outlook, Thunderbird oder Apple Mail. Am Handy geben Sie sie mit „Teilen“ an Ihre Mail-App.": "On a computer, the finished email opens in Outlook, Thunderbird or Apple Mail. On a phone you pass it to your mail app with “Share”.",
  "Den Text der E-Mail legen Sie einmal fest, Nummer, Betrag und Frist setzt Kontovia selbst ein.": "You set the email text once; Kontovia fills in the number, amount and deadline itself.",
  "Auf dem Handy passt die Anmeldeseite wieder ganz auf den Bildschirm.": "On the phone, the sign-in page fits on the screen again.",
  "Daten übernehmen und neue Dateien für ELSTER und Excel": "Import data and new files for ELSTER and Excel",
  "Neu: Unter „Daten übernehmen“ holen Sie Buchungen, Kunden und Produkte aus Ihrem bisherigen Programm, von der Steuerkanzlei, aus Excel oder als Visitenkarten. Was schon da ist, wird nicht doppelt übernommen.": "New: under “Import data” you bring in transactions, customers and products from your previous program, from your tax firm, from Excel or as business cards. Anything already there is not imported twice.",
  "Die Umsatzsteuer-Voranmeldung gibt es als Datei, die „Mein ELSTER“ direkt einliest. Umgekehrt liest Kontovia solche Dateien ein und zeigt, ob sie zu Ihren Buchungen passen.": "The VAT return is available as a file that “Mein ELSTER” reads directly. Conversely, Kontovia reads such files and shows whether they match your transactions.",
  "Neu im Export: eine Excel-Datei mit Buchungen und Auswertungen, Ihre Kontakte als Visitenkarten und die Zusammenfassende Meldung für Lieferungen ins EU-Ausland.": "New in export: an Excel file with transactions and reports, your contacts as business cards and the EC sales list for supplies to other EU countries.",
  "Auf sehr kleinen Handys passt die Buchungsliste wieder ganz auf den Bildschirm.": "On very small phones the transaction list fits on the screen again.",
  "Jahresvergleich, Drucken und ein sicheres Verbinden": "Year comparison, printing and secure connecting",
  "Neu: Unter Auswertungen vergleichen Sie Ausgaben oder Einnahmen über mehrere Jahre, je Kategorie und im Verlauf der Monate. Das laufende Jahr zählt nur bis zum gleichen Tag, damit es fair bleibt.": "New: under Reports you compare expenses or income over several years, by category and over the months. The current year only counts up to the same day, so it stays fair.",
  "Die Buchungsliste lässt sich drucken oder als PDF sichern, genau so, wie Sie sie gerade eingestellt haben.": "The transaction list can be printed or saved as a PDF, exactly as you have just set it up.",
  "Ein weiteres Gerät verbinden: Kontovia meldet nicht mehr zu früh „fehlgeschlagen“. Ist das Gerät trotzdem verbunden, nehmen Sie es mit einem Klick in die Liste auf.": "Connecting another device: Kontovia no longer reports “failed” too early. If the device is connected anyway, you add it to the list with one click.",
  "Fingerabdruck oder Gesicht einrichten klappt auf mehr Geräten, und die Meldungen sagen jetzt, woran es liegt.": "Setting up fingerprint or face works on more devices, and the messages now say what the problem is.",
  "Der leere Knopf unter „Feedback“ in der Seitenleiste ist weg.": "The empty button below “Feedback” in the sidebar is gone.",
  "Zweites Gerät per QR-Code": "Second device via QR code",
  "Neu: Ein zweites Gerät, etwa Ihr Handy, öffnen Sie mit einem QR-Code. Er erscheint am ersten Gerät unter Einstellungen, am Handy scannen Sie ihn. Weder Google noch wir können Ihre Buchhaltung dabei lesen.": "New: you open a second device, such as your phone, with a QR code. It appears on the first device under Settings, and you scan it with the phone. Neither Google nor we can read your accounting in the process.",
  "Es braucht beides, Ihr Google-Konto und den QR-Code. Der Code gilt fünf Minuten und nur einmal, und das erste Gerät fragt nach, bevor das neue hineinkommt.": "It takes both, your Google account and the QR code. The code is valid for five minutes and only once, and the first device asks before the new one gets in.",
  "Unter Einstellungen sehen Sie die Geräte, die Sie von diesem aus verbunden haben.": "Under Settings you see the devices you have connected from this one.",
  "Mit Google verbundene Geräte bestätigen alle 30 Tage von selbst, dass das Konto zugelassen ist. Ohne Internet passiert nichts. Entfernt wird Ihre Buchhaltung nie, ohne dass sie gesichert in der Cloud liegt.": "Devices connected to Google confirm by themselves every 30 days that the account is approved. Without internet nothing happens. Your accounting is never removed unless it is backed up in the cloud.",
  "Benutzer, Rechtliches und richtige Zahlen": "Users, legal matters and correct figures",
  "Die hochzählenden Zahlen auf der Übersicht enden jetzt auf dem richtigen Wert. Vorher liefen sie auf einen falschen zu und sprangen erst am Schluss um.": "The counting figures on the overview now end at the correct value. Previously they ran towards a wrong one and only jumped at the end.",
  "Neu: Benutzer in einem Konto mit Rollen (alles, buchen, nur lesen). Das Änderungsjournal zeigt, wer etwas geändert hat. Konten auf dem Gerät lassen sich umbenennen und entfernen.": "New: users in an account with roles (everything, bookkeeping, read only). The change log shows who changed something. Accounts on the device can be renamed and removed.",
  "Impressum, Nutzungsbedingungen und Datenschutz sind überall erreichbar, auch vor dem Entsperren. Den Nutzungsbedingungen stimmen Sie einmal zu. Beim Löschen der Cloud-Daten verschwindet auch Ihr Anmeldekonto dort.": "Legal notice, terms of use and privacy notice are reachable everywhere, even before unlocking. You agree to the terms of use once. When you delete the cloud data, your sign-in account there disappears too.",
  "Mahnwesen: Sie wählen, ob der Kunde ein Unternehmen oder eine Privatperson ist. Die Pauschale von 40 € gibt es nur bei Unternehmen, und Kontovia warnt vor zu hohen Sätzen.": "Dunning: you choose whether the customer is a business or a private person. The €40 lump sum only applies to businesses, and Kontovia warns about rates that are too high.",
  "Kontoauszug: Kontovia schlägt Kategorien vor (etwa Lebensunterhalt oder Software), nur auf Ihrem Gerät. Eilige buchen auch ohne Kategorie und ordnen später zu. Angekreuzt wird nichts von selbst.": "Bank statement: Kontovia suggests categories (such as living costs or software), only on your device. If you are in a hurry you can also book without a category and assign it later. Nothing is ticked automatically.",
  "Mahnwesen, GiroCode und Kontoauszug einlesen": "Dunning, GiroCode and importing bank statements",
  "Neu: Mahnwesen. Überfällige Rechnungen bekommen mit einem Klick eine Zahlungserinnerung oder Mahnung als PDF, mit Frist, Gebühr und auf Wunsch einem Verzugsaufschlag.": "New: dunning. Overdue invoices get a payment reminder or reminder as a PDF with one click, with deadline, fee and, if you wish, a late payment surcharge.",
  "Rechnungen tragen jetzt einen GiroCode: Wer ihn mit der Banking-App scannt, hat die Überweisung schon ausgefüllt. Im Gestalter lässt er sich abschalten.": "Invoices now carry a GiroCode: anyone who scans it with their banking app has the transfer already filled in. It can be turned off in the designer.",
  "Neu: Kontoauszug einlesen (CSV, CAMT.053 und MT940). Kontovia schlägt vor, welche Zahlung zu welcher Rechnung gehört; gebucht wird erst nach Ihrer Bestätigung.": "New: import bank statements (CSV, CAMT.053 and MT940). Kontovia suggests which payment belongs to which invoice; nothing is booked until you confirm.",
  "Ein schon eingelesener Umsatz wird nie doppelt gebucht, auch nicht bei einer Datei mit überlappendem Zeitraum.": "A transaction that has already been imported is never booked twice, not even with a file covering an overlapping period.",
  "Mahngebühr und Verzugsaufschlag zählen als Einnahme ohne Umsatzsteuer und werden erst gebucht, wenn das Geld eingegangen ist.": "Reminder fees and late payment surcharges count as income without VAT and are only booked once the money has arrived.",
  "Rückmeldefenster überarbeitet": "Feedback window revised",
  "Das Rückmeldefenster ist aufgeräumter. Es sagt vor dem Senden deutlich, dass andere Nutzer Ihre Nachricht lesen können.": "The feedback window is tidier. Before sending it clearly says that other users can read your message.",
  "Das Bild der Seite geht weiterhin nur mit, wenn Sie es selbst ankreuzen.": "The picture of the page is still only sent if you tick it yourself.",
  "Hinweis im Rückmeldefenster": "Note in the feedback window",
  "Das Rückmeldefenster weist jetzt darauf hin, dass Ihre Nachricht nicht vertraulich ist.": "The feedback window now points out that your message is not confidential.",
  "Neues dunkles Aussehen, Bewegung und Rückmeldungen an uns": "New dark look, motion and feedback to us",
  "Das dunkle Aussehen ist neu: ein warmes Graphit mit kräftigerem Akzent. Alle Farben sind auf gute Lesbarkeit geprüft.": "The dark look is new: a warm graphite with a stronger accent. All colors have been checked for good readability.",
  "Seiten, Zahlen, Diagramme, Fenster und Meldungen bewegen sich jetzt weich. Wer Bewegung im System abgestellt hat, sieht davon nichts.": "Pages, figures, charts, windows and messages now move smoothly. If you have turned off motion in your system, you will not see any of it.",
  "Auf dem Handy bleibt die Leiste oben immer gleich groß. Zeitraum und Knöpfe der Seite scrollen einfach mit. Fenster lassen sich am Griff nach unten wegziehen.": "On the phone the bar at the top always stays the same size. Period and page buttons simply scroll along. Windows can be swiped down by their handle.",
  "Mit „Feedback“ senden Sie Ihre Nachricht jetzt wirklich an uns. Ein Bild der Seite geht nur mit, wenn Sie es selbst ankreuzen. Nichts aus Ihrer Buchhaltung wird dabei übertragen.": "With “Feedback” your message now really reaches us. A picture of the page is only sent if you tick it yourself. Nothing from your accounting is transmitted.",
  "Kleine Fehler behoben: Knöpfe im Export liefen über den Rand, auf kleinen Fenstern waren Einstellungen zu eng, und im Rechnungsgestalter gibt es echte Pfeile für Rückgängig und Wiederholen.": "Small bugs fixed: buttons in export ran over the edge, settings were too cramped in small windows, and the invoice designer has real arrows for undo and redo.",
  "Mehrere Konten und Abmelden mit Abgleich": "Several accounts and signing out with sync",
  "Auf einem Gerät können mehrere Konten angemeldet sein, etwa für zwei Betriebe. Ein Klick auf den Namen oben in der Seitenleiste wechselt das Konto oder fügt eines hinzu.": "Several accounts can be signed in on one device, for example for two businesses. A click on the name at the top of the sidebar switches the account or adds one.",
  "Jedes Konto hat sein eigenes Passwort und bleibt von den anderen getrennt. Vor dem Wechsel gleicht Kontovia ab, wenn das Konto mit Google verbunden ist.": "Each account has its own password and stays separate from the others. Before switching, Kontovia syncs if the account is connected to Google.",
  "Beim Abmelden gleicht Kontovia zuerst mit Google ab. Klappt das nicht, etwa ohne Netz, entscheiden Sie: noch einmal versuchen, abbrechen oder trotzdem abmelden.": "When signing out, Kontovia first syncs with Google. If that does not work, for example without a network, you decide: try again, cancel or sign out anyway.",
  "Das Eintippen von „ABMELDEN“ entfällt. Abmelden betrifft nur das offene Konto, die anderen bleiben erhalten.": "Typing “ABMELDEN” is no longer needed. Signing out only affects the open account; the others are kept.",
  "Auf dem Sperrbildschirm sehen Sie, zu welchem Konto das Passwort gehört, und wechseln dort bei Bedarf das Konto.": "On the lock screen you see which account the password belongs to, and you can switch the account there if needed.",
  "Aufgaben mit Text, Bildern und Unteraufgaben": "Tasks with text, images and subtasks",
  "Aufgaben können jetzt formatierten Text mit Überschriften, Listen und Links enthalten, dazu Bilder (auch per Strg+V) und Unteraufgaben, die Sie schon in der Liste abhaken.": "Tasks can now contain formatted text with headings, lists and links, as well as images (also with Ctrl+V) and subtasks that you can tick off right in the list.",
  "Eine Aufgabe lässt sich mit Terminen, Buchungen, Kontakten und Rechnungen verknüpfen. Dort steht sie dann auch, und von dort legen Sie gleich eine neue an. Aufgaben mit Datum erscheinen im Kalender.": "A task can be linked to appointments, transactions, contacts and invoices. It then also appears there, and from there you can create a new one right away. Tasks with a date appear in the calendar.",
  "Wie weit die Aufgabenliste vorausschaut, wählen Sie selbst: 7 Tage, 4 Wochen, 1 Monat oder einen eigenen Zeitraum. Die Zeile zum schnellen Anlegen ist weg, „Aufgabe“ oben rechts reicht.": "You choose how far ahead the task list looks: 7 days, 4 weeks, 1 month or a custom period. The quick-add line is gone; “Task” at the top right is enough.",
  "Neu: Mit Strg+K durchsuchen Sie alles auf einmal, also Buchungen, Rechnungen, Kontakte, Termine, Aufgaben und Einstellungen. Auf dem Handy öffnet das Suchsymbol oben die Suche.": "New: with Ctrl+K you search everything at once: transactions, invoices, contacts, appointments, tasks and settings. On the phone the search icon at the top opens the search.",
  "Buchungen, die nicht zum Betrieb gehören, heißen jetzt „privat“ statt „nicht gelistet“. An der Wirkung ändert sich nichts.": "Transactions that do not belong to the business are now called “private” instead of “unlisted”. The effect does not change.",
  "Abmelden, Fingerabdruck und Rückmeldungen": "Signing out, fingerprint and feedback",
  "Neben „Sperren“ gibt es jetzt „Abmelden“. Damit räumen Sie dieses Gerät auf und melden sich mit einem anderen Konto an. Kontovia gleicht vorher noch einmal ab.": "Next to “Lock” there is now “Sign out”. With it you clear this device and sign in with a different account. Kontovia syncs once more beforehand.",
  "Auf dem Handy öffnen Sie Kontovia mit Fingerabdruck oder Gesicht. Wenn Sie es möchten, geht das Entsperren auch über Ihr Google-Konto. Das Passwort bleibt immer gültig. Einschalten unter Einstellungen, Sicherheit.": "On the phone you open Kontovia with your fingerprint or face. If you wish, unlocking also works via your Google account. The password always stays valid. Turn it on under Settings, Security.",
  "Mit „Feedback“ in der Seitenleiste schreiben Sie uns, was Ihnen auffällt, auf Wunsch mit einem Bild der aktuellen Seite.": "With “Feedback” in the sidebar you write to us about what you notice, with a picture of the current page if you like.",
  "Im Rechnungsgestalter schließt ein Klick neben ein Fenster nur dieses Fenster. Farben stellen Sie auch im Rechtsklick-Menü ein.": "In the invoice designer, a click next to a window only closes that window. You can also set colors in the right-click menu.",
  "Texte auf der Rechnung ändern Sie mit einem Doppelklick direkt auf der Vorschau. Bilder aus der Zwischenablage fügen Sie mit Strg+V ein.": "You change texts on the invoice with a double-click directly on the preview. You paste images from the clipboard with Ctrl+V.",
  "Rechnungen einfacher gestalten": "Designing invoices made easier",
  "Sie ändern die Rechnung jetzt direkt auf der Vorschau: Teil anklicken, und ein kleines Fenster zeigt Farbe, Größe, Texte und mehr. Ein Rechtsklick zeigt weitere Möglichkeiten.": "You now change the invoice directly on the preview: click a part, and a small window shows color, size, texts and more. A right-click shows further options.",
  "Die Tabelle wählen Sie mit Bildern aus: Farbfläche, Linien, Streifen oder Raster. Spalten und Überschriften klappen Sie bei Bedarf auf.": "You choose the table with pictures: color fill, lines, stripes or grid. You expand columns and headings when needed.",
  "Das Verschieben folgt der Maus jetzt genau. Tabelle und Texte ordnen Sie durch Ziehen nach oben oder unten.": "Moving now follows the mouse exactly. You arrange the table and texts by dragging them up or down.",
  "Egal wie Sie gestalten: Pflichtangaben und die Daten der E-Rechnung bleiben vollständig und lesbar. Teile, die sich überlappen würden, rücken von selbst zur Seite.": "No matter how you design: mandatory details and the e-invoice data stay complete and readable. Parts that would overlap move aside by themselves.",
  "Zu helle Farben dunkelt Kontovia in der Schrift ab, und Beträge werden nie abgeschnitten.": "Kontovia darkens colors that are too light in the text, and amounts are never cut off.",
  "Rechnungen frei gestalten": "Design invoices freely",
  "Im Gestalter verschieben Sie die Bausteine Ihrer Rechnung per Hand und fügen eigene Texte, Bilder, Flächen und Linien hinzu. Auch Briefpapier, Tabellenstil und Spalten lassen sich anpassen, ein Schritt zurück geht immer.": "In the designer you move the building blocks of your invoice by hand and add your own texts, images, areas and lines. Letterhead, table style and columns can also be adjusted, and you can always go back a step.",
  "Die Fälligkeit setzen Sie mit einem Klick auf „Sofort“, „+14 Tage“ oder „+30 Tage“. Fälligkeit und Zahlungsziel bleiben dabei im Gleichklang.": "You set the due date with one click on “Immediately”, “+14 days” or “+30 days”. Due date and payment term stay in sync.",
  "Bilder können Sie für jede Rechnung einzeln wählen. Ein Hinweis erinnert Sie daran, Rechnungen zehn Jahre aufzubewahren.": "You can choose images for each invoice individually. A note reminds you to keep invoices for ten years.",
  "Bei Schlussrechnungen werden Anzahlungen samt Umsatzsteuer abgezogen. Gutschriften bucht Kontovia als Minusbetrag.": "In final invoices, down payments including VAT are deducted. Kontovia books credit notes as a negative amount.",
  "Steuernummer, Anschrift und Register bleiben auf dem PDF, auch wenn Sie die Fußzeile ausschalten. Eine USt-IdNr. ohne Länderkürzel zeigt Kontovia jetzt als fehlende Angabe.": "Tax number, address and register stay on the PDF even if you turn off the footer. Kontovia now shows a VAT ID without a country code as a missing detail.",
  "Im neuen Bereich „Rechnungen“ schreiben Sie E-Rechnungen, die den gesetzlichen Vorgaben entsprechen: als PDF mit eingebetteten Rechnungsdaten und als XRechnung für Behörden.": "In the new “Invoices” section you write e-invoices that meet the legal requirements: as a PDF with embedded invoice data and as an XRechnung for public authorities.",
  "Kunden und Positionen wählen Sie aus Kontakten und Produkten oder tragen sie frei ein, mit Einheiten wie Stunden, Tage oder Pauschale. Rechts sehen Sie die fertige Seite.": "You choose customers and items from contacts and products or enter them freely, with units such as hours, days or lump sum. On the right you see the finished page.",
  "Fehlende Pflichtangaben zeigt Kontovia als Liste. Speichern geht immer, ausstellen nach einer Rückfrage auch dann, wenn noch etwas fehlt.": "Kontovia shows missing mandatory details as a list. Saving always works; issuing also works after a confirmation even if something is still missing.",
  "Logo, Farbe, Stil und ein Zusatzbild wie Ihre Unterschrift lassen sich frei wählen. Häufige Rechnungen speichern Sie als Vorlage.": "Logo, color, style and an additional image such as your signature can be chosen freely. You save frequent invoices as a template.",
  "Beim Ausstellen entsteht die offene Einnahme von selbst. Erhaltene E-Rechnungen legen Sie unter „Eingang“ ab und buchen sie mit einem Klick.": "When issuing, the open income is created by itself. You file received e-invoices under “Incoming” and book them with one click.",
  "Neues, ruhigeres Aussehen": "New, calmer look",
  "Kontovia sieht jetzt aufgeräumter und moderner aus: mehr Luft, feine Linien, große Zahlen und eine neue Schrift.": "Kontovia now looks tidier and more modern: more space, fine lines, large figures and a new font.",
  "Eine neue Buchung legen Sie jetzt mit einem einzigen Knopf oben links an. Ein Klick darauf lässt Sie zwischen Einnahme und Ausgabe wählen.": "You now create a new transaction with a single button at the top left. A click on it lets you choose between income and expense.",
  "In der Seitenleiste stehen die vier wichtigsten Bereiche oben, Auswertungen und Export darunter, Stammdaten, Einstellungen und Hilfe ganz unten.": "In the sidebar, the four most important sections are at the top, reports and export below, and master data, settings and help at the very bottom.",
  "Am Telefon gibt es eine feste Leiste am unteren Rand mit Übersicht, Buchungen, Neue Buchung, Kalender und Mehr.": "On the phone there is a fixed bar at the bottom with Overview, Transactions, New transaction, Calendar and More.",
  "In den Diagrammen sind Einnahmen blau und Ausgaben grau, damit man zuerst sieht, was hereinkommt.": "In the charts, income is blue and expenses gray, so you see first what is coming in.",
  "Besser am Telefon, Installieren auf Android, verlässlicherer Google Kalender": "Better on the phone, install on Android, more reliable Google Calendar",
  "Auf Android lässt sich Kontovia jetzt mit einem Tipp als App installieren: Der Knopf „App installieren“ steht im Menü und auf dem Anmeldebildschirm.": "On Android, Kontovia can now be installed as an app with one tap: the button “Install app” is in the menu and on the sign-in screen.",
  "Am Telefon sind Fenster nicht mehr zu breit, die Kennzahlen stehen untereinander, und die Zeile mit Zeitraum und Neu-Knöpfen klappt beim Hinunterscrollen weg.": "On the phone, windows are no longer too wide, the key figures are stacked, and the row with period and new buttons folds away when scrolling down.",
  "Im Monatskalender zeigen kleine Striche die Termine. Gelesen werden sie in der Liste darunter.": "In the month calendar, small lines show the appointments. You read them in the list below.",
  "Google Kalender: Wo ein zweites Fenster nicht geht, etwa in der App auf dem iPhone, wechselt Kontovia kurz zu Google und kommt danach zurück. Blockiert der Browser das Fenster, fragt Kontovia vorher.": "Google Calendar: where a second window does not work, such as in the app on the iPhone, Kontovia briefly switches to Google and then comes back. If the browser blocks the window, Kontovia asks beforehand.",
  "Übersicht zum Anklicken, Zurück-Taste und PDF am Telefon": "Clickable overview, back button and PDF on the phone",
  "In der Übersicht führt jede Zahl zu den Buchungen oder Auswertungen dahinter, auch ein Monat im Verlauf oder eine Kategorie.": "On the overview, every figure leads to the transactions or reports behind it, including a month in the trend or a category.",
  "Die Breite eines Moduls lässt sich jetzt auch auf drei Viertel stellen. So füllt es mit einem Viertel zusammen eine ganze Zeile.": "A module's width can now also be set to three quarters. Together with a quarter it then fills a whole row.",
  "Die Zurück-Taste des Browsers geht jetzt einen Schritt in Kontovia zurück, schließt ein offenes Fenster oder bleibt in der Übersicht, statt die Seite zu verlassen.": "The browser's back button now goes one step back in Kontovia, closes an open window or stays on the overview instead of leaving the page.",
  "Auf Telefon und Tablet gibt es keinen Druckknopf mehr. PDF-Dateien werden gespeichert und nicht an einen Drucker geschickt.": "On phones and tablets there is no print button anymore. PDF files are saved and not sent to a printer.",
  "Kontovia gibt es jetzt nur noch im Browser": "Kontovia is now only available in the browser",
  "Kontovia läuft nur noch im Browser: auf dem Rechner genauso wie auf Telefon und Tablet, auch ohne Internet.": "Kontovia now only runs in the browser: on the computer just like on phones and tablets, even without internet.",
  "In Chrome und Edge lässt es sich als eigene App mit Symbol installieren und die Buchhaltung in einem Ordner auf dem Gerät führen. Das ersetzt die Windows-Fassung und die Fassung ohne Installation.": "In Chrome and Edge it can be installed as a separate app with its own icon, and the accounting can be kept in a folder on the device. This replaces the Windows version and the version without installation.",
  "Was die Windows-Fassung konnte, gibt es auch hier: echte PDF-Dateien, Google Kalender, Sperre nach dem Ruhezustand und angemeldet bleiben nach einem Update.": "What the Windows version could do is also available here: real PDF files, Google Calendar, locking after sleep and staying signed in after an update.",
  "Buchhaltungen, Vollsicherungen und Cloud-Stände aus der Windows-Fassung lassen sich weiter öffnen.": "Accounting data, full backups and cloud versions from the Windows version can still be opened.",
  "Kontovia zieht in den Browser um": "Kontovia moves to the browser",
  "Dies ist das letzte Update der Windows-Fassung. Kontovia geht im Browser weiter, auch ohne Internet und in Chrome oder Edge als eigene App.": "This is the last update of the Windows version. Kontovia continues in the browser, even without internet and in Chrome or Edge as a separate app.",
  "Unter Windows zeigen ein Hinweis nach dem Start und eine Karte unter Hilfe → Neuigkeiten die drei Schritte für den Umzug.": "On Windows, a note after starting and a card under Help → News show the three steps for the move.",
  "Auf Wunsch legt Kontovia eine Kopie des Datenordners unter Dokumente an, die der Browser direkt öffnen kann.": "If you wish, Kontovia creates a copy of the data folder under Documents that the browser can open directly.",
  "Google Kalender im Browser": "Google Calendar in the browser",
  "Google Kalender lässt sich jetzt auch im Browser, auf iPhone und iPad verbinden, in beide Richtungen wie unter Windows.": "Google Calendar can now also be connected in the browser, on iPhone and iPad, in both directions as on Windows.",
  "Zur Anmeldung öffnet sich ein kleines Fenster von Google. Danach gilt der Zugriff jeweils eine Stunde und wird mit einem Tipp verlängert.": "A small Google window opens for signing in. After that, access is valid for one hour at a time and is extended with one tap.",
  "Im Browser sperrt sich Kontovia jetzt auch nach dem Ruhezustand des Geräts, in Chrome und Edge auf Wunsch auch bei gesperrtem Bildschirm.": "In the browser, Kontovia now also locks after the device sleeps, and in Chrome and Edge optionally also when the screen is locked.",
  "Nach einer Aktualisierung im Browser bleiben Sie angemeldet.": "After an update in the browser you stay signed in.",
  "Als App installiert, zeigt ein Punkt am Symbol, dass eine neue Fassung bereitliegt.": "When installed as an app, a dot on the icon shows that a new version is ready.",
  "Echte PDF-Dateien": "Real PDF files",
  "Berichte lassen sich jetzt auch im Browser, auf iPhone und iPad als echte PDF-Datei speichern, ohne Umweg über den Druckdialog.": "Reports can now also be saved as real PDF files in the browser, on iPhone and iPad, without going through the print dialog.",
  "Das Paket „Alles für das Finanzamt“ enthält die Berichte als PDF.": "The package “Everything for the tax office” contains the reports as PDF.",
  "Lange Tabellen gehen sauber über mehrere Seiten, mit Spaltenköpfen auf jeder Seite; das Buchungsjournal steht im Querformat.": "Long tables flow cleanly over several pages, with column headers on each page; the transaction journal is in landscape format.",
  "Drucken geht in der Web-Fassung weiterhin über den eigenen Knopf.": "Printing in the web version still works via its own button.",
  "Buchhaltung in einem Ordner": "Accounting in a folder",
  "In Chrome und Edge lässt sich die Buchhaltung jetzt in einem Ordner auf dem Gerät speichern statt im Speicher des Browsers: Einstellungen → Sicherung und Speicherort.": "In Chrome and Edge, the accounting can now be saved in a folder on the device instead of in the browser's storage: Settings → Backup and storage location.",
  "Der Ordner ist so aufgebaut wie unter Windows. Eine Kopie des Windows-Datenordners öffnen Sie beim ersten Start mit „Ordner öffnen“.": "The folder is structured as on Windows. You open a copy of the Windows data folder at the first start with “Open folder”.",
  "Liegt die Buchhaltung nur im Browser, erinnert Kontovia gelegentlich an die Cloud-Sicherung oder eine Vollsicherung.": "If the accounting is only in the browser, Kontovia occasionally reminds you about cloud backup or a full backup.",
  "Aufgeräumt": "Tidied up",
  "Die Cloud-Sicherung läuft nur noch auf einem Weg. Wer sie über Google Drive oder ein eigenes Google-Projekt genutzt hat, verbindet sie einmal neu; die Einstellungen weisen darauf hin.": "Cloud backup now only works one way. If you used it via Google Drive or your own Google project, connect it again once; the settings point this out.",
  "Die Fassung ohne Installation gibt es nicht mehr. Wer sie benutzt, bekommt beim nächsten Update das normale Installationsprogramm, die Buchhaltung bleibt, wo sie ist.": "The version without installation no longer exists. If you use it, you get the normal installer with the next update; the accounting stays where it is.",
  "Kontovia prüft jetzt bei jeder Änderung, dass Buchhaltungen aus älteren Versionen lesbar bleiben.": "With every change, Kontovia now checks that accounting data from older versions stays readable.",
  "Ruhigerer Neustart nach Updates, natürlichere Texte": "Calmer restart after updates, more natural texts",
  "Beim Aktualisieren sehen Sie jetzt Schritt für Schritt, was passiert und wann Kontovia von selbst zurückkommt.": "When updating you now see step by step what happens and when Kontovia comes back by itself.",
  "Der Fortschritt erscheint auch in der Taskleiste, und Windows meldet, dass Kontovia gleich wieder da ist.": "The progress also appears in the taskbar, and Windows reports that Kontovia will be back shortly.",
  "Die zweite Rückfrage vor dem Update entfällt, die Erklärung steht jetzt direkt am Knopf.": "The second confirmation before the update is gone; the explanation is now right at the button.",
  "Viele Texte in Hilfe, Dialogen und Hinweisen sind klarer und kürzer formuliert.": "Many texts in help, dialogs and notes are worded more clearly and briefly.",
  "Neuigkeiten im Programm und eine aufgeräumte Hilfe": "News in the program and a tidier help",
  "Was neu ist, steht jetzt unter Hilfe → Neuigkeiten, für jede Version seit der ersten. Nach einem Update weist Kontovia einmal darauf hin.": "What is new is now under Help → News, for every version since the first. After an update Kontovia points this out once.",
  "Hilfe und Einstellungen sind aufgeräumt: Anleitungen, die nur für den Hersteller gedacht waren, sind verschwunden. Die Datenschutzhinweise öffnen sich direkt im Programm.": "Help and settings are tidied up: guides only meant for the vendor are gone. The privacy notice opens directly in the program.",
  "Wer beim ersten Start die Google-Anmeldung abbricht oder die Cloud auf einem Gerät trennt, lässt die anderen Geräte verbunden. Bisher musste dort Google Kalender neu verbunden werden.": "If you cancel the Google sign-in at the first start or disconnect the cloud on one device, the other devices stay connected. Previously Google Calendar had to be reconnected there.",
  "Das Änderungsjournal nennt jeden Vorgang in Worten, etwa „Buchung angelegt“.": "The change log names every action in words, such as “Transaction created”.",
  "In schmalen Fenstern bleibt die Beschreibung in der Buchungsliste lesbar, und das Warten auf die Anmeldung bei Google Kalender lässt sich abbrechen.": "In narrow windows the description in the transaction list stays readable, and waiting for the Google Calendar sign-in can be cancelled.",
  "Test-Update": "Test update",
  "Nur zum Ausprobieren der neuen Aktualisierung, sonst keine Änderungen.": "Only for trying out the new update mechanism, otherwise no changes.",
  "Aktualisieren ohne Umweg": "Updating without detours",
  "Kontovia installiert neue Versionen selbst und startet danach von allein neu.": "Kontovia installs new versions itself and then restarts by itself.",
  "Sie bleiben dabei angemeldet und müssen Ihr Passwort nicht erneut eingeben.": "You stay signed in and do not have to enter your password again.",
  "Die Größenanzeige beim Herunterladen stimmt wieder.": "The size display when downloading is correct again.",
  "Alle Ihre Google-Kalender": "All your Google calendars",
  "Auf Wunsch gleicht Kontovia auch Ihren Hauptkalender und weitere Google-Kalender ab, in beide Richtungen.": "If you wish, Kontovia also syncs your main calendar and other Google calendars, in both directions.",
  "Web-Fassung: Anmeldung bei Google ohne Code, und sie lädt Ihre Buchhaltung jetzt auch aus der Cloud.": "Web version: Google sign-in without a code, and it now also loads your accounting from the cloud.",
  "Nach der Anmeldung im Browser kommt Kontovia von selbst wieder nach vorn.": "After signing in in the browser, Kontovia comes to the front by itself.",
  "Wer die Cloud trennt, behält die Verbindung zu Google Kalender.": "If you disconnect the cloud, you keep the connection to Google Calendar.",
  "Cloud auch in der Web-Fassung": "Cloud in the web version too",
  "Auf iPhone, iPad und Mac lässt sich Kontovia jetzt mit Google verbinden und mit Ihren anderen Geräten abgleichen.": "On iPhone, iPad and Mac, Kontovia can now be connected to Google and synced with your other devices.",
  "Mit Google anmelden, Sicherungen in der Cloud": "Sign in with Google, backups in the cloud",
  "Auf einem neuen Gerät: mit Google anmelden, Passwort eingeben, fertig. Ihre Buchhaltung ist da.": "On a new device: sign in with Google, enter your password, done. Your accounting is there.",
  "Kontovia sichert täglich in der Cloud; jede Sicherung lässt sich wiederherstellen.": "Kontovia backs up to the cloud daily; every backup can be restored.",
  "Ist die Anmeldung bei Google abgelaufen, hilft der Knopf „Neu anmelden“.": "If the Google sign-in has expired, the button “Sign in again” helps.",
  "Mehrere Fehler beim Abgleich zwischen Geräten sind behoben.": "Several bugs in syncing between devices have been fixed.",
  "E-Rechnungen, wiederkehrende Buchungen, Steuertermine": "E-invoices, recurring transactions, tax deadlines",
  "E-Rechnungen (XRechnung, ZUGFeRD) erscheinen lesbar und lassen sich mit einem Klick übernehmen.": "E-invoices (XRechnung, ZUGFeRD) appear readable and can be taken over with one click.",
  "Wiederkehrende Buchungen für Miete, Telefon oder Abos.": "Recurring transactions for rent, phone or subscriptions.",
  "Übersicht und Kalender zeigen die nächsten Steuertermine.": "The overview and calendar show the next tax deadlines.",
  "Computer und Software lassen sich in einem Jahr abschreiben, neue Anschaffungen auch degressiv.": "Computers and software can be depreciated in one year, new purchases also by declining balance.",
  "Korrekturen am Änderungsjournal und an der Festschreibung.": "Corrections to the change log and the period lock.",
  "Korrekturen": "Corrections",
  "Offene Rechnungen aus einem festgeschriebenen Zeitraum lassen sich noch als bezahlt vermerken.": "Open invoices from a locked period can still be marked as paid.",
  "Beträge mit Tausenderpunkt wie „1.500“ werden richtig gelesen.": "Amounts with thousands separators like “1.500” are read correctly.",
  "Monatliche Termine am 31. landen in kurzen Monaten am Monatsende.": "Monthly appointments on the 31st land at the end of the month in short months.",
  "Sperren ist sicherer, Filter bleiben erhalten, Termine und Aufgaben fragen vor dem Verwerfen.": "Locking is safer, filters are kept, appointments and tasks ask before discarding.",
  "Neue Aufgabenliste zum Abhaken, auf Wunsch zu einem Termin.": "New task list to tick off, linked to an appointment if you like.",
  "Einnahmen und Ausgaben zählen in dem Monat, in dem das Geld fließt.": "Income and expenses count in the month in which the money flows.",
  "Die Buchungsliste zeigt auch, was im Zeitraum bezahlt wurde.": "The transaction list also shows what was paid in the period.",
  "Sonderzeichen wie & oder \" bleiben beim Speichern, wie sie sind.": "Special characters such as & or \" stay as they are when saving.",
  "Dringende Korrektur": "Urgent correction",
  "Unter Windows blieb das Fenster von Version 1.6.0 schwarz. Wer 1.6.0 hat, installiert 1.6.1 bitte einmal von Hand. Ihre Daten waren nicht betroffen.": "On Windows, the window of version 1.6.0 stayed black. If you have 1.6.0, please install 1.6.1 manually once. Your data was not affected.",
  "Stornos, Anlage EÜR und DATEV": "Reversals, Anlage EÜR and DATEV",
  "Stornierte Buchungen zählen nicht mehr doppelt.": "Reversed transactions no longer count twice.",
  "Die Anlage EÜR folgt den amtlichen Vordrucken 2025 und 2026.": "The Anlage EÜR follows the official forms 2025 and 2026.",
  "DATEV-Export und Prüfungsordner lassen sich sauber einlesen.": "DATEV export and audit folder can be imported cleanly.",
  "Hinweis, wenn Sie die Kleinunternehmergrenze überschreiten; schneller bei vielen Buchungen.": "A note when you exceed the small business limit; faster with many transactions.",
  "Richtige Vergleiche, bessere Handy-Ansicht": "Correct comparisons, better phone view",
  "Der Vergleich mit dem Vorjahr zählt bis zum gleichen Tag.": "The comparison with the previous year counts up to the same day.",
  "Auf dem Handy erscheinen Buchungen als übersichtliche Karten.": "On the phone, transactions appear as clear cards.",
  "Ungespeicherte Einstellungen gehen beim Verlassen nicht mehr verloren.": "Unsaved settings are no longer lost when leaving.",
  "Kontovia warnt, wenn eine Kasse ins Minus rutscht.": "Kontovia warns when a cash account goes negative.",
  "Sortieren überall": "Sorting everywhere",
  "Jede Liste lässt sich nach jeder Spalte sortieren.": "Every list can be sorted by every column.",
  "Suche und Filter jetzt auch in Stammdaten, offenen Posten und im Änderungsjournal.": "Search and filters now also in master data, open items and the change log.",
  "Eigene Übersicht, einfachere Filter": "Your own overview, simpler filters",
  "Die Übersicht lässt sich frei anordnen; Bereiche blenden Sie ein und aus.": "The overview can be arranged freely; you show and hide sections.",
  "Den Zeitraum wählen Sie mit einem Klick.": "You choose the period with one click.",
  "Gefiltert wird direkt in den Spaltenköpfen.": "Filtering happens directly in the column headers.",
  "Diagramme, Google Kalender und die Web-Fassung": "Charts, Google Calendar and the web version",
  "Diagramme lassen sich umschalten, dazu Durchschnittswerte.": "Charts can be switched, with averages too.",
  "Termine gleichen sich mit Google Kalender ab.": "Appointments sync with Google Calendar.",
  "Buchungen lassen sich als „nicht gelistet“ kennzeichnen.": "Transactions can be marked as “unlisted”.",
  "Hell oder dunkel mit einem Klick. Neu ist Kontovia im Browser für iPhone, iPad und Mac.": "Light or dark with one click. New: Kontovia in the browser for iPhone, iPad and Mac.",
  "Wichtige Korrekturen bei Belegen und Abgleich": "Important fixes for receipts and sync",
  "Angehängte Belege konnten verloren gehen. Das ist behoben, vorhandene Belege werden wiederhergestellt.": "Attached receipts could get lost. This is fixed, existing receipts are restored.",
  "Mehrere Fehler im Cloud-Abgleich sind behoben.": "Several bugs in cloud sync have been fixed.",
  "Bessere Bedienung": "Better usability",
  "Fenster fragen nach, bevor begonnene Eingaben verloren gehen.": "Windows ask before started entries are lost.",
  "Vieles geht jetzt auch mit der Tastatur.": "Many things now also work with the keyboard.",
  "Das Passwort lässt sich beim Eintippen anzeigen.": "The password can be shown while typing.",
  "Mehr Kontrolle": "More control",
  "Beim Trennen der Cloud lassen sich Ihre Daten dort auch löschen.": "When disconnecting the cloud, your data there can also be deleted.",
  "Ob Kontovia nach Updates sucht, entscheiden Sie selbst.": "You decide yourself whether Kontovia checks for updates.",
  "Das Anlagenverzeichnis gibt es als eigenes PDF.": "The asset register is available as a separate PDF.",
  "Ort und Anzahlungen": "Location and down payments",
  "Bei Einnahmen lässt sich der Ort festhalten und danach filtern.": "For income, the location can be recorded and filtered.",
  "Anzahlungen mit Veranstaltungstermin; die Restzahlung legt Kontovia auf Wunsch gleich an.": "Down payments with an event date; Kontovia creates the remaining payment right away if you wish.",
  "Hinweis auf neue Versionen": "Notice about new versions",
  "Auf Wunsch meldet sich Kontovia, sobald es eine neue Version gibt.": "If you wish, Kontovia lets you know as soon as there is a new version.",
  "Sicherheit": "Security",
};
