/** Wörterbuch Englisch, Teil t09. Quellen: lib/versionen.js, lib/wiederkehrend.js, lib/xlsx.js, lib/zugaenge.js, lib/zulassung.js, lib/zuordnung.js, views/anlageform.js, views/calendar.js, views/calendarsync.js. */

export default {
  "Exporte lassen sich gefahrlos in Excel öffnen.": "Exports can be opened safely in Excel.",
  "Festgeschriebene Zeiträume sind besser geschützt.": "Locked periods are better protected.",
  "Rechtliches und Datenschutz finden Sie unter Hilfe.": "You find legal information and privacy under Help.",
  "Abgleich zwischen Geräten": "Sync between devices",
  "Ihre Buchhaltung lässt sich zwischen mehreren Rechnern abgleichen.": "Your accounting can be synced between several computers.",
  "Updates installieren sich auf Knopfdruck.": "Updates install at the push of a button.",
  "Einnahmen erscheinen grün, Ausgaben rot.": "Income appears green, expenses red.",
  "Die erste Version": "The first version",
  "Einnahmen und Ausgaben samt Belegen, verschlüsselt auf Ihrem Rechner.": "Income and expenses including receipts, encrypted on your computer.",
  "Kalender, Auswertungen, Anlage EÜR und Umsatzsteuer.": "Calendar, reports, Anlage EÜR and VAT.",
  "Export für ELSTER, DATEV und Betriebsprüfung.": "Export for ELSTER, DATEV and tax audits.",
  "tx_w{0}_": "tx_w{0}_",
  "Die Excel-Datei ist auf eine Weise gepackt, die Kontovia nicht lesen kann.": "The Excel file is packed in a way that Kontovia cannot read.",
  "Die Datei ist keine Excel-Datei (.xlsx).": "The file is not an Excel file (.xlsx).",
  "Die Excel-Datei ist zu groß.": "The Excel file is too large.",
  "Die Excel-Datei enthält kein Tabellenblatt.": "The Excel file contains no worksheet.",
  "Blatt": "Sheet",
  "'{0}'!$A$1:${1}$": "'{0}'!$A$1:${1}$",
  "kontovia.{0}.": "kontovia.{0}.",
  "Kontovia ist gesperrt.": "Kontovia is locked.",
  "Die Buchhaltung in Ihrem Google-Konto und die auf diesem Gerät passen nicht zusammen. Klären Sie das zuerst in den Einstellungen unter Cloud.": "The accounting in your Google account and the one on this device do not match. Resolve this first in the settings under Cloud.",
  "Ein anderer Abgleich lief gleichzeitig. Bitte noch einmal versuchen.": "Another sync was running at the same time. Please try again.",
  "Der Abgleich hat nicht geklappt.": "The sync did not work.",
  "Ihre anderen Konten bleiben erhalten. Danach öffnet Kontovia „{0}“.": "Your other accounts are kept. Kontovia then opens “{0}”.",
  "Danach können Sie sich hier mit einem anderen Konto anmelden oder neu anfangen.": "After that you can sign in here with a different account or start fresh.",
  "Kontovia gleicht jetzt noch einmal mit Ihrem Google-Konto{0} ab{1}. Danach können Sie die Buchhaltung hier oder auf einem anderen Gerät wieder laden.": "Kontovia now syncs once more with your Google account{0}{1}. After that you can load the accounting again here or on another device.",
  ", zuletzt war das": ", last time that was",
  "Kontovia ist gesperrt und kann deshalb nicht mehr abgleichen. Was Sie seit dem letzten Abgleich geändert haben, geht verloren. Möchten Sie vorher abgleichen, entsperren Sie Kontovia zuerst. Ohne Cloud-Sicherung oder Vollsicherung ist die Buchhaltung danach unwiederbringlich weg.": "Kontovia is locked and therefore can no longer sync. What you have changed since the last sync will be lost. If you want to sync first, unlock Kontovia first. Without a cloud backup or full backup, the accounting is then gone forever.",
  "Danach ist sie weg, wenn Sie keine Vollsicherung oder Cloud-Sicherung haben.": "After that it is gone if you have no full backup or cloud backup.",
  "Diese Buchhaltung liegt nur auf diesem Gerät.": "This accounting is only on this device.",
  "Zur Sicherung": "To the backup",
  "„{0}“ von diesem Gerät entfernen?": "Remove “{0}” from this device?",
  "Von diesem Gerät entfernen?": "Remove from this device?",
  "Kontovia entfernt dieses Konto mit Buchhaltung, Belegen und allen Zugängen (Fingerabdruck, Google-Verbindung) von diesem Gerät. Zum kurzen Weggehen genügt „Sperren“.": "Kontovia removes this account with its accounting, receipts and all access methods (fingerprint, Google connection) from this device. If you are only stepping away briefly, “Lock” is enough.",
  "Abgleichen und entfernen": "Sync and remove",
  "Trotzdem entfernen": "Remove anyway",
  "Von diesem Gerät entfernen": "Remove from this device",
  "Kontovia gleicht mit Ihrem Google-Konto ab …": "Kontovia is syncing with your Google account …",
  "Entfernen Sie das Konto trotzdem, gehen die Änderungen seit dem letzten Abgleich{0} verloren. Ihr Konto ist sonst unverändert; Sie können es später noch einmal versuchen.": "If you remove the account anyway, the changes since the last sync{0} will be lost. Otherwise your account is unchanged; you can try again later.",
  "Entfernen nicht möglich": "Removing not possible",
  "„{0}“ ist von diesem Gerät entfernt.": "“{0}” has been removed from this device.",
  "Das Konto ist von diesem Gerät entfernt.": "The account has been removed from this device.",
  "Konto wechseln": "Switch account",
  "Kontovia gleicht dieses Konto ab, bevor es wechselt …": "Kontovia is syncing this account before switching …",
  "Trotzdem wechseln": "Switch anyway",
  "Ihre Daten bleiben auf diesem Gerät. Der Abgleich holt bei der nächsten Gelegenheit nach, was fehlt.": "Your data stays on this device. The sync will catch up on what is missing at the next opportunity.",
  "Wechsel nicht möglich": "Switching not possible",
  "Konten": "Accounts",
  "Konten auf diesem Gerät": "Accounts on this device",
  "das offene Konto, vorher wird abgeglichen": "the open account, synced first",
  "Konto „{0}“": "Account “{0}”",
  "Mit Fingerabdruck oder Gesicht entsperren": "Unlock with fingerprint or face",
  "Mit Google entsperren": "Unlock with Google",
  "Nur wenn Sie das auf einem Ihrer Geräte eingeschaltet haben.": "Only if you have turned this on on one of your devices.",
  "Dieser Browser kann das nicht.": "This browser cannot do this.",
  "Eingerichtet. Auf dem Sperrbildschirm erscheint ein Knopf dafür.": "Set up. A button for it appears on the lock screen.",
  "Auf diesem Gerät ist keine Bildschirmsperre mit Fingerabdruck oder Gesicht eingerichtet.": "No screen lock with fingerprint or face is set up on this device.",
  "Öffnet Kontovia nach einer Bestätigung mit Fingerabdruck oder Gesicht. Gilt nur für dieses Gerät.": "Opens Kontovia after confirming with fingerprint or face. Only applies to this device.",
  "Weitere Wege zum Entsperren": "More ways to unlock",
  "Ihr Passwort bleibt immer gültig": "Your password always stays valid",
  "Fingerabdruck oder Gesicht": "Fingerprint or face",
  "Ausschalten": "Turn off",
  "Einschalten": "Turn on",
  "Ausgeschaltet": "Turned off",
  "Auf diesem Gerät entsperren Sie wieder nur mit dem Passwort.": "On this device you unlock with the password only again.",
  "Google:": "Google:",
  "gerade offen": "currently open",
  "zuletzt geöffnet": "last opened",
  "noch nie geöffnet": "never opened",
  "Konto umbenennen": "Rename account",
  "Die Bezeichnung erscheint in den Listen, auch auf dem Sperrbildschirm. Die Buchhaltung selbst ändert sich nicht.": "The name appears in the lists, including on the lock screen. The accounting itself does not change.",
  "Leer lassen, um wieder den Namen des Betriebs zu zeigen.": "Leave empty to show the business name again.",
  "Buchhaltung, Belege, Sicherungen und alle Zugänge dieses Kontos (Fingerabdruck, Google-Verbindung) werden von diesem Gerät gelöscht. Ihre anderen Konten bleiben, wie sie sind.": "Accounting, receipts, backups and all access methods of this account (fingerprint, Google connection) will be deleted from this device. Your other accounts stay as they are.",
  "Dieses Konto ist gerade nicht entsperrt, Kontovia kann es deshalb nicht noch einmal abgleichen.": "This account is not unlocked right now, so Kontovia cannot sync it once more.",
  "Was nicht in der Cloud oder in einer Vollsicherung liegt, ist danach weg.": "Anything not in the cloud or in a full backup will be gone afterwards.",
  "Ich weiß, dass sich das nicht rückgängig machen lässt.": "I know that this cannot be undone.",
  "jedes mit eigenem Passwort und eigener Buchhaltung": "each with its own password and its own accounting",
  "Offenes Konto von diesem Gerät entfernen": "Remove the open account from this device",
  "Jedes Konto liegt für sich im Speicher des Browsers; beim Wechseln lädt Kontovia neu, damit nichts von einem Konto ins andere gelangt. Auf dem Sperrbildschirm erscheinen nur auf Wunsch die Namen der anderen Konten. Das offene Konto entfernen Sie mit dem Knopf darüber, Kontovia gleicht vorher ab; ein anderes entfernen Sie in seiner Zeile.": "Each account is stored separately in the browser's storage; when switching, Kontovia reloads so that nothing gets from one account into another. The names of the other accounts only appear on the lock screen if you want. You remove the open account with the button above, Kontovia syncs first; you remove another one in its row.",
  "Umbenennen": "Rename",
  "Wechseln": "Switch",
  "Es gilt wieder der Name des Betriebs.": "The business name applies again.",
  "Konto entfernt": "Account removed",
  "Ihr Konto ist für Kontovia nicht mehr zugelassen. Deshalb wurde die Buchhaltung am {0} von diesem Gerät entfernt. {1} Ist das ein Irrtum, wenden Sie sich an den Betreiber. Sobald Ihr Konto wieder zugelassen ist, melden Sie sich unten mit Google an. Ihre Buchhaltung wird dann geladen, mit dem Passwort oder mit dem QR-Code von einem anderen Gerät.": "Your account is no longer approved for Kontovia. Therefore the accounting was removed from this device on {0}. {1} If this is a mistake, contact the operator. As soon as your account is approved again, sign in with Google below. Your accounting will then be loaded, with the password or with the QR code from another device.",
  "Dieses Gerät wurde vom Betreiber abgemeldet.": "This device was signed out by the operator.",
  "In der Cloud ist sie vollständig erhalten.": "It is fully preserved in the cloud.",
  "Einen Moment": "One moment",
  "Kontovia prüft, ob Ihr Konto noch zugelassen ist …": "Kontovia is checking whether your account is still approved …",
  "Zulassung nicht geprüft:": "Approval not checked:",
  "noch 1 Tag": "1 day left",
  "noch {0} Tage": "{0} days left",
  "Dieses Gerät ist vom Cloud-Abgleich getrennt, weil das Konto beim Betreiber gesperrt wurde. Ihre Buchhaltung liegt weiter hier und öffnet sich mit dem Passwort. In der Cloud ist sie unverändert. Legen Sie jetzt eine Vollsicherung an.": "This device is disconnected from cloud sync because the account was blocked by the operator. Your accounting is still here and opens with the password. In the cloud it is unchanged. Create a full backup now.",
  "Das Konto ist beim Betreiber gesperrt. Ihre Buchhaltung bleibt vorerst hier. Frühestens ab {0} entfernt Kontovia sie von diesem Gerät,": "The account is blocked by the operator. Your accounting stays here for now. Kontovia removes it from this device no earlier than {0},",
  "Das Konto ist beim Betreiber gesperrt. Ihre Buchhaltung bleibt vorerst hier. Frühestens ab {0} entfernt Kontovia sie von diesem Gerät, nachdem sie noch einmal in der Cloud gesichert wurde. In der Cloud bleibt sie erhalten. Ist das ein Irrtum, wenden Sie sich an den Betreiber. Eine Vollsicherung schadet jetzt nicht.": "The account is blocked by the operator. Your accounting stays here for now. Kontovia removes it from this device no earlier than {0}, after it has been backed up to the cloud once more. It is preserved in the cloud. If this is a mistake, contact the operator. A full backup does no harm now.",
  "Erneut prüfen": "Check again",
  "Die Bestätigung Ihres Kontos ist überfällig. Verbinden Sie dieses Gerät mit dem Internet und tippen Sie auf „Jetzt bestätigen“. Ihre Buchhaltung bleibt dabei, wie sie ist.": "The confirmation of your account is overdue. Connect this device to the internet and tap “Confirm now”. Your accounting stays as it is.",
  "Bitte bestätigen Sie bis zum {0} ({1}), dass Ihr Konto noch zugelassen ist. Das geschieht von selbst, sobald dieses Gerät Internet hat. Ihre Daten in der Cloud bleiben in jedem Fall erhalten.": "Please confirm by {0} ({1}) that your account is still approved. This happens by itself as soon as this device has internet. Your data in the cloud is preserved in any case.",
  "Jetzt bestätigen": "Confirm now",
  "Eine Prüfung läuft schon.": "A check is already running.",
  "Keine Verbindung": "No connection",
  "Kontovia kommt gerade nicht an den Cloud-Speicher. Versuchen Sie es mit Internet noch einmal. Ihre Daten sind nicht betroffen.": "Kontovia cannot reach the cloud storage right now. Try again with internet. Your data is not affected.",
  "Bestätigt": "Confirmed",
  "Nächste Bestätigung bis {0}.": "Next confirmation by {0}.",
  "Konto gesperrt": "Account blocked",
  "Das Konto ist beim Betreiber gesperrt. Details stehen oben im Fenster.": "The account is blocked by the operator. Details are at the top of the window.",
  "Nicht eindeutig": "Not clear",
  "Die Prüfung hat kein klares Ergebnis gebracht, zum Beispiel wegen einer Störung. Ihre Daten sind nicht betroffen. Versuchen Sie es später noch einmal.": "The check did not give a clear result, for example due to a disruption. Your data is not affected. Try again later.",
  "Konto nicht mehr zugelassen": "Account no longer approved",
  "Dieses Konto ist beim Betreiber nicht mehr zugelassen. Kontovia sichert Ihre Buchhaltung jetzt noch einmal in der Cloud und entfernt sie dann von diesem Gerät.": "This account is no longer approved by the operator. Kontovia now backs up your accounting to the cloud once more and then removes it from this device.",
  "In der Cloud bleibt sie erhalten.": "It is preserved in the cloud.",
  "Kontovia konnte sie nicht sicher in der Cloud ablegen und hat deshalb nichts gelöscht. Sie liegt weiter auf diesem Gerät und öffnet sich mit Ihrem Passwort. Die Verbindung zur Cloud, der Fingerabdruck und der Google-Zugang dieses Geräts sind entfernt.": "Kontovia could not store it safely in the cloud and therefore did not delete anything. It is still on this device and opens with your password. The cloud connection, the fingerprint and the Google access of this device have been removed.",
  "Das Gerät ist gesperrt, Ihre Buchhaltung ist noch da.": "The device is locked, your accounting is still there.",
  "Legen Sie jetzt eine {0} an: Einstellungen, Sicherung und Speicherort. Die Cloud-Kopie bleibt unverändert erhalten.": "Create a {0} now: Settings, Backup and storage location. The cloud copy is kept unchanged.",
  "Vollsicherung": "full backup",
  "Zulassung dieses Geräts": "Approval of this device",
  "alle 30 Tage, von selbst": "every 30 days, automatically",
  "Dieses Gerät ist nicht mit einem Google-Konto verbunden. Dann gibt es nichts zu bestätigen.": "This device is not connected to a Google account. Then there is nothing to confirm.",
  "Mit Google verbundene Geräte fragen alle 30 Tage bei Ihrem Konto im Cloud-Speicher nach, ob es noch zugelassen ist. Dabei wird nur gelesen; es gehen keine Daten über Ihre Buchhaltung hinaus. So kann der Betreiber ein verlorenes oder nicht mehr berechtigtes Gerät vom Konto trennen. Wird die Frist überschritten, passiert nichts außer Hinweisen. Entfernt wird nichts, außer das Konto ist ausdrücklich gesperrt, und auch dann erst, wenn Ihre Buchhaltung gesichert in der Cloud liegt. Wer „Cloud trennen“ wählt, ist davon nicht mehr betroffen. Das ist kein vollständiger Schutz: Wer ein Gerät nie öffnet, wird auch nicht gefragt.": "Devices connected to Google ask your account in the cloud storage every 30 days whether it is still approved. This only reads; no data about your accounting is sent. This lets the operator disconnect a lost or no longer authorized device from the account. If the deadline is exceeded, nothing happens except notices. Nothing is removed unless the account is explicitly blocked, and even then only once your accounting is backed up in the cloud. Anyone who chooses “Disconnect cloud” is no longer affected. This is not complete protection: a device that is never opened is never asked.",
  "Dieses Gerät ist vom Cloud-Abgleich getrennt, weil das Konto beim Betreiber gesperrt wurde. Ihre Buchhaltung liegt weiter hier. Legen Sie eine Vollsicherung an.": "This device is disconnected from cloud sync because the account was blocked by the operator. Your accounting is still here. Create a full backup.",
  "Zuletzt bestätigt": "Last confirmed",
  "noch nicht (die erste Bestätigung folgt von selbst)": "not yet (the first confirmation happens automatically)",
  "Nächste Bestätigung bis": "Next confirmation by",
  "Das Konto ist beim Betreiber gesperrt. Frühestens ab {0} wird die Buchhaltung von diesem Gerät entfernt, nachdem sie in der Cloud gesichert wurde.": "The account is blocked by the operator. The accounting will be removed from this device no earlier than {0}, after it has been backed up to the cloud.",
  "Sicher": "Certain",
  "Wahrscheinlich": "Likely",
  "Unsicher": "Uncertain",
  "Regel": "Rule",
  "Vorschlag": "Suggestion",
  "Von Ihnen gewählt": "Chosen by you",
  "Keine Zuordnung": "No match",
  "Rechnungsnummer {0} steht im Verwendungszweck": "Invoice number {0} is in the payment reference",
  "Betrag stimmt mit dem offenen Betrag überein": "Amount matches the open amount",
  "Betrag entspricht Rechnung plus Mahnkosten": "Amount equals invoice plus reminder costs",
  "Betrag entspricht den offenen Mahnkosten": "Amount equals the open reminder costs",
  "Name passt ({0})": "Name matches ({0})",
  "Name ähnelt": "Name is similar",
  "IBAN kennt Kontovia von früheren Zahlungen": "Kontovia knows the IBAN from earlier payments",
  "Betrag weicht ab: offen sind {0}, überwiesen wurden": "Amount differs: {0} is open, transferred was",
  "Rechnungsnummern im Verwendungszweck": "Invoice numbers in the payment reference",
  "Summe der offenen Beträge stimmt": "Sum of the open amounts matches",
  "Mehrere offene Rechnungen passen gleich gut": "Several open invoices match equally well",
  "Teilzahlung": "Partial payment",
  "Betrag höher als offen": "Amount higher than open",
  "Rechnungsnummer steht im Verwendungszweck": "Invoice number is in the payment reference",
  "Betrag stimmt mit der offenen Eingangsrechnung überein": "Amount matches the open incoming invoice",
  "Betrag weicht ab: offen sind": "Amount differs: open is",
  "Gegenseite": "Counterparty",
  "Passt zur wiederkehrenden Buchung „{0}“ (Betrag, Name, Termin {1})": "Matches the recurring transaction “{0}” (amount, name, date {1})",
  "Beweglich (Geräte, Möbel, Fahrzeuge)": "Movable (equipment, furniture, vehicles)",
  "Immateriell (Software, Lizenzen, Rechte)": "Intangible (software, licenses, rights)",
  "Gebäude und Grundstücksteile": "Buildings and parts of land",
  "Verkauft": "Sold",
  "Ins Privatvermögen übernommen": "Taken into private assets",
  "Verschrottet oder verloren": "Scrapped or lost",
  "bis {0} (höchstens {1} %)": "until {0} (at most {1}%)",
  "Computer, Notebook, Tablet, Drucker, Software (1 Jahr)": "Computer, notebook, tablet, printer, software (1 year)",
  "Mobiltelefon (5 Jahre)": "Mobile phone (5 years)",
  "Pkw (6 Jahre)": "Car (6 years)",
  "Kopiergerät (7 Jahre)": "Copier (7 years)",
  "Büromöbel (13 Jahre)": "Office furniture (13 years)",
  "Bezeichnung *": "Description *",
  "Anschaffungskosten ({0})": "Acquisition cost ({0})",
  "Anschaffungsdatum": "Acquisition date",
  "Übliche Werte": "Typical values",
  "Wirtschaftsgut wählen, um die Nutzungsdauer zu übernehmen": "Choose an asset to take over the useful life",
  "Nach der amtlichen AfA-Tabelle; für anderes dort nachschlagen oder mit der Steuerberatung klären.": "According to the official depreciation table; for anything else look it up there or clarify with your tax advisor.",
  "Abschreibung": "Depreciation",
  "linear (gleiche Beträge)": "straight-line (equal amounts)",
  "degressiv (fallend, höchstens 30 %)": "declining balance (decreasing, at most 30%)",
  "1 Jahr (voll im Anschaffungsjahr)": "1 year (fully in the year of purchase)",
  "Nutzungsdauer in Jahren": "Useful life in years",
  "Art des Wirtschaftsguts": "Type of asset",
  "Bestimmt die Zeile der Anlage EÜR für die Abschreibung.": "Determines the Anlage EÜR line for depreciation.",
  "Die Anschaffung liegt im festgeschriebenen Zeitraum (bis {0}). Kosten, Datum und Abschreibung bleiben deshalb so, wie sie erklärt wurden; nur die Bezeichnung und ein späterer Abgang lassen sich noch eintragen.": "The purchase is in the locked period (until {0}). Cost, date and depreciation therefore stay as declared; only the description and a later disposal can still be entered.",
  "Verkauft, entnommen oder verschrottet?": "Sold, withdrawn or scrapped?",
  "Ausgeschieden am": "Disposed on",
  "Wie": "How",
  "Abgeschrieben wird bis einschließlich des Monats, in dem das Gut ausscheidet. Was übrig ist, steht als Restbuchwert in der Anlage EÜR. Den Verkaufserlös oder bei einer Übernahme ins Privatvermögen den Wert buchen Sie als Einnahme in der Kategorie „Verkauf von Anlagevermögen“.": "Depreciation runs up to and including the month in which the asset is disposed of. What remains appears as the residual book value in the Anlage EÜR. Book the sales proceeds, or the value when taken into private assets, as income in the category “Sale of fixed assets”.",
  "Der Abgang liegt im festgeschriebenen Zeitraum und bleibt so.": "The disposal is in the locked period and stays as it is.",
  "Restbuchwert: {0} €.": "Residual book value: {0} €.",
  "Computerhardware und Software: ein Jahr Nutzungsdauer, der volle Betrag im Anschaffungsjahr (BMF-Schreiben vom 22.02.2022).": "Computer hardware and software: useful life of one year, the full amount in the year of purchase (BMF letter of 22.02.2022).",
  "% vom jeweiligen Restwert, im ersten Jahr anteilig nach Monaten; sobald die lineare Rate höher ist, wechselt Kontovia zu ihr (§ 7 Abs. 2 und 3 EStG).": "% of the respective residual value, pro rata by month in the first year; as soon as the straight-line rate is higher, Kontovia switches to it (§ 7 (2) and (3) EStG).",
  "Bei unter vier Jahren Nutzungsdauer bringt degressiv nichts, es bleibt praktisch linear.": "With a useful life under four years, declining balance brings nothing; it stays practically straight-line.",
  "Degressiv nur für bewegliche Wirtschaftsgüter, angeschafft {0}.": "Declining balance only for movable assets purchased {0}.",
  "% je Jahr, monatsgenau ab dem Anschaffungsmonat (§ 7 Abs. 1 EStG).": "% per year, by month from the month of purchase (§ 7 (1) EStG).",
  "Bitte eine Bezeichnung eintragen": "Please enter a description",
  "Bitte die Anschaffungskosten eintragen": "Please enter the acquisition cost",
  "Zeitraum ist festgeschrieben": "Period is locked",
  "Bis {0} lässt sich kein Anlagegut mehr anschaffen. Bitte ein späteres Datum wählen.": "No fixed asset can be acquired up to {0}. Please choose a later date.",
  "Degressiv hier nicht möglich": "Declining balance not possible here",
  "Nur für bewegliche Wirtschaftsgüter, angeschafft {0}.": "Only for movable assets purchased {0}.",
  "Abgang vor der Anschaffung": "Disposal before purchase",
  "Bitte das Datum des Abgangs prüfen.": "Please check the disposal date.",
  "Bis 800 € netto": "Up to €800 net",
  "Das Wirtschaftsgut kostet {0} €. Wirtschaftsgüter bis 800 € netto dürfen als geringwertiges Wirtschaftsgut sofort in voller Höhe abgezogen werden (§ 6 Abs. 2 EStG). Trotzdem über mehrere Jahre abschreiben?": "The asset costs {0} €. Assets up to €800 net may be deducted in full immediately as low-value assets (§ 6 (2) EStG). Depreciate over several years anyway?",
  "Trotzdem abschreiben": "Depreciate anyway",
  "Bis {0} lässt sich kein Abgang mehr eintragen. Bitte ein späteres Datum wählen.": "No disposal can be entered up to {0}. Please choose a later date.",
  "wöchentlich": "weekly",
  "alle zwei Wochen": "every two weeks",
  "· Restbetrag {0} €": "· remaining {0} €",
  "tax_{0}_": "tax_{0}_",
  "data-tax=\"1\" data-tax-from=\"{0}\" data-tax-to=\"{1}\" data-tax-jahr=\"{2}\"": "data-tax=\"1\" data-tax-from=\"{0}\" data-tax-to=\"{1}\" data-tax-jahr=\"{2}\"",
  "Darstellung": "Display",
  "Was der Kalender zeigt": "What the calendar shows",
  "Anzeige": "View",
  "Mit Google Kalender oder per Kalenderdatei (.ics) abgleichen": "Sync with Google Calendar or via calendar file (.ics)",
  "Abgleich": "Sync",
  "Im Kalender zeigen": "Show in calendar",
  "Zahlungstermine offener Rechnungen": "Payment dates of open invoices",
  "Veranstaltungen aus Anzahlungen": "Events from down payments",
  "Steuertermine (Voranmeldung, Erklärungen)": "Tax deadlines (VAT returns, annual returns)",
  "Aufgaben mit Fälligkeit": "Tasks with a due date",
  "Erledigte Termine": "Completed appointments",
  "Kalender-Abgleich öffnen": "Open calendar sync",
  "Vorheriger Monat": "Previous month",
  "Heute": "Today",
  "Termine im": "Appointments in",
  "Keine Termine": "No appointments",
  "In diesem Monat ist nichts eingetragen.": "Nothing is scheduled this month.",
  "Zahlungstermine": "Payment dates",
  "Veranstaltungen": "Events",
  "Erledigte": "Completed",
  "Über „Anzeige“ oben rechts wieder einblenden": "Show again via “View” at the top right",
  ", neuer Termin": ", new appointment",
  "Aufgabe:": "Task:",
  "· Google Kalender „{0}“": "· Google Calendar “{0}”",
  "+ {0} weitere": "+ {0} more",
  "von {0} Aufgaben erledigt": "of {0} tasks done",
  "· KW": "· wk",
  "Wiederholung": "Repeat",
  "Veranstaltung": "Event",
  "Steuertermin": "Tax deadline",
  "fällig": "due",
  "ganztägig": "all day",
  "Kommende Termine": "Upcoming appointments",
  "nächste zwölf Monate": "next twelve months",
  "Vergangene Termine": "Past appointments",
  "letzte zwölf Monate": "last twelve months",
  "Nichts geplant": "Nothing planned",
  "Legen Sie oben rechts einen Termin an.": "Create an appointment at the top right.",
  "Hier erscheinen zurückliegende Termine.": "Past appointments appear here.",
  "Termin bearbeiten": "Edit appointment",
  "Als offen markieren": "Mark as open",
  "Als erledigt markieren": "Mark as done",
  "Termin anlegen": "Create appointment",
  "Aufgaben zu diesem Termin": "Tasks for this appointment",
  "Aufgabe hinzufügen, z. B. Vertrag ausdrucken": "Add a task, e.g. print the contract",
  "Neue Aufgabe zum Termin": "New task for the appointment",
  "Hinzufügen": "Add",
  "Vorhandene Aufgabe verknüpfen": "Link existing task",
  "Vorhandene Aufgabe verknüpfen …": "Link existing task …",
  "Vom Termin lösen (die Aufgabe bleibt bestehen)": "Detach from the appointment (the task remains)",
  "Wieder entfernen": "Remove again",
  "vom Termin lösen": "detach from appointment",
  "Was bis zum Termin zu erledigen ist, lässt sich hier abhaken.": "You can tick off here what needs to be done before the appointment.",
  "Aus Google Kalender {0}.": "From Google Calendar {0}.",
  "Änderungen und Löschen gehen beim nächsten Abgleich auch dorthin.": "Changes and deletions also go there at the next sync.",
  "Dieser Kalender wird derzeit nicht abgeglichen; Änderungen bleiben in Kontovia.": "This calendar is currently not synced; changes stay in Kontovia.",
  "In welchem Google-Kalender der Termin erscheint.": "The Google calendar in which the appointment appears.",
  "Titel *": "Title *",
  "Datum *": "Date *",
  "Keiner": "None",
  "Wiederholen bis": "Repeat until",
  "Was ist zu tun, was wird gebraucht …": "What needs to be done, what is needed …",
  "Verknüpfte Buchungen und Rechnungen": "Linked transactions and invoices",
  "Vorhandene verknüpfen": "Link existing",
  "Buchung anlegen": "Create transaction",
  "Dieser Termin wiederholt sich in Google Kalender nach einer Regel, die Kontovia nicht darstellen kann ({0}). Hier erscheint nur der erste Termin; die Regel bleibt in Google erhalten, solange Sie oben keine eigene Wiederholung wählen.": "This appointment repeats in Google Calendar by a rule that Kontovia cannot display ({0}). Only the first appointment appears here; the rule is kept in Google as long as you do not choose your own repetition above.",
  "Verknüpfung lösen": "Unlink",
  "· Nr.": "· No.",
  "Noch nichts verknüpft. So halten Sie fest, welche Rechnung zu welchem Auftrag oder Termin gehört.": "Nothing linked yet. This lets you record which invoice belongs to which order or appointment.",
  "Bitte zuerst einen Titel eintragen": "Please enter a title first",
  "Termin und Buchung verknüpft": "Appointment and transaction linked",
  "Bitte einen Titel eintragen": "Please enter a title",
  "Ende liegt vor dem Beginn": "End is before start",
  "Bitte die Uhrzeiten prüfen. Ein Termin über Mitternacht lässt sich als ganztägig eintragen.": "Please check the times. An appointment past midnight can be entered as all day.",
  "Wiederholung endet vor dem ersten Termin": "Repetition ends before the first appointment",
  "Bitte „Wiederholen bis“ prüfen.": "Please check “Repeat until”.",
  "Termin angelegt": "Appointment created",
  "Termin gespeichert": "Appointment saved",
  "Beim nächsten Abgleich wird er auch in Google Kalender „{0}“ gelöscht.": "At the next sync it will also be deleted in Google Calendar “{0}”.",
  "Termin löschen?": "Delete appointment?",
  "Der Termin wird entfernt. Verknüpfte Buchungen{0} bleiben erhalten.": "The appointment will be removed. Linked transactions{0} are kept.",
  "und Aufgaben": "and tasks",
  "Termin gelöscht": "Appointment deleted",
  "Als erledigt markiert": "Marked as done",
  "Wieder als offen markiert": "Marked as open again",
  "weiterer Kalender": "other calendar",
  "Buchungen verknüpfen": "Link transactions",
  "Keine Buchungen gefunden.": "No transactions found.",
  "Google: Abgleich läuft …": "Google: syncing …",
  "Google: bitte kurz bestätigen": "Google: please confirm briefly",
  "Google: Fehler beim Abgleich": "Google: sync error",
  "Veranstaltungstermine aus Anzahlungen mit übertragen": "Also transfer event dates from down payments",
  "Fälligkeiten offener Rechnungen mit übertragen": "Also transfer due dates of open invoices",
  "Notizen der Termine mit übertragen": "Also transfer appointment notes",
  "Beträge, Buchungen, Kontakte und Belege gehen nie an Google.": "Amounts, transactions, contacts and receipts never go to Google.",
  "Kalender-Abgleich": "Calendar sync",
  "Google Kalender und Kalenderdateien": "Google Calendar and calendar files",
  "für Apple Kalender, Outlook oder ein zweites Google-Konto. Der Export enthält alle Termine; beim Import werden bereits übernommene Termine erkannt und aktualisiert statt doppelt angelegt.": "for Apple Calendar, Outlook or a second Google account. The export contains all appointments; on import, appointments already taken over are recognized and updated instead of being created twice.",
  "Kalenderdatei (.ics):": "Calendar file (.ics):",
  "Als .ics exportieren": "Export as .ics",
  "Aus Google Kalender: Einstellungen → Importieren und exportieren → Exportieren. Google liefert eine ZIP-Datei; darin liegt je Kalender eine .ics-Datei.": "From Google Calendar: Settings → Import & export → Export. Google provides a ZIP file containing one .ics file per calendar.",
  "Termine lassen sich weiterhin als Kalenderdatei (.ics) übertragen.": "Appointments can still be transferred as a calendar file (.ics).",
  "Google Kalender ist gerade nicht erreichbar.": "Google Calendar is not reachable right now.",
  "mit {0} · Kalender „{1}“": "with {0} · calendar “{1}”",
  "Verbunden": "Connected",
  "Trennen": "Disconnect",
  "Ihrem Google-Konto": "your Google account",
  "Abgleich läuft …": "Syncing …",
  "Zuletzt abgeglichen": "Last synced",
  "Noch nicht abgeglichen": "Not synced yet",
  "Der Abgleich wartet auf eine kurze Bestätigung bei Google. Im Browser gilt der Zugriff auf den Kalender jeweils eine Stunde; danach genügt ein Tipp, meist ohne erneute Anmeldung.": "The sync is waiting for a short confirmation at Google. In the browser, access to the calendar is valid for one hour at a time; after that a tap is enough, usually without signing in again.",
  "Bestätigen und abgleichen": "Confirm and sync",
  "Jetzt abgleichen": "Sync now",
  "Kontovia legt in Ihrem Google-Konto einen eigenen Kalender {0} an und gleicht Ihre Termine in beide Richtungen damit ab. Auf dem Telefon sehen Sie sie in der Google-Kalender-App, und was Sie dort im Kalender „Kontovia“ eintragen, erscheint hier. Auf Wunsch kommen Ihre übrigen Kalender dazu, etwa der Hauptkalender, ebenfalls in beide Richtungen.": "Kontovia creates its own calendar {0} in your Google account and syncs your appointments with it in both directions. On the phone you see them in the Google Calendar app, and what you enter there in the “Kontovia” calendar appears here. If you wish, your other calendars are added, such as the main calendar, also in both directions.",
  "„Kontovia“": "“Kontovia”",
  "Mit Google Kalender verbinden": "Connect with Google Calendar",
  "[data-cal=\"connect\"]": "[data-cal=\"connect\"]",
  "[data-cal=\"disconnect\"]": "[data-cal=\"disconnect\"]",
  "[data-cal=\"sync\"]": "[data-cal=\"sync\"]",
  "[data-cal=\"weitere-freigeben\"]": "[data-cal=\"weitere-freigeben\"]",
  "[data-cal=\"weitere-waehlen\"]": "[data-cal=\"weitere-waehlen\"]",
  "[data-cal=\"ics-export\"]": "[data-cal=\"ics-export\"]",
  "[data-cal=\"ics-import\"]": "[data-cal=\"ics-import\"]",
  "Gilt ab dem nächsten Abgleich.": "Applies from the next sync.",
  "Weitere Google-Kalender": "Other Google calendars",
  "Termine aus Ihrem Hauptkalender und anderen Kalendern in Kontovia sehen und bearbeiten. Änderungen und Löschungen gehen in beide Richtungen. Dafür braucht Kontovia einmal zusätzlich Ihre Freigabe bei Google.": "See and edit appointments from your main calendar and other calendars in Kontovia. Changes and deletions go both ways. For this, Kontovia needs your additional approval at Google once.",
  "Weitere Kalender einbeziehen": "Include other calendars",
  "Ausgewählt sind {0}, auf diesem Gerät fehlt aber noch die Freigabe.": "{0} selected, but approval is still missing on this device.",
  "Kalender auswählen": "Choose calendars",
  "In beide Richtungen abgeglichen: {0}. Termine ab gut einem Jahr zurück.": "Synced in both directions: {0}. Appointments from about one year back.",
  "Noch kein weiterer Kalender ausgewählt.": "No other calendar selected yet.",
  "Fenster blockiert": "Window blocked",
  "Ihr Browser hat das kleine Fenster von Google blockiert. Kontovia kann stattdessen für einen Moment zu Google wechseln und danach hierher zurückkehren. Sie entsperren Kontovia dann mit Ihrem Passwort, und es geht dort weiter, wo Sie waren. Möchten Sie das?": "Your browser blocked the small Google window. Kontovia can instead switch to Google for a moment and then come back here. You then unlock Kontovia with your password, and it continues where you were. Would you like that?",
  "Zu Google wechseln": "Switch to Google",
  "Weitere Kalender einbeziehen?": "Include other calendars?",
  "Kontovia fragt bei Google zusätzlich das Recht an, Ihre Kalender aufzulisten und Termine darin zu lesen und zu ändern. Abgeglichen werden danach nur die Kalender, die Sie anschließend auswählen, und zwar in beide Richtungen: Was Sie dort ändern oder löschen, ändert sich hier, und umgekehrt. Es öffnet sich die Anmeldung bei Google; danach geht es hier weiter.": "Kontovia additionally asks Google for the right to list your calendars and to read and change appointments in them. After that, only the calendars you then select are synced, in both directions: what you change or delete there changes here, and vice versa. The Google sign-in opens; after that it continues here.",
  "Weiter zu Google": "Continue to Google",
  "Nicht freigegeben": "Not approved",
};
