/** Wörterbuch Englisch, Teil t10. Quellen: views/calendarsync.js, views/cloudpanel.js, views/dashboard.js. */

export default {
  "Im Google-Dialog wurde der Zugriff auf die übrigen Kalender nicht erlaubt. Der Kalender „Kontovia“ wird weiter abgeglichen.": "In the Google dialog, access to the other calendars was not allowed. The “Kontovia” calendar continues to be synced.",
  "Freigabe fehlgeschlagen": "Approval failed",
  "Kalender nicht abrufbar": "Calendars not available",
  "Weitere Google-Kalender abgleichen": "Sync other Google calendars",
  "Die Termine der gewählten Kalender erscheinen in Kontovia, ab gut einem Jahr zurück. Ändern oder löschen Sie einen davon hier oder in Google, gilt das beim nächsten Abgleich auf beiden Seiten. Neue Termine können Sie in Kontovia direkt einem dieser Kalender zuordnen.": "The appointments of the selected calendars appear in Kontovia, from about one year back. If you change or delete one of them here or in Google, it applies on both sides at the next sync. You can assign new appointments in Kontovia directly to one of these calendars.",
  "(Hauptkalender)": "(main calendar)",
  "Es gibt keine weiteren Kalender, in die Kontovia schreiben darf.": "There are no other calendars that Kontovia may write to.",
  "Termine abgewählter Kalender": "Appointments of deselected calendars",
  "Termine stammen aus Kalendern, die nicht mehr abgeglichen werden. Aus Kontovia entfernen? In Google bleiben sie unverändert.": "appointments come from calendars that are no longer synced. Remove them from Kontovia? They stay unchanged in Google.",
  "Aus Kontovia entfernen": "Remove from Kontovia",
  "Behalten": "Keep",
  "Google Kalender: {0} Termine abgewählter Kalender entfernt": "Google Calendar: {0} appointments of deselected calendars removed",
  "Auswahl gespeichert": "Selection saved",
  "Kein weiterer Kalender": "No other calendar",
  "Kalenderabgleich fehlgeschlagen": "Calendar sync failed",
  "Kalender abgeglichen": "Calendar synced",
  "Kalender abgleichen": "Sync calendar",
  "Bestätigung bei Google fehlgeschlagen": "Confirmation at Google failed",
  "Kein Abgleich": "No sync",
  "Google Kalender ist nicht verbunden.": "Google Calendar is not connected.",
  "Der Abgleich wartet auf eine kurze Bestätigung bei Google.": "The sync is waiting for a short confirmation at Google.",
  "Kontovia legt in Ihrem Google-Konto einen eigenen Kalender {0} an und gleicht Ihre Termine in beide Richtungen damit ab. Auf Ihre übrigen Kalender greift Kontovia nur zu, wenn Sie das unten ankreuzen.": "Kontovia creates its own calendar {0} in your Google account and syncs your appointments with it in both directions. Kontovia only accesses your other calendars if you tick that below.",
  "Titel, Datum, Uhrzeit, Ort und Wiederholung Ihrer Termine, auf Wunsch auch die Notiz. Das geschieht unverschlüsselt, sonst könnte Google die Termine nicht anzeigen. {0} übertragen werden Beträge, Buchungen, Kontakte und Belege. Stehen Namen von Kunden im Titel, gibt Kontovia sie damit an Google weiter; für die geschäftliche Nutzung ist ein Google-Konto mit Auftragsverarbeitungsvertrag (Google Workspace) die saubere Lösung.": "Title, date, time, location and repetition of your appointments, and the note if you wish. This is unencrypted, otherwise Google could not display the appointments. {0} transferred are amounts, transactions, contacts and receipts. If customer names are in the title, Kontovia passes them on to Google; for business use, a Google account with a data processing agreement (Google Workspace) is the clean solution.",
  "Was dafür an Google geht:": "What goes to Google for this:",
  "Nicht": "Not",
  "Veranstaltungstermine aus Anzahlungen mit übertragen (ohne Beträge)": "Also transfer event dates from down payments (without amounts)",
  "Fälligkeiten offener Rechnungen mit übertragen (ohne Beträge)": "Also transfer due dates of open invoices (without amounts)",
  "Auch meine anderen Google-Kalender einbeziehen (z. B. den Hauptkalender), in beide Richtungen. Welche, wählen Sie danach": "Also include my other Google calendars (e.g. the main calendar), in both directions. You choose which ones afterwards",
  "Es öffnet sich die Anmeldung bei Google, meist in einem kleinen Fenster; auf manchen Telefonen wechselt dafür die ganze Seite, und Sie entsperren Kontovia danach mit Ihrem Passwort. Dann geht es hier weiter. Erscheint dort der Hinweis „Google hat diese App nicht überprüft“, geht es über {0} und den Link darunter weiter. Die Verbindung lässt sich jederzeit unter Einstellungen → Kalender-Abgleich trennen.": "The Google sign-in opens, usually in a small window; on some phones the whole page switches for this, and you then unlock Kontovia with your password. Then it continues here. If the notice “Google hasn't verified this app” appears there, continue via {0} and the link below it. The connection can be disconnected at any time under Settings → Calendar sync.",
  "Erweitert": "Advanced",
  "Mit Google verbinden": "Connect with Google",
  "Bei Google abgebrochen": "Cancelled at Google",
  "Der Kalenderabgleich wartet weiter auf Ihre Bestätigung.": "The calendar sync is still waiting for your confirmation.",
  "Google Kalender wurde nicht verbunden.": "Google Calendar was not connected.",
  "Verbinden fehlgeschlagen": "Connecting failed",
  "Bei Google bestätigt": "Confirmed at Google",
  "Der Kalenderabgleich läuft weiter.": "The calendar sync continues.",
  "Bitte melden Sie sich bei Google an und erlauben Sie den Zugriff auf den Kalender. Dieser Hinweis schließt sich danach von selbst.": "Please sign in to Google and allow access to the calendar. This notice closes by itself afterwards.",
  "Nach fünf Minuten ohne Anmeldung bricht Kontovia den Versuch ab.": "After five minutes without sign-in, Kontovia cancels the attempt.",
  "Google Kalender verbunden": "Google Calendar connected",
  "· Kalender „{0}“": "· calendar “{0}”",
  "Erster Abgleich fehlgeschlagen": "First sync failed",
  "Weitere Kalender nicht freigegeben": "Other calendars not approved",
  "Im Google-Dialog wurde der Zugriff auf die übrigen Kalender nicht erlaubt.": "In the Google dialog, access to the other calendars was not allowed.",
  "Google Kalender trennen?": "Disconnect Google Calendar?",
  "Kontovia gleicht danach nicht mehr mit Google ab, und die Freigabe im Google-Konto wird zurückgezogen. Ihre Termine in Kontovia bleiben unverändert. Ist Google Kalender auch auf einem anderen Gerät verbunden, muss er dort danach neu verbunden werden.": "Kontovia will then no longer sync with Google, and the approval in the Google account is withdrawn. Your appointments in Kontovia stay unchanged. If Google Calendar is also connected on another device, it must be reconnected there afterwards.",
  "Auch den Kalender „Kontovia“ in Google löschen": "Also delete the “Kontovia” calendar in Google",
  "Nur ankreuzen, wenn kein anderes Gerät mehr mit diesem Kalender arbeitet.": "Only tick this if no other device works with this calendar anymore.",
  "Google Kalender getrennt": "Google Calendar disconnected",
  "Der Kalender „Kontovia“ wurde in Google gelöscht.": "The “Kontovia” calendar was deleted in Google.",
  "Trennen fehlgeschlagen": "Disconnecting failed",
  "Kontovia:": "Kontovia:",
  "Kontovia-Termine_{0}.ics": "Kontovia-Termine_{0}.ics",
  "Kalenderdatei": "Calendar file",
  "Kalenderdatei gespeichert": "Calendar file saved",
  "Termine ·": "appointments ·",
  "Export fehlgeschlagen": "Export failed",
  "Datei nicht lesbar": "File not readable",
  "Die Datei ist keine gültige Kalenderdatei.": "The file is not a valid calendar file.",
  "Keine Termine gefunden": "No appointments found",
  "Die Datei enthält keine Termine, die Kontovia übernehmen kann.": "The file contains no appointments that Kontovia can take over.",
  "Nichts Neues": "Nothing new",
  "Alle {0} Termine der Datei sind schon in Kontovia.": "All {0} appointments in the file are already in Kontovia.",
  "Termine übernehmen?": "Take over appointments?",
  ": {0} neue Termine{1} aus {2} Einträgen.": ": {0} new appointments{1} from {2} entries.",
  "und {0} geänderte": "and {0} changed",
  "Kalenderdatei {0}: {1} neu, {2} geändert": "Calendar file {0}: {1} new, {2} changed",
  "Termine übernommen": "Appointments taken over",
  "neu, {0} geändert": "new, {0} changed",
  "von {0} in Ihrem Google-Konto belegt": "of {0} used in your Google account",
  "Cloud-Abgleich und Sicherung": "Cloud sync and backup",
  "Ausschließlich Ihre bereits verschlüsselte Buchhaltung. {0} Sie liegt im Cloud-Speicher von Kontovia bei Google, in einem Bereich, an den nur Ihr Google-Konto herankommt. Kosten entstehen Ihnen keine. Daneben bleiben bis zu {1} ältere Stände als Sicherung dort liegen.": "Only your already encrypted accounting. {0} It is stored in Kontovia's cloud storage at Google, in an area only your Google account can access. It costs you nothing. In addition, up to {1} older versions are kept there as backups.",
  "Was dabei übertragen wird.": "What is transferred.",
  "nicht verbunden": "not connected",
  "(siehe unten).": "(see below).",
  "Weil „Mit Google entsperren“ eingeschaltet ist, liegt dort auch der Schlüssel dazu": "Because “Unlock with Google” is turned on, the key to it is stored there too",
  "Ohne Ihr Passwort lässt sie sich nicht lesen, weder von Google noch vom Hersteller von Kontovia.": "It cannot be read without your password, neither by Google nor by the maker of Kontovia.",
  "Ihre Buchhaltung auf diesem Gerät ist vollständig. Verbinden Sie die Cloud-Sicherung bitte einmal neu, dann ist sie wieder auf dem aktuellen Stand.": "Your accounting on this device is complete. Please reconnect the cloud backup once, then it will be up to date again.",
  "Ihre Cloud-Sicherung lief bisher über Google Drive. Diesen Weg gibt es nicht mehr.": "Your cloud backup previously ran via Google Drive. This option no longer exists.",
  "Ihre Cloud-Sicherung lief bisher über ein eigenes Google-Projekt. Das lässt sich nicht mehr einstellen.": "Your cloud backup previously ran via your own Google project. This can no longer be set up.",
  "In dieser Fassung ist kein Cloud-Abgleich verfügbar. Ihre Buchhaltung bleibt auf diesem Gerät; sichern Sie sie regelmäßig mit einer Vollsicherung.": "Cloud sync is not available in this version. Your accounting stays on this device; back it up regularly with a full backup.",
  "Ihre Buchhaltung bleibt dabei, wie sie ist. Ist das Konto noch leer, wird sie hochgeladen; liegt dort schon eine, fragt Kontovia, welche gelten soll.": "Your accounting stays as it is. If the account is still empty, it is uploaded; if there is already one there, Kontovia asks which one should apply.",
  "Mit der Verbindung bestätigt dieses Gerät alle 30 Tage von selbst bei Ihrem Konto, dass es noch zugelassen ist. Dabei wird nur gelesen, es gehen keine Angaben zu Ihrer Buchhaltung hinaus.": "With the connection, this device confirms by itself every 30 days with your account that it is still approved. This only reads; no details about your accounting are sent.",
  "Klappt nicht? Mit Code verbinden": "Not working? Connect with a code",
  "Sie werden zu Google weitergeleitet und kommen nach der Anmeldung hierher zurück. Kontovia ist dann gesperrt. Entsperren Sie es einmal mit Ihrem Passwort, dann steht die Verbindung.": "You are redirected to Google and come back here after signing in. Kontovia is then locked. Unlock it once with your password, and the connection is set up.",
  "Kontovia zeigt einen kurzen Code, den Sie auf google.com/device eingeben, auf diesem oder einem anderen Gerät. Dort sehen Sie in der Adresszeile, dass Sie Ihr Passwort bei Google eingeben und nicht bei Kontovia.": "Kontovia shows a short code that you enter at google.com/device, on this or another device. There you can see in the address bar that you are entering your password at Google and not at Kontovia.",
  "Letzter Abgleich": "Last sync",
  "Dieses Gerät": "This device",
  "Automatisch abgleichen": "Sync automatically",
  "Nach jeder Änderung mit kurzer Verzögerung, beim Programmstart und regelmäßig.": "After every change with a short delay, at program start and regularly.",
  "Regelmäßig alle": "Regularly every",
  "Verbindung trennen": "Disconnect",
  "Sicherungen in der Cloud": "Backups in the cloud",
  "Einmal am Tag legt der Abgleich zusätzlich eine Kopie des verschlüsselten Tresors in Ihrem Konto ab, außerdem vor jedem Überschreiben und jeder Wiederherstellung. Die {0} neuesten bleiben erhalten. So lässt sich auch ein Stand zurückholen, den alle Geräte schon übernommen haben, etwa nach einem versehentlichen Löschen.": "Once a day, the sync additionally stores a copy of the encrypted vault in your account, and also before every overwrite and every restore. The {0} newest are kept. This way you can also get back a version that all devices have already taken over, for example after an accidental deletion.",
  "Jetzt in der Cloud sichern": "Back up to the cloud now",
  "Sicherungen ansehen": "View backups",
  "noch keiner": "none yet",
  "Speicher": "Storage",
  "Minuten": "minutes",
  "Konflikt{0} ansehen": "View conflict{0}",
  "Die letzte Sicherung in der Cloud ist fehlgeschlagen:": "The last backup in the cloud failed:",
  "Noch keine Sicherung von diesem Gerät": "No backup from this device yet",
  "Mit Google entsperren, ohne Passwort": "Unlock with Google, without password",
  "Wer sich mit {0} bei Google anmeldet, öffnet Ihre Buchhaltung ohne Ihr Kontovia-Passwort, auf jedem Gerät. Ihre Daten sind damit nur noch durch das Passwort Ihres Google-Kontos geschützt.": "Anyone who signs in to Google with {0} opens your accounting without your Kontovia password, on any device. Your data is then only protected by your Google account password.",
  "Eingeschaltet. Das ist ein großes Sicherheitsrisiko.": "Turned on. This is a major security risk.",
  "Auf Wunsch öffnet Kontovia Ihre Buchhaltung auf jedem Gerät allein mit der Anmeldung bei Google.": "If you wish, Kontovia opens your accounting on any device with just the Google sign-in.",
  "Dafür liegt der Schlüssel zu Ihrer Buchhaltung unverschlüsselt in Ihrem Cloud-Speicher. Ihre Daten sind dann nur noch durch das Passwort Ihres Google-Kontos geschützt, nicht mehr durch Ihr Kontovia-Passwort: Wer Ihr Google-Konto übernimmt, kann Ihre ganze Buchhaltung lesen. Technisch kämen dann auch Google und der Hersteller von Kontovia an sie heran. Wir raten davon ab.": "For this, the key to your accounting is stored unencrypted in your cloud storage. Your data is then only protected by your Google account password, no longer by your Kontovia password: anyone who takes over your Google account can read your entire accounting. Technically, Google and the maker of Kontovia could then also access it. We advise against it.",
  "Großes Sicherheitsrisiko.": "Major security risk.",
  "Trotzdem einschalten …": "Turn on anyway …",
  "Der Schlüssel ist aus Ihrem Cloud-Speicher gelöscht. Kontovia öffnet sich wieder nur mit Ihrem Passwort oder Fingerabdruck.": "The key has been deleted from your cloud storage. Kontovia opens again only with your password or fingerprint.",
  "Kontovia lässt sich jetzt mit Ihrem Google-Konto öffnen, ohne Passwort. Auf Ihren anderen Geräten erscheint der Knopf nach dem nächsten Entsperren.": "Kontovia can now be opened with your Google account, without a password. On your other devices the button appears after the next unlock.",
  "Mit Google entsperren einschalten?": "Turn on unlock with Google?",
  "Das ist ein großes Sicherheitsrisiko.": "This is a major security risk.",
  "Der Schlüssel zu Ihrer Buchhaltung liegt dann unverschlüsselt in Ihrem Cloud-Speicher.": "The key to your accounting is then stored unencrypted in your cloud storage.",
  "Ihre Daten sind nur noch durch das Passwort Ihres Google-Kontos{0} geschützt. Ihr Kontovia-Passwort schützt sie dann nicht mehr.": "Your data is then only protected by the password of your Google account{0}. Your Kontovia password no longer protects it.",
  "Wer Ihr Google-Konto übernimmt, kann Ihre ganze Buchhaltung lesen, auf jedem Gerät. Technisch kämen auch Google und der Hersteller von Kontovia an sie heran.": "Anyone who takes over your Google account can read your entire accounting, on any device. Technically, Google and the maker of Kontovia could also access it.",
  "Ausschalten löscht den Schlüssel dort wieder. Wer ihn vorher kopiert hat, kann Ihre Buchhaltung aber weiter öffnen, auch mit allen späteren Änderungen.": "Turning it off deletes the key there again. But anyone who copied it before can still open your accounting, including all later changes.",
  "Sicherer: ein neues Gerät mit dem QR-Code verbinden (Sicherheit & Zugang, Weitere Geräte) und dort Fingerabdruck oder Gesicht einschalten.": "Safer: connect a new device with the QR code (Security & access, Other devices) and turn on fingerprint or face there.",
  "Ich habe verstanden, dass meine Buchhaltung dann nur noch durch mein Google-Konto geschützt ist.": "I understand that my accounting is then only protected by my Google account.",
  "Trotzdem einschalten": "Turn on anyway",
  "Mit Google verbunden": "Connected with Google",
  "Verbindung fehlgeschlagen": "Connection failed",
  "In der Cloud gesichert": "Backed up to the cloud",
  "Sicherung fehlgeschlagen": "Backup failed",
  "Automatik eingeschaltet": "Automation turned on",
  "Automatik ausgeschaltet": "Automation turned off",
  "Abstand gespeichert": "Interval saved",
  "Verbindung getrennt": "Disconnected",
  "Tresor, Belege, Sicherungen und Ihr Anmeldekonto wurden auch in der Cloud gelöscht.": "Vault, receipts, backups and your sign-in account were also deleted in the cloud.",
  "Der verschlüsselte Stand bleibt in der Cloud liegen.": "The encrypted version stays in the cloud.",
  "Verbindung zur Cloud trennen?": "Disconnect from the cloud?",
  "Dieses Gerät meldet sich von der Cloud ab. Ihre Buchhaltung bleibt vollständig auf diesem Gerät, und Ihre anderen Geräte bleiben verbunden.": "This device signs out of the cloud. Your accounting stays complete on this device, and your other devices stay connected.",
  "Tresor, Belege und Sicherungen auch in der Cloud löschen, samt Ihrem Anmeldekonto dort (E-Mail-Adresse)": "Also delete vault, receipts and backups in the cloud, including your sign-in account there (email address)",
  "Ohne Häkchen bleibt der verschlüsselte Stand dort liegen, etwa für Ihre anderen Geräte oder um sich später wieder zu verbinden. Den Zugriff von Kontovia auf Ihr Google-Konto entfernen Sie ganz unter myaccount.google.com/connections.": "Without the tick, the encrypted version stays there, for example for your other devices or to reconnect later. You remove Kontovia's access to your Google account completely at myaccount.google.com/connections.",
  "täglich": "daily",
  "von Hand": "manually",
  "vor dem Überschreiben": "before overwriting",
  "vor einer Wiederherstellung": "before a restore",
  "vor dem Übernehmen": "before taking over",
  "Stand vor Version 2.26": "Version before 2.26",
  "von einem Gerät mit älterer Version": "from a device with an older version",
  "Die Liste ließ sich nicht laden:": "The list could not be loaded:",
  "Noch keine Sicherung": "No backup yet",
  "Die erste entsteht beim nächsten Abgleich oder mit „Jetzt in der Cloud sichern“.": "The first one is created at the next sync or with “Back up to the cloud now”.",
  "Eine Sicherung ersetzt beim Wiederherstellen den Bestand dieses Geräts; der nächste Abgleich bringt ihn zu Ihren anderen Geräten. Der jetzige Stand wird vorher gesichert, und zwar hier in der Liste und im Sicherungsordner dieses Geräts.": "When restored, a backup replaces this device's data; the next sync brings it to your other devices. The current version is backed up first, here in the list and in this device's backup folder.",
  "Zeitpunkt": "Time",
  "Anlass": "Reason",
  "Wiederherstellen": "Restore",
  "Stand vom {0} wiederherstellen?": "Restore the version of {0}?",
  "Der Bestand dieses Geräts wird durch die Sicherung ersetzt, und beim nächsten Abgleich gilt sie auch für Ihre anderen Geräte: Was nach diesem Zeitpunkt angelegt oder geändert wurde, ist danach überall auf dem Stand der Sicherung. Der jetzige Stand wird vorher in der Cloud und auf diesem Gerät gesichert. Die Verbindungen dieses Geräts bleiben bestehen.": "This device's data is replaced by the backup, and at the next sync it also applies to your other devices: anything created or changed after this point will then be at the backup's state everywhere. The current version is backed up first in the cloud and on this device. This device's connections remain.",
  "Passwort dieser Sicherung": "Password of this backup",
  "Diese Sicherung gehört zu einer anderen Buchhaltung als der auf diesem Gerät, etwa dem Stand, der vor einem „Cloud überschreiben“ dort lag. Mit ihrem Passwort wird sie zur Buchhaltung dieses Geräts; die jetzige kommt vorher in den Sicherungsordner.": "This backup belongs to a different accounting than the one on this device, such as the version that was there before a “Overwrite cloud”. With its password it becomes this device's accounting; the current one goes into the backup folder first.",
  "Laden": "Load",
  "Stand der Cloud-Sicherung vom {0} wiederhergestellt": "Cloud backup of {0} restored",
  "Sicherung wiederhergestellt": "Backup restored",
  "Buchungen. Der Abgleich bringt den Stand jetzt zu Ihren anderen Geräten.": "transactions. The sync now brings this version to your other devices.",
  "Wiederherstellung fehlgeschlagen": "Restore failed",
  "Das Passwort passt nicht zu dieser Sicherung.": "The password does not match this backup.",
  "Cloud nicht erreichbar": "Cloud not reachable",
  "Cloud ist noch leer": "Cloud is still empty",
  "Ihr aktueller Stand wird hochgeladen.": "Your current version is being uploaded.",
  "In der Cloud liegt bereits eine andere Buchhaltung": "There is already a different accounting in the cloud",
  "In Ihrem Google-Konto liegt schon ein Kontovia-Tresor, der sich mit dem Passwort dieses Geräts nicht öffnen lässt. Das ist der normale Fall, wenn Sie Kontovia vorher auf einem anderen Rechner eingerichtet haben.": "Your Google account already contains a Kontovia vault that cannot be opened with this device's password. This is normal if you set up Kontovia on another computer before.",
  "Cloud-Stand: {0}, zuletzt geändert {1}.": "Cloud version: {0}, last changed {1}.",
  "Auf diesem Gerät: {0} Buchungen, {1} Termine.": "On this device: {0} transactions, {1} appointments.",
  "Wie möchten Sie weitermachen?": "How would you like to continue?",
  "ist der empfohlene Weg, wenn dieses Gerät neu dazukommt. Ihr hiesiger Tresor wird vorher gesichert, dann durch den Cloud-Stand ersetzt. Danach melden Sie sich mit dem Passwort des anderen Geräts an, und ab da arbeiten beide Geräte auf demselben Bestand.": "is the recommended way if this device is new. Your vault here is backed up first, then replaced by the cloud version. After that you sign in with the other device's password, and from then on both devices work on the same data.",
  "Cloud-Stand übernehmen": "Take over cloud version",
  "brauchen Sie nur, wenn der Cloud-Stand veraltet oder ein Fehlversuch war. Was dort liegt, wird vorher als Sicherung abgelegt und lässt sich unter {0} mit seinem Passwort zurückholen.": "is only needed if the cloud version is outdated or was a failed attempt. What is there is stored as a backup first and can be restored with its password under {0}.",
  "Cloud überschreiben": "Overwrite cloud",
  "Später entscheiden": "Decide later",
  "Cloud-Stand übernehmen?": "Take over cloud version?",
  "Der Tresor dieses Geräts wird zuvor in den Sicherungsordner kopiert und dann ersetzt. Anschließend werden Sie nach dem Passwort des Cloud-Tresors gefragt.": "This device's vault is first copied into the backup folder and then replaced. You will then be asked for the password of the cloud vault.",
  "Übernahme fehlgeschlagen": "Takeover failed",
  "Cloud-Stand überschreiben?": "Overwrite cloud version?",
  "Die Buchhaltung, die derzeit in Ihrem Google-Konto liegt, wird durch den Stand dieses Geräts ersetzt. Vorher legt Kontovia sie als Sicherung ab; sie bleibt dort, bis 30 neuere Sicherungen sie verdrängen, und lässt sich mit ihrem Passwort zurückholen.": "The accounting currently in your Google account will be replaced by this device's version. Kontovia stores it as a backup first; it stays there until 30 newer backups push it out and can be restored with its password.",
  "Überschreiben": "Overwrite",
  "Cloud-Stand ersetzt": "Cloud version replaced",
  "Fehlgeschlagen": "Failed",
  "Nichts zu tun": "Nothing to do",
  "Neu anmelden": "Sign in again",
  "Wieder angemeldet": "Signed in again",
  "Letzter Versuch fehlgeschlagen:": "Last attempt failed:",
  "Zuletzt {0}: {1}.": "Last {0}: {1}.",
  "Belege: {0} hoch, {1} runter.": "Receipts: {0} up, {1} down.",
  "Konflikte beim Abgleich": "Sync conflicts",
  "Ein Konflikt entsteht, wenn derselbe Datensatz auf zwei Geräten unterschiedlich geändert wurde. Kontovia behält die zuletzt bearbeitete Fassung und legt die andere hier ab. Es geht nichts verloren.": "A conflict arises when the same record was changed differently on two devices. Kontovia keeps the most recently edited version and stores the other one here. Nothing is lost.",
  "Konflikte": "Conflicts",
  "nowrap small": "nowrap small",
  "Datensatz": "Record",
  "dieses Gerät": "this device",
  "Cloud": "Cloud",
  "Verworfene Fassung": "Discarded version",
  "Alle Arten": "All types",
  "Behalten:": "Kept:",
  "Beide": "Both",
  "Keine Konflikte": "No conflicts",
  "Bisher gab es beim Abgleich nichts zu entscheiden.": "So far there was nothing to decide during sync.",
  "Liste leeren": "Clear list",
  "Konfliktliste geleert": "Conflict list cleared",
  "Liste geleert": "List cleared",
  "Diese Fassung wurde beim Abgleich zurückgestellt. Sie können die Werte von Hand übernehmen, wenn sie die richtigen waren.": "This version was set aside during sync. You can take over the values manually if they were the right ones.",
  "Programmaktualisierung": "Program updates",
  "Version": "Version",
  "Kontovia liegt vollständig auf diesem Gerät und läuft auch ohne Netz. Eine neue Version wird erst geladen, wenn Sie es hier bestätigen.": "Kontovia is stored completely on this device and also runs without a network. A new version is only loaded once you confirm it here.",
  "Nach Updates suchen": "Check for updates",
  "regelmäßig von selbst suchen": "check regularly by itself",
  "Gesucht wird nur, wenn Sie es auslösen oder oben einschalten. Der Server sieht dabei Ihre IP-Adresse; Angaben zu Ihrem Gerät oder Ihrer Buchhaltung werden nicht mitgesendet. Bevor eine neue Version eingesetzt wird, prüft Kontovia, dass sie vollständig und unverändert angekommen ist, und installiert sie erst nach Ihrer Bestätigung.": "Checking only happens when you trigger it or turn it on above. The server sees your IP address; no details about your device or your accounting are sent. Before a new version is used, Kontovia checks that it arrived complete and unchanged, and only installs it after your confirmation.",
  "Prüfung eingeschaltet": "Checking turned on",
  "Prüfung ausgeschaltet": "Checking turned off",
  "Jetzt aktualisieren": "Update now",
  "Kontovia lädt die neue Version, prüft sie und lädt sich dann neu. Ihre Daten bleiben, wie sie sind, und Sie bleiben angemeldet.": "Kontovia downloads the new version, checks it and then reloads. Your data stays as it is and you stay signed in.",
  "Sie verwenden Version {0}.": "You are using version {0}.",
  "Die neue Fassung wurde am {0} veröffentlicht.": "The new version was released on {0}.",
  "Später erinnern": "Remind me later",
  "Die Prüfung war nicht erfolgreich.": "The check was not successful.",
  "Es ist keine Update-Adresse hinterlegt.": "No update address is set.",
  "Der Update-Server ist gerade nicht erreichbar.": "The update server is not reachable right now.",
  "Sie verwenden bereits die neueste Version ({0}).": "You are already using the latest version ({0}).",
  "Sie haben Version {0}.": "You have version {0}.",
  "Version {0} ist verfügbar.": "Version {0} is available.",
  "Veröffentlicht am {0}.": "Released on {0}.",
  "Herunterladen": "Download",
  "Prüfen": "Check",
  "Version {0} ist geladen. Die Seite lädt sich gleich neu, und Sie bleiben angemeldet.": "Version {0} is loaded. The page will reload shortly, and you stay signed in.",
  "Kontovia wird neu geladen": "Kontovia is reloading",
  "Die Datei wird geprüft …": "Checking the file …",
  "Verbindung wird aufgebaut …": "Connecting …",
  "von {0} · {1} %": "of {0} · {1}%",
  "Update heruntergeladen": "Update downloaded",
  "Es wurde noch nicht installiert. Sie finden es weiterhin unter „Version verfügbar“.": "It has not been installed yet. You still find it under “Version available”.",
  "ein Viertel": "one quarter",
  "ein Drittel": "one third",
  "halbe Breite": "half width",
  "zwei Drittel": "two thirds",
  "drei Viertel": "three quarters",
  "ganze Breite": "full width",
  "data-ziel=\"{0}\"{1} role=\"link\" tabindex=\"0\"": "data-ziel=\"{0}\"{1} role=\"link\" tabindex=\"0\"",
  "Count": "Count",
  "einer Rechnung": "one invoice",
  "einem Beleg": "one receipt",
  "Belegen": "receipts",
  "mit Datum im Zeitraum, die noch nicht bezahlt sind ({0}). Sie zählen erst an ihrem Zahlungstag.": "dated in the period that have not been paid yet ({0}). They only count on their payment date.",
  "+ {0} € offen": "+ {0} € open",
  "Belege": "Receipts",
  "Enthält {0} € aus {1} anderer Zeiträume, im Zeitraum bezahlt und deshalb hier gezählt.": "Includes {0} € from {1} of other periods, paid in the period and therefore counted here.",
  "nichts offen": "nothing open",
  "nach Kategorie": "by category",
  "Die Zahlungseingänge dieses Zeitraums ansehen": "View the incoming payments of this period",
  "Die Zahlungsausgänge dieses Zeitraums ansehen": "View the outgoing payments of this period",
  "Gewinn oder Verlust": "Profit or loss",
  "Gewinn- und Verlustrechnung öffnen": "Open profit and loss statement",
  "Marge {0} %": "Margin {0}%",
  "Umsatzsteuer-Zahllast": "VAT payable",
  "Vorsteuer-Erstattung": "Input VAT refund",
  "Umsatzsteuer-Voranmeldung öffnen": "Open VAT return",
  "€ · Vorsteuer {0} €": "€ · input VAT {0} €",
  "Nach Rechnungsdatum (Soll-Versteuerung)": "By invoice date (accrual basis)",
  "Nach Zahlungseingang (Ist-Versteuerung)": "By payment received (cash basis)",
  "Kontostände heute": "Account balances today",
  "Zu den Zahlungskonten": "To the payment accounts",
  "über {0} Konten": "across {0} accounts",
  "Zur Gewinn- und Verlustrechnung": "To the profit and loss statement",
  "Details": "Details",
  "Ihre Forderungen": "Your receivables",
  "Ihre Verbindlichkeiten": "Your payables",
  "Noch nicht bezahlte Einnahmen ansehen": "View unpaid income",
  "Noch nicht bezahlte Ausgaben ansehen": "View unpaid expenses",
  "Am längsten offen:": "Open the longest:",
  "seit so vielen Tagen überfällig": "overdue for this many days",
  "1 Tag": "1 day",
  "noch nicht fällig": "not yet due",
  "Alle Einnahmen sind bezahlt.": "All income has been paid.",
  "Liste der offenen Posten öffnen": "Open the list of open items",
  "Größte Ausgabenblöcke": "Largest expense blocks",
  "Alle Ausgaben dieses Zeitraums ansehen": "View all expenses of this period",
  "Umsatz nach Kategorie": "Revenue by category",
  "Alle Einnahmen dieses Zeitraums ansehen": "View all income of this period",
  "Konten und Vermögen": "Accounts and assets",
  "Anlagevermögen (Restwert)": "Fixed assets (residual value)",
  "Zum Anlagevermögen": "To fixed assets",
  "Unbezahlte Rechnungen ansehen": "View unpaid invoices",
  "Offene Rechnungen ansehen": "View open invoices",
  "Vermögensübersicht öffnen": "Open statement of assets",
  "Anstehende Termine": "Upcoming appointments",
  "In den nächsten sechs Wochen steht nichts an.": "Nothing is coming up in the next six weeks.",
  "Zum Kalender": "To the calendar",
  "Fällt eine Frist auf ein Wochenende oder einen Feiertag, gilt der nächste Werktag.": "If a deadline falls on a weekend or public holiday, the next working day applies.",
  "Kennzahl 83 nach dem heutigen Stand": "Box 83 as of today",
  "Mit Dauerfristverlängerung.": "With permanent extension.",
  "Eine Dauerfristverlängerung stellen Sie in den Einstellungen ein.": "You set up a permanent extension in the settings.",
  "In den nächsten Monaten steht keine Steuerfrist an.": "No tax deadline is coming up in the next months.",
  "nächste Fristen": "next deadlines",
  "Im Kalender ansehen": "View in calendar",
  "Offene Aufgaben": "Open tasks",
  "und {0} weitere": "and {0} more",
  "Alle Aufgaben sind erledigt.": "All tasks are done.",
  "Zu allen Aufgaben": "To all tasks",
  "Ordnung und Vollständigkeit": "Order and completeness",
  "Belegquote": "Receipt ratio",
  "von {0} {1} einen Beleg.": "of {0} {1} a receipt.",
  "Buchungen ohne Beleg ansehen": "View transactions without receipt",
  "Keine Auffälligkeiten gefunden.": "No irregularities found.",
  "Alle Buchungen des Zeitraums ansehen": "View all transactions of the period",
  "Letzte Buchungen": "Latest transactions",
  "(ohne Beschreibung)": "(no description)",
  "Noch keine Buchungen": "No transactions yet",
  "Oben rechts legen Sie die erste an.": "Create the first one at the top right.",
  "Alle Buchungen ansehen": "View all transactions",
  "Durchschnittswerte": "Averages",
  "Einnahmen je Monat": "Income per month",
  "Die Einnahmen ansehen": "View the income",
  "Ausgaben je Monat": "Expenses per month",
  "Die Ausgaben ansehen": "View the expenses",
  "Ergebnis je Monat": "Result per month",
  "Einnahme je Buchung": "Income per transaction",
  "Ausgabe je Buchung": "Expense per transaction",
  "Bester Monat": "Best month",
  "Die Buchungen dieses Monats ansehen": "View this month's transactions",
  "über": "over",
  "Zum Verschieben ziehen": "Drag to move",
  "Breite von": "Width of",
  "nach vorn": "forward",
  "Nach vorn": "Forward",
  "nach hinten": "back",
  "Nach hinten": "Back",
  "Übersicht anpassen": "Customize overview",
  "Module an ihren Platz ziehen oder mit den Pfeilen verschieben, die Breite wählen, Unnötiges ausblenden. Die Anordnung gilt für dieses Gerät.": "Drag modules to their place or move them with the arrows, choose the width, hide what you don't need. The layout applies to this device.",
  "Voreinstellung": "Default",
  "Ausgeblendet:": "Hidden:",
  "nichts, alle Module sind zu sehen.": "nothing, all modules are visible.",
  "Einnahmen, Ausgaben und Gewinn zählen am Tag der Zahlung, wie in der Anlage EÜR. Eine im Zeitraum bezahlte Rechnung zählt also auch dann, wenn ihr Datum außerhalb liegt.": "Income, expenses and profit count on the day of payment, as in the Anlage EÜR. An invoice paid in the period therefore also counts if its date is outside it.",
  "Einnahmen und Ausgaben nach Zahlungsdatum ·": "Income and expenses by payment date ·",
  "Module anordnen, Größe ändern, ein- und ausblenden. Oder eine Kachel gedrückt halten und gleich verschieben.": "Arrange modules, change their size, show and hide them. Or press and hold a tile to move it right away.",
  "Anpassen": "Customize",
  "Ihre Buchhaltung": "Your accounting",
  "Kleinunternehmer § 19 UStG": "Small business § 19 UStG",
  "Umsatzsteuer nach Rechnungsdatum (Soll)": "VAT by invoice date (accrual)",
  "Umsatzsteuer nach Zahlungseingang (Ist)": "VAT by payment received (cash)",
  "fällig.": "due.",
};
