/** Wörterbuch Englisch, Teil t11. Quellen: views/dashboard.js, views/datenimport.js, views/erechnung.js, views/export.js, views/help.js. */

export default {
  "Ansehen und anlegen": "View and create",
  "Eine wiederkehrende Buchung ist": "One recurring transaction is",
  "wiederkehrende Buchungen sind": "recurring transactions are",
  "Alle Module sind ausgeblendet": "All modules are hidden",
  "Über „Anpassen“ holen Sie sie zurück.": "Bring them back via “Customize”.",
  "[data-widget=\"{0}\"] .dash-body": "[data-widget=\"{0}\"] .dash-body",
  "Voreinstellung wiederhergestellt": "Default restored",
  "[data-size=\"{0}\"][data-id=\"{1}\"]": "[data-size=\"{0}\"][data-id=\"{1}\"]",
  "[data-hide=\"{0}\"]": "[data-hide=\"{0}\"]",
  "[data-move=\"{0}\"][data-id=\"{1}\"]": "[data-move=\"{0}\"][data-id=\"{1}\"]",
  "button, input, select, textarea, a": "button, input, select, textarea, a",
  "[data-widget=\"{0}\"]": "[data-widget=\"{0}\"]",
  "px {0}px": "px {0}px",
  "Nichts übernommen": "Nothing imported",
  "Die gewählten Einträge sind noch nicht übernommen. Wenn Sie die Seite verlassen, geht die Auswahl verloren.": "The selected entries have not been imported yet. If you leave the page, the selection is lost.",
  "Verlassen": "Leave",
  "Buchungen aus einem anderen Programm": "Transactions from another program",
  "DATEV-Format (von der Kanzlei, aus Lexware Office, sevDesk und anderen), Excel-Tabelle oder CSV. Kategorien werden am Sachkonto oder am Namen erkannt.": "DATEV format (from your tax firm, from Lexware Office, sevDesk and others), Excel spreadsheet or CSV. Categories are recognized by the ledger account or by name.",
  "Umsatzsteuer-Voranmeldung aus ELSTER": "VAT return from ELSTER",
  "XML-Datei einer Voranmeldung, etwa aus Ihrem bisherigen Programm. Kontovia stellt sie neben die eigene Berechnung und zeigt Abweichungen.": "XML file of a VAT return, for example from your previous program. Kontovia puts it next to its own calculation and shows differences.",
  "Visitenkarten (vCard) aus Outlook, Google oder vom Telefon, Tabellen mit Adressen oder DATEV-Debitoren und -Kreditoren.": "Business cards (vCard) from Outlook, Google or your phone, tables with addresses or DATEV debtors and creditors.",
  "Produkte und Leistungen": "Products and services",
  "Tabelle mit Bezeichnung, Preis, Einheit und Steuersatz, zum Beispiel aus Ihrem bisherigen Rechnungsprogramm.": "Table with description, price, unit and tax rate, for example from your previous invoicing program.",
  "CSV, CAMT.053 oder MT940 von Ihrer Bank. Zahlungen werden offenen Rechnungen zugeordnet.": "CSV, CAMT.053 or MT940 from your bank. Payments are matched to open invoices.",
  "E-Rechnung erhalten": "Received e-invoice",
  "Die E-Rechnung eines Lieferanten, als XML-Datei oder PDF. Kontovia zeigt sie lesbar an und bereitet die Buchung vor.": "A supplier's e-invoice, as an XML file or PDF. Kontovia shows it in readable form and prepares the transaction.",
  "Kalenderdatei (.ics) aus Outlook, Google oder Apple Kalender.": "Calendar file (.ics) from Outlook, Google or Apple Calendar.",
  "Aus einem anderen Programm, von Ihrer Steuerkanzlei oder aus ELSTER. Die Datei wird nur auf diesem Gerät gelesen und nirgends hochgeladen. Übernommen wird erst, wenn Sie es bestätigen.": "From another program, from your tax firm or from ELSTER. The file is only read on this device and not uploaded anywhere. Nothing is imported until you confirm.",
  "Datei hierher ziehen oder auswählen": "Drag a file here or choose one",
  "Kontovia erkennt das Format selbst: DATEV, Excel, CSV, ELSTER-XML, vCard, Kalenderdatei, E-Rechnung und Kontoauszug.": "Kontovia detects the format itself: DATEV, Excel, CSV, ELSTER XML, vCard, calendar file, e-invoice and bank statement.",
  "Datei wählen": "Choose file",
  "Zum Kontoauszug": "To bank statement",
  "Eingelesene Voranmeldungen": "Imported VAT returns",
  "Summe Kennzahl 83": "Total box 83",
  "Voranmeldung": "VAT return",
  "Voranmeldungen": "VAT returns",
  "strong nowrap": "strong nowrap",
  "Kennzahl 83": "Box 83",
  "Abgleich mit Kontovia": "Comparison with Kontovia",
  "Kleinunternehmer": "Small business",
  "stimmt überein": "matches",
  "weicht ab": "differs",
  "Kennzahl 83 um {0} €": "Box 83 by {0} €",
  "bei einzelnen Kennzahlen": "in individual boxes",
  "Datei": "File",
  "nowrap right": "nowrap right",
  "Voranmeldung entfernen?": "Remove VAT return?",
  "Die eingelesene Voranmeldung für {0} wird aus Kontovia entfernt. Beim Finanzamt ändert sich dadurch nichts.": "The imported VAT return for {0} will be removed from Kontovia. Nothing changes at the tax office.",
  "In Kontovia ist die Kleinunternehmerregelung eingestellt; einen Vergleich gibt es deshalb nicht.": "The small business rule is set in Kontovia; therefore there is no comparison.",
  "Bemessungsgrundlagen zählen wie in ELSTER in vollen Euro.": "Tax bases count in whole euros as in ELSTER.",
  "Kennzahl": "Box",
  "Unterschied": "Difference",
  "Die Werte stimmen mit den Buchungen in Kontovia überein.": "The values match the transactions in Kontovia.",
  "Wo die Werte abweichen, fehlt meist eine Buchung, oder eine Buchung liegt in einem anderen Zeitraum oder hat einen anderen Steuersatz.": "Where the values differ, usually a transaction is missing, or a transaction is in a different period or has a different tax rate.",
  "Keine Beträge.": "No amounts.",
  "Steuernummer {0} · Datei": "Tax number {0} · file",
  "Buchungen des Zeitraums": "Transactions of the period",
  "Datei zu groß": "File too large",
  "Bitte eine kleinere Datei wählen oder sie aufteilen.": "Please choose a smaller file or split it.",
  "„{0}“ wird gelesen …": "Reading “{0}” …",
  "Excel-Tabelle": "Excel spreadsheet",
  "PDF lässt sich nicht übernehmen": "PDF cannot be imported",
  "Aus einem PDF lassen sich keine Daten lesen, auch nicht aus dem Ausdruck von „Mein ELSTER“. E-Rechnungen im ZUGFeRD-Format übernehmen Sie unter „E-Rechnung erhalten“.": "No data can be read from a PDF, not even from the printout of “Mein ELSTER”. You import e-invoices in ZUGFeRD format under “Received e-invoice”.",
  "Kontoauszug erkannt": "Bank statement detected",
  "Kontoauszüge lesen Sie unter „Kontoauszug“ ein; dort werden Zahlungen offenen Rechnungen zugeordnet.": "You import bank statements under “Bank statement”; there payments are matched to open invoices.",
  "Das Format dieser Datei kennt Kontovia nicht.": "Kontovia does not know the format of this file.",
  "Datei nicht übernommen": "File not imported",
  "Was steht in der Tabelle?": "What is in the table?",
  "An den Überschriften von „{0}“ ist das nicht sicher zu erkennen.": "This cannot be reliably recognized from the headings of “{0}”.",
  "Buchungen (Einnahmen und Ausgaben)": "Transactions (income and expenses)",
  "Umsätze eines Bankkontos": "Transactions of a bank account",
  "Ausgewählt": "Selected",
  "Schon übernommen": "Already imported",
  "Mögliche Dubletten": "Possible duplicates",
  "Nicht übernehmbar": "Cannot be imported",
  ", {0} Zeilen": ", {0} rows",
  "Andere Datei": "Different file",
  "Nichts ist übernommen. Ausgewählt ist, was sich eindeutig übernehmen lässt. Zeilen, die schon einmal übernommen wurden, bleiben aus.": "Nothing has been imported. Selected is what can be imported unambiguously. Rows that were already imported are left out.",
  "Alle übernehmbaren auswählen": "Select all importable",
  "Auswahl aufheben": "Clear selection",
  "DATEV-Buchungsstapel": "DATEV booking batch",
  ", Berater {0}, Mandant": ", advisor {0}, client",
  "vom {0} bis": "from {0} to",
  "Zahlungskonto, wenn die Datei keines nennt": "Payment account if the file does not name one",
  "Zahlungskonto": "Payment account",
  "Kontakt wird": "contact will be",
  "Kontakte werden": "contacts will be",
  "zur Datei": "to the file",
  "Hinweise": "Notes",
  "Mögliche Dubletten auch auswählen ({0})": "Also select possible duplicates ({0})",
  "Einnahmen {0} €, Ausgaben {1} €{2}.": "Income {0} €, expenses {1} €{2}.",
  "ausgewählt:": "selected:",
  ", {0} {1} zu vorhandenen Buchungen": ", {0} {1} for existing transactions",
  "Nichts ausgewählt.": "Nothing selected.",
  "übernehmen …": "import …",
  "Zeilen": "rows",
  "Text, Beleg oder Betrag suchen …": "Search text, receipt or amount …",
  "Zeile {0} übernehmen": "Import row {0}",
  "Konto {0} an": "Account {0} to",
  "schon übernommen": "already imported",
  "bleibt aus": "left out",
  "in der Rechnung": "in the invoice",
  "mögliche Dublette": "possible duplicate",
  "Keine Zeilen in dieser Ansicht": "No rows in this view",
  "Wählen Sie oben eine andere Anzeige.": "Choose a different view above.",
  "übernehmen?": "import?",
  "Jede Buchung nennt „{0}“ als Herkunft, auch im Änderungsjournal.{1} Übernommene Buchungen lassen sich wie jede andere ändern oder stornieren.": "Each transaction names “{0}” as its origin, also in the change log.{1} Imported transactions can be changed or reversed like any other.",
  "ohne Kategorie und {0} erst in der Steuerübersicht, wenn Sie eine Kategorie ergänzen.": "without a category and {0} only in the tax overview once you add a category.",
  "Buchung kommt": "transaction comes",
  "Buchungen kommen": "transactions come",
  "zählt": "counts",
  "zählen": "count",
  "Jetzt übernehmen": "Import now",
  "Beim Übernehmen ist ein Fehler aufgetreten": "An error occurred during import",
  "Wird übernommen": "Importing",
  "von {0} …": "of {0} …",
  "Nichts gefunden": "Nothing found",
  "Die Datei enthält keine lesbaren Kontakte.": "The file contains no readable contacts.",
  "Die Datei enthält keine lesbaren Produkte.": "The file contains no readable products.",
  "Kunde & Lieferant": "Customer & supplier",
  "Nichts ist übernommen. Was es in Kontovia schon gibt (gleicher Name{0}), ist nicht ausgewählt.": "Nothing has been imported. Anything that already exists in Kontovia (same name{0}) is not selected.",
  "oder gleiche Artikelnummer": "or same article number",
  "Neue Kontakte sind": "New contacts are",
  "wie in der Datei": "as in the file",
  "ausgewählt.": "selected.",
  "übernehmen": "import",
  "Nicht übernommen": "Not imported",
  "E-Mail und Telefon": "Email and phone",
  "Preis netto": "Net price",
  "ELSTER-Datei,": "ELSTER file,",
  "Kontovia vergleicht die gemeldeten Werte mit den Buchungen desselben Zeitraums. Gespeichert wird die Meldung als Nachweis, was beim Finanzamt angegeben ist; Buchungen entstehen daraus nicht.": "Kontovia compares the reported values with the transactions of the same period. The return is saved as proof of what was declared to the tax office; no transactions are created from it.",
  "speichern, um sie später wieder zu vergleichen.": "save to compare them again later.",
  "Umsatzsteuer-Voranmeldungen": "VAT returns",
  "· ersetzt die früher eingelesene": "· replaces the one imported earlier",
  "Meldung": "return",
  "Meldungen": "returns",
  "Voranmeldungen gespeichert": "VAT returns saved",
  ", {0} ersetzt": ", {0} replaced",
  "übernommen{0}{1}.": "imported{0}{1}.",
  ", {0} {1} zu vorhandenen Buchungen eingetragen": ", {0} {1} entered for existing transactions",
  ", {0} {1} angelegt": ", {0} {1} created",
  "übernommen.": "imported.",
  "Aus „{0}“:": "From “{0}”:",
  "Weitere Datei übernehmen": "Import another file",
  "Fertig, mit Hinweisen": "Done, with notes",
  "nicht übernommen:": "not imported:",
  "Zeile wurde": "row was",
  "Zeilen wurden": "rows were",
  "Dieselbe Datei noch einmal einzulesen, übernimmt nichts doppelt.": "Importing the same file again does not import anything twice.",
  "Zu den Buchungen": "To transactions",
  "Zu den Kontakten": "To contacts",
  "Zu den Produkten": "To products",
  "Keine Positionen angegeben.": "No items given.",
  "· fällig am": "· due on",
  "Von (Verkäufer)": "From (seller)",
  "An (Käufer)": "To (buyer)",
  "Umsatzsteuer {0} auf": "VAT {0} on",
  "(Kategorie {0})": "(category {0})",
  "Zu zahlen": "Amount due",
  "Verwendungszweck:": "Payment reference:",
  "Käuferreferenz (Leitweg-ID):": "Buyer reference (routing ID):",
  "E-Rechnung": "E-invoice",
  "Lesbare Darstellung der strukturierten Rechnungsdaten ({0}). Aufbewahrt wird die Originaldatei, unverändert und mit Prüfsumme.": "Readable display of the structured invoice data ({0}). The original file is kept, unchanged and with a checksum.",
  "In die Buchung übernehmen": "Take over into transaction",
  "Zeitraum der Voranmeldung": "VAT return period",
  "Quartale": "Quarters",
  "Bitte wählen": "Please choose",
  "Export für": "Export for",
  "Buchungen · {0} Belege ·": "transactions · {0} receipts ·",
  "So steht es in der Anlage EÜR. Dort zählt die Umsatzsteuer als Einnahme und Ausgabe mit, deshalb weicht der Wert vom Gewinn der Übersicht ab.": "This is how it appears in the Anlage EÜR. There VAT counts as income and expense, so the value differs from the profit on the overview.",
  "Kontovia sendet nichts an das Finanzamt. Sie bekommen hier aufbereitete Werte zum Eintragen in „Mein ELSTER“ und Dateien für Ihre Steuerkanzlei. Die Werte entstehen nach festen Rechenregeln, nicht durch künstliche Intelligenz; die Verantwortung für die Erklärung bleibt bei Ihnen.": "Kontovia does not send anything to the tax office. Here you get prepared values for entering in “Mein ELSTER” and files for your tax firm. The values are created using fixed rules, not by artificial intelligence; responsibility for the return remains with you.",
  "Was das rechtlich bedeutet": "What this means legally",
  "Einzelne Berichte als PDF": "Individual reports as PDF",
  "Gewinn & Verlust": "Profit & loss",
  "Gewinn laut EÜR": "Profit according to EÜR",
  "Verlust laut EÜR": "Loss according to EÜR",
  "· Umsatzsteuer-Zahllast {0} €": "· VAT payable {0} €",
  "(Einnahmen {0} €, Ausgaben {1} €) sind in keinem dieser Exporte enthalten, weder in Zahlen noch im Journal, im DATEV-Stapel, im Prüfungsordner oder in den Belegen. Nur der Gesamtexport „Alles (JSON)“ enthält den vollständigen Bestand.": "(income {0} €, expenses {1} €) are not included in any of these exports, neither in figures nor in the journal, the DATEV batch, the audit folder or the receipts. Only the full export “Everything (JSON)” contains the complete data.",
  "private Buchungen": "private transactions",
  "Alles für das Finanzamt": "Everything for the tax office",
  "Alle Unterlagen für Ihre Steuererklärung in einem Ordner, mit einer Anleitung zum Übertragen nach ELSTER.": "All documents for your tax return in one folder, with instructions for transferring them to ELSTER.",
  "Enthalten sind die Zeilen der Anlage EÜR{0}, das Buchungsjournal, die offenen Posten, das Anlagenverzeichnis und ein DATEV-Stapel für die Kanzlei, dazu die vollständigen Berichte als PDF.": "Included are the lines of the Anlage EÜR{0}, the transaction journal, the open items, the asset register and a DATEV batch for your tax firm, plus the complete reports as PDF.",
  ", die Kennzahlen der Umsatzsteuer": ", the VAT boxes",
  "Paket erstellen": "Create package",
  "Nur Tabellen (CSV)": "Tables only (CSV)",
  "Alle Berichte in einer PDF": "All reports in one PDF",
  "ein Dokument": "one document",
  "Alle Berichte hintereinander in einer Datei, zum Ablegen oder Ausdrucken.": "All reports one after another in one file, for filing or printing.",
  "Gewinn- und Verlustrechnung, Anlage EÜR{0}, Vermögensübersicht, offene Posten und das komplette Buchungsjournal, mit Seitenzahlen und Ihren Firmendaten im Kopf.": "Profit and loss statement, Anlage EÜR{0}, statement of assets, open items and the complete transaction journal, with page numbers and your company details in the header.",
  ", Umsatzsteuer-Voranmeldung": ", VAT return",
  "PDF erstellen": "Create PDF",
  "Vorschau": "Preview",
  "Für Ihre Steuerkanzlei": "For your tax firm",
  "Ihre Buchungen als Datei, die Kanzleiprogramme wie DATEV direkt einlesen.": "Your transactions as a file that accounting firm programs such as DATEV read directly.",
  "Buchungsstapel im DATEV-Format (EXTF 700), je Wirtschaftsjahr eine Datei. Verwendet die Sachkonten des {0} aus Ihren Kategorien und bucht {1}. Steuerschlüssel für Konten ohne Automatik lassen sich auf Wunsch mitgeben.": "Booking batch in DATEV format (EXTF 700), one file per financial year. Uses the ledger accounts of {0} from your categories and books {1}. Tax keys for accounts without automation can optionally be included.",
  "Rechnungen über Sammeldebitor und -kreditor, Zahlungen aufs Geldkonto": "invoices via a collective debtor and creditor, payments to the money account",
  "nach Zahlungsdatum gegen das Geldkonto": "by payment date against the money account",
  "Buchungsstapel": "Booking batch",
  "Wenn das Finanzamt prüft": "When the tax office audits",
  "Betriebsprüfung": "Tax audit",
  "Alle Daten so, wie eine Prüferin oder ein Prüfer sie verlangt, samt Nachweis, dass nichts nachträglich verändert wurde.": "All data as an auditor requires it, including proof that nothing was changed afterwards.",
  "Datenträgerüberlassung nach GoBD (Z3): alle Daten in maschinell auswertbarer Form mit beschreibender {0} nach dem GDPdU-Beschreibungsstandard. Enthält auch das verkettete Änderungsjournal.": "Data transfer according to GoBD (Z3): all data in machine-readable form with a descriptive {0} according to the GDPdU description standard. Also contains the chained change log.",
  "Prüfungsordner": "Audit folder",
  "Belege ausleiten": "Export receipts",
  "Dateien im Zeitraum": "files in the period",
  "Alle Rechnungen und Quittungen des Zeitraums als einzelne Dateien. {0} Sie liegen danach unverschlüsselt im Zielordner.": "All invoices and receipts of the period as individual files. {0} They are then unencrypted in the target folder.",
  "Achtung:": "Caution:",
  "Die Dateien sind nach Datum, Belegnummer und Beschreibung benannt. Ein Verzeichnis mit Prüfsummen belegt, dass sie unverändert sind.": "The files are named by date, receipt number and description. A list with checksums proves that they are unchanged.",
  "Belege exportieren": "Export receipts",
  "Rohdaten": "Raw data",
  "CSV und JSON": "CSV and JSON",
  "Buchungen und Kontakte als Tabellen zum Weiterverarbeiten, etwa in Excel oder LibreOffice. Private Buchungen fehlen darin.": "Transactions and contacts as tables for further processing, for example in Excel or LibreOffice. Private transactions are missing from them.",
  "„Alles (JSON)“ enthält dagegen den kompletten Bestand samt privater Buchungen, etwa für den Umzug in ein anderes Programm.": "“Everything (JSON)”, on the other hand, contains the complete data including private transactions, for example for moving to another program.",
  "Buchungen (CSV)": "Transactions (CSV)",
  "Kontakte (CSV)": "Contacts (CSV)",
  "Alles (JSON)": "Everything (JSON)",
  "Voranmeldung für „Mein ELSTER“": "VAT return for “Mein ELSTER”",
  "zum Hochladen": "for uploading",
  "Die Umsatzsteuer-Voranmeldung als Datei, die „Mein ELSTER“ direkt einliest.": "The VAT return as a file that “Mein ELSTER” reads directly.",
  "In „Mein ELSTER“: Formular „Umsatzsteuer-Voranmeldung“ öffnen, Jahr wählen, Reiter „XML-Import“, Datei hochladen, prüfen, absenden. Bemessungsgrundlagen stehen darin wie verlangt in vollen Euro.": "In “Mein ELSTER”: open the form “Umsatzsteuer-Voranmeldung”, choose the year, tab “XML-Import”, upload the file, check, send. Tax bases are in whole euros as required.",
  "ELSTER-Datei erstellen": "Create ELSTER file",
  "Excel und weitere Formate": "Excel and other formats",
  "zum Weitergeben": "for sharing",
  "Eine Excel-Mappe mit den wichtigsten Tabellen, dazu Ihre Kontakte als Visitenkarten und die Produkte als Tabelle.": "An Excel workbook with the most important tables, plus your contacts as business cards and the products as a table.",
  "Die Mappe enthält Buchungen, Anlage EÜR{0}, offene Posten und Kontakte, mit echten Datums- und Eurozellen. Die Visitenkarten (vCard) lesen Outlook, Google und das Telefon.": "The workbook contains transactions, Anlage EÜR{0}, open items and contacts, with real date and euro cells. The business cards (vCard) can be read by Outlook, Google and your phone.",
  ", Umsatzsteuer": ", VAT",
  "Wer an Unternehmen im EU-Ausland liefert oder leistet, bekommt die Zusammenfassende Meldung als Datei für das Online-Portal des Bundeszentralamts für Steuern.": "If you supply goods or services to businesses in other EU countries, you get the EC sales list as a file for the online portal of the Federal Central Tax Office.",
  "Excel-Mappe": "Excel workbook",
  "Kontakte (vCard)": "Contacts (vCard)",
  "Produkte (CSV)": "Products (CSV)",
  "Buchungen ohne Kategorie": "Transactions without a category",
  "Im Zeitraum {0} ohne Kategorie. Ohne Kategorie ist nicht klar, ob und wie viel Umsatzsteuer anfällt und in welche Zeile der EÜR {1}. Ordnen Sie {2} am besten erst zu.": "In the period {0} without a category. Without a category it is unclear whether and how much VAT is due and in which EÜR line {1}. Best assign {2} first.",
  "sie gehört": "it belongs",
  "sie gehören": "they belong",
  "Trotzdem erstellen": "Create anyway",
  "Erst zuordnen": "Assign first",
  "Zeitraum festschreiben?": "Lock the period?",
  "Ist die Voranmeldung abgegeben, gehört der Zeitraum bis {0} festgeschrieben. Danach lassen sich die Buchungen nur noch stornieren, offene Rechnungen weiter als bezahlt vermerken. Das lässt sich nicht zurücknehmen.": "Once the VAT return has been filed, the period up to {0} should be locked. After that the transactions can only be reversed, and open invoices can still be marked as paid. This cannot be undone.",
  "Festschreiben": "Lock",
  "Festgeschrieben bis {0} (nach der Voranmeldung)": "Locked until {0} (after the VAT return)",
  "Zeitraum festgeschrieben": "Period locked",
  "Arbeite …": "Working …",
  "Zielordner für die Finanzamt-Unterlagen": "Target folder for the tax office documents",
  "Unterlagen gespeichert": "Documents saved",
  "Dateien in": "files in",
  "Unterlagen erstellt": "Documents created",
  "PDF erstellt": "PDF created",
  "Buchungsstapel gespeichert": "Booking batch saved",
  "Zielordner für die DATEV-Stapel": "Target folder for the DATEV batches",
  "je Wirtschaftsjahr eine Datei in": "one file per financial year in",
  "Zielordner für die Datenträgerüberlassung": "Target folder for the data transfer",
  "Prüfungsordner erstellt": "Audit folder created",
  "Belege unverschlüsselt ausleiten?": "Export receipts unencrypted?",
  "Die Dateien werden im Zielordner im Klartext abgelegt. Wählen Sie einen Ort, der ausreichend geschützt ist. Ein ungesicherter Cloud-Ordner oder ein USB-Stick, der herumliegt, ist dafür nicht geeignet.": "The files are stored in plain text in the target folder. Choose a location that is sufficiently protected. An unsecured cloud folder or a USB stick lying around is not suitable for this.",
  "Verstanden, exportieren": "Understood, export",
  "Keine Belege im Zeitraum": "No receipts in the period",
  "Beleg-Nr": "Receipt no.",
  "Zielordner für die Belege": "Target folder for the receipts",
  "Belege exportiert": "Receipts exported",
  "Buchungen_{0}_{1}.csv": "Buchungen_{0}_{1}.csv",
  "CSV-Tabelle": "CSV table",
  "Tabelle gespeichert": "Table saved",
  "Unverschlüsselten Gesamtexport erstellen?": "Create unencrypted full export?",
  "Die JSON-Datei enthält Ihre komplette Buchhaltung im Klartext, ohne Belege, aber mit allen Beträgen, Kontakten und Notizen. Für eine Sicherung nehmen Sie besser die verschlüsselte Vollsicherung unter Einstellungen.": "The JSON file contains your complete accounting in plain text, without receipts, but with all amounts, contacts and notes. For a backup, better use the encrypted full backup under Settings.",
  "Trotzdem exportieren": "Export anyway",
  "Export gespeichert": "Export saved",
  "ELSTER-Datei": "ELSTER file",
  "ELSTER-Datei gespeichert": "ELSTER file saved",
  ". In „Mein ELSTER“: Umsatzsteuer-Voranmeldung, Reiter „XML-Import“.": ". In “Mein ELSTER”: Umsatzsteuer-Voranmeldung, tab “XML-Import”.",
  "Kontovia_{0}_{1}.xlsx": "Kontovia_{0}_{1}.xlsx",
  "Excel-Mappe gespeichert": "Excel workbook saved",
  "Noch keine Kontakte": "No contacts yet",
  "Visitenkarten": "Business cards",
  "Kontakte gespeichert": "Contacts saved",
  "Noch keine Produkte": "No products yet",
  "Angaben fehlen": "Details missing",
  "in die Zusammenfassende Meldung, aber beim Kontakt fehlt eine ausländische USt-IdNr. ({0}{1}). Ergänzen Sie die Nummer unter Stammdaten. Ohne sie fehlen diese Beträge in der Datei.": "in the EC sales list, but the contact is missing a foreign VAT ID ({0}{1}). Add the number under Master data. Without it these amounts are missing from the file.",
  "Buchung gehört": "transaction belongs",
  "Buchungen gehören": "transactions belong",
  "Nichts zu melden": "Nothing to report",
  "Im Zeitraum gibt es keine Lieferungen oder Leistungen an Unternehmen im EU-Ausland.": "There are no supplies or services to businesses in other EU countries in the period.",
  "ZM_{0}_{1}.csv": "ZM_{0}_{1}.csv",
  "Zusammenfassende Meldung gespeichert": "EC sales list saved",
  ". Im Online-Portal des Bundeszentralamts für Steuern beim Formular über „Import“ einlesen.": ". Import it via “Import” on the form in the online portal of the Federal Central Tax Office.",
  "PDF gespeichert": "PDF saved",
  "Steuernummer für ELSTER": "Tax number for ELSTER",
  "ELSTER erwartet die Steuernummer in einer einheitlichen Schreibweise mit 13 Ziffern. Kontovia rechnet sie aus der Nummer auf Ihrem Steuerbescheid um; dafür braucht es das Bundesland Ihres Finanzamts.": "ELSTER expects the tax number in a uniform 13-digit format. Kontovia converts it from the number on your tax assessment; for this it needs the federal state of your tax office.",
  "z. B. 12/345/67890": "e.g. 12/345/67890",
  "Bundesland des Finanzamts": "Federal state of the tax office",
  "Datei erstellen": "Create file",
  "Für ELSTER:": "For ELSTER:",
  "Steuernummer und Bundesland passen noch nicht zusammen.": "Tax number and federal state do not match yet.",
  "small mb0": "small mb0",
  "Angaben für DATEV": "Details for DATEV",
  "Ihre Steuerkanzlei nennt Ihnen Berater- und Mandantennummer. Ohne die richtigen Nummern weist DATEV den Stapel ab oder ordnet ihn keinem Mandat zu.": "Your tax firm gives you the advisor and client numbers. Without the correct numbers DATEV rejects the batch or does not assign it to any client.",
  "Beraternummer": "Advisor number",
  "1001 bis 9999999": "1001 to 9999999",
  "Mandantennummer": "Client number",
  "1 bis 99999": "1 to 99999",
  "Angaben für das nächste Mal merken": "Remember details for next time",
  "Steuerschlüssel mitgeben (9/8 Vorsteuer, 3/2 Umsatzsteuer). Das ist nur für Konten ohne Automatik gedacht; vorher mit der Kanzlei abstimmen": "Include tax keys (9/8 input VAT, 3/2 VAT). This is only intended for accounts without automation; agree with your tax firm first",
  "Ohne Nummern weiter": "Continue without numbers",
  "Stapel erzeugen": "Create batch",
  "Beraternummer 1001 bis 9999999, Mandantennummer 1 bis 99999, nur Ziffern.": "Advisor number 1001 to 9999999, client number 1 to 99999, digits only.",
  "Kurzanleitung": "Quick guide",
  "Cloud und Geräte": "Cloud and devices",
  "Dazu steht hier nichts. Versuchen Sie ein anderes Wort oder den anderen Reiter.": "Nothing here about that. Try another word or the other tab.",
  "In der Hilfe suchen …": "Search the help …",
  "In der Hilfe suchen": "Search the help",
  "p, li": "p, li",
  "In fünf Minuten startklar": "Ready in five minutes",
  "Unter {0} tragen Sie Ihr Geschäftskonto mit dem Anfangsbestand ein. Das ist der Kontostand an dem Tag, ab dem Sie mit Kontovia buchen. Sonst stimmen die Kontostände nicht.": "Under {0} you enter your business account with the opening balance. This is the account balance on the day from which you book with Kontovia. Otherwise the account balances will not be correct.",
  "Konto anlegen.": "Create an account.",
  "Stammdaten → Zahlungskonten": "Master data → Payment accounts",
  "+{0} öffnet den Dialog. Beschreibung, Datum, Kategorie, Betrag, fertig. Den Beleg ziehen Sie einfach mit der Maus ins Fenster.": "+{0} opens the dialog. Description, date, category, amount, done. Simply drag the receipt into the window with the mouse.",
  "Erste Ausgabe erfassen.": "Record the first expense.",
  "Unter {0} schreiben Sie E-Rechnungen mit Ihrem Logo. Beim Ausstellen entsteht die offene Einnahme von selbst; sie taucht in der Übersicht und im Kalender auf, bis sie bezahlt ist.": "Under {0} you write e-invoices with your logo. When issuing, the open income is created by itself; it appears on the overview and in the calendar until it is paid.",
  "Rechnungen stellen.": "Write invoices.",
  "Unter {0} sehen Sie Gewinn, Umsatzsteuer und Vermögen für jeden beliebigen Zeitraum, und im Jahresvergleich, wie sich Ausgaben oder Einnahmen von Jahr zu Jahr entwickeln. Listen und Berichte drucken Sie oder sichern sie als PDF.": "Under {0} you see profit, VAT and assets for any period, and in the year comparison how expenses or income develop from year to year. You print lists and reports or save them as PDF.",
  "Auswerten.": "Evaluate.",
  "Unter {0} erzeugen Sie einen Ordner mit allen Zahlen für ELSTER und für Ihre Steuerkanzlei.": "Under {0} you create a folder with all figures for ELSTER and for your tax firm.",
  "Abgeben.": "File.",
  "Zwei Einstellungen, auf die es ankommt": "Two settings that matter",
  "In der Einnahmen-Überschuss-Rechnung zählt eine Buchung erst, wenn das Geld geflossen ist (§ 11 EStG). Eine im Dezember gestellte und im Januar bezahlte Rechnung gehört also ins neue Jahr. Das gilt für die Anlage EÜR immer. Übersicht, Buchungsliste und Gewinn & Verlust richten sich ebenfalls danach: Eine im Zeitraum bezahlte Rechnung steht dort auch dann, wenn ihr Datum außerhalb liegt. Bei der Umsatzsteuer haben Sie die Wahl. Nach dem Gesetz entsteht sie mit der Leistung, also zum Rechnungsdatum (Soll-Versteuerung). Auf Antrag nach § 20 UStG entsteht sie erst mit dem Zahlungseingang (Ist-Versteuerung). Was für Sie gilt, steht im Fragebogen zur steuerlichen Erfassung oder im Bescheid. Bei Ihnen ist eingestellt: {0}.": "In the cash-basis income statement, a transaction only counts once the money has flowed (§ 11 EStG). An invoice issued in December and paid in January therefore belongs to the new year. This always applies to the Anlage EÜR. Overview, transaction list and profit & loss also follow this: an invoice paid in the period appears there even if its date is outside it. For VAT you have a choice. By law it arises with the service, i.e. on the invoice date (accrual basis). On application under § 20 UStG it only arises when payment is received (cash basis). What applies to you is stated in the tax registration questionnaire or in your assessment. Your setting: {0}.",
  "Zahlungsfluss oder Rechnungsdatum.": "Cash flow or invoice date.",
  "Als Kleinunternehmer nach § 19 UStG rechnen Sie durchgehend brutto, weisen keine Umsatzsteuer aus und ziehen keine Vorsteuer. Bei Ihnen ist eingestellt: {0}.": "As a small business under § 19 UStG you work with gross amounts throughout, show no VAT and deduct no input VAT. Your setting: {0}.",
  "Regelbesteuerung oder Kleinunternehmer.": "Standard taxation or small business.",
  "Ändern Sie eine der beiden Einstellungen, fragt Kontovia, ab wann der Wechsel gilt. Frühere Zeiträume bleiben, wie sie waren: Wer etwa ab Januar nicht mehr Kleinunternehmer ist, sieht das alte Jahr weiter als Kleinunternehmer. Die Vorsteuer zählt übrigens immer mit dem Datum der Rechnung, auch bei Ist-Versteuerung.": "If you change one of the two settings, Kontovia asks from when the change applies. Earlier periods stay as they were: if you are no longer a small business from January, for example, you still see the old year as a small business. By the way, input VAT always counts with the invoice date, even with cash basis.",
  "Wechsel.": "Change.",
  "Regelmäßige Zahlungen wie Miete, Leasing oder die Umsatzsteuer-Vorauszahlung, die bis zehn Tage vor oder nach dem Jahreswechsel fällig sind und gezahlt werden, zählen in der Anlage EÜR im Jahr, zu dem sie gehören (§ 11 EStG). Kontovia erkennt sie an der wiederkehrenden Buchung, an der Kategorie „An Finanzamt gezahlte Umsatzsteuer“ und an Kategorien, die Sie unter Stammdaten als „regelmäßig wiederkehrend“ kennzeichnen.": "Regular payments such as rent, leasing or the VAT advance payment that are due and paid within ten days before or after the turn of the year count in the Anlage EÜR in the year they belong to (§ 11 EStG). Kontovia recognizes them by the recurring transaction, by the category “VAT paid to the tax office” and by categories you mark as “regularly recurring” under Master data.",
  "Zahlungen um den Jahreswechsel.": "Payments around the turn of the year.",
  "Keine Betriebsausgabe ohne Beleg. Kontovia speichert jede Rechnung verschlüsselt im Tresor und merkt sich eine Prüfsumme, mit der sich später nachweisen lässt, dass die Datei unverändert ist. Auf der Übersicht sehen Sie Ihre Belegquote.": "No business expense without a receipt. Kontovia stores every invoice encrypted in the vault and remembers a checksum that can later prove the file is unchanged. On the overview you see your receipt ratio.",
  "Bei Bewirtungskosten gehören der betriebliche Anlass und die Teilnehmerliste dazu. Schreiben Sie beides ins Notizfeld. Kontovia zieht davon automatisch nur 70 % ab.": "For entertainment expenses, the business occasion and the list of participants are required. Write both in the notes field. Kontovia automatically only deducts 70% of it.",
  "Anschaffungen über 800 €": "Purchases over €800",
  "Eine Maschine für 5.000 € ist im Jahr des Kaufs nicht in voller Höhe abziehbar, sondern wird über die Nutzungsdauer verteilt. Beim Erfassen der Ausgabe wählen Sie „Als Anlagegut abschreiben“. Kontovia rechnet die Abschreibung monatsgenau aus, führt das Anlagenverzeichnis und trägt den Betrag in Zeile {0} der Anlage EÜR ein (Software und Lizenzen in Zeile {1}).": "A machine for €5,000 cannot be deducted in full in the year of purchase but is spread over its useful life. When recording the expense, choose “Depreciate as fixed asset”. Kontovia calculates depreciation by month, keeps the asset register and enters the amount in line {0} of the Anlage EÜR (software and licenses in line {1}).",
  "dürfen mit einem Jahr Nutzungsdauer voll im Jahr der Anschaffung abgezogen werden (BMF-Schreiben vom 22.02.2022). Wählen Sie dafür die Abschreibung „1 Jahr“.": "may be deducted in full in the year of purchase with a useful life of one year (BMF letter of 22.02.2022). Choose the depreciation “1 year” for this.",
  "Computer, Notebooks, Tablets, Drucker und Software": "Computers, notebooks, tablets, printers and software",
  "geht für bewegliche Wirtschaftsgüter, die vom 01.07.2025 bis 31.12.2027 angeschafft werden: höchstens das Dreifache der linearen Rate und höchstens 30 % vom Restwert (§ 7 Abs. 2 EStG). Für frühere Anschaffungen kennt Kontovia auch die älteren Fenster (2020 bis 2022 und April bis Dezember 2024). Kontovia wechselt von selbst zur linearen Rate, sobald sie höher ist.": "is possible for movable assets acquired from 01.07.2025 to 31.12.2027: at most three times the straight-line rate and at most 30% of the residual value (§ 7 (2) EStG). For earlier purchases Kontovia also knows the older windows (2020 to 2022 and April to December 2024). Kontovia switches to the straight-line rate by itself as soon as it is higher.",
  "Degressiv": "Declining balance",
  "Scheidet ein Gut aus, tragen Sie das unter Stammdaten beim Anlagegut ein. Abgeschrieben wird bis zu diesem Monat, der Rest steht als Restbuchwert in der Anlage EÜR. Den Erlös buchen Sie als Einnahme in „Verkauf von Anlagevermögen“.": "If an asset is disposed of, enter this under Master data at the asset. Depreciation runs up to this month, the rest appears as the residual book value in the Anlage EÜR. Book the proceeds as income in “Sale of fixed assets”.",
};
