/** Wörterbuch Englisch, Teil t13. Quellen: views/jahresvergleich.js, views/kontoimport.js, views/mahneinstellungen.js, views/mahnwesen.js, views/master.js. */

export default {
  "1.1. bis": "1 Jan to",
  "ganze Jahre": "whole years",
  "Veränderung {0} zum Jahr davor": "Change {0} vs. the year before",
  "Veränderung in Prozent": "Change in percent",
  "Verlauf über das Jahr": "Trend over the year",
  "Kategorie für den Verlauf": "Category for the trend",
  "je Monat,": "per month,",
  "Was verglichen wird": "What is compared",
  "Bis": "Until",
  "Ganze Jahre": "Whole years",
  "Zeitraum der Jahre": "Period of the years",
  "Wählen Sie mindestens zwei Jahre, um sie zu vergleichen.": "Choose at least two years to compare them.",
  "Das laufende Jahr ist noch nicht zu Ende. Deshalb zählt jedes Jahr nur bis zum {0}, damit die Zahlen vergleichbar bleiben.": "The current year has not ended yet. Therefore each year only counts up to {0}, so that the figures stay comparable.",
  "Je Monat": "Per month",
  "Regeln und Vorlagen": "Rules and templates",
  "Spalten": "Columns",
  "Schritte": "Steps",
  "Import verlassen?": "Leave import?",
  "ausgewählt, gebucht ist noch nichts. Wenn Sie die Ansicht verlassen, gehen Auswahl und eingelesene Datei verloren.": "selected, nothing is booked yet. If you leave the view, the selection and the imported file are lost.",
  "Eine Zeile ist": "One row is",
  "Zeilen sind": "rows are",
  "Hierbleiben": "Stay here",
  "Auf dieses Konto werden die Umsätze gebucht. Kontovia wählt es selbst, wenn die IBAN in der Datei zu einem Konto passt.": "The transactions are booked to this account. Kontovia selects it itself if the IBAN in the file matches an account.",
  "Kontoauszug hierher ziehen oder auswählen": "Drag a bank statement here or choose one",
  "CSV (Sparkasse, Volksbank, ING, DKB und andere), CAMT.053 (XML) und MT940": "CSV (Sparkasse, Volksbank, ING, DKB and others), CAMT.053 (XML) and MT940",
  "Die Datei wird nur auf diesem Gerät gelesen. Sie wird nicht hochgeladen und nirgends gespeichert. Gebucht wird erst, wenn Sie es bestätigen.": "The file is only read on this device. It is not uploaded or stored anywhere. Nothing is booked until you confirm.",
  "Frühere Importe": "Earlier imports",
  "Importe": "Imports",
  "Wann": "When",
  "Gebucht": "Booked",
  "neu, {0} zugeordnet": "new, {0} matched",
  "Die Datei wird gelesen …": "Reading the file …",
  "In der Datei stehen keine Umsätze.": "The file contains no transactions.",
  "Die Datei lässt sich nicht lesen": "The file cannot be read",
  "Unbekanntes Format.": "Unknown format.",
  "Nicht lesbar": "Not readable",
  "Semikolon": "Semicolon",
  "Komma": "Comma",
  "Tabulator": "Tab",
  "Senkrechter Strich": "Vertical bar",
  "Trennzeichen": "Separator",
  "Dezimalzeichen bei Beträgen": "Decimal separator for amounts",
  "Zeile mit den Überschriften": "Row with the headings",
  "Zeilen davor, etwa Angaben der Bank, werden übersprungen.": "Rows before it, such as bank details, are skipped.",
  "Überschrift in der Datei": "Heading in the file",
  "Bedeutung": "Meaning",
  "Beispiele": "Examples",
  "Diese Zuordnung für künftige Dateien dieser Bank merken": "Remember this assignment for future files from this bank",
  "Name der Vorlage": "Template name",
  "Weiter zum Prüfen": "Continue to review",
  "Die gemerkte Zuordnung „{0}“ wurde angewendet.": "The remembered assignment “{0}” was applied.",
  "erkannt, vom {0} bis {1}: Eingänge {2} €, Ausgänge {3} €.": "detected, from {0} to {1}: incoming {2} €, outgoing {3} €.",
  "Umsätze": "transactions",
  "Bitte ordnen Sie unten mindestens Buchungstag und Betrag zu.": "Please assign at least booking date and amount below.",
  "Noch keine Umsätze erkannt.": "No transactions detected yet.",
  "übersprungen.": "skipped.",
  "Es fehlt noch: {0}.": "Still missing: {0}.",
  "Komma (1.234,56)": "Comma (1.234,56)",
  "Punkt (1,234.56)": "Point (1,234.56)",
  "Bedeutung der Spalte": "Meaning of the column",
  "Nicht verwenden": "Do not use",
  "Spalte": "Column",
  "Keine Überschriften gefunden. Geben Sie oben die Zeile der Überschriften an.": "No headings found. Enter the row of the headings above.",
  "So sehen die ersten Umsätze aus": "This is what the first transactions look like",
  "Übersprungene Zeilen ({0})": "Skipped rows ({0})",
  "Zeile {0}:": "Row {0}:",
  "Das hat nicht geklappt": "That did not work",
  "Umsätze werden geprüft: {0} von {1} …": "Checking transactions: {0} of {1} …",
  "Umsätze werden zugeordnet …": "Matching transactions …",
  "Zu prüfen": "To review",
  "Eigene Regel": "Own rule",
  "Kategorie-Vorschlag": "Category suggestion",
  "Ohne Zuordnung": "Unmatched",
  "Mögliche Dublette": "Possible duplicate",
  "Schon importiert": "Already imported",
  ", dazu Mahnkosten {0} €": ", plus reminder costs {0} €",
  "Offene Ausgabe:": "Open expense:",
  "Neue {0}, ohne Kategorie": "New {0}, no category",
  "Neue {0}, Kategorie": "New {0}, category",
  "Bitte zuordnen, eine Kategorie wählen oder ohne Kategorie buchen": "Please match, choose a category or book without a category",
  "Die Umsätze werden geprüft …": "Checking the transactions …",
  ", {0} Umsätze vom {1} bis {2}, Konto": ", {0} transactions from {1} to {2}, account",
  "Nichts ist gebucht. Ausgewählt sind nur sichere Treffer und Ihre eigenen Regeln. Kategorie-Vorschläge entstehen auf diesem Gerät aus Ihren früheren Buchungen und bekannten Händlernamen, nichts davon wird übertragen. Prüfen Sie den Rest und haken Sie an, was gebucht werden soll. Wer es eilig hat, bucht den Rest auch ohne Kategorie und ordnet später zu.": "Nothing is booked. Only certain matches and your own rules are selected. Category suggestions are created on this device from your earlier transactions and known merchant names; none of this is transmitted. Check the rest and tick what should be booked. If you are in a hurry, book the rest without a category and assign it later.",
  "Alle sicheren auswählen": "Select all certain",
  "Vorschläge auswählen ({0})": "Select suggestions ({0})",
  "Bucht diese Umsätze ohne Kategorie. Die Kategorie lässt sich später in der Buchungsliste ergänzen.": "Books these transactions without a category. The category can be added later in the transaction list.",
  "Rest ohne Kategorie auswählen ({0})": "Select rest without category ({0})",
  "Von Ihnen gewählt: ohne Kategorie": "Chosen by you: no category",
  "zu offenen Posten, {0} neue {1}. Eingänge {2} €, Ausgänge {3} €.": "to open items, {0} new {1}. Incoming {2} €, outgoing {3} €.",
  "buchen …": "book …",
  "Name, Verwendungszweck oder Betrag suchen …": "Search name, reference or amount …",
  "Umsatz vom {0} buchen": "Book transaction of {0}",
  "Gegenseite und Verwendungszweck": "Counterparty and reference",
  "Zuordnung": "Matching",
  "Mögliche Dublette:": "Possible duplicate:",
  "Ändern": "Change",
  "Keine Umsätze in dieser Ansicht": "No transactions in this view",
  "Umsatz zuordnen": "Match transaction",
  "Als neue Buchung": "As new transaction",
  "Nicht buchen": "Do not book",
  "Ohne Kategorie buchen (später zuordnen)": "Book without category (assign later)",
  "Ohne Kategorie zählt die Buchung in der Steuerübersicht (EÜR) noch nicht mit und wird ohne Umsatzsteuer gebucht. Die Kategorie lässt sich in der Buchungsliste jederzeit ergänzen.": "Without a category the transaction does not count in the tax overview (EÜR) yet and is booked without VAT. The category can be added in the transaction list at any time.",
  "Für ähnliche Umsätze künftig so vorschlagen (Regel merken)": "Suggest this for similar transactions in future (remember rule)",
  "Wenn": "If",
  "die Gegenseite": "the counterparty",
  "der Verwendungszweck": "the reference",
  "irgendein Text": "any text",
  "enthält": "contains",
  "Mögliche Dublette: {0}. Haken Sie den Umsatz nur an, wenn es eine andere Zahlung ist.": "Possible duplicate: {0}. Only tick the transaction if it is a different payment.",
  "Trotzdem noch einmal buchen": "Book again anyway",
  "Zu einer offenen Rechnung": "To an open invoice",
  "Zu einer offenen Ausgabe": "To an open expense",
  "Offene Rechnung": "Open invoice",
  "Offene Ausgabe": "Open expense",
  "· {0} · offen {1} €": "· {0} · open {1} €",
  "+ Mahnkosten {0} €": "+ reminder costs {0} €",
  "Mahnkosten {0} € sind mit gezahlt": "Reminder costs {0} € are included in the payment",
  "Bitte wählen.": "Please choose.",
  "Das ist eine Teilzahlung: {0} € werden verbucht, der Rest bleibt offen.": "This is a partial payment: {0} € will be booked, the rest stays open.",
  "Den Rest als Skonto ausbuchen (der Kunde durfte weniger zahlen)": "Write off the rest as an early payment discount (the customer was allowed to pay less)",
  "Passt.": "Fits.",
  "Für eine Regel bitte eine Kategorie wählen": "Please choose a category for a rule",
  "Regel gemerkt": "Rule remembered",
  "Wenn „{0}“ vorkommt, schlägt Kontovia diese Kategorie vor.": "If “{0}” occurs, Kontovia suggests this category.",
  "Regel nicht gespeichert": "Rule not saved",
  "buchen?": "book?",
  "offenen Rechnungen und Ausgaben zugeordnet, {0} neue {1} angelegt, jeweils mit Hinweis auf die Datei „{2}“.{3} {4} Eine Buchung lässt sich danach nur noch stornieren.": "matched to open invoices and expenses, {0} new {1} created, each with a reference to the file “{2}”.{3} {4} A transaction can then only be reversed.",
  "Zahlung wird": "payment will be",
  "Zahlungen werden": "payments will be",
  "Buchung wird": "transaction will be",
  "Buchungen werden": "transactions will be",
  "davon {0} nicht sicher zugeordnet, Sie haben {1} selbst angehakt.": "of which {0} not matched with certainty, you ticked {1} yourself.",
  "keine Kategorie: {0} in der Steuerübersicht erst mit, wenn Sie eine Kategorie ergänzen.": "no category: {0} in the tax overview only once you add a category.",
  "Buchung bekommt": "transaction gets",
  "Buchungen bekommen": "transactions get",
  "Sie zählt": "It counts",
  "Sie zählen": "They count",
  "Jetzt buchen": "Book now",
  "Es wird gebucht": "Booking",
  "von {0} gebucht …": "of {0} booked …",
  "Beim Buchen ist ein Fehler aufgetreten": "An error occurred while booking",
  "Aus „{0}“ {1} bearbeitet: {2} {3} zu offenen Posten zugeordnet, {4} neue {5} angelegt{6}.": "From “{0}” {1} processed: {2} {3} matched to open items, {4} new {5} created{6}.",
  "Jede Buchung nennt die Datei als Herkunft, auch im Änderungsjournal. Dieselbe Datei noch einmal einzulesen, bucht nichts doppelt.": "Each transaction names the file as its origin, also in the change log. Importing the same file again books nothing twice.",
  "Weitere Datei einlesen": "Import another file",
  "wurde ein Umsatz": "one transaction was",
  "wurden {0} Umsätze": "{0} transactions were",
  ", davon {0} für Mahnkosten": ", of which {0} for reminder costs",
  "Umsatz wurde": "transaction was",
  "Umsätze wurden": "transactions were",
  "die IBAN": "the IBAN",
  "bei Eingängen": "for incoming payments",
  "bei Ausgängen": "for outgoing payments",
  "bei Ein- und Ausgängen": "for incoming and outgoing payments",
  "Regeln und Vorlagen für Kontoauszüge": "Rules and templates for bank statements",
  "Eine Regel schlägt für Umsätze, die zu keiner Rechnung passen, eine Kategorie vor: „Wenn der Verwendungszweck oder die Gegenseite … enthält, dann Kategorie …“. Es gilt die erste passende Regel von oben. Die Regeln liegen verschlüsselt in Ihrem Tresor.": "A rule suggests a category for transactions that do not match any invoice: “If the reference or counterparty contains …, then category …”. The first matching rule from the top applies. The rules are stored encrypted in your vault.",
  "Dann": "Then",
  "Neue Regel": "New rule",
  "Gemerkte Spaltenzuordnungen": "Remembered column assignments",
  "enthält „{0}“,": "contains “{0}”,",
  "Noch keine Regeln.": "No rules yet.",
  "Spalten zugeordnet": "columns assigned",
  "Noch keine gemerkt. Beim Einlesen einer CSV-Datei lässt sich die Zuordnung merken.": "None remembered yet. When importing a CSV file, the assignment can be remembered.",
  "Regel löschen?": "Delete rule?",
  "Schon gebuchte Umsätze bleiben, wie sie sind.": "Transactions already booked stay as they are.",
  "Regel bearbeiten": "Edit rule",
  "Gilt": "Applies",
  "Dann Kategorie": "Then category",
  "Kontakt (optional)": "Contact (optional)",
  "Beschreibung (optional)": "Description (optional)",
  "Regel ist eingeschaltet": "Rule is turned on",
  "Mahnwesen": "Dunning",
  "Fristen, Gebühren, Verzugsaufschlag": "Deadlines, fees, late payment surcharge",
  "Für Zahlungserinnerung, 1. Mahnung und 2. Mahnung stellen Sie hier die Zahlungsfrist und die Mahngebühr ein. Beim Erstellen jeder einzelnen Mahnung lässt sich beides noch ändern.": "Here you set the payment deadline and the reminder fee for the payment reminder, 1st reminder and 2nd reminder. Both can still be changed when creating each individual reminder.",
  "Zahlungsfrist in Tagen": "Payment deadline in days",
  "Mahngebühr in €": "Reminder fee in €",
  "Eine Gebühr von 0 € steht nicht auf dem Schreiben. Ohne fest vereinbarten Zahlungstermin bringt erst die Zahlungserinnerung den Kunden in Verzug; ihre Kosten lassen sich dann meist nicht verlangen.": "A fee of €0 does not appear on the letter. Without a firmly agreed payment date, only the payment reminder puts the customer in default; its costs can then usually not be claimed.",
  "Verzugsaufschlag für verspätete Zahlung": "Late payment surcharge",
  "Standardmäßig aus. Wenn Sie ihn einschalten, schlägt Kontovia ihn beim Erstellen einer Mahnung vor, Sie können ihn dort für das einzelne Schreiben aber abwählen. Auf dem Schreiben steht er als „Verzugsaufschlag“ mit Zeitraum, Satz und Betrag.": "Off by default. If you turn it on, Kontovia suggests it when creating a reminder, but you can deselect it there for the individual letter. On the letter it appears as “Late payment surcharge” with period, rate and amount.",
  "Auf den offenen Betrag, tageweise ab Beginn des Verzugs. Bei Geschäftskunden gilt gesetzlich üblich der Basiszinssatz plus 9 Prozentpunkte. Der Basiszinssatz ändert sich halbjährlich (Januar und Juli). Sie tragen den Satz selbst ein und halten ihn aktuell, Kontovia kennt ihn nicht.": "On the open amount, daily from the start of default. For business customers the statutory standard is the base rate plus 9 percentage points. The base rate changes every six months (January and July). You enter the rate yourself and keep it up to date; Kontovia does not know it.",
  "Feste Pauschale in €": "Fixed lump sum in €",
  "Vorgabe 40 €: die gesetzliche Verzugspauschale bei Geschäftskunden (§ 288 Abs. 5 BGB), nur gegenüber Unternehmen. Sie wird höchstens einmal je Rechnung berechnet, Mahngebühren werden auf sie angerechnet.": "Default €40: the statutory late payment lump sum for business customers (§ 288 (5) BGB), only for businesses. It is charged at most once per invoice; reminder fees are credited against it.",
  "Verzug beginnt": "Default begins",
  "Ein Zahlungsziel, das nur auf der Rechnung steht, bringt den Kunden noch nicht in Verzug. Das tut erst die Zahlungserinnerung, bei Geschäftskunden spätestens 30 Tage nach Fälligkeit, bei Privatkunden nur, wenn die Rechnung darauf hinweist (§ 286 BGB). Kontovia druckt diesen Hinweis auf Rechnungen an Privatkunden.": "A payment term that only appears on the invoice does not yet put the customer in default. Only the payment reminder does that, for business customers at the latest 30 days after the due date, for private customers only if the invoice points this out (§ 286 BGB). Kontovia prints this note on invoices to private customers.",
  "Vorschlagen ab": "Suggest from",
  "Ab diesem Schreiben ist der Verzugsaufschlag vorausgewählt.": "From this letter on, the late payment surcharge is preselected.",
  "Für Privatkunden gelten engere Grenzen; Kontovia fragt deshalb bei jeder Mahnung, ob der Kunde ein Unternehmen ist. Welche Beträge Sie verlangen, verantworten Sie selbst.": "Stricter limits apply to private customers; Kontovia therefore asks for each reminder whether the customer is a business. You are responsible for the amounts you claim.",
  "Bei Privatkunden (Verbrauchern) gilt der Basiszinssatz plus 5 Prozentpunkte, die Pauschale wird {0} berechnet, und eine Mahngebühr darf nur den tatsächlichen Aufwand abdecken. Verzug setzt außerdem voraus, dass die Zahlungsfrist abgelaufen ist und der Kunde gemahnt wurde oder 30 Tage vergangen sind (§ 286 BGB). Kontovia rechnet nach Ihren Angaben und ersetzt keine Rechtsberatung. Mahngebühr und Verzugsaufschlag sind kein Entgelt für eine Leistung: Sie werden ohne Umsatzsteuer gebucht, erst wenn das Geld eingegangen ist.": "For private customers (consumers) the base rate plus 5 percentage points applies, the lump sum is {0} charged, and a reminder fee may only cover the actual costs. Default also requires that the payment deadline has passed and the customer was reminded or 30 days have passed (§ 286 BGB). Kontovia calculates according to your details and does not replace legal advice. Reminder fees and late payment surcharges are not payment for a service: they are booked without VAT, only once the money has arrived.",
  "Mahnwesen speichern": "Save dunning settings",
  "Frist in Tagen,": "Deadline in days,",
  "Gebühr in Euro,": "Fee in euros,",
  "Zahlungsfrist prüfen": "Check payment deadline",
  ": bitte 1 bis 90 Tage eintragen.": ": please enter 1 to 90 days.",
  "Gebühr prüfen": "Check fee",
  ": Die Gebühr darf nicht negativ sein.": ": the fee must not be negative.",
  "Satz prüfen": "Check rate",
  "Bitte einen Satz zwischen 0 und 50 Prozent eintragen.": "Please enter a rate between 0 and 50 percent.",
  "Satz fehlt": "Rate missing",
  "Für „Prozent pro Jahr“ tragen Sie bitte einen Satz ein, etwa Basiszinssatz plus 9 Prozentpunkte.": "For “Percent per year” please enter a rate, such as the base rate plus 9 percentage points.",
  "Pauschale prüfen": "Check lump sum",
  "Die Pauschale darf nicht negativ sein.": "The lump sum must not be negative.",
  "Mahnwesen eingestellt": "Dunning set up",
  "Mahnwesen gespeichert": "Dunning settings saved",
  "Fristen, Gebühren und Verzugsaufschlag": "Deadlines, fees and late payment surcharge",
  "Alle Mahnungen": "All reminders",
  "ohne Rechnung aus Kontovia gebucht (zusammen {0} €). Mahnen lässt sich hier nur, was Sie in Kontovia geschrieben haben.": "booked without a Kontovia invoice (together {0} €). Only what you wrote in Kontovia can be reminded here.",
  "In den Buchungen ansehen": "View in transactions",
  "Eine überfällige Einnahme ist": "One overdue income is",
  "überfällige Einnahmen sind": "overdue incomes are",
  "Noch nicht gemahnt": "Not yet reminded",
  "Zahlungserinnerung fehlt noch": "Payment reminder still missing",
  "alle überfälligen sind gemahnt": "all overdue ones have been reminded",
  "Mahnkosten offen": "Reminder costs open",
  "Gebühr und Verzugsaufschlag, noch nicht eingegangen": "Fee and late payment surcharge, not yet received",
  "Mahnkosten, die noch nicht eingegangen sind": "Reminder costs not yet received",
  "Überfällige Einnahmen ohne Rechnung": "Overdue income without invoice",
  "noch nicht gemahnt": "not yet reminded",
  "Frist bis": "Deadline until",
  "läuft noch": "still running",
  "Nummer oder Kunde suchen …": "Search number or customer …",
  "Fällig am": "Due on",
  "seit {0} Tagen": "for {0} days",
  "Letzte Mahnung": "Last reminder",
  "Als Nächstes": "Next",
  "alle Stufen durchlaufen": "all levels completed",
  "Erneut mahnen": "Remind again",
  "Mahnen": "Remind",
  "Stand": "Status",
  "Frist läuft noch": "Deadline still running",
  "Frist abgelaufen": "Deadline expired",
  "Nichts überfällig": "Nothing overdue",
  "Sobald eine ausgestellte Rechnung nach ihrer Fälligkeit noch offen ist, erscheint sie hier mit dem Vorschlag für die nächste Stufe.": "As soon as an issued invoice is still open after its due date, it appears here with the suggestion for the next level.",
  "Eingang buchen": "Book receipt",
  "Verzugsaufschlag": "Late payment surcharge",
  "Gefordert": "Claimed",
  "PDF ansehen": "View PDF",
  "Noch keine Mahnungen": "No reminders yet",
  "Erstellte Zahlungserinnerungen und Mahnungen stehen hier mit ihrem PDF.": "Created payment reminders and reminders are listed here with their PDF.",
  "Seit {0} Tagen überfällig, {1} € offen.": "Overdue for {0} days, {1} € open.",
  "Letzte Mahnung: {0} am {1}, Frist bis {2}{3}.": "Last reminder: {0} on {1}, deadline until {2}{3}.",
  "(läuft noch)": "(still running)",
  "(abgelaufen)": "(expired)",
  "Noch nicht gemahnt.": "Not yet reminded.",
  "Gefordert {0} € bis": "Claimed {0} € by",
  "Mahnung zurücknehmen": "Withdraw reminder",
  "Mahnkosten (Gebühr und Verzugsaufschlag): {0} €{1}.": "Reminder costs (fee and late payment surcharge): {0} €{1}.",
  ", davon {0} € eingegangen": ", of which {0} € received",
  "Noch offen: {0}. Gebucht wird erst, wenn das Geld eingegangen ist.": "Still open: {0}. Booking only happens once the money has arrived.",
  "Alles eingegangen.": "Everything received.",
  "Mahnung erneut erstellen": "Create reminder again",
  "Mahnkosten als eingegangen buchen": "Book reminder costs as received",
  "Mahnung zurücknehmen?": "Withdraw reminder?",
  "vom {0} bleibt mit ihrem PDF im Verlauf stehen, zählt aber nicht mehr für die nächste Stufe und die Mahnkosten. Das ist für ein Schreiben gedacht, das Sie noch nicht verschickt haben.": "of {0} stays in the history with its PDF, but no longer counts for the next level and the reminder costs. This is intended for a letter you have not sent yet.",
  "Zurücknehmen": "Withdraw",
  "Mahnung zurückgenommen": "Reminder withdrawn",
  "Nicht zurückgenommen": "Not withdrawn",
  "Die PDF-Datei liegt auf diesem Gerät nicht vor": "The PDF file is not available on this device",
  "Diese Rechnung gibt es nicht mehr": "This invoice no longer exists",
  "Nicht mahnbar": "Cannot be reminded",
  "Mahnung zu": "Reminder for",
  "· {0} € offen · fällig war {1} ({2} Tage her)": "· {0} € open · was due {1} ({2} days ago)",
  "Der Kunde ist": "The customer is",
  "Datum des Schreibens": "Date of the letter",
  "Zahlen bis": "Pay by",
  "Mahngebühr €": "Reminder fee €",
  "0 oder leer: keine Gebühr, sie steht dann nicht auf dem Schreiben.": "0 or empty: no fee; it then does not appear on the letter.",
  "Text des Schreibens anpassen": "Adjust the letter text",
  "Text vor der Aufstellung": "Text before the breakdown",
  "{frist} und {betrag} werden eingesetzt.": "{frist} and {betrag} are filled in.",
  "Das Schreiben erscheint mit Ihrer Vorlage, Ihrem Absender und dem GiroCode als PDF. Gebucht wird erst, wenn Gebühr und Verzugsaufschlag eingegangen sind. Die Rechnung selbst bleibt unverändert. Gebühr und Verzugsaufschlag verantworten Sie selbst, bei Privatkunden gelten andere Regeln als bei Geschäftskunden.": "The letter appears as a PDF with your template, your sender details and the GiroCode. Booking only happens once the fee and late payment surcharge have been received. The invoice itself stays unchanged. You are responsible for the fee and late payment surcharge; different rules apply to private customers than to business customers.",
  "Mahnung erstellen": "Create reminder",
  "Prozent pro Jahr ({0} %), tageweise ab": "Percent per year ({0}%), daily from",
  "Beginn des Verzugs": "start of default",
  "Prozent pro Jahr (in den Einstellungen ist noch kein Satz eingetragen)": "Percent per year (no rate entered in the settings yet)",
  "Pauschale ({0} €, schon früher berechnet, bleibt in der Forderung)": "Lump sum ({0} €, already charged earlier, remains in the claim)",
  "Feste Pauschale ({0} €, höchstens einmal je Rechnung)": "Fixed lump sum ({0} €, at most once per invoice)",
  "Verbraucher: Basiszinssatz plus 5 Prozentpunkte, keine Pauschale, Mahngebühr nur für tatsächlichen Aufwand. Wählen Sie „Unternehmen“, wenn der Kunde gewerblich bestellt hat.": "Consumer: base rate plus 5 percentage points, no lump sum, reminder fee only for actual costs. Choose “Business” if the customer ordered commercially.",
  "Unternehmen: Basiszinssatz plus 9 Prozentpunkte, dazu die Pauschale von 40 € (§ 288 BGB).": "Business: base rate plus 9 percentage points, plus the €40 lump sum (§ 288 BGB).",
  "In den Einstellungen ist der Verzugsaufschlag ausgeschaltet. Hier lässt er sich für dieses eine Schreiben einschalten.": "The late payment surcharge is turned off in the settings. Here it can be turned on for this one letter.",
  "font-weight:600;border-top:1px solid var(--border);padding-top:6px;margin-top:4px": "font-weight:600;border-top:1px solid var(--border);padding-top:6px;margin-top:4px",
  "Verzugsaufschlag {0} % für {1} Tage": "Late payment surcharge {0}% for {1} days",
  "abzüglich Mahngebühren, auf die Pauschale angerechnet": "less reminder fees, credited against the lump sum",
  "Mahnung nicht erstellt": "Reminder not created",
  "Es stehen keine Mahnkosten offen": "There are no open reminder costs",
  "Mahnkosten zu {0} buchen": "Book reminder costs for {0}",
  "Gebühr und Verzugsaufschlag sind kein Entgelt für eine Leistung. Sie werden deshalb ohne Umsatzsteuer als eigene Einnahme gebucht, und zwar an dem Tag, an dem das Geld eingegangen ist.": "The fee and late payment surcharge are not payment for a service. They are therefore booked without VAT as separate income, on the day the money arrived.",
  "Betrag €": "Amount €",
  "Offen sind {0} €.": "{0} € is open.",
  "Eingegangen am": "Received on",
  "Festgeschrieben bis {0}: Das Datum muss danach liegen.": "Locked until {0}: the date must be after that.",
  "Mahnkosten gebucht": "Reminder costs booked",
  "Kunden & Lieferanten": "Customers & suppliers",
  "Wiederkehrend": "Recurring",
  "Neue Kategorie": "New category",
  "Neues Konto": "New account",
  "Neues Anlagegut": "New fixed asset",
  "Neue Wiederholung": "New recurrence",
  "Bereich": "Section",
  "Verwendung": "Usage",
  "Mit und ohne Buchungen": "With and without transactions",
  "Mit Buchungen": "With transactions",
  "Ohne Buchungen": "Without transactions",
  "Die Kategorie einer Buchung entscheidet, in welche Zeile der Anlage EÜR und auf welches Konto im DATEV-Export sie fließt. Die mitgelieferte Zuordnung folgt der Anlage EÜR (Vordruck {0}) und dem {1}. Prüfen Sie sie einmal mit Ihrer Steuerberatung und passen Sie sie hier an, wenn sich das Formular ändert.": "A transaction's category determines which line of the Anlage EÜR and which account in the DATEV export it goes to. The supplied assignment follows the Anlage EÜR (form {0}) and the {1}. Check it once with your tax advisor and adjust it here when the form changes.",
  "Name, Konto oder EÜR-Zeile suchen …": "Search name, account or EÜR line …",
  "Einnahmen zuerst": "Income first",
  "Ausgaben zuerst": "Expenses first",
  "EÜR-Zeile": "EÜR line",
  "Steuersatz": "Tax rate",
  "Besonderheit": "Special feature",
  "Nur Einnahmen": "Income only",
  "Nur Ausgaben": "Expenses only",
  "Alle Kategorien": "All categories",
  "Ohne Besonderheit": "No special feature",
  "Privatvorgang": "Private item",
  "Nur teilweise abziehbar": "Only partially deductible",
  "Finanzamt-Verrechnung": "Tax office settlement",
  "Innergemeinschaftlich oder Reverse Charge": "Intra-community or reverse charge",
  "privat, kein Betriebsvorgang": "private, not a business item",
  "regelmäßig": "regular",
  "nur {0} % abziehbar": "only {0}% deductible",
  "Reverse Charge": "Reverse charge",
  "Name, E-Mail, Telefon oder Steuernummer suchen …": "Search name, email, phone or tax number …",
  "Steuernummer / USt-IdNr.": "Tax number / VAT ID",
  "Alle Kontakte": "All contacts",
  "Kontakte helfen beim Auswerten: Wer bringt Umsatz, wo geben Sie am meisten aus.": "Contacts help with evaluation: who brings revenue, where you spend the most.",
  "Sonstiges": "Other",
  "Zahlungskonten bilden Ihre Bankkonten und Ihre Bargeldkasse ab. Der Anfangsbestand ist der Saldo an dem Tag, ab dem Sie mit Kontovia buchen. Nur dann stimmen die Kontostände in der Übersicht.": "Payment accounts represent your bank accounts and your cash box. The opening balance is the balance on the day from which you book with Kontovia. Only then are the account balances on the overview correct.",
  "Anfangsbestand": "Opening balance",
  "Gültig ab": "Valid from",
  "Keine Konten": "No accounts",
  "Legen Sie mindestens ein Bankkonto an.": "Create at least one bank account.",
  "Wirtschaftsgüter über 800 € netto werden nicht sofort abgezogen, sondern über ihre Nutzungsdauer verteilt (§ 7 EStG): linear, degressiv (Anschaffung 07/2025 bis 12/2027) oder bei Computern und Software mit einem Jahr. Kontovia rechnet monatsgenau ab dem Anschaffungsmonat und übernimmt den Betrag automatisch in Ihre Betriebsausgaben und in Zeile {0} der Anlage EÜR {1}.": "Assets over €800 net are not deducted immediately but spread over their useful life (§ 7 EStG): straight-line, declining balance (purchase 07/2025 to 12/2027) or, for computers and software, over one year. Kontovia calculates by month from the month of purchase and automatically includes the amount in your business expenses and in line {0} of the Anlage EÜR {1}.",
  "Restbuchwert {0} €": "Residual book value {0} €",
  "J. ·": "yrs ·",
  "Restbuchwert heute": "Residual book value today",
  "Abschreibungsplan": "Depreciation schedule",
  "Kein Anlagevermögen": "No fixed assets",
  "Beim Erfassen einer Ausgabe können Sie „Als Anlagegut abschreiben“ wählen.": "When recording an expense, you can choose “Depreciate as fixed asset”.",
  "Miete, Telefon, Versicherungen, Software-Abos: Eine wiederkehrende Buchung entsteht beim Erfassen (Weitere Angaben → Wiederholen). Sobald die nächste fällig ist, bietet Kontovia sie zum Anlegen an, nach dem Entsperren oder über „Jetzt anlegen“. Jede wird eine gewöhnliche Buchung mit eigenem Beleg.": "Rent, phone, insurance, software subscriptions: a recurring transaction is created when recording (More details → Repeat). As soon as the next one is due, Kontovia offers to create it, after unlocking or via “Create now”. Each becomes an ordinary transaction with its own receipt.",
  "Jetzt anlegen": "Create now",
  "Abschreibungsplan:": "Depreciation schedule:",
};
