/** Wörterbuch Englisch, Teil t14. Quellen: views/master.js, views/rechnungen.js, views/rechnungseditor.js, views/rechnungsgestalter.js. */

export default {
  "Anschaffungskosten {0} € · {1}{2} · ab {3} · im ersten Jahr anteilig nach Monaten (§ 7 Abs. 1 Satz 4 EStG)": "Acquisition cost {0} € · {1}{2} · from {3} · pro rata by month in the first year (§ 7 (1) sentence 4 EStG)",
  "Restbuchwert am Jahresende": "Residual book value at year end",
  "· {0} Jahre": "· {0} years",
  "· {0} % vom Restwert": "· {0}% of residual value",
  "Festgeschrieben": "Locked",
  "Die Anschaffung liegt im festgeschriebenen Zeitraum. Ihre Abschreibung ist erklärt und bleibt stehen.": "The purchase is in the locked period. Its depreciation has been declared and stays as it is.",
  "Wird noch verwendet": "Still in use",
  "Buchungen verweisen darauf. Ändern Sie diese zuerst oder blenden Sie den Eintrag nur aus.": "Transactions refer to it. Change them first or just hide the entry.",
  "Wirklich löschen?": "Really delete?",
  "Der Eintrag wird entfernt.": "The entry will be removed.",
  "Gelöscht": "Deleted",
  "(keine Eingabezeile im Formular 2025, bitte ändern)": "(no input line in form 2025, please change)",
  "Kategorie bearbeiten": "Edit category",
  "Name *": "Name *",
  "Zeile der Anlage EÜR": "Anlage EÜR line",
  "Keine Zuordnung (nicht steuerwirksam)": "No assignment (not tax-relevant)",
  "Bestimmt, wo der Betrag in der EÜR-Auswertung erscheint. Nummern nach dem Vordruck {0}; für andere Jahre rechnet Kontovia um.": "Determines where the amount appears in the EÜR report. Numbers according to form {0}; Kontovia converts them for other years.",
  "Konto SKR03": "Account SKR03",
  "Konto SKR04": "Account SKR04",
  "Abziehbarer Anteil": "Deductible share",
  "100 % (voll abziehbar)": "100% (fully deductible)",
  "70 % (Bewirtungskosten)": "70% (entertainment expenses)",
  "0 % (nicht abziehbar)": "0% (not deductible)",
  "Privatvorgang (Entnahme oder Einlage, wirkt nicht auf den Gewinn)": "Private item (withdrawal or contribution, does not affect profit)",
  "Regelmäßig wiederkehrend (etwa Miete, Leasing, Versicherung)": "Regularly recurring (such as rent, leasing, insurance)",
  "Zahlungen bis zehn Tage vor oder nach dem Jahreswechsel zählen dann in der Anlage EÜR im Jahr, zu dem sie gehören (§ 11 EStG).": "Payments within ten days before or after the turn of the year then count in the Anlage EÜR in the year they belong to (§ 11 EStG).",
  "in der Auswahl anzeigen": "show in selection",
  "Diese Kategorie hat Buchungen im festgeschriebenen Zeitraum (bis {0}). Eine andere EÜR-Zeile, ein anderer Steuersatz oder „Privatvorgang“ verändern auch die Auswertungen dieser Zeiträume. Legen Sie für Neues besser eine neue Kategorie an.": "This category has transactions in the locked period (until {0}). A different EÜR line, a different tax rate or “Private item” also change the reports of these periods. Better create a new category for new items.",
  "Bitte einen Namen eintragen": "Please enter a name",
  "Festgeschriebene Zeiträume ändern sich mit": "Locked periods change too",
  "Die Änderung gilt auch für Buchungen, die schon festgeschrieben und erklärt sind. Deren EÜR sähe danach anders aus. Trotzdem ändern?": "The change also applies to transactions that are already locked and declared. Their EÜR would then look different. Change anyway?",
  "Trotzdem ändern": "Change anyway",
  "Kategorie gespeichert": "Category saved",
  "Kontakt bearbeiten": "Edit contact",
  "Kunde und Lieferant": "Customer and supplier",
  "Zusatz zur Anschrift": "Address supplement",
  "Land": "Country",
  "Kundennummer": "Customer number",
  "nur bei Behörden": "only for public authorities",
  "Aufgaben zu diesem Kontakt": "Tasks for this contact",
  "Kontakt gespeichert": "Contact saved",
  "Neues Zahlungskonto": "New payment account",
  "Konto bearbeiten": "Edit account",
  "z. B. Geschäftskonto Sparkasse": "e.g. business account Sparkasse",
  "Kasse (Bargeld)": "Cash box (cash)",
  "Sonstiges (PayPal, Kreditkarte …)": "Other (PayPal, credit card …)",
  "Der Anfangsbestand gilt ab einem festgeschriebenen Tag (bis {0}) und lässt sich deshalb nicht mehr ändern.": "The opening balance applies from a locked day (until {0}) and therefore can no longer be changed.",
  "Der Anfangsbestand kann erst nach dem {0} beginnen.": "The opening balance can only start after {0}.",
  "Konto gespeichert": "Account saved",
  "Anlagegut bearbeiten": "Edit fixed asset",
  "Anlagegut gespeichert": "Fixed asset saved",
  "Vorlagen": "Templates",
  "Gestaltung": "Design",
  "Rechnungen, die Sie schreiben": "Invoices you write",
  "E-Rechnungen, die Sie erhalten": "E-invoices you receive",
  "Überfällige Rechnungen und Mahnungen": "Overdue invoices and reminders",
  "Positionen und Texte, aus denen mit einem Klick eine neue Rechnung entsteht": "Items and texts from which a new invoice is created with one click",
  "Leistungen und Waren, die Sie öfter berechnen": "Services and goods you invoice often",
  "Aussehen der Rechnung, Bankverbindung und Voreinstellungen": "Invoice appearance, bank details and defaults",
  "Leere Rechnung": "Blank invoice",
  "Aus Vorlage": "From template",
  "seit dem Fälligkeitstag offen": "open since the due date",
  "nichts überfällig": "nothing overdue",
  "Gestellt": "Issued",
  "Entwürfe": "Drafts",
  "noch nicht ausgestellt": "not issued yet",
  "keine offenen Entwürfe": "no open drafts",
  "Zum Mahnwesen": "To dunning",
  "Rechnung ist": "invoice is",
  "Rechnungen sind": "invoices are",
  "Nummer, Kunde oder Betreff suchen …": "Search number, customer or subject …",
  "Noch keine Rechnungen": "No invoices yet",
  "Mit „Neue Rechnung“ schreiben Sie Ihre erste Rechnung. Sie entsteht als PDF, das zugleich als E-Rechnung gilt.": "With “New invoice” you write your first invoice. It is created as a PDF that also counts as an e-invoice.",
  "PDF nicht erstellt": "PDF not created",
  "Zur Übersicht": "To the overview",
  "Ausgestellt": "Issued",
  "Verschicken": "Send",
  "Per E-Mail senden": "Send by email",
  "PDF speichern": "Save PDF",
  "XRechnung speichern": "Save XRechnung",
  "Das PDF ist eine E-Rechnung nach ZUGFeRD (EN 16931): Es enthält die Rechnungsdaten maschinenlesbar. Behörden verlangen meist die XRechnung als eigene Datei.": "The PDF is an e-invoice according to ZUGFeRD (EN 16931): it contains the invoice data in machine-readable form. Public authorities usually require the XRechnung as a separate file.",
  "Zahlung und Buchung": "Payment and transaction",
  "Eine ausgestellte Rechnung bleibt, wie sie ist. Fehler behebt eine Korrektur: Die Rechnung wird storniert und als neuer Entwurf mit Bezug auf die alte geöffnet.": "An issued invoice stays as it is. Errors are fixed by a correction: the invoice is reversed and opened as a new draft referring to the old one.",
  "Duplizieren": "Duplicate",
  "Als Vorlage": "As template",
  "Aufbewahrung": "Retention",
  "Rechnungen müssen acht Jahre aufbewahrt werden (§ 14b UStG). Kontovia hält beide Dateien unverändert im Tresor und gibt sie mit jedem Export und jeder Sicherung mit.": "Invoices must be kept for eight years (§ 14b UStG). Kontovia keeps both files unchanged in the vault and includes them with every export and every backup.",
  "Ansicht der Rechnung": "Invoice view",
  "Storniert durch {0} vom {1}.": "Reversed by {0} of {1}.",
  "Bezieht sich auf {0}.": "Refers to {0}.",
  "Versendet am": "Sent on",
  "Die Buchungen der ursprünglichen Rechnung sind storniert.": "The transactions of the original invoice are reversed.",
  "Zu dieser Rechnung gibt es keine Buchung.": "There is no transaction for this invoice.",
  "Als bezahlt markieren": "Mark as paid",
  "Korrigieren": "Correct",
  "Stornieren": "Reverse",
  "Prüfsumme {0}…": "Checksum {0}…",
  "Die Dateien liegen auf diesem Gerät noch nicht vor.": "The files are not yet available on this device.",
  "Zu dieser Rechnung": "For this invoice",
  "Zahlungseingang prüfen:": "Check incoming payment:",
  "XRechnung gespeichert": "XRechnung saved",
  "Buchung zu {0} angelegt": "Transaction for {0} created",
  "von Hand vermerkt": "recorded manually",
  "über Gmail": "via Gmail",
  "über Outlook": "via Outlook",
  "Mit Gmail senden": "Send with Gmail",
  "Kontovia sendet die E-Mail direkt über Ihr Google-Konto {0}. Sie steht danach in Gmail unter „Gesendet“.": "Kontovia sends the email directly via your Google account {0}. It then appears in Gmail under “Sent”.",
  "Kontovia sendet die E-Mail direkt über Ihr Google-Konto. Beim ersten Mal fragt Google in einem kleinen Fenster, ob Kontovia E-Mails in Ihrem Namen senden darf. Die E-Mail steht danach in Gmail unter „Gesendet“.": "Kontovia sends the email directly via your Google account. The first time, Google asks in a small window whether Kontovia may send emails in your name. The email then appears in Gmail under “Sent”.",
  "Mit Outlook senden (Outlook.com oder Microsoft 365)": "Send with Outlook (Outlook.com or Microsoft 365)",
  "Kontovia sendet die E-Mail direkt über Ihr Microsoft-Konto {0}. Sie steht danach in Outlook unter „Gesendete Elemente“.": "Kontovia sends the email directly via your Microsoft account {0}. It then appears in Outlook under “Sent Items”.",
  "Kontovia sendet die E-Mail direkt über Ihr Microsoft-Konto. Beim ersten Mal fragt Microsoft in einem kleinen Fenster, ob Kontovia E-Mails in Ihrem Namen senden darf. Die E-Mail steht danach in Outlook unter „Gesendete Elemente“.": "Kontovia sends the email directly via your Microsoft account. The first time, Microsoft asks in a small window whether Kontovia may send emails in your name. The email then appears in Outlook under “Sent Items”.",
  "E-Mail-Datei für Outlook, Thunderbird oder Apple Mail": "Email file for Outlook, Thunderbird or Apple Mail",
  "E-Mail erstellen": "Create email",
  "Kontovia legt die fertige E-Mail mit Anhang in Ihren Download-Ordner. Ein Klick darauf in der Download-Leiste des Browsers öffnet sie in Ihrem E-Mail-Programm, dort senden Sie sie ab.": "Kontovia puts the finished email with attachment in your download folder. A click on it in the browser's download bar opens it in your email program, where you send it.",
  "Teilen": "Share",
  "Übergibt Anhang und Text an Mail, Outlook, Gmail oder eine andere App auf diesem Gerät. Die Empfängeradresse kopiert Kontovia vorher, Sie fügen sie dort ein.": "Passes the attachment and text to Mail, Outlook, Gmail or another app on this device. Kontovia copies the recipient address beforehand; you paste it there.",
  "Nur den Text übergeben": "Pass only the text",
  "E-Mail-Programm öffnen": "Open email program",
  "Öffnet Ihr E-Mail-Programm mit Empfänger, Betreff und Text. Den Anhang fügen Sie dort selbst hinzu, vorher speichern Sie ihn mit „PDF speichern“.": "Opens your email program with recipient, subject and text. You add the attachment there yourself; save it first with “Save PDF”.",
  "An": "To",
  "E-Mail-Adresse des Kunden": "Customer email address",
  "Betreff": "Subject",
  "Nachricht": "Message",
  "Standardtext ändern": "Change default text",
  "Anhang": "Attachment",
  "PDF mit E-Rechnung (ZUGFeRD)": "PDF with e-invoice (ZUGFeRD)",
  "XRechnung als eigene Datei": "XRechnung as a separate file",
  "Weg": "Method",
  "Anderes Konto": "Other account",
  "(meist nur für Behörden nötig)": "(usually only needed for public authorities)",
  "Wenn Sie die Rechnung anders verschickt haben": "If you sent the invoice another way",
  "Als versendet vermerken": "Mark as sent",
  "Die Rechnung ließ sich nicht vorbereiten": "The invoice could not be prepared",
  "Dieses Gerät kann die XRechnung nicht teilen. Nehmen Sie sie aus dem Anhang oder wählen Sie einen anderen Weg.": "This device cannot share the XRechnung. Remove it from the attachment or choose another method.",
  "Der Anhang ist für Outlook zu groß. Wählen Sie einen anderen Weg, etwa die E-Mail-Datei.": "The attachment is too large for Outlook. Choose another method, such as the email file.",
  "Beim nächsten Senden wählen Sie das Konto neu": "You will choose the account again the next time you send",
  "PDF nicht gespeichert": "PDF not saved",
  "Versand vermerkt": "Sending recorded",
  "Nicht vermerkt": "Not recorded",
  "Haben Sie die E-Mail abgeschickt? Dann vermerkt Kontovia den Versand bei der Rechnung.": "Did you send the email? Then Kontovia records the sending with the invoice.",
  "Noch nicht": "Not yet",
  "Ja, als versendet vermerken": "Yes, mark as sent",
  "Bitte die Adresse prüfen": "Please check the address",
  "Bitte eine Empfängeradresse eingeben": "Please enter a recipient address",
  "Wird gesendet …": "Sending …",
  "Bitte im Fenster bestätigen …": "Please confirm in the window …",
  "E-Mail gesendet": "Email sent",
  "Gesendet, aber nicht vermerkt": "Sent, but not recorded",
  "Die Adresse {0} ist kopiert. Fügen Sie sie in der E-Mail als Empfänger ein.": "The address {0} has been copied. Paste it into the email as the recipient.",
  "Die Dateien sind übergeben.": "The files have been passed on.",
  "E-Mail_{0}.eml": "E-Mail_{0}.eml",
  "„{0}“ liegt in Ihrem Download-Ordner. Klicken Sie in der Download-Leiste des Browsers darauf, dann öffnet sich die E-Mail in Ihrem E-Mail-Programm. Prüfen Sie sie dort und senden Sie sie ab.": "“{0}” is in your download folder. Click it in the browser's download bar, and the email opens in your email program. Check it there and send it.",
  "Der Text war für diesen Weg zu lang und ist gekürzt. Der ganze Text liegt in der Zwischenablage. Den Anhang fügen Sie selbst hinzu.": "The text was too long for this method and has been shortened. The full text is on the clipboard. You add the attachment yourself.",
  "Ihr E-Mail-Programm sollte sich geöffnet haben. Den Anhang fügen Sie dort selbst hinzu.": "Your email program should have opened. You add the attachment there yourself.",
  "Nicht gesendet": "Not sent",
  "Bitte noch einmal senden": "Please send again",
  "Standardtext für E-Mails": "Default text for emails",
  "Gilt für jede Rechnung, die Sie per E-Mail senden. Die Wörter in geschweiften Klammern ersetzt Kontovia durch die Angaben der Rechnung.": "Applies to every invoice you send by email. Kontovia replaces the words in curly brackets with the invoice details.",
  "Ursprünglichen Text nehmen": "Use the original text",
  "Standardtext für E-Mails zu Rechnungen geändert": "Default text for invoice emails changed",
  "Standardtext gespeichert": "Default text saved",
  "als bezahlt markieren": "mark as paid",
  "Die offene Einnahme bekommt dieses Zahlungsdatum.": "The open income gets this payment date.",
  "Als bezahlt markiert": "Marked as paid",
  "Nicht markiert": "Not marked",
  "Grund (steht auf der Stornorechnung)": "Reason (appears on the cancellation invoice)",
  "z. B. falscher Rechnungsempfänger": "e.g. wrong invoice recipient",
  "Kontovia storniert die Rechnung mit einer Stornorechnung und öffnet eine Kopie als neuen Entwurf. Die neue Rechnung bekommt beim Ausstellen eine eigene Nummer.": "Kontovia reverses the invoice with a cancellation invoice and opens a copy as a new draft. The new invoice gets its own number when issued.",
  "Es entsteht eine Stornorechnung mit eigener Nummer, die die Rechnung in voller Höhe aufhebt. Die Buchungen dazu werden storniert.": "A cancellation invoice with its own number is created that cancels the invoice in full. The associated transactions are reversed.",
  "Stornieren und neu erstellen": "Reverse and create again",
  "Stornorechnung {0} ausgestellt": "Cancellation invoice {0} issued",
  "Nicht storniert": "Not reversed",
  "Als Vorlage speichern": "Save as template",
  "Kunde mit speichern": "Save customer too",
  "Vorlage gespeichert": "Template saved",
  "E-Rechnungen empfangen": "Receiving e-invoices",
  "Seit 2025 muss jedes Unternehmen E-Rechnungen annehmen können. Speichern Sie eine erhaltene E-Rechnung aus Ihrem Postfach und fügen Sie sie hier hinzu. Kontovia zeigt sie lesbar an und bereitet die Buchung vor.": "Since 2025 every business must be able to receive e-invoices. Save a received e-invoice from your mailbox and add it here. Kontovia shows it in readable form and prepares the transaction.",
  "E-Rechnung hinzufügen": "Add e-invoice",
  "Absender oder Nummer suchen …": "Search sender or number …",
  "Noch keine erhaltenen E-Rechnungen": "No received e-invoices yet",
  "Fügen Sie eine E-Rechnung hinzu, als XML-Datei oder als PDF mit eingebetteten Daten.": "Add an e-invoice, as an XML file or as a PDF with embedded data.",
  "Keine E-Rechnung gefunden": "No e-invoice found",
  "Die Datei enthält keine lesbaren Rechnungsdaten. Eine gewöhnliche Rechnung als PDF hängen Sie direkt an eine Buchung.": "The file contains no readable invoice data. Attach an ordinary invoice as a PDF directly to a transaction.",
  "E-Rechnung erhalten:": "E-invoice received:",
  "E-Rechnung hinzugefügt": "E-invoice added",
  "Die Datei lässt sich nicht mehr lesen": "The file can no longer be read",
  "Rechnung nicht lesbar": "Invoice not readable",
  "Erhaltene Rechnung {0} gebucht": "Received invoice {0} booked",
  "Aus dem Eingang entfernen?": "Remove from incoming?",
  "Die Rechnung bleibt als Beleg an ihrer Buchung. Nur der Eintrag im Eingang verschwindet.": "The invoice stays as a receipt on its transaction. Only the entry in incoming disappears.",
  "Die Datei wird aus dem Tresor gelöscht.": "The file will be deleted from the vault.",
  "Erhaltene Rechnung entfernt": "Received invoice removed",
  "Leistungen und Waren, die Sie öfter berechnen. In der Rechnung fügen Sie sie mit einem Klick ein und können jede Angabe dort noch ändern.": "Services and goods you invoice often. In the invoice you insert them with one click and can still change every detail there.",
  "Neues Produkt": "New product",
  "Name, Nummer oder Kategorie suchen …": "Search name, number or category …",
  "Legen Sie Leistungen mit Preis und Einheit an, etwa „Beratung, 95 € je Stunde“ oder „Wartungspauschale, 120 € je Monat“.": "Create services with price and unit, such as “Consulting, €95 per hour” or “Maintenance flat rate, €120 per month”.",
  "Produkt löschen?": "Delete product?",
  "„{0}“ verschwindet aus der Liste. Rechnungen, die es schon enthalten, bleiben unverändert.": "“{0}” disappears from the list. Invoices that already contain it stay unchanged.",
  "Produkt bearbeiten": "Edit product",
  "Preis netto €": "Net price €",
  "je Einheit": "per unit",
  "Artikelnummer": "Article number",
  "Diese Einheit steht in der E-Rechnung als Stück.": "This unit appears as piece in the e-invoice.",
  "Produkt gespeichert": "Product saved",
  "Eine Vorlage hält Positionen, Texte und Zahlungsbedingungen fest, auf Wunsch auch den Kunden. Daraus entsteht mit einem Klick eine neue Rechnung. Speichern lässt sich jede Rechnung als Vorlage.": "A template keeps items, texts and payment terms, and the customer if you wish. A new invoice is created from it with one click. Any invoice can be saved as a template.",
  "Neue Vorlage": "New template",
  "Positionen": "Items",
  "Noch keine Vorlagen": "No templates yet",
  "Legen Sie eine Vorlage an oder speichern Sie eine fertige Rechnung als Vorlage, etwa für monatliche Wartung oder ein Standardpaket.": "Create a template or save a finished invoice as a template, for example for monthly maintenance or a standard package.",
  "Vorlage löschen?": "Delete template?",
  "„{0}“ wird entfernt. Rechnungen daraus bleiben unverändert.": "“{0}” will be removed. Invoices created from it stay unchanged.",
  "Ihre Angaben": "Your details",
  "Aussehen ändern": "Change appearance",
  "Aus Kontakten": "From contacts",
  "Eine Anschrift aus einer E-Mail oder einem Dokument einfügen": "Paste an address from an email or a document",
  "Anschrift einfügen": "Paste address",
  "Name oder Firma": "Name or company",
  "Pflicht": "Required",
  "E-Mail für Rechnungen": "Email for invoices",
  "nur bei Firmenkunden": "only for business customers",
  "nur bei Behörden, z. B. 04011000-12345-67": "only for public authorities, e.g. 04011000-12345-67",
  "Öffentliche Auftraggeber nennen sie im Auftrag. Mit ihr entsteht eine XRechnung.": "Public clients state it in the order. With it, an XRechnung is created.",
  "Aus Kontakt": "From contact",
  "Verbindung zum Kontakt lösen": "Unlink from contact",
  "Kontakt aktualisieren": "Update contact",
  "Als Kontakt speichern": "Save as contact",
  "Tragen Sie den Kunden einfach direkt ein. Mit „Als Kontakt speichern“ steht er beim nächsten Mal hier.": "Simply enter the customer directly. With “Save as contact” they will be here next time.",
  "Kontakt wählen": "Choose contact",
  "Freie Eingabe ohne Kontakt": "Free entry without contact",
  "Fügen Sie die Anschrift ein, wie sie in einer E-Mail, einer Bestellung oder einer Signatur steht. Kontovia verteilt sie auf die Felder; prüfen Sie das Ergebnis danach.": "Paste the address as it appears in an email, an order or a signature. Kontovia distributes it into the fields; check the result afterwards.",
  "Muster GmbH z. Hd. Frau Beispiel Hauptstraße 1 12345 Musterstadt": "Muster GmbH z. Hd. Frau Beispiel Hauptstraße 1 12345 Musterstadt",
  "Bitte zuerst einen Namen eintragen": "Please enter a name first",
  "Kontakt aktualisiert": "Contact updated",
  "wird beim Ausstellen vergeben": "assigned when issued",
  "Leistung erbracht": "Service provided",
  "Leistungsdatum oder Zeitraum": "Service date or period",
  "Bestellnummer des Kunden": "Customer order number",
  "Pflicht bei Arbeiten an Haus oder Grundstück für Privatkunden (§ 14 Abs. 4 Nr. 9 UStG)": "Required for work on a house or property for private customers (§ 14 (4) No. 9 UStG)",
  "Arbeiten an Haus oder Grundstück für einen Privatkunden": "Work on a house or property for a private customer",
  "(Hinweis auf die Aufbewahrungspflicht)": "(notice of the retention obligation)",
  "Grund der Steuerbefreiung": "Reason for tax exemption",
  "z. B. Steuerfreie Heilbehandlung nach § 4 Nr. 14 UStG": "e.g. tax-exempt medical treatment under § 4 No. 14 UStG",
  "Das Datum kommt beim Erstellen der Rechnung dazu.": "The date is added when the invoice is created.",
  "Bezieht sich auf Rechnung": "Refers to invoice",
  "Nummer der ursprünglichen Rechnung": "Number of the original invoice",
  "Bezeichnung, z. B. Beratung": "Description, e.g. consulting",
  "Bezeichnung Position": "Item description",
  "Aus Produkten wählen": "Choose from products",
  "Beschreibung Position": "Item details",
  "Mehr": "More",
  "Weitere Aktionen für Position": "More actions for item",
  "Aus Produkten": "From products",
  "Unter Rechnungen → Produkte legen Sie Leistungen mit Preis und Einheit an. Oder: Position ausfüllen und im Menü der Zeile „Als Produkt speichern“.": "Under Invoices → Products you create services with price and unit. Or: fill in an item and choose “Save as product” in the row's menu.",
  "Produkt wählen": "Choose product",
  "Produkt aktualisieren": "Update product",
  "Als Produkt speichern": "Save as product",
  "Bitte zuerst eine Bezeichnung eintragen": "Please enter a description first",
  "Produkt aktualisiert": "Product updated",
  "Als Produkt gespeichert": "Saved as product",
  "USt {0} auf": "VAT {0} on",
  "1 Position": "1 item",
  "[data-summe=\"{0}\"]": "[data-summe=\"{0}\"]",
  "Texte": "Texts",
  "stehen auf dem PDF über und unter den Positionen": "appear on the PDF above and below the items",
  "Sofort": "Immediately",
  "Zahlbar sofort": "Payable immediately",
  "+14 T": "+14 d",
  "14 Tage ab Rechnungsdatum": "14 days from invoice date",
  "+30 T": "+30 d",
  "30 Tage ab Rechnungsdatum": "30 days from invoice date",
  "liegt vor dem Rechnungsdatum": "is before the invoice date",
  "Tage nach dem Rechnungsdatum": "days after the invoice date",
  "Zahlungsart": "Payment method",
  "Zahlungsziel in Tagen": "Payment term in days",
  "Bereits gezahlt (Anzahlung) €": "Already paid (down payment) €",
  "Skonto: innerhalb von Tagen": "Discount: within days",
  "Skonto in %": "Discount in %",
  "Zahlungsbedingungen": "Payment terms",
  "Leer lassen, dann bildet Kontovia den Text aus Zahlungsziel und Skonto.": "Leave empty and Kontovia builds the text from payment term and discount.",
  "Gutschrift: Sie zahlen an den Kunden": "Credit note: you pay the customer",
  "ergibt sich aus dem Rechnungsdatum": "results from the invoice date",
  "Werden aus Zahlungsziel und Skonto gebildet": "Built from payment term and discount",
  "Bilder": "Images",
  "etwa Fotos der Arbeit oder ein Lageplan": "such as photos of the work or a site plan",
  "Die Bilder stehen auf der Rechnung unter den Positionen. Die Stelle legen Sie unter Gestaltung fest.": "The images appear on the invoice below the items. You set the position under Design.",
  "lädt …": "loading …",
  "Bildunterschrift (optional)": "Caption (optional)",
  "Bildunterschrift": "Caption",
  "Breite": "Width",
  "Weiter nach vorne": "Move forward",
  "Bild entfernen": "Remove image",
  "[data-rbild=\"{0}\"]": "[data-rbild=\"{0}\"]",
  "[data-rb=\"text\"]": "[data-rb=\"text\"]",
  "[data-rb=\"breite\"]": "[data-rb=\"breite\"]",
  "Eine Pflichtangabe fehlt": "A mandatory detail is missing",
  "Pflichtangaben fehlen": "Mandatory details are missing",
  "Alle Pflichtangaben sind da": "All mandatory details are present",
  "Positionen und Ihre Angaben sind vollständig. Kunde und Datum kommen beim Erstellen der Rechnung dazu.": "Items and your details are complete. Customer and date are added when the invoice is created.",
  "Die Rechnung erfüllt § 14 UStG und ergibt eine gültige E-Rechnung.": "The invoice meets § 14 UStG and results in a valid e-invoice.",
  "Ein Hinweis": "One note",
  "Für eine XRechnung an Behörden": "For an XRechnung to public authorities",
  "fehlt eine Angabe": "one detail is missing",
  "fehlen {0} Angaben": "{0} details are missing",
  "[data-bereich=\"{0}\"]": "[data-bereich=\"{0}\"]",
  "Seite": "Page",
  "Die Vorschau ließ sich nicht erstellen:": "The preview could not be created:",
  "vollständig": "complete",
  "Entwurf löschen": "Delete draft",
  "Entwurf gespeichert": "Draft saved",
  "Entwurf löschen?": "Delete draft?",
  "Der Entwurf wird entfernt. Eine Nummer wurde noch nicht vergeben.": "The draft will be removed. No number has been assigned yet.",
  "Entwurf gelöscht": "Draft deleted",
  "Gespeichert werden Positionen, Texte und Zahlungsbedingungen. Datum und Nummer kommen beim Erstellen der Rechnung neu dazu.": "Items, texts and payment terms are saved. Date and number are added anew when the invoice is created.",
  "Ohne diese Angaben erfüllt die Rechnung die gesetzlichen Vorgaben nicht, und die E-Rechnung kann beim Empfänger abgelehnt werden:": "Without these details the invoice does not meet the legal requirements, and the e-invoice may be rejected by the recipient:",
  "Sie können trotzdem ausstellen, etwa wenn eine Angabe noch nicht bekannt ist. Nachtragen lässt sich das dann mit einer Korrektur der Rechnung.": "You can issue it anyway, for example if a detail is not known yet. It can then be added later with a correction of the invoice.",
  "Zurück zur Rechnung": "Back to the invoice",
  "Trotzdem ausstellen": "Issue anyway",
  "Danach steht die Rechnung fest: Kontovia legt das PDF mit der E-Rechnung und die XRechnung unverändert ab. Ändern lässt sie sich dann nur noch durch Stornieren oder Korrigieren.": "After that the invoice is final: Kontovia stores the PDF with the e-invoice and the XRechnung unchanged. It can then only be changed by reversing or correcting it.",
  "Schon bezahlt am": "Already paid on",
  "leer lassen, wenn die Zahlung noch aussteht": "leave empty if payment is still pending",
  "Als Minderung der Einnahmen buchen": "Book as a reduction of income",
  "Als offene Einnahme buchen": "Book as open income",
  "(je Steuersatz eine Buchung)": "(one transaction per tax rate)",
  "Rechnung ausstellen": "Issue invoice",
  "Die Einnahme ist gebucht.": "The income has been booked.",
  "Nicht ausgestellt": "Not issued",
  "Bild eingefügt": "Image inserted",
  "Es steht unter den Positionen.": "It appears below the items.",
  "[data-f=\"{0}\"]": "[data-f=\"{0}\"]",
  "Änderungen speichern?": "Save changes?",
  "Die Rechnung hat Änderungen, die noch nicht gespeichert sind.": "The invoice has changes that have not been saved yet.",
  "Blau": "Blue",
  "Petrol": "Petrol",
  "Bernstein": "Amber",
  "Rot": "Red",
  "Violett": "Violet",
  "Anthrazit": "Anthracite",
  "Hellblau": "Light blue",
  "Grün": "Green",
  "Schwarz": "Black",
};
