/** Wörterbuch Englisch, Teil t15. Quellen: views/rechnungsgestalter.js, views/reports.js, views/settings.js. */

export default {
  "Nachtblau": "Navy blue",
  "Dunkelgrau": "Dark gray",
  "Grau": "Gray",
  "Weiß": "White",
  "Kopf": "Header",
  "Rechnungsangaben": "Invoice details",
  "Tabelle und Summen": "Table and totals",
  "Text oben": "Text above",
  "Zahlung und Hinweise": "Payment and notes",
  "Text unten": "Text below",
  "Zusatzbild": "Additional image",
  "Fußzeile": "Footer",
  "Fläche": "Area",
  "Linie": "Line",
  "Klein": "Small",
  "Normal": "Normal",
  "Beispiel für Ihre Rechnung": "Example for your invoice",
  "Muster GmbH": "Muster GmbH",
  "Hauptstraße 1": "Hauptstraße 1",
  "Musterstadt": "Musterstadt",
  "K-1001": "K-1001",
  "Erstgespräch und Konzept": "Initial meeting and concept",
  "Umsetzung": "Implementation",
  "Farbe": "Color",
  "Eigene Farbe wählen": "Choose your own color",
  "Keine": "None",
  "Keine Farbe": "No color",
  "Firmenname": "Company name",
  "Steuernummer oder USt-IdNr.": "Tax number or VAT ID",
  "Die Gestaltung ist noch nicht übernommen.": "The design has not been applied yet.",
  "Freie Gestaltung zurücksetzen": "Reset free design",
  "Rückgängig (Strg+Z)": "Undo (Ctrl+Z)",
  "Rückgängig": "Undo",
  "Wiederholen (Strg+Y)": "Redo (Ctrl+Y)",
  "Klicken Sie auf einen Teil der Rechnung, um ihn zu ändern, und ziehen Sie ihn an eine andere Stelle. Ein Rechtsklick (am Telefon: länger drücken) zeigt weitere Möglichkeiten. Tabelle und Texte ordnen Sie durch Ziehen nach oben oder unten.": "Click a part of the invoice to change it, and drag it to another place. A right-click (on the phone: long press) shows more options. You arrange the table and texts by dragging them up or down.",
  "Pflichtangaben und die Daten der E-Rechnung bleiben immer erhalten, egal wie Sie gestalten. Teile, die sich überlappen würden, rücken von selbst zur Seite.": "Mandatory details and the e-invoice data are always preserved, no matter how you design. Parts that would overlap move aside by themselves.",
  "Stil und Farbe": "Style and color",
  "gilt für alle neuen Rechnungen": "applies to all new invoices",
  "Stil": "Style",
  "Für Titel, Tabellenkopf und Linien. Eine zu helle Farbe dunkelt Kontovia in der Schrift ab, damit die Rechnung lesbar bleibt.": "For title, table header and lines. Kontovia darkens a color that is too light in the text so the invoice stays readable.",
  "Schrift": "Font",
  "Klassisch": "Classic",
  "Modern": "Modern",
  "Schlicht": "Plain",
  "Logo, Briefpapier und Bild": "Logo, letterhead and image",
  "kein Logo": "no logo",
  "Logo hochladen": "Upload logo",
  "Anderes Logo": "Different logo",
  "Position und Größe stellen Sie in der Vorschau ein: Logo anklicken.": "You set position and size in the preview: click the logo.",
  "PNG, JPG oder SVG. Ohne Logo steht Ihr Firmenname im Kopf.": "PNG, JPG or SVG. Without a logo your company name appears in the header.",
  "Briefpapier hochladen": "Upload letterhead",
  "Anderes Briefpapier": "Different letterhead",
  "Nur erste Seite": "First page only",
  "Alle Seiten": "All pages",
  "Ein Bild Ihres Briefbogens im Format A4, etwa als JPG oder PNG. Es liegt hinter der ganzen Rechnung.": "An image of your letterhead in A4 format, for example as JPG or PNG. It lies behind the whole invoice.",
  "Steht Ihr Name schon auf dem Briefpapier, blenden Sie in der Vorschau die Fußzeile aus: Fußzeile anklicken.": "If your name is already on the letterhead, hide the footer in the preview: click the footer.",
  "kein Bild": "no image",
  "Bild hochladen": "Upload image",
  "Anderes Bild": "Different image",
  "Im Text": "In the text",
  "Über der Fußzeile": "Above the footer",
  "Etwa Ihre Unterschrift oder ein Siegel. Frei platzieren lassen sich Bilder mit „Hinzufügen: Bild“ über der Vorschau.": "For example your signature or a seal. Images can be placed freely with “Add: image” above the preview.",
  "Ihre Angaben auf Rechnungen": "Your details on invoices",
  "DE00 0000 0000 0000 0000 00": "DE00 0000 0000 0000 0000 00",
  "Bank": "Bank",
  "Kontoinhaber": "Account holder",
  "Land Ihres Betriebs": "Country of your business",
  "Handelsregister": "Commercial register",
  "z. B. Amtsgericht München HRB 12345": "e.g. Amtsgericht München HRB 12345",
  "Geschäftsführung": "Management",
  "bei GmbH und UG Pflicht": "required for GmbH and UG",
  "Website": "Website",
  "In den Einstellungen fehlen noch: {0}. Diese Angaben müssen auf jeder Rechnung stehen.": "Still missing in the settings: {0}. These details must appear on every invoice.",
  "Zu den Firmendaten": "To the company details",
  "Name, Anschrift und Steuernummer kommen aus den Einstellungen: {0}, {1}.": "Name, address and tax number come from the settings: {0}, {1}.",
  "Firmendaten ändern": "Change company details",
  "Voreinstellungen für neue Rechnungen": "Defaults for new invoices",
  "Vor der Nummer": "Before the number",
  "Diese IBAN ist ungültig. Bitte auf Zahlendreher prüfen.": "This IBAN is invalid. Please check for transposed digits.",
  "Erste Nummer: {0}{1}-0001": "First number: {0}{1}-0001",
  "Genaue Maße": "Exact dimensions",
  "Zurück an die Standardstelle": "Back to the default position",
  "Oben (mm)": "Top (mm)",
  "Links (mm)": "Left (mm)",
  "Ziehen Sie das Logo an eine andere Stelle oder am Eck größer und kleiner.": "Drag the logo to another place or make it larger and smaller at the corner.",
  "Ohne Logo steht Ihr Firmenname im Kopf.": "Without a logo your company name appears in the header.",
  "Links": "Left",
  "Mitte": "Center",
  "Rechts": "Right",
  "Firmenname im Kopf zeigen": "Show company name in the header",
  "Am Standardplatz sitzt sie im Fenster eines Briefumschlags. Anderswo passt sie nicht mehr ins Fenster.": "In the default position it sits in the window of an envelope. Elsewhere it no longer fits the window.",
  "Absender in kleiner Schrift darüber": "Sender in small print above",
  "Nummer, Datum, Leistungszeitraum und weitere Angaben. Sie stehen immer auf der Rechnung.": "Number, date, service period and other details. They always appear on the invoice.",
  "Ziehen Sie den Titel nach oben oder unten, um zu bestimmen, wo der Inhalt beginnt.": "Drag the title up or down to set where the content starts.",
  "Größe des Titels": "Title size",
  "Nach Stil": "By style",
  "Sehr groß": "Very large",
  "checked disabled": "checked disabled",
  "Spalten und Überschriften": "Columns and headings",
  "Haken: Spalte zeigen. Feld daneben: eigene Überschrift.": "Tick: show column. Field next to it: your own heading.",
  "Ziehen Sie die Tabelle nach oben oder unten, um die Reihenfolge zu ändern.": "Drag the table up or down to change the order.",
  "Stil der Tabelle": "Table style",
  "Farbfläche": "Color fill",
  "Streifen": "Stripes",
  "Raster": "Grid",
  "Kopfzeile in der Farbe": "Header row in the color",
  "sonst bei der Menge": "otherwise with the quantity",
  "bei mehreren Sätzen immer": "always with several rates",
  "Das ist die Vorgabe für neue Rechnungen. Jede Rechnung können Sie einzeln ändern.": "This is the default for new invoices. You can change each invoice individually.",
  "Bankverbindung, Zahlungsziel und Steuerhinweise stehen immer auf der Rechnung.": "Bank details, payment term and tax notes always appear on the invoice.",
  "GiroCode zum Bezahlen mit der Banking-App": "GiroCode for paying with the banking app",
  "Erscheint bei Überweisung, wenn eine gültige IBAN eingetragen ist.": "Appears for bank transfer if a valid IBAN is entered.",
  "Diese Bilder wählen Sie in der Rechnung selbst, etwa Fotos Ihrer Arbeit.": "You choose these images in the invoice itself, such as photos of your work.",
  "Kontakt, Bank und Steuernummer. Ohne Fußzeile setzt Kontovia Steuernummer, Anschrift und Registerangaben an eine andere Stelle, weil sie auf jeder Rechnung stehen müssen.": "Contact, bank and tax number. Without a footer, Kontovia places the tax number, address and register details elsewhere, because they must appear on every invoice.",
  "Fußzeile anzeigen": "Show footer",
  "Einstellungen für die ganze Seite.": "Settings for the whole page.",
  "Seitenränder": "Page margins",
  "Schmal": "Narrow",
  "Breit": "Wide",
  "Falzmarken für den Fensterumschlag": "Fold marks for window envelopes",
  "Hinweis auf die enthaltene E-Rechnung": "Note about the included e-invoice",
  "Hier einfügen": "Insert here",
  "Einfügen:": "Insert:",
  "Bild wählen": "Choose image",
  "Unter Text hellt Kontovia die Fläche bei Bedarf auf, damit der Text lesbar bleibt.": "Under text, Kontovia lightens the area if needed so the text stays readable.",
  "Füllung": "Fill",
  "Rand": "Border",
  "Richtung": "Direction",
  "Waagerecht": "Horizontal",
  "Senkrecht": "Vertical",
  "Stärke": "Thickness",
  "Dünn": "Thin",
  "Dick": "Thick",
  "Sehr dick": "Very thick",
  "Länge (mm)": "Length (mm)",
  "Breite (mm)": "Width (mm)",
  "Höhe (mm)": "Height (mm)",
  "Ziehen verschiebt, das Eck ändert die Größe. Eigene Elemente liegen immer hinter dem Inhalt der Rechnung.": "Dragging moves it, the corner changes the size. Your own elements always lie behind the invoice content.",
  "Hier ist kein Platz: Das Element würde Inhalt der Rechnung berühren und wird deshalb nicht gedruckt. Ziehen Sie es an eine freie Stelle.": "There is no room here: the element would touch the invoice content and is therefore not printed. Drag it to a free spot.",
  "Auf welchen Seiten": "On which pages",
  "[data-e=\"x\"]": "[data-e=\"x\"]",
  "[data-e=\"y\"]": "[data-e=\"y\"]",
  "[data-e=\"b\"]": "[data-e=\"b\"]",
  "[data-e=\"h\"]": "[data-e=\"h\"]",
  "[data-pos=\"x\"]": "[data-pos=\"x\"]",
  "[data-pos=\"y\"]": "[data-pos=\"y\"]",
  ": anklicken zum Ändern": ": click to change",
  ", ziehen zum Verschieben": ", drag to move",
  "[data-st=\"name\"]": "[data-st=\"name\"]",
  "[data-e=\"text\"]": "[data-e=\"text\"]",
  "[data-p=\"{0}\"]": "[data-p=\"{0}\"]",
  "Akzentfarbe": "Accent color",
  "Schriftfarbe": "Text color",
  "Text direkt ändern (Doppelklick)": "Change text directly (double-click)",
  "Nach oben schieben": "Move up",
  "Nach unten schieben": "Move down",
  "Fußzeile einschalten": "Turn on footer",
  "Fußzeile ausschalten": "Turn off footer",
  "Absenderzeile einschalten": "Turn on sender line",
  "Absenderzeile ausschalten": "Turn off sender line",
  "hier einfügen": "insert here",
  "Seite einrichten": "Page setup",
  "Verschieben und Größe ändern gehen wie bei jedem Teil.": "Moving and resizing work as with any part.",
  "[data-fz=\"{0}\"]": "[data-fz=\"{0}\"]",
  "button[data-wert=\"{0}\" i]": "button[data-wert=\"{0}\" i]",
  "[data-wert-von=\"{0}\"]": "[data-wert-von=\"{0}\"]",
  "[data-wert-von-e=\"{0}\"]": "[data-wert-von-e=\"{0}\"]",
  "[data-d=\"{0}\"]": "[data-d=\"{0}\"]",
  "button, a": "button, a",
  "[data-seg], [data-eseg], [data-rand]": "[data-seg], [data-eseg], [data-rand]",
  "[data-seg=\"{0}\"] [data-wert]": "[data-seg=\"{0}\"] [data-wert]",
  "Logo übernommen": "Logo applied",
  "Briefpapier übernommen": "Letterhead applied",
  "Bild übernommen": "Image applied",
  "Mit „Übernehmen“ gilt es für neue Rechnungen.": "With “Apply” it applies to new invoices.",
  "Rechnungsgestaltung und -angaben geändert": "Invoice design and details changed",
  "Übernommen": "Applied",
  "Gilt für alle Rechnungen, die Sie ab jetzt ausstellen.": "Applies to all invoices you issue from now on.",
  "Freie Gestaltung zurücksetzen?": "Reset free design?",
  "Verschobene Teile kommen an ihre Standardstelle, eigene Texte, Bilder, Flächen und Linien werden entfernt, Reihenfolge, Spalten und Ränder wie am Anfang. Logo, Farben und Ihre Angaben bleiben.": "Moved parts return to their default position, your own texts, images, areas and lines are removed, order, columns and margins as at the start. Logo, colors and your details remain.",
  "Zurücksetzen": "Reset",
  "Als PDF": "As PDF",
  "Drucken": "Print",
  "Auswertung": "Report",
  "[data-tab=\"{0}\"]": "[data-tab=\"{0}\"]",
  "Für ELSTER gelten die Werte ohne sie. Entfernen Sie dafür oben das Häkchen oder nehmen Sie die Unterlagen unter „Import & Export“, die private Buchungen nie enthalten.": "For ELSTER the values without them apply. Remove the tick at the top for this, or use the documents under “Import & export”, which never contain private transactions.",
  "Enthält {0}.": "Includes {0}.",
  "eine private Buchung": "one private transaction",
  "im Schnitt {0} € je Monat": "on average {0} € per month",
  "Anteil": "Share",
  "Keine Einnahmen": "No income",
  "Keine Ausgaben": "No expenses",
  "Aufteilung nach Kategorie": "Breakdown by category",
  "Gemittelt wird über die Monate des Zeitraums, die schon begonnen haben, im laufenden Jahr also nicht über zwölf. Die Tabelle beim Verlauf (Knopf „Tabelle“) zeigt jeden Monat einzeln.": "The average is taken over the months of the period that have already started, so in the current year not over twelve. The table in the trend (button “Table”) shows each month individually.",
  "Ergebnisrechnung": "Income statement",
  "Abschreibungen im Zeitraum": "Depreciation in the period",
  "Wirtschaftsgüter": "assets",
  "Welche Seite": "Which page",
  "Zeitraum hat noch nicht begonnen": "Period has not started yet",
  "Ausgaben, ohne Abschreibung": "Expenses, without depreciation",
  "Bester / schwächster Monat": "Best / weakest month",
  "davon steuerlich abziehbar (nach Kürzung, z. B. Bewirtung 70 %)": "of which tax-deductible (after reduction, e.g. entertainment 70%)",
  "Warum anders?": "Why different?",
  "Nachrichtlich, wirkt sich nicht auf den Gewinn aus:": "For information, does not affect profit:",
  "Umsatzsteuer-Verrechnung mit dem Finanzamt (kein Aufwand, sondern Ausgleich des Steuerkontos):": "VAT settlement with the tax office (not an expense, but balancing of the tax account):",
  "im Zeitraum an das Finanzamt gezahlt": "paid to the tax office in the period",
  "vom Finanzamt erstattet": "refunded by the tax office",
  "mehr gezahlt, als im Zeitraum angefallen ist (etwa für den Vorzeitraum)": "paid more than arose in the period (e.g. for the previous period)",
  "danach noch offene Zahllast des Zeitraums": "VAT still payable for the period afterwards",
  "Von jedem eingenommenen Euro bleiben {0} Cent als Gewinn übrig.": "Of every euro earned, {0} cents remain as profit.",
  "Hinweise zur Datenqualität": "Notes on data quality",
  "Buchungen:": "Transactions:",
  "· Ein Klick auf eine Zeile öffnet die Buchung.": "· A click on a row opens the transaction.",
  "In diesen Buchungen suchen …": "Search these transactions …",
  "Keine Buchungen": "No transactions",
  "Summe ({0})": "Total ({0})",
  "abziehbarer Teil · nicht abziehbar {0} € (im Formular linke Spalte)": "deductible part · not deductible {0} € (left column in the form)",
  "Ihre Buchungen, zusammengefasst nach den Zeilen der amtlichen Anlage EÜR (Vordruck {0}), immer nach Zahlungsfluss (§ 11 EStG). Sie können die Beträge direkt in „Mein ELSTER“ übertragen. Die Zeilennummern des Formulars ändern sich fast jährlich. Bitte einmal gegen das Formular des jeweiligen Jahres prüfen. Die Zuordnung jeder Kategorie lässt sich unter Stammdaten anpassen.": "Your transactions, grouped by the lines of the official Anlage EÜR (form {0}), always by cash flow (§ 11 EStG). You can transfer the amounts directly into “Mein ELSTER”. The line numbers of the form change almost every year. Please check once against the form for the respective year. The assignment of each category can be adjusted under Master data.",
  "Was Sie hier sehen.": "What you see here.",
  "Zeile {0} · {1} vor Korrekturen (Zeilen {2} bis {3})": "Line {0} · {1} before corrections (lines {2} to {3})",
  "Zuflussprinzip § 11 EStG": "Cash principle § 11 EStG",
  "Für {0} ist in dieser Fassung noch kein eigener Vordruck hinterlegt. Die Zeilennummern folgen dem Vordruck {1}. Bitte gegen das Formular {2} prüfen.": "No separate form for {0} is stored in this version yet. The line numbers follow form {1}. Please check against form {2}.",
  "Sie stehen vorläufig in Zeile {0} (Einnahmen) bzw. {1} (Ausgaben). Ordnen Sie sie einer Kategorie zu, bevor Sie die Zahlen übernehmen.": "They are temporarily in line {0} (income) or {1} (expenses). Assign them to a category before you use the figures.",
  "Buchungen zeigen": "Show transactions",
  "Eine Buchung": "One transaction",
  ": {0} im Jahr, zu dem sie gehören, nicht im Jahr der Zahlung (10-Tage-Regel, § 11 EStG). Das gilt etwa für die Umsatzsteuer-Vorauszahlung für Dezember, gezahlt bis zum 10. Januar.": ": {0} in the year they belong to, not in the year of payment (10-day rule, § 11 EStG). This applies, for example, to the VAT advance payment for December, paid by 10 January.",
  ", bezahlt am": ", paid on",
  "Diese regelmäßige Zahlung zählt": "This regular payment counts",
  "Diese regelmäßigen Zahlungen zählen": "These regular payments count",
  "Warum weicht das vom Gewinn in der GuV ab?": "Why does this differ from the profit in the P&L?",
  "In der Einnahmen-Überschuss-Rechnung läuft die Umsatzsteuer als Betriebseinnahme und Betriebsausgabe mit. Die vereinnahmte Umsatzsteuer erhöht den EÜR-Gewinn so lange, bis Sie sie an das Finanzamt überweisen und diese Zahlung als Ausgabe erfassen. Über die Jahre gleicht sich das aus. Die Umsatzsteuer kostet Sie keinen Cent Gewinn.": "In the cash-basis income statement, VAT is included as business income and business expense. The VAT collected increases the EÜR profit until you transfer it to the tax office and record this payment as an expense. Over the years this evens out. VAT does not cost you a cent of profit.",
  "Ergebnis ohne Umsatzsteuer (wie in der Gewinn- und Verlustrechnung)": "Result without VAT (as in the profit and loss statement)",
  "+ vereinnahmte Umsatzsteuer (Zeile {0})": "+ VAT collected (line {0})",
  "− gezahlte Vorsteuer (Zeile {0})": "− input VAT paid (line {0})",
  "− an das Finanzamt gezahlte Umsatzsteuer (Zeile {0})": "− VAT paid to the tax office (line {0})",
  "Gewinn laut Anlage EÜR (Zeile {0})": "Profit according to Anlage EÜR (line {0})",
  "+ Erstattung vom Finanzamt (Zeile {0})": "+ refund from the tax office (line {0})",
  "Sie haben im Zeitraum noch keine Umsatzsteuer-Vorauszahlung als Ausgabe erfasst. Sobald Sie an das Finanzamt überweisen, buchen Sie das mit der Kategorie „An Finanzamt gezahlte Umsatzsteuer“. Dann stimmt der EÜR-Gewinn.": "You have not yet recorded a VAT advance payment as an expense in the period. As soon as you transfer to the tax office, book it with the category “VAT paid to the tax office”. Then the EÜR profit is correct.",
  "Kennzahlen der Voranmeldung": "VAT return boxes",
  "Voranmeldungszeiträume": "VAT return periods",
  "Jahr gesamt": "Whole year",
  "Zeitraum anklicken, um ihn oben als Auswertungszeitraum zu übernehmen. Die Voranmeldung ist bis zum 10. Tag nach Ablauf des Zeitraums zu übermitteln{0}; die Termine stehen auch in Übersicht und Kalender.": "Click a period to use it as the report period at the top. The VAT return must be submitted by the 10th day after the end of the period{0}; the dates also appear on the overview and in the calendar.",
  "In diesem Zeitraum waren Sie Kleinunternehmer und geben keine Voranmeldung ab.": "In this period you were a small business and do not file a VAT return.",
  "Ohne Kategorie ist nicht klar, ob Umsatzsteuer anfällt; ohne Steuersatz fehlen sie in den Kennzahlen. Ordnen Sie sie zu, bevor Sie die Voranmeldung abgeben.": "Without a category it is unclear whether VAT is due; without a tax rate they are missing from the boxes. Assign them before you file the VAT return.",
  "Zahllast (Kennzahl 83)": "VAT payable (box 83)",
  "Erstattung (Kennzahl 83)": "Refund (box 83)",
  "vom Finanzamt zu erstatten": "to be refunded by the tax office",
  "darauf Umsatzsteuer": "VAT on this",
  "Steuer dazu": "Tax on this",
  "Nicht steuerbare sonstige Leistungen (§ 18b)": "Non-taxable other services (§ 18b)",
  "Nicht steuerbare Leistungen an Unternehmen außerhalb der EU": "Non-taxable services to businesses outside the EU",
  "Umsätze, für die der Kunde die Steuer schuldet (§ 13b)": "Sales for which the customer owes the tax (§ 13b)",
  "Leistungen aus der EU nach § 13b": "Services from the EU under § 13b",
  "Steuer darauf": "Tax on this",
  "Andere Leistungen nach § 13b": "Other services under § 13b",
  "Vorsteuer aus i.g. Erwerben": "Input VAT from intra-community acquisitions",
  "Vorsteuer nach § 13b": "Input VAT under § 13b",
  "Abzug der Sondervorauszahlung": "Deduction of the special advance payment",
  "Davon Forderungsausfall (in den Umsätzen enthalten, in ELSTER von Hand eintragen)": "Of which bad debt (included in sales, enter manually in ELSTER)",
  "Verbleibende Vorauszahlung": "Remaining advance payment",
  "Verbleibender Überschuss": "Remaining surplus",
  ", mit Dauerfristverlängerung einen Monat später": ", with permanent extension one month later",
  "Bei einer Einnahmen-Überschuss-Rechnung besteht keine Bilanzierungspflicht. Diese Gegenüberstellung zeigt trotzdem, was dem Betrieb zum Stichtag gehört und was er schuldet. Die Differenz ist Ihr Reinvermögen. Sie folgt nicht der Gliederung des § 266 HGB.": "With a cash-basis income statement there is no obligation to prepare a balance sheet. This comparison still shows what the business owns and owes on the reporting date. The difference is your net assets. It does not follow the structure of § 266 HGB.",
  "Vermögensübersicht statt Bilanz.": "Statement of assets instead of a balance sheet.",
  "Schulden und Reinvermögen": "Liabilities and net assets",
  "am längsten fällig zuerst": "longest due first",
  "zuletzt fällig zuerst": "most recently due first",
  "Tage über": "days over",
  "Alle offenen": "All open",
  "Nur überfällige": "Overdue only",
  "Nur im Zahlungsziel": "Within payment term only",
  "Summe der angezeigten ({0})": "Total of displayed ({0})",
  "1–30 Tage": "1–30 days",
  "31–60 Tage": "31–60 days",
  "61–90 Tage": "61–90 days",
  "über 90 Tage": "over 90 days",
  "Forderungen gegen Kunden": "Receivables from customers",
  "Rechnungen, davon {0} überfällig": "invoices, of which {0} overdue",
  "Eigene Verbindlichkeiten": "Own payables",
  "Altersstruktur Forderungen": "Ageing of receivables",
  "Altersstruktur Verbindlichkeiten": "Ageing of payables",
  "Forderungen: Kunden schulden Ihnen Geld": "Receivables: customers owe you money",
  "Verbindlichkeiten: Sie schulden noch Geld": "Payables: you still owe money",
  "Zufluss {0} € · Abfluss {1} €": "Inflow {0} € · outflow {1} €",
  "Legen Sie unter Stammdaten ein Bankkonto an.": "Create a bank account under Master data.",
  "Ins Privatvermögen entnommen": "Withdrawn to private assets",
  "Verschrottet": "Scrapped",
  "§ 4 Abs. 3 Satz 5 EStG": "§ 4 (3) sentence 5 EStG",
  "Anschaffungskosten gesamt": "Total acquisition cost",
  "Abschreibung im Zeitraum": "Depreciation in the period",
  "Restbuchwert am Stichtag": "Residual book value on the reporting date",
  "am {0}, Restbuchwert {1} €": "on {0}, residual book value {1} €",
  "Ausgeschieden": "Disposed",
  "Anschaffungen über 800 € netto tragen Sie beim Erfassen der Ausgabe als Anlagegut ein.": "Enter purchases over €800 net as a fixed asset when recording the expense.",
  "Enthält {0} private Buchung{1}.": "Includes {0} private transaction{1}.",
  "Diese Aufstellung ist nur für den eigenen Gebrauch; für das Finanzamt gelten die Werte ohne sie.": "This statement is only for your own use; for the tax office the values without them apply.",
  "PDF konnte nicht erstellt werden": "PDF could not be created",
  "Firma & Steuern": "Company & taxes",
  "Firmendaten, Steuer, Mahnwesen, Festschreibung": "Company details, taxes, dunning, period lock",
  "Sicherheit & Zugang": "Security & access",
  "Sperre, Geräte, Benutzer, Konten": "Lock, devices, users, accounts",
  "Daten & Cloud": "Data & cloud",
  "Sicherung, Speicherort, Abgleich, Kalender": "Backup, storage location, sync, calendar",
  "Darstellung & Update": "Display & updates",
  "Erscheinungsbild, Start, Programmfassung": "Appearance, start, program version",
  "Firmendaten, Steuer, Sicherheit und Darstellung gelten erst nach dem Übernehmen.": "Company details, taxes, security and display only apply after applying.",
  "Jetzt sichern": "Back up now",
  "Bereiche der Einstellungen": "Settings sections",
  "Firmendaten": "Company details",
  "erscheinen im Kopf jedes Berichts": "appear in the header of every report",
  "Firma": "Company",
  "Bankverbindung, Handelsregister und Website für Ihre Rechnungen stehen unter {0}.": "Bank details, commercial register and website for your invoices are under {0}.",
  "Rechnungen → Gestaltung": "Invoices → Design",
  "Bei einem Wechsel fragt Kontovia, ab wann er gilt. Frühere Zeiträume bleiben, wie sie waren.": "When you change it, Kontovia asks from when it applies. Earlier periods stay as they were.",
  "Zahlungseingang (Ist-Versteuerung, § 20 UStG)": "Payment received (cash basis, § 20 UStG)",
  "Rechnungsdatum (Soll-Versteuerung)": "Invoice date (accrual basis)",
  "Gilt für die Voranmeldung und die Umsatzsteuer-Angaben in der Übersicht. Einnahmen, Ausgaben und Gewinn zählen überall am Zahlungstag, wie in der Anlage EÜR (§ 11 EStG).": "Applies to the VAT return and the VAT figures on the overview. Income, expenses and profit always count on the payment date, as in the Anlage EÜR (§ 11 EStG).",
  "Abgabe der Voranmeldung": "Filing the VAT return",
  "mit Dauerfristverlängerung (+1 Monat)": "with permanent extension (+1 month)",
  "Für die Steuertermine in Übersicht und Kalender. Die Dauerfristverlängerung beantragen Sie beim Finanzamt (§ 46 UStDV).": "For the tax deadlines on the overview and in the calendar. You apply for the permanent extension at the tax office (§ 46 UStDV).",
  "Kontenrahmen": "Chart of accounts",
  "Erstes Buchungsjahr": "First booking year",
  "Nur zur Orientierung. Die Auswertungen richten sich nach dem jeweils gewählten Zeitraum.": "For orientation only. The reports follow the selected period.",
  "Beginn der Tätigkeit": "Start of business",
  "Für Kleinunternehmer: Im ersten Jahr gilt die Grenze von 25.000 € schon im laufenden Jahr.": "For small businesses: in the first year the €25,000 limit already applies in the current year.",
  "Wird in der Voranmeldung für Dezember abgezogen (Kennzahl 39). Ein Elftel der Vorauszahlungen des Vorjahres, wie vom Finanzamt festgesetzt.": "Deducted in the VAT return for December (box 39). One eleventh of the previous year's advance payments, as assessed by the tax office.",
  "Weitere Steuertermine in Übersicht und Kalender": "More tax deadlines on the overview and in the calendar",
  "Einkommensteuer-Vorauszahlungen (10. März, Juni, September, Dezember)": "Income tax prepayments (10 March, June, September, December)",
  "Gewerbesteuer-Vorauszahlungen (15. Februar, Mai, August, November)": "Trade tax prepayments (15 February, May, August, November)",
  "Für Lieferungen und Leistungen an Unternehmen in anderen EU-Ländern, fällig am 25. nach dem Zeitraum.": "For supplies and services to businesses in other EU countries, due on the 25th after the period.",
  "Unveränderbarkeit und Festschreibung": "Immutability and period lock",
  "Buchungen festschreiben bis einschließlich": "Lock transactions up to and including",
  "Festgeschriebene Buchungen lassen sich nicht mehr ändern oder löschen, sondern nur noch stornieren. Das ist der übliche Umgang mit einem abgeschlossenen und ans Finanzamt gemeldeten Zeitraum. Noch offene Rechnungen daraus lassen sich weiterhin als bezahlt vermerken.": "Locked transactions can no longer be changed or deleted, only reversed. This is the usual way of handling a period that is closed and reported to the tax office. Open invoices from it can still be marked as paid.",
  "Jede Änderung landet im Änderungsjournal. Die Einträge sind über Prüfsummen miteinander verkettet. Wird nachträglich etwas verändert, passen sie nicht mehr zusammen. Kontovia löscht keinen Eintrag; ältere liegen im Archiv und gehen in jede Sicherung und jeden Export fürs Finanzamt mit.": "Every change goes into the change log. The entries are chained together via checksums. If something is changed afterwards, they no longer fit together. Kontovia does not delete any entry; older ones are in the archive and are included in every backup and every export for the tax office.",
  "Journal prüfen": "Check log",
  "Journal ansehen ({0})": "View log ({0})",
  "Automatisch sperren nach": "Lock automatically after",
  "Nach dem Ruhezustand des Geräts und nach drei Minuten im Hintergrund sperrt Kontovia zusätzlich sofort.": "After the device sleeps and after three minutes in the background, Kontovia also locks immediately.",
  "Passwort ändern": "Change password",
  "Jetzt sperren": "Lock now",
  "Die gesamte Buchhaltung ist mit Ihrem Passwort verschlüsselt (AES-256). Das Entschlüsseln ist bewusst aufwendig, damit niemand Passwörter in großer Zahl durchprobieren kann. Belege werden einzeln verschlüsselt und tragen auf der Festplatte keine sprechenden Namen. Eine Wiederherstellung ohne Passwort gibt es nicht, außer über Wege, die Sie selbst einschalten: Fingerabdruck oder Gesicht (unten) und „Mit Google entsperren“ (unter Daten & Cloud, ein großes Sicherheitsrisiko). Der freiwillige Cloud-Abgleich überträgt ausschließlich die bereits verschlüsselte Buchhaltung.": "Your entire accounting is encrypted with your password (AES-256). Decryption is deliberately costly so that nobody can try out passwords in large numbers. Receipts are encrypted individually and do not carry meaningful names on the disk. There is no recovery without the password, except via methods you turn on yourself: fingerprint or face (below) and “Unlock with Google” (under Data & cloud, a major security risk). The optional cloud sync only transmits the already encrypted accounting.",
  "Wie Ihre Daten geschützt sind.": "How your data is protected.",
  "Sicherung und Speicherort": "Backup and storage location",
  "Vollsicherung erstellen": "Create full backup",
  "Sicherung wiederherstellen": "Restore backup",
  "Die Vollsicherung enthält alle Buchungen {0} alle Belege in einer Datei, verschlüsselt mit einem Passwort Ihrer Wahl. Bewahren Sie sie an einem anderen Ort auf als den Arbeitsrechner. Eine defekte Festplatte nimmt sonst beides mit.": "The full backup contains all transactions {0} all receipts in one file, encrypted with a password of your choice. Keep it in a different place than the work computer. Otherwise a broken hard drive takes both with it.",
  "Kontovia legt beim Speichern höchstens alle 30 Minuten eine Sicherung ab und hält die letzten 25 vor. Der Stand vor dem Wechsel auf die neue Datenbank (Version 2.26) bleibt dauerhaft.": "When saving, Kontovia creates a backup at most every 30 minutes and keeps the last 25. The version before switching to the new database (version 2.26) stays permanently.",
  "Nicht mehr benötigte Belegdateien löschen": "Delete receipt files that are no longer needed",
  "Wirkt sofort. Schneller geht es mit dem Umschalter links unten in der Seitenleiste.": "Takes effect immediately. It is quicker with the toggle at the bottom left of the sidebar.",
  "Sprache": "Language",
  "Wirkt sofort und gilt für dieses Gerät. Rechnungen haben eine eigene Sprache.": "Takes effect immediately and applies to this device. Invoices have their own language.",
  "Ansicht beim Start": "View at start",
  "Einstellungen übernehmen": "Apply settings",
  "Festgeschrieben bis {0}.": "Locked until {0}.",
  "Bisher ist nichts festgeschrieben.": "Nothing is locked so far.",
  "nie (nicht empfohlen)": "never (not recommended)",
  "Minuten Inaktivität": "minutes of inactivity",
  "Dateien ·": "files ·",
  "Automatische Sicherungen": "Automatic backups",
  "Vor dem Löschen geschützt": "Protected from deletion",
};
