/** Wörterbuch Englisch, Teil t16. Quellen: views/settings.js, views/spruenge.js, views/todos.js, views/transactions.js. */

export default {
  "nein, der Browser darf bei Platzmangel löschen": "no, the browser may delete it when space runs low",
  "Neueste: {0}.": "Newest: {0}.",
  "Sicherungen auf diesem Gerät": "Backups on this device",
  "Anzeigen": "Show",
  "nach oben": "up",
  "nach unten": "down",
  "Seitenleiste": "Sidebar",
  "gilt für dieses Gerät": "applies to this device",
  "Blenden Sie Bereiche aus, die Sie nicht brauchen, und ordnen Sie die übrigen an. In der Seitenleiste selbst geht das auch per Rechtsklick; mit der Maus lassen sich Einträge nach kurzem Halten verschieben. Ausgeblendete Bereiche finden Sie weiterhin über die Suche.": "Hide sections you don't need and arrange the rest. In the sidebar itself this also works with a right-click; with the mouse, entries can be moved after a short hold. You can still find hidden sections via search.",
  "[data-an=\"{0}\"]": "[data-an=\"{0}\"]",
  "[data-schieb=\"{0}\"][data-id=\"{1}\"]": "[data-schieb=\"{0}\"][data-id=\"{1}\"]",
  "Seitenleiste zurückgesetzt": "Sidebar reset",
  "noch nicht übernommen.": "not applied yet.",
  "Eine Änderung ist": "One change is",
  "Änderungen sind": "changes are",
  "Einstellungen übernehmen?": "Apply settings?",
  "in den Einstellungen {0} noch nicht übernommen.": "in the settings {0} not applied yet.",
  "Eine Änderung": "One change",
  "Änderungen": "changes",
  "Eine Bildschirmsperre kann dieser Browser nicht melden. Dafür gelten die Sperre nach Inaktivität, nach dem Ruhezustand und nach drei Minuten im Hintergrund.": "This browser cannot report a screen lock. Instead, locking after inactivity, after sleep and after three minutes in the background applies.",
  "Auch sperren, sobald der Bildschirm gesperrt wird": "Also lock as soon as the screen is locked",
  "Gilt für diesen Browser. Er fragt dafür einmal, ob Kontovia erkennen darf, wann das Gerät benutzt wird.": "Applies to this browser. It asks once whether Kontovia may detect when the device is in use.",
  "Die Erlaubnis wurde verweigert; sie lässt sich in den Website-Einstellungen des Browsers geben.": "Permission was denied; it can be granted in the browser's site settings.",
  "Sperre bei Bildschirmsperre an": "Lock on screen lock on",
  "Sperre bei Bildschirmsperre aus": "Lock on screen lock off",
  "Nicht eingeschaltet": "Not turned on",
  "nach Zahlungseingang": "by payment received",
  "nach Rechnungsdatum": "by invoice date",
  "Bisherige Stände": "Previous states",
  "Ab wann gilt die Änderung?": "From when does the change apply?",
  "Bisher: {0}.{1}Neu: {2}.": "Previously: {0}.{1}New: {2}.",
  "Ab einem Tag, frühere Zeiträume bleiben": "From a certain day, earlier periods stay",
  "Gilt ab": "Applies from",
  "Wer die Kleinunternehmerregelung nach einem Jahr über 25.000 € verlässt, stellt zum 1. Januar um. Wird im laufenden Jahr die Grenze von 100.000 € überschritten, gilt der Tag des Umsatzes.": "If you leave the small business rule after a year over €25,000, switch on 1 January. If the €100,000 limit is exceeded during the current year, the day of the sale applies.",
  "Für alle Zeiträume (die bisherige Angabe war falsch)": "For all periods (the previous setting was wrong)",
  "Bis {0} ist festgeschrieben; davor lässt sich nichts mehr ändern.": "Locked until {0}; nothing before that can be changed.",
  "Bitte ein Datum wählen": "Please choose a date",
  "Bis {0} lässt sich nichts mehr ändern. Bitte ein späteres Datum wählen.": "Nothing can be changed up to {0}. Please choose a later date.",
  "Einstellungen geändert, Steuer": "Settings changed, tax",
  "für alle Zeiträume": "for all periods",
  "Einstellungen geändert": "Settings changed",
  "Einstellungen übernommen": "Settings applied",
  "Tresor, Belege und Sicherungen stehen dort als Dateien, verschlüsselt wie immer. Sichern Sie den Ordner mit Ihren übrigen Dateien.": "Vault, receipts and backups are stored there as files, encrypted as always. Back up the folder with your other files.",
  "Ihre Buchhaltung liegt im Ordner „{0}“ auf diesem Gerät.": "Your accounting is in the folder “{0}” on this device.",
  "Zurück in den Browser …": "Back to the browser …",
  "Sicherer liegt sie in einem Ordner auf diesem Gerät: Dort sehen Sie die Dateien und sichern sie mit Ihren übrigen Dateien.": "It is safer in a folder on this device: there you see the files and back them up with your other files.",
  "Ihre Buchhaltung liegt im Speicher dieses Browsers.": "Your accounting is in this browser's storage.",
  "In einen Ordner verschieben …": "Move to a folder …",
  "Der Browser hat zugesagt, ihn nicht von selbst zu leeren.": "The browser has promised not to clear it by itself.",
  "Den darf der Browser bei Platzmangel löschen.": "The browser may delete it when space runs low.",
  ", und den darf der Browser bei Platzmangel löschen. Schalten Sie deshalb die Cloud-Sicherung ein oder legen Sie regelmäßig eine Vollsicherung an. In Chrome oder Edge lässt sich die Buchhaltung stattdessen in einem Ordner auf dem Gerät speichern.": ", and the browser may delete it when space runs low. So turn on cloud backup or create a full backup regularly. In Chrome or Edge the accounting can instead be saved in a folder on the device.",
  "Ihre Buchhaltung liegt im Speicher dieses Browsers": "Your accounting is in this browser's storage",
  "Kopiere …": "Copying …",
  "von {0} Dateien kopiert und geprüft": "of {0} files copied and checked",
  "Dort liegt schon eine Buchhaltung": "There is already an accounting there",
  "Im Ordner „{0}“ liegt bereits eine Kontovia-Buchhaltung. Wählen Sie einen anderen Ordner.": "The folder “{0}” already contains a Kontovia accounting. Choose a different folder.",
  "In den Ordner verschieben?": "Move to the folder?",
  "Kontovia kopiert Ihre Buchhaltung samt Belegen und Sicherungen nach „{0}“, liest jede Datei zur Kontrolle zurück und löscht erst danach den Speicher im Browser. Ab dann arbeitet Kontovia in diesem Ordner. Nach einem Neustart des Browsers fragt er einmal, ob Kontovia wieder darauf zugreifen darf.": "Kontovia copies your accounting including receipts and backups to “{0}”, reads back every file to check it and only then deletes the browser storage. From then on Kontovia works in this folder. After a browser restart it asks once whether Kontovia may access it again.",
  "Verschieben": "Move",
  "Buchhaltung wird verschoben": "Moving accounting",
  "Buchhaltung verschoben": "Accounting moved",
  "Dateien liegen jetzt in „{0}“.": "files are now in “{0}”.",
  "Nicht verschoben": "Not moved",
  "Ihre Buchhaltung liegt unverändert im Browser.": "Your accounting is unchanged in the browser.",
  "Zurück in den Browser?": "Back to the browser?",
  "Kontovia kopiert die Buchhaltung aus dem Ordner „{0}“ in den Speicher dieses Browsers und prüft jede Datei.": "Kontovia copies the accounting from the folder “{0}” into this browser's storage and checks every file.",
  "Kontovia kopiert die Buchhaltung aus dem Ordner „{0}“ in den Speicher dieses Browsers und prüft jede Datei. Die Dateien im Ordner bleiben liegen. Arbeiten Sie danach nicht mehr mit ihnen, sonst gibt es zwei Stände; löschen Sie den Ordner, wenn Sie ihn nicht mehr brauchen.": "Kontovia copies the accounting from the folder “{0}” into this browser's storage and checks every file. The files in the folder stay. Do not work with them afterwards, otherwise there will be two versions; delete the folder when you no longer need it.",
  "Zurück in den Browser": "Back to the browser",
  "Buchhaltung wird zurückgeholt": "Bringing back accounting",
  "Buchhaltung im Browser": "Accounting in the browser",
  "Dateien kopiert. Der Ordner „{0}“ wird nicht mehr verwendet.": "files copied. The folder “{0}” is no longer used.",
  "Nicht zurückgeholt": "Not brought back",
  "Ihre Buchhaltung liegt unverändert im Ordner.": "Your accounting is unchanged in the folder.",
  "Steuertermine eingestellt": "Tax deadlines set",
  "Zuerst zur Sicherheit das aktuelle Passwort.": "First, for security, the current password.",
  "Aktuelles Passwort": "Current password",
  "Neues Passwort": "New password",
  "Mindestens 10 Zeichen. Es gibt keine Wiederherstellung, notieren Sie es deshalb an einem sicheren Ort.": "At least 10 characters. There is no recovery, so write it down in a safe place.",
  "Passwort geändert": "Password changed",
  "Die Tresordatei wurde mit dem neuen Passwort neu verschlüsselt.": "The vault file was re-encrypted with the new password.",
  "Passwort nicht geändert": "Password not changed",
  "Sicherung wiederherstellen?": "Restore backup?",
  "Der aktuelle Datenbestand wird vollständig durch den Inhalt der Sicherung ersetzt. Erstellen Sie vorher eine Sicherung des jetzigen Standes, wenn Sie ihn behalten wollen. Ist der Cloud-Abgleich eingerichtet, gilt der wiederhergestellte Stand beim nächsten Abgleich auch für Ihre anderen Geräte: Was nach der Sicherung angelegt und schon abgeglichen wurde, verschwindet dann auch dort. Die Verbindungen dieses Geräts (Cloud, Google Kalender) bleiben bestehen.": "The current data will be completely replaced by the content of the backup. Create a backup of the current state first if you want to keep it. If cloud sync is set up, the restored state also applies to your other devices at the next sync: anything created after the backup and already synced then disappears there too. This device's connections (cloud, Google Calendar) remain.",
  "Weiter zur Auswahl": "Continue to selection",
  "Passwort der Sicherung": "Backup password",
  "Vollsicherung eingespielt ({0} Buchungen, {1} Belege)": "Full backup restored ({0} transactions, {1} receipts)",
  "Sicherung eingespielt": "Backup restored",
  "Buchungen, {0} Belege": "transactions, {0} receipts",
  "Nicht mehr benötigte Belegdateien löschen?": "Delete receipt files that are no longer needed?",
  "Entfernt werden nur Dateien, die zu keiner Buchung mehr gehören. {0} verknüpfte Belege bleiben unangetastet.": "Only files that no longer belong to any transaction are removed. {0} linked receipts stay untouched.",
  "nicht mehr benötigte Dateien gelöscht": "files no longer needed deleted",
  "Nichts zu löschen": "Nothing to delete",
  "Datum liegt in der Zukunft": "Date is in the future",
  "Festschreiben lässt sich nur ein Zeitraum, der schon vorbei ist, höchstens bis heute.": "Only a period that is already over can be locked, at most up to today.",
  "Schon festgeschrieben": "Already locked",
  "Bis zum {0} ist bereits festgeschrieben. Wählen Sie ein späteres Datum.": "It is already locked up to {0}. Choose a later date.",
  "Buchungen bis zum {0} lassen sich danach nicht mehr ändern oder löschen, nur noch stornieren. Offene Rechnungen lassen sich weiterhin als bezahlt vermerken. Das Festschreiben lässt sich nicht zurücknehmen.": "Transactions up to {0} can then no longer be changed or deleted, only reversed. Open invoices can still be marked as paid. The period lock cannot be undone.",
  "Festgeschrieben bis {0} ({1} Buchungen)": "Locked until {0} ({1} transactions)",
  "Die Prüfsummenkette ist unversehrt. {0} Einträge geprüft.": "The checksum chain is intact. {0} entries checked.",
  "Die Kette bricht bei Eintrag Nr. {0}. Der Datenbestand wurde außerhalb von Kontovia verändert.": "The chain breaks at entry no. {0}. The data was changed outside Kontovia.",
  "Die Sicherung enthält alle Buchungen und Belege. Wählen Sie ein Passwort. Sie können dasselbe wie für den Tresor nehmen oder ein eigenes.": "The backup contains all transactions and receipts. Choose a password. You can use the same one as for the vault or a separate one.",
  "Passwort für die Sicherung": "Password for the backup",
  "Sicherung erstellen": "Create backup",
  "Sicherung wird erstellt …": "Creating backup …",
  "Bei vielen Belegen kann das einen Moment dauern.": "With many receipts this can take a moment.",
  "Sicherung erstellt": "Backup created",
  "geändert": "changed",
  "Update-Suche geändert": "Update check changed",
  "Darstellung geändert": "Display changed",
  "Kalender-Abgleich eingestellt": "Calendar sync set up",
  "DATEV-Angaben geändert": "DATEV details changed",
  "Vollsicherung eingespielt": "Full backup restored",
  "Cloud-Sicherung wiederhergestellt": "Cloud backup restored",
  "Kalenderabgleich": "Calendar sync",
  "Belege aufgeräumt": "Receipts cleaned up",
  "Rückmeldung geändert": "Feedback changed",
  "Wiederkehrende Buchungen angelegt": "Recurring transactions created",
  "Vorführdaten ergänzt": "Demo data added",
  "Nutzungsbedingungen zugestimmt": "Terms of use agreed",
  "Stand vor Version 2.26 (bleibt immer)": "Version before 2.26 (kept forever)",
  "vor dem Übernehmen aus der Cloud": "before taking over from the cloud",
  "Eine Sicherung ersetzt beim Zurückholen den Bestand. Der jetzige Stand wird vorher als Sicherung abgelegt, die Verbindungen dieses Geräts bleiben. Mit Cloud bringt der nächste Abgleich den Stand zu Ihren anderen Geräten.": "When restored, a backup replaces the data. The current state is stored as a backup first, and this device's connections remain. With the cloud, the next sync brings the state to your other devices.",
  "Zurückholen": "Restore",
  "Stand vom {0} zurückholen?": "Restore the state of {0}?",
  "Der Bestand wird durch diese Sicherung ersetzt. Was danach angelegt oder geändert wurde, ist dann auf dem Stand der Sicherung. Der jetzige Stand wird vorher als Sicherung abgelegt.": "The data will be replaced by this backup. Anything created or changed after it will then be at the backup's state. The current state is stored as a backup first.",
  "Stand der Sicherung vom {0} auf diesem Gerät zurückgeholt": "Backup of {0} restored on this device",
  "Sicherung zurückgeholt": "Backup restored",
  "Buchungen.": "transactions.",
  "Zurückholen fehlgeschlagen": "Restore failed",
  "Änderungsjournal": "Change log",
  "Die letzten {0} von {1} Einträgen. Jeder Eintrag enthält die Prüfsumme des vorherigen. So lässt sich nachträgliches Verändern erkennen. Kein Eintrag wird gelöscht; alle stehen in der Datenträgerüberlassung (Import und Export).": "The last {0} of {1} entries. Each entry contains the checksum of the previous one. This makes later changes detectable. No entry is deleted; all are included in the data transfer (import and export).",
  "Vorgang, Benutzer oder Beschreibung suchen …": "Search action, user or description …",
  "Nr.": "No.",
  "small nowrap": "small nowrap",
  "Prüfsumme": "Checksum",
  "tiny muted": "tiny muted",
  "Alle Vorgänge": "All actions",
  "Noch keine Einträge": "No entries yet",
  "Alle ansehen": "View all",
  "überfällig seit": "overdue since",
  ". Abhaken setzt sie auf den": ". Ticking it off sets it to",
  "Kein eigenes Datum, es gilt der Termin am": "No date of its own, the appointment applies on",
  "Termin öffnen": "Open appointment",
  "öffnen:": "open:",
  "im Plan": "on track",
  "im Rückstand": "behind",
  "Frist vorbei": "Deadline passed",
  "Hochgerechnet aus dem bisherigen Tempo ({0}{1} pro Tag)": "Projected from the pace so far ({0}{1} per day)",
  "in Verzug": "behind schedule",
  ": fertig am": ": done on",
  "Voraussichtlich fertig am": "Expected to be done on",
  "Aktuellen Stand eintippen und Enter drücken, oder mit den Pfeilen ändern": "Type the current progress and press Enter, or change it with the arrows",
  "von {0} Unteraufgaben erledigt": "of {0} subtasks done",
  "Mit Bild": "With image",
  "Nach dem Abhaken kommt die Aufgabe von selbst wieder": "After ticking it off, the task comes back by itself",
  ", bisher {0}-mal erledigt": ", done {0} times so far",
  "wieder öffnen": "reopen",
  "als geschafft abhaken": "tick off as achieved",
  "als erledigt abhaken": "tick off as done",
  ", nächstes Mal am": ", next time on",
  "Bitte eine Zahl ab 0 eintragen": "Please enter a number from 0",
  "Ziel geschafft": "Goal achieved",
  "[role=\"progressbar\"]": "[role=\"progressbar\"]",
  "[data-open-appt],[data-open-link],.todo-subs,.todo-ziel-zeile": "[data-open-appt],[data-open-link],.todo-subs,.todo-ziel-zeile",
  "Aufgaben dazu": "Related tasks",
  "Zeitraum der Vorschau": "Preview period",
  "menu hz": "menu hz",
  "Vorschau in der Liste": "Preview in the list",
  "Noch keine Aufgaben": "No tasks yet",
  "Mit „Aufgabe“ oben rechts legen Sie die erste an. Aufgaben können Text, Bilder und Unteraufgaben enthalten und lassen sich mit Terminen, Buchungen, Kontakten und Rechnungen verknüpfen.": "With “Task” at the top right you create the first one. Tasks can contain text, images and subtasks and can be linked to appointments, transactions, contacts and invoices.",
  "Keine erledigte Aufgabe passt zur Suche.": "No completed task matches the search.",
  "Noch nichts abgehakt.": "Nothing ticked off yet.",
  "Ohne Datum": "No date",
  "Keine Aufgabe passt zur Suche.": "No task matches the search.",
  "Alles erledigt": "All done",
  "erledigte Aufgaben stehen unter „Erledigt“.": "completed tasks are under “Done”.",
  "Keine offenen Aufgaben.": "No open tasks.",
  "Welche Aufgaben": "Which tasks",
  "Aufgaben durchsuchen …": "Search tasks …",
  "Aufgaben durchsuchen": "Search tasks",
  "Wie weit die Liste vorausschaut": "How far ahead the list looks",
  "Vorschau:": "Preview:",
  "(Serie)": "(series)",
  "Kein Termin": "No appointment",
  "Aufgabe bearbeiten": "Edit task",
  "Aufgabe *": "Task *",
  "z. B. Unterlagen für den Steuerberater zusammenstellen": "e.g. compile documents for the tax advisor",
  "Art der Aufgabe": "Type of task",
  "Wie viel insgesamt?": "How much in total?",
  "Schon geschafft": "Already done",
  "Beginn": "Start",
  "Nach dem Abhaken kommt die Aufgabe am nächsten Termin wieder, die Unteraufgaben sind dann wieder offen.": "After ticking it off, the task comes back on the next date, and the subtasks are open again.",
  "Freiwillig. Ohne Datum gilt der verknüpfte Termin.": "Optional. Without a date, the linked appointment applies.",
  "Gehört zum Termin": "Belongs to appointment",
  "Freiwillig. Die Aufgabe steht dann auch im Termin.": "Optional. The task then also appears in the appointment.",
  "Unteraufgabe hinzufügen und Enter drücken": "Add subtask and press Enter",
  "Neue Unteraufgabe": "New subtask",
  "Buchung, Kontakt oder Rechnung suchen …": "Search transaction, contact or invoice …",
  "Verknüpfung suchen": "Search link",
  "Freiwillig. Die Aufgabe erscheint dann auch bei der Buchung, dem Kontakt oder der Rechnung.": "Optional. The task then also appears with the transaction, the contact or the invoice.",
  "Aufgabe anlegen": "Create task",
  "Eine Menge bis zu einem Tag, zum Beispiel 20 Seiten in 10 Tagen. Kontovia rechnet aus, was pro Tag noch nötig ist.": "A quantity by a certain day, for example 20 pages in 10 days. Kontovia calculates what is still needed per day.",
  "Eine Aufgabe, die immer wieder anfällt, etwa jeden Monat die Umsatzsteuer vorbereiten.": "A task that comes up again and again, for example preparing the VAT every month.",
  "Wählen Sie unten eine Frist, dann rechnet Kontovia mit.": "Choose a deadline below, and Kontovia calculates along.",
  "Plan: {0}{1} pro Tag, {2} {3} lang. {4}.": "Plan: {0}{1} per day, for {2} {3}. {4}.",
  "Frist *": "Deadline *",
  "Nächstes Mal am": "Next time on",
  "Bis dahin soll die ganze Menge geschafft sein.": "The whole quantity should be done by then.",
  "Freiwillig. Ohne Datum gilt der Tag des ersten Abhakens als Start.": "Optional. Without a date, the day of the first tick counts as the start.",
  "Unteraufgabe": "Subtask",
  "Unteraufgabe entfernen": "Remove subtask",
  "Verknüpfung entfernen": "Remove link",
  "Verknüpfen": "Link",
  "Ein Ziel gibt es nicht mehr": "One target no longer exists",
  "Ziele gibt es nicht mehr": "targets no longer exist",
  "Noch nichts zum Verknüpfen vorhanden.": "Nothing to link yet.",
  "Bitte die Aufgabe benennen": "Please name the task",
  "Bitte die Gesamtmenge eintragen": "Please enter the total quantity",
  "Bitte eine Frist wählen": "Please choose a deadline",
  "Der Beginn liegt nach der Frist": "The start is after the deadline",
  "Aufgabe angelegt": "Task created",
  "Aufgabe gespeichert": "Task saved",
  "Aufgabe löschen?": "Delete task?",
  "„{0}“ wird entfernt.": "“{0}” will be removed.",
  "Aufgabe gelöscht": "Task deleted",
  "Regelbesteuert": "Standard-rated",
  "Steuerfrei": "Tax-exempt",
  "Nicht steuerbar (kein Entgelt, etwa Mahngebühren)": "Not taxable (no consideration, e.g. reminder fees)",
  "Innergemeinschaftliche Lieferung": "Intra-community supply",
  "Ausfuhr außerhalb der EU (steuerfrei mit Vorsteuerabzug)": "Export outside the EU (tax-exempt with input tax deduction)",
  "Leistung an Unternehmen außerhalb der EU (nicht steuerbar)": "Service to a business outside the EU (not taxable)",
  "Steuerschuld beim Kunden im Inland (§ 13b, etwa Bauleistungen)": "Reverse charge within Germany (§ 13b, e.g. construction services)",
  "Innergemeinschaftlicher Erwerb": "Intra-community acquisition",
  "Leistung aus dem EU-Ausland (§ 13b, Sie schulden die Steuer)": "Service from another EU country (§ 13b, you owe the tax)",
  "Andere Leistung nach § 13b (aus dem Nicht-EU-Ausland oder Inland)": "Other service under § 13b (from outside the EU or Germany)",
  "Noch offen (ohne Kategorie)": "Still open (no category)",
  "ausgewählte Buchungen": "selected transactions",
  "Umsätze aus einer Datei Ihrer Bank übernehmen": "Import transactions from a file from your bank",
  "Nichts zu drucken": "Nothing to print",
  "Die Liste ist leer. Ändern Sie Zeitraum oder Filter.": "The list is empty. Change the period or filters.",
  "Auszug der Buchungsliste so, wie sie bei Erstellung eingestellt war (Zeitraum, Filter, Suche, Sortierung). Stornierte Buchungen sind durchgestrichen.": "Extract of the transaction list as set up when created (period, filters, search, sorting). Reversed transactions are struck through.",
  "Enthält private Buchungen.": "Contains private transactions.",
  "Diese Liste ist nur für den eigenen Gebrauch; für das Finanzamt gelten die Unterlagen unter „Import & Export“.": "This list is only for your own use; for the tax office, the documents under “Import & export” apply.",
  "tiny muted nowrap": "tiny muted nowrap",
  "small truncate": "small truncate",
  "Offenes zuerst": "Open first",
  "Bezahltes zuerst": "Paid first",
  "Beleg(e)": "Receipt(s)",
  "Auswahl": "Selection",
  "Keine feste Auswahl": "No fixed selection",
  "Im Zeitraum liegt": "In the period",
  "Buchungs- oder Zahlungsdatum": "Booking or payment date",
  "Zahlungen im Zeitraum": "Payments in the period",
  "Buchungsdatum im Zeitraum": "Booking date in the period",
  "Zahlungen zu Buchungen anderer Zeiträume": "Payments for transactions of other periods",
  "Ort der Leistung": "Place of service",
  "Ort:": "Place:",
  "Alle Orte": "All places",
  "Status:": "Status:",
  "Jeder Zahlstatus": "Any payment status",
  "Finanzamt-Unterlagen": "Tax office documents",
  "Alle, auch private": "All, including private",
  "Ohne private": "Without private",
  "Nur private": "Private only",
  "Stornierte Buchungen": "Reversed transactions",
  "Mit Stornos": "With reversals",
  "Einblenden (mit Gegenbuchung)": "Show (with contra entry)",
  "Art der Buchung": "Transaction type",
  "Mit und ohne Beleg": "With and without receipt",
  "Mit Beleg": "With receipt",
  "Ohne Beleg": "Without receipt",
  "Buchungen durchsuchen": "Search transactions",
  "Wählen Sie oben rechts einen anderen Zeitraum.": "Choose a different period at the top right.",
  "Zurück zum laufenden Jahr": "Back to the current year",
  "Erfassen Sie Ihre erste Einnahme oder Ausgabe über den Knopf oben rechts.": "Record your first income or expense with the button at the top right.",
  "Erste Buchung anlegen": "Create first transaction",
  "€ zu erhalten": "€ to receive",
  "€ zu zahlen": "€ to pay",
  "Eingänge und Ausgänge: im Zeitraum bezahlt, nach Zahlungsdatum, brutto": "Incoming and outgoing: paid in the period, by payment date, gross",
  "Eingänge": "Incoming",
  "Ausgänge": "Outgoing",
  "Alle Zahlungen der Liste mit Umsatzsteuer, auch Privatentnahmen und Zahlungen an das Finanzamt. Die Übersicht zeigt dagegen Betriebseinnahmen und Betriebsausgaben ohne Umsatzsteuer, deshalb weichen die Zahlen dort ab.": "All payments in the list including VAT, also private withdrawals and payments to the tax office. The overview, on the other hand, shows business income and business expenses without VAT, so the figures there differ.",
  "brutto, alle Zahlungen": "gross, all payments",
  "Noch nicht bezahlt, zählt erst am Zahlungstag": "Not yet paid, only counts on the payment date",
  "In den Summen enthalten, in den Unterlagen fürs Finanzamt nicht": "Included in the totals, not in the documents for the tax office",
  "Gebucht am {0}, bezahlt am {1}. Zählt im gewählten Zeitraum": "Booked on {0}, paid on {1}. Counts in the selected period",
  "Privat: gehört nicht zum Betrieb und steht nicht in EÜR, Umsatzsteuer, DATEV und den Unterlagen fürs Finanzamt": "Private: does not belong to the business and does not appear in EÜR, VAT, DATEV and the documents for the tax office",
  "Durch eine Gegenbuchung aufgehoben": "Cancelled by a contra entry",
  "Hebt eine stornierte Buchung auf": "Cancels a reversed transaction",
  "Gegenbuchung": "Contra entry",
  "überfällig": "overdue",
  "Als heute bezahlt markieren": "Mark as paid today",
  "Das Zahlungsdatum lässt sich hier nicht mehr nachtragen.": "The payment date can no longer be added here.",
  "Als bezahlt vermerkt": "Recorded as paid",
  "· heute": "· today",
  "Anzahlung {0} % von {1} €": "Down payment {0}% of {1} €",
  "Restbetrag {0} €": "Remaining amount {0} €",
  "Zuletzt verwendet": "Recently used",
  "Alle weiteren": "All others",
  "Weitere Kontakte": "More contacts",
  "Offenen Betrag ausbuchen": "Write off open amount",
  ": {0} € sind offen.": ": {0} € is open.",
  "Skonto oder Nachlass: Der Kunde durfte weniger zahlen": "Early payment discount or reduction: the customer was allowed to pay less",
  "Forderungsausfall: Das Geld ist nicht mehr zu bekommen": "Bad debt: the money can no longer be collected",
  "Am": "On",
  "Umsatzsteuer und Einnahme werden im Zeitraum dieses Tages berichtigt (§ 17 UStG). Die Rechnung gilt danach als erledigt. Zahlt der Kunde doch noch, erfassen Sie die Zahlung als neue Einnahme.": "VAT and income are corrected in the period of this day (§ 17 UStG). The invoice is then considered settled. If the customer pays after all, record the payment as new income.",
  "Ausbuchen": "Write off",
  "Buchung bearbeiten": "Edit transaction",
  "Ausbuchen …": "Write off …",
  "Änderungen speichern": "Save changes",
  "Verschlüsselt gespeichert, höchstens 40 MB je Datei": "Stored encrypted, at most 40 MB per file",
  "Rechnung oder Quittung hierher ziehen oder": "Drag an invoice or receipt here or",
  "Datei auswählen": "choose a file",
  "Beschreibung *": "Description *",
  "Kategorie *": "Category *",
  "Neuen Kontakt anlegen": "Create new contact",
  "Keins": "None",
  "Rechnungs-/Belegnummer": "Invoice / receipt number",
  "14 Tage ab Belegdatum": "14 days from receipt date",
  "+14 Tage": "+14 days",
  "30 Tage ab Belegdatum": "30 days from receipt date",
  "+30 Tage": "+30 days",
  "Eine private Buchung gehört nicht zum Betrieb und steht nicht in EÜR, Umsatzsteuer, DATEV und den Unterlagen fürs Finanzamt": "A private transaction does not belong to the business and does not appear in EÜR, VAT, DATEV and the documents for the tax office",
  "Privat": "Private",
  "(gehört nicht zum Betrieb)": "(does not belong to the business)",
  "Diese Buchung ist privat. Sie gehört nicht zum Betrieb und steht deshalb nicht in den Unterlagen für Finanzamt und Steuerkanzlei (EÜR, Umsatzsteuer, DATEV, Betriebsprüfung). In Übersicht und Auswertungen zählt sie nur mit, wenn dort {0} gesetzt ist. Betriebliche Einnahmen und Ausgaben dürfen nicht als privat gekennzeichnet werden, sie müssen vollständig erklärt werden (§ 146 Abs. 1 AO).": "This transaction is private. It does not belong to the business and therefore does not appear in the documents for the tax office and tax firm (EÜR, VAT, DATEV, tax audit). On the overview and in reports it only counts if {0} is set there. Business income and expenses must not be marked as private; they must be declared in full (§ 146 (1) AO).",
  "Weitere Angaben": "More details",
  "Referenz / Verwendungszweck": "Reference / payment reference",
  "Interne Bemerkung, betrieblicher Anlass bei Bewirtung, …": "Internal note, business occasion for entertainment, …",
  "Diese Buchung liegt im festgeschriebenen Zeitraum (bis {0}). Sie kann nicht mehr geändert, sondern nur noch storniert werden.": "This transaction is in the locked period (until {0}). It can no longer be changed, only reversed.",
  "Die Zahlung lässt sich weiterhin eintragen: mit einem Datum nach der Festschreibung, zusammen mit dem Zahlungskonto.": "The payment can still be recorded: with a date after the period lock, together with the payment account.",
  "Diese Buchung wurde{0} storniert{1}. Eine Gegenbuchung hebt sie auf; beide bleiben unverändert erhalten und lassen sich weder bearbeiten noch löschen.": "This transaction was{0} reversed{1}. A contra entry cancels it; both are kept unchanged and can neither be edited nor deleted.",
  "Das ist die Gegenbuchung zu einem Storno. Sie hebt die stornierte Buchung auf und lässt sich weder bearbeiten noch löschen.": "This is the contra entry of a reversal. It cancels the reversed transaction and can neither be edited nor deleted.",
  "Übernommen aus {0}{1}{2}.": "Imported from {0}{1}{2}.",
  "einer Tabelle": "a table",
  ", Konto": ", account",
  "Aus einem Kontoauszug übernommen: Datei „{0}“, {1}.": "Imported from a bank statement: file “{0}”, {1}.",
  "Mahngebühr und Verzugsaufschlag zu einer Rechnung. Das ist kein Entgelt für eine Leistung und deshalb ohne Umsatzsteuer.": "Reminder fee and late payment surcharge for an invoice. This is not payment for a service and therefore without VAT.",
  "z. B. Bürostühle, Bahnfahrt Berlin": "e.g. office chairs, train ride Berlin",
  "Belegdatum": "Receipt date",
  "Wo die Leistung erbracht wurde. Die Liste schlägt bereits verwendete Orte vor; in der Buchungsliste lässt sich danach filtern.": "Where the service was provided. The list suggests places already used; the transaction list can be filtered by it.",
  "Kleinunternehmer, keine Umsatzsteuer": "Small business, no VAT",
  "Brutto eingeben": "Enter gross",
  "Netto eingeben": "Enter net",
  "Bruttobetrag": "Gross amount",
  "Nettobetrag": "Net amount",
  "Umsatzsteuersatz": "VAT rate",
  "Nächste freie Nummer": "Next free number",
  "Anzahlung auf einen späteren Termin": "Down payment for a later date",
  "Termin der Veranstaltung": "Date of the event",
  "Bei Hochzeiten das Hochzeitsdatum. Der Termin erscheint im Kalender.": "For weddings the wedding date. The date appears in the calendar.",
  "Anteil der Anzahlung": "Share of the down payment",
  "Anteil am vereinbarten Gesamtbetrag.": "Share of the agreed total.",
  "Dieses Datum zählt für die Anlage EÜR; die Umsatzsteuer richtet sich bei Ihnen nach dem Rechnungsdatum.": "This date counts for the Anlage EÜR; for you, VAT follows the invoice date.",
  "Dieses Datum zählt für die Anlage EÜR und die Umsatzsteuer.": "This date counts for the Anlage EÜR and VAT.",
  "Umsatzsteuerliche Behandlung": "VAT treatment",
  "Bestimmt, in welche Kennzahl der Umsatzsteuer-Voranmeldung der Betrag fließt.": "Determines which box of the VAT return the amount goes into.",
  "Auf der Rechnung steht „Versteuerung nach vereinnahmten Entgelten“": "The invoice says “Versteuerung nach vereinnahmten Entgelten” (cash-basis taxation)",
  "Ab 2028 zählt die Vorsteuer aus solchen Rechnungen erst, wenn Sie bezahlt haben.": "From 2028, input VAT from such invoices only counts once you have paid.",
  "Diese Anschaffung wird über {0} abgeschrieben ({1} €, {2}{3}).": "This purchase is depreciated over {0} ({1} €, {2}{3}).",
  ", {0} Jahre": ", {0} years",
  "Als Anlagegut abschreiben …": "Depreciate as fixed asset …",
  "Für Anschaffungen über 800 € netto, die über mehrere Jahre genutzt werden.": "For purchases over €800 net that are used over several years.",
  "Verknüpfte Termine": "Linked appointments",
  "Aufgaben zu dieser Buchung": "Tasks for this transaction",
  "Zeile {0} der Anlage EÜR": "Line {0} of the Anlage EÜR",
  "Privat, zählt nicht zum Gewinn": "Private, does not count towards profit",
  "Entstanden aus der wiederkehrenden Buchung „{0}“ ({1}). Turnus und Vorlage ändern Sie unter Stammdaten → Wiederkehrend.": "Created from the recurring transaction “{0}” ({1}). You change the interval and template under Master data → Recurring.",
  "nicht wiederholen": "do not repeat",
  "Für Miete, Telefon, Abos: Kontovia bietet die nächsten Buchungen zum Anlegen an, sobald sie fällig sind.": "For rent, phone, subscriptions: Kontovia offers to create the next transactions as soon as they are due.",
  "Wiederholen bis (freiwillig)": "Repeat until (optional)",
  "({0}): {1}{2} · {3} € vom": "({0}): {1}{2} · {3} € of",
  "E-Rechnung erkannt": "E-invoice detected",
  "Rechnung ansehen": "View invoice",
  "ohne Namen": "unnamed",
  "Die Rechnung enthält mehrere Steuersätze ({0}). Übernommen werden Datum, Nummer und Kontakt; die Beträge bitte je Steuersatz als eigene Buchung erfassen.": "The invoice contains several tax rates ({0}). Date, number and contact are taken over; please record the amounts per tax rate as separate transactions.",
  "Werte übernehmen": "Take over values",
  "Kontakt „{0}“ anlegen": "Create contact “{0}”",
  "Kontakt angelegt": "Contact created",
  "Betrag nicht übernommen": "Amount not taken over",
};
