/** Wörterbuch Englisch, Teil t17. Quellen: views/transactions.js, views/wiederkehrend.js, web/ablage.js, web/aktualisierung.js, web/anmeldung.js, web/bridge.js, web/cloud.js, web/dateien.js, web/entsperrung.js, web/firebase.js, web/gcal.js, web/installation.js, web/kern.js, web/ki.js, web/konten.js, web/koppeln.js, web/mailversand.js, web/mobil.js, web/netz.js, web/rueckmeldung.js, web/scrypt.js, web/seed.js. */

export default {
  "Die Rechnung nennt {0} %. Bitte Betrag und Satz selbst eintragen.": "The invoice states {0}%. Please enter amount and rate yourself.",
  "Die Rechnung schlüsselt die Umsatzsteuer nicht auf. Bitte Betrag und Satz selbst eintragen.": "The invoice does not break down the VAT. Please enter amount and rate yourself.",
  "Werte übernommen": "Values taken over",
  "Bitte prüfen, Kategorie wählen und die Buchung anlegen.": "Please check, choose a category and create the transaction.",
  "Betrag:": "Amount:",
  "Vorsteuer abziehbar": "Input VAT deductible",
  "Sobald der Anteil eingetragen ist, rechnet Kontovia den Gesamtbetrag und den offenen Rest aus.": "As soon as the share is entered, Kontovia calculates the total and the open remainder.",
  "Restbetrag": "Remaining amount",
  "fällig zum": "due on",
  "Restzahlung als offene Buchung vorbereiten": "Prepare the remaining payment as an open transaction",
  "Kein offener Restbetrag": "No open remaining amount",
  "Restzahlung:": "Remaining payment:",
  "Restbetrag nach Anzahlung vom {0} ({1} % von {2} €).": "Remaining amount after down payment of {0} ({1}% of {2} €).",
  "Anzahlung gespeichert": "Down payment saved",
  "Der Restbetrag ist vorbereitet. Bitte noch prüfen und anlegen.": "The remaining amount is prepared. Please check and create it.",
  "Noch kein Beleg. Eine Kopie jeder eigenen Rechnung gehört in Ihre Unterlagen.": "No receipt yet. A copy of each of your own invoices belongs in your records.",
  "Noch kein Beleg. Hängen Sie ihn am besten gleich an, das Finanzamt fragt danach.": "No receipt yet. Best attach it right away; the tax office asks for it.",
  "Speichern unter": "Save as",
  "aus einer älteren Fassung wiederhergestellt, Name und Prüfsumme fehlen": "restored from an older version, name and checksum missing",
  "· Prüfsumme {0}…": "· checksum {0}…",
  "Beleg gespeichert": "Receipt saved",
  "Beleg entfernen?": "Remove receipt?",
  "Die Datei wird endgültig aus dem Tresor gelöscht.": "The file will be permanently deleted from the vault.",
  "Beleg konnte nicht gespeichert werden": "Receipt could not be saved",
  "Bitte zuerst einen Betrag eintragen": "Please enter an amount first",
  "Bitte eine Beschreibung eintragen.": "Please enter a description.",
  "Der Betrag darf nicht 0 sein.": "The amount must not be 0.",
  "Bitte einen Wert zwischen 1 und 100 Prozent eintragen.": "Please enter a value between 1 and 100 percent.",
  "Teil eines Stornos": "Part of a reversal",
  "Stornierte Buchungen und Gegenbuchungen bleiben unverändert. Duplizieren Sie die Buchung, um sie neu zu erfassen.": "Reversed transactions and contra entries stay unchanged. Duplicate the transaction to record it again.",
  "Eintragen lässt sich nur noch die Zahlung (Datum nach der Festschreibung, Zahlungskonto). Alles andere bitte stornieren und neu erfassen.": "Only the payment can still be recorded (date after the period lock, payment account). Please reverse everything else and record it again.",
  "Bitte stornieren Sie die Buchung statt sie zu ändern.": "Please reverse the transaction instead of changing it.",
  "Für diesen Zeitraum sind keine neuen Buchungen mehr möglich. Wählen Sie ein Datum nach der Festschreibung.": "No new transactions are possible for this period. Choose a date after the period lock.",
  "Das Ende liegt vor dem Datum der Buchung.": "The end is before the date of the transaction.",
  "Ist diese Einnahme wirklich privat?": "Is this income really private?",
  "Als „privat“ gekennzeichnet steht sie weder in der EÜR noch in der Umsatzsteuer noch in den Unterlagen fürs Finanzamt. Das ist nur richtig, wenn sie nicht zum Betrieb gehört, etwa beim Verkauf eigener Privatsachen. Einnahmen aus Ihrer betrieblichen Tätigkeit müssen vollständig erklärt werden (§ 146 Abs. 1 AO).": "Marked as “private”, it appears neither in the EÜR nor in VAT nor in the documents for the tax office. This is only correct if it does not belong to the business, for example when selling your own private belongings. Income from your business activity must be declared in full (§ 146 (1) AO).",
  "Ja, sie ist privat": "Yes, it is private",
  "Buchung angelegt": "Transaction created",
  "Buchung gespeichert": "Transaction saved",
  "Festgeschriebene Buchungen dürfen nicht gelöscht werden": "Locked transactions must not be deleted",
  "Nutzen Sie stattdessen „Stornieren“.": "Use “Reverse” instead.",
  "Buchung löschen?": "Delete transaction?",
  "Die Buchung wird endgültig entfernt. Der Vorgang wird im Änderungsjournal vermerkt.": "The transaction will be removed permanently. This is recorded in the change log.",
  "Endgültig löschen": "Delete permanently",
  "Buchung nicht gelöscht": "Transaction not deleted",
  "Buchung gelöscht": "Transaction deleted",
  "Warum wird diese Buchung storniert?": "Why is this transaction being reversed?",
  "Buchung storniert": "Transaction reversed",
  "Original und Gegenbuchung bleiben nachvollziehbar erhalten.": "Original and contra entry are kept and remain traceable.",
  "Nicht ausgebucht": "Not written off",
  "Skonto ausgebucht": "Early payment discount written off",
  "Forderungsausfall ausgebucht": "Bad debt written off",
  "Die Umsatzsteuer wird im Zeitraum des Ausbuchens berichtigt.": "VAT is corrected in the period of the write-off.",
  "Beides": "Both",
  "Anlegen": "Create",
  "Anlagegut abschreiben": "Depreciate fixed asset",
  "Anschaffungen über 800 € netto werden nicht sofort abgezogen, sondern über die betriebsgewöhnliche Nutzungsdauer verteilt (AfA, § 7 EStG).": "Purchases over €800 net are not deducted immediately but spread over the usual useful life (depreciation, § 7 EStG).",
  "Beleg kann nicht gelesen werden": "Receipt cannot be read",
  "Keine Vorschau möglich": "No preview possible",
  "Diese Datei kann Kontovia nicht selbst anzeigen. Sie können den Beleg speichern oder extern öffnen.": "Kontovia cannot display this file itself. You can save the receipt or open it externally.",
  "E-Rechnung anzeigen": "Show e-invoice",
  "Extern öffnen": "Open externally",
  "XML anzeigen": "Show XML",
  "Extern öffnen?": "Open externally?",
  "Der Beleg wird entschlüsselt in einem neuen Browser-Tab geöffnet. Was der Browser nicht anzeigen kann, wird stattdessen zum Sichern angeboten.": "The receipt is decrypted and opened in a new browser tab. Anything the browser cannot display is offered for saving instead.",
  "Rechnung anzeigen": "Show invoice",
  "festgeschrieben, wird übersprungen": "locked, will be skipped",
  "· als bezahlt": "· as paid",
  "· offen": "· open",
  "Angelegt wird, was angehakt ist. Jede ist eine eigene Buchung, die Sie danach wie jede andere ändern oder stornieren können. Ohne Häkchen lässt Kontovia eine Buchung für diesen Termin aus und bietet sie nicht noch einmal an. Belege hängen Sie an die einzelne Buchung an.": "What is ticked will be created. Each is a separate transaction that you can change or reverse like any other afterwards. Without a tick, Kontovia skips a transaction for this date and does not offer it again. You attach receipts to the individual transaction.",
  "Eine Buchung anlegen": "Create one transaction",
  "Buchungen anlegen": "Create transactions",
  "Alle auslassen": "Skip all",
  "Eine Buchung angelegt": "One transaction created",
  "Buchungen angelegt": "transactions created",
  "Belege lassen sich an jede Buchung einzeln anhängen.": "Receipts can be attached to each transaction individually.",
  "Regeln": "Rules",
  "Beschreibung suchen …": "Search description …",
  "Turnus": "Interval",
  "Keine wiederkehrenden Buchungen": "No recurring transactions",
  "Beim Erfassen einer Buchung unter „Weitere Angaben → Wiederholen“ einen Turnus wählen, etwa für Miete, Telefon oder Software-Abos.": "When recording a transaction, choose an interval under “More details → Repeat”, for example for rent, phone or software subscriptions.",
  "Wiederkehrende Buchung löschen?": "Delete recurring transaction?",
  "„{0}“ wird nicht mehr angeboten. Bereits angelegte Buchungen bleiben unverändert.": "“{0}” will no longer be offered. Transactions already created stay unchanged.",
  "Betrag (brutto)": "Amount (gross)",
  "Nächste Buchung am": "Next transaction on",
  "Endet am (freiwillig)": "Ends on (optional)",
  "gleich als bezahlt anlegen (etwa bei Lastschrift oder Dauerauftrag)": "create as paid right away (e.g. for direct debit or standing order)",
  "aktiv (fällige Buchungen werden angeboten)": "active (due transactions are offered)",
  "Weitere Angaben der Vorlage (Kontakt, Notiz) stammen aus der ersten Buchung.": "Further template details (contact, note) come from the first transaction.",
  "Als Kleinunternehmer ohne Umsatzsteuer.": "As a small business without VAT.",
  "Umsatzsteuer wie in der Vorlage: {0} %.": "VAT as in the template: {0}%.",
  "Bitte eine Beschreibung eintragen": "Please enter a description",
  "Der Betrag darf nicht 0 sein": "The amount must not be 0",
  "Bitte das nächste Datum wählen": "Please choose the next date",
  "Das Ende liegt vor der nächsten Buchung": "The end is before the next transaction",
  ".{0}-sql": ".{0}-sql",
  "Der Speicher des Browsers ist nicht verfügbar. Im privaten Modus kann Kontovia nichts ablegen.": "The browser's storage is not available. In private mode Kontovia cannot store anything.",
  "Kontovia ist noch in einem anderen Fenster mit einer älteren Fassung geöffnet.": "Kontovia is still open in another window with an older version.",
  "Speichern im Browser fehlgeschlagen.": "Saving in the browser failed.",
  "Der Speichervorgang wurde abgebrochen.": "The saving process was aborted.",
  "Kontovia darf gerade nicht auf den Ordner „{0}“ zugreifen. Erlauben Sie den Zugriff, wenn der Browser danach fragt.": "Kontovia is currently not allowed to access the folder “{0}”. Allow access when the browser asks.",
  "Der Ordner „{0}“ ist nicht mehr da. Wurde er verschoben, umbenannt oder gelöscht?": "The folder “{0}” is no longer there. Was it moved, renamed or deleted?",
  "Auf dem Datenträger ist nicht genug Platz frei.": "There is not enough free space on the storage medium.",
  "Eine Datei im Ordner „{0}“ ist gerade von einem anderen Programm belegt. Bitte gleich noch einmal versuchen.": "A file in the folder “{0}” is currently in use by another program. Please try again shortly.",
  "Der Ordner ließ sich nicht lesen oder schreiben.": "The folder could not be read or written.",
  "„{0}“ gehört nicht in den Ordner.": "“{0}” does not belong in the folder.",
  "Ungültige Beleg-Kennung.": "Invalid receipt identifier.",
  "Ungültiger Name einer Sicherung.": "Invalid backup name.",
  "Unbekannter Bereich:": "Unknown area:",
  "Im Ordner „{0}“ liegt keine Kontovia-Buchhaltung.": "The folder “{0}” contains no Kontovia accounting.",
  "Es gibt keine Tresordatei, die sich verschieben ließe.": "There is no vault file that could be moved.",
  "Die Kopie von {0} stimmt nicht mit dem Original überein. Der Umzug wurde abgebrochen.": "The copy of {0} does not match the original. The move was aborted.",
  "Die Buchhaltung liegt bereits in einem Ordner.": "The accounting is already in a folder.",
  "Im Ordner „{0}“ liegt schon eine Kontovia-Buchhaltung. Wählen Sie einen anderen Ordner.": "The folder “{0}” already contains a Kontovia accounting. Choose a different folder.",
  "Die Buchhaltung liegt bereits im Browser.": "The accounting is already in the browser.",
  "Im Speicher des Browsers liegt noch eine andere Buchhaltung. Der Umzug wurde abgebrochen.": "There is another accounting in the browser's storage. The move was aborted.",
  "Offline-Betrieb nicht verfügbar:": "Offline mode not available:",
  "Der Server hat keine gültige Versionsdatei geliefert.": "The server did not deliver a valid version file.",
  "Die Versionsdatei enthält keine gültige Versionsnummer.": "The version file contains no valid version number.",
  "Die Versionsdatei nennt keine Programmdateien.": "The version file names no program files.",
  "Unzulässiger Pfad in der Versionsdatei:": "Invalid path in the version file:",
  "Für {0} fehlt eine gültige Prüfsumme. Das Update wurde abgebrochen.": "A valid checksum is missing for {0}. The update was aborted.",
  "Die Versionsdatei nennt keine Startseite.": "The version file names no start page.",
  "?t=": "?t=",
  "Der Server ist nicht erreichbar:": "The server is not reachable:",
  "Kontovia-": "Kontovia-",
  "Dieser Browser kann Kontovia nicht auf dem Gerät ablegen. Laden Sie die Seite einfach neu.": "This browser cannot store Kontovia on the device. Simply reload the page.",
  "?kv-neu=": "?kv-neu=",
  "konnte nicht geladen werden (HTTP {0}).": "could not be loaded (HTTP {0}).",
  "Die Prüfsumme von {0} stimmt nicht. Die neue Fassung wurde verworfen.": "The checksum of {0} does not match. The new version was discarded.",
  "Ungültige Version.": "Invalid version.",
  "Die neue Fassung liegt nicht vollständig vor. Bitte erneut herunterladen.": "The new version is not completely available. Please download it again.",
  "Es ist keine Google-Client-ID für die Web-Fassung hinterlegt.": "No Google client ID is set for the web version.",
  "Google kennt diese Client-ID für die Anmeldung per Code nicht. Sie muss vom Typ „Fernseher und Geräte mit eingeschränkter Eingabe“ sein.": "Google does not know this client ID for sign-in with a code. It must be of the type “TVs and Limited Input devices”.",
  "Der Code ist abgelaufen. Bitte die Anmeldung neu starten.": "The code has expired. Please restart the sign-in.",
  "Die Freigabe wurde abgelehnt.": "The approval was declined.",
  "Google meldet:": "Google reports:",
  "Google hat kein dauerhaftes Zugriffsrecht erteilt. Bitte in den Google-Kontoeinstellungen den Zugriff für Kontovia entfernen und erneut anmelden.": "Google did not grant permanent access. Please remove Kontovia's access in the Google account settings and sign in again.",
  "Die Anmeldung wurde abgebrochen.": "The sign-in was cancelled.",
  "Google hat kein neues Zugriffstoken geliefert.": "Google did not deliver a new access token.",
  "Anmeldung nach Weiterleitung:": "Sign-in after redirect:",
  "Der Vorgang ist fehlgeschlagen.": "The operation failed.",
  "Android": "Android",
  "Mac": "Mac",
  "Linux": "Linux",
  "Gerät": "Device",
  "Browser": "Browser",
  "Öffnen Sie {0}, hier oder auf einem anderen Gerät.": "Open {0}, here or on another device.",
  "Melden Sie sich mit Ihrem Google-Konto an und geben Sie diesen Code ein:": "Sign in with your Google account and enter this code:",
  "Bestätigen Sie danach die Freigabe. Dieses Fenster schließt sich von selbst, sobald Google die Anmeldung meldet. Der Code gilt {0} Minuten.": "Then confirm the approval. This window closes by itself as soon as Google reports the sign-in. The code is valid for {0} minutes.",
  "Code kopieren": "Copy code",
  "Google öffnen": "Open Google",
  "Code kopiert": "Code copied",
  "Zum Lesen der Rückmeldungen mit dem Konto des Betreibers bei der Cloud anmelden.": "To read the feedback, sign in to the cloud with the operator's account.",
  "Kontovia-Finanzamt_": "Kontovia-Finanzamt_",
  "Kontovia-Datentraegerueberlassung_": "Kontovia-Datentraegerueberlassung_",
  "Kontovia-Belege_": "Kontovia-Belege_",
  "Kontovia-Export_": "Kontovia-Export_",
  "Ordner „{0}“ auf diesem Gerät": "Folder “{0}” on this device",
  "Speicher dieses Browsers": "This browser's storage",
  "Kontovia ist in einem anderen Fenster geöffnet. Bitte dort weiterarbeiten oder dieses Fenster neu laden.": "Kontovia is open in another window. Please continue working there or reload this window.",
  "Verbindung nach Übernahme:": "Connection after takeover:",
  "Einen Ordner öffnet der Browser nicht selbst. Wo Ihre Buchhaltung liegt, steht unter Einstellungen → Sicherung und Speicherort.": "The browser does not open a folder by itself. Where your accounting is stored is shown under Settings → Backup and storage location.",
  "Die Web-Fassung läuft in Ihrem Browser; es gelten dessen Lizenzbedingungen.": "The web version runs in your browser; its license terms apply.",
  "Unbekanntes Dokument.": "Unknown document.",
  "Dieser Text ist in dieser Fassung nicht enthalten.": "This text is not included in this version.",
  "Anmeldung nach der Aktualisierung:": "Sign-in after the update:",
  "Ungültiger Datenbestand. Speichern abgebrochen.": "Invalid data. Saving aborted.",
  "Das neue Passwort muss mindestens 10 Zeichen haben.": "The new password must have at least 10 characters.",
  "image/*,.pdf,.txt,.xml,.csv,.zip,.eml,.docx,.xlsx": "image/*,.pdf,.txt,.xml,.csv,.zip,.eml,.docx,.xlsx",
  "Für die Sicherung ist ein Passwort mit mindestens 10 Zeichen nötig.": "A password with at least 10 characters is required for the backup.",
  "Kontovia-Sicherung-{0}.kvbak": "Kontovia-Sicherung-{0}.kvbak",
  "Kontovia-Sicherung": "Kontovia backup",
  "Kontovia ist schon entsperrt.": "Kontovia is already unlocked.",
  "In dieser Fassung ist die Anmeldung bei Google nicht eingerichtet.": "Google sign-in is not set up in this version.",
  "Für dieses Google-Konto ist das Entsperren ohne Passwort nicht eingeschaltet. Bitte entsperren Sie mit Ihrem Passwort.": "Unlocking without a password is not turned on for this Google account. Please unlock with your password.",
  "Der Schlüssel im Google-Konto gehört zu einer anderen Buchhaltung. Bitte mit dem Passwort entsperren.": "The key in the Google account belongs to a different accounting. Please unlock with the password.",
  "Dieser Browser kann nicht in einen Ordner auf dem Gerät speichern. Das geht in Chrome und Edge.": "This browser cannot save to a folder on the device. This works in Chrome and Edge.",
  "Diesen Ordner gibt der Browser nicht frei. Wählen Sie einen Ordner zum Beispiel unter Dokumente.": "The browser does not grant access to this folder. Choose a folder, for example under Documents.",
  "Der Ordner ließ sich nicht öffnen.": "The folder could not be opened.",
  "Ohne Erlaubnis zum Schreiben kann Kontovia den Ordner nicht verwenden.": "Without permission to write, Kontovia cannot use the folder.",
  "Im gewählten Ordner liegt keine Kontovia-Buchhaltung.": "The selected folder contains no Kontovia accounting.",
  "In diesem Browser gibt es schon eine Buchhaltung. Ziehen Sie sie in den Einstellungen in einen Ordner um, oder öffnen Sie den Ordner in einem anderen Browser.": "There is already an accounting in this browser. Move it to a folder in the settings, or open the folder in another browser.",
  "Bitte zuerst einen Ordner wählen.": "Please choose a folder first.",
  "Bitte zuerst sperren.": "Please lock first.",
  "Übergabe:": "Handover:",
  "Ungültiger Datenbestand. Abgleich abgebrochen.": "Invalid data. Sync aborted.",
  "Bericht": "Report",
  "Kontovia braucht eine verschlüsselte Verbindung (https). Über eine unverschlüsselte Adresse gibt der Browser die Verschlüsselungsfunktionen nicht frei.": "Kontovia needs an encrypted connection (https). Over an unencrypted address the browser does not make the encryption functions available.",
  "Dieser Browser ist zu alt für Kontovia. Nötig ist mindestens iOS bzw. Safari 16.4, Chrome 103 oder Firefox 113.": "This browser is too old for Kontovia. At least iOS or Safari 16.4, Chrome 103 or Firefox 113 is required.",
  "Der Browser erlaubt Kontovia nicht, Daten abzulegen. Das ist im privaten Modus üblich. Bitte in einem normalen Fenster öffnen.": "The browser does not allow Kontovia to store data. This is common in private mode. Please open it in a normal window.",
  "Kontovia kann hier nicht starten": "Kontovia cannot start here",
  "Kontovia hat die Antwort erhalten. Sie können dieses Fenster schließen.": "Kontovia has received the answer. You can close this window.",
  "Konten:": "Accounts:",
  "Speicherort:": "Storage location:",
  "Als App installieren": "Install as app",
  "In Safari auf „Teilen“ und dann „Zum Home-Bildschirm“ tippen. Kontovia startet dann wie eine App und funktioniert offline.": "In Safari tap “Share” and then “Add to Home Screen”. Kontovia then starts like an app and works offline.",
  "Z_{0}.kv": "Z_{0}.kv",
  "T{0}:{1}:{2}.000Z": "T{0}:{1}:{2}.000Z",
  "Der Tresor ist gesperrt.": "The vault is locked.",
  "In diesem Browser gibt es bereits eine Buchhaltung. Die Verbindung zu Google richten Sie in den Einstellungen ein.": "There is already an accounting in this browser. You set up the connection to Google in the settings.",
  "In dieser Fassung ist keine Anmeldung bei Google hinterlegt.": "No Google sign-in is set in this version.",
  "Angemeldet, aber die Cloud ist nicht erreichbar:": "Signed in, but the cloud is not reachable:",
  "In Ihrem Konto liegt keine Buchhaltung, die sich laden ließe.": "Your account contains no accounting that could be loaded.",
  "Für dieses Konto ist das Öffnen ohne Passwort nicht eingeschaltet. Bitte geben Sie das Passwort ein.": "Opening without a password is not turned on for this account. Please enter the password.",
  "Dazu muss Kontovia mit Ihrem Google-Konto verbunden sein.": "For this, Kontovia must be connected to your Google account.",
  "Es läuft gerade keine Kopplung.": "No pairing is currently running.",
  "Ein Verweis gehört nicht in die Cloud.": "A reference does not belong in the cloud.",
  "Kein laufender Abgleich. Bitte erneut starten.": "No sync running. Please start again.",
  "Ein anderes Gerät hat währenddessen gespeichert.": "Another device saved in the meantime.",
  "Das Hochladen ist unvollständig angekommen. Bitte noch einmal abgleichen.": "The upload arrived incomplete. Please sync again.",
  "Die Sicherung der alten Datei ist nicht vollständig in der Cloud angekommen.": "The backup of the old file did not arrive completely in the cloud.",
  "Die neue Datei in der Cloud weicht vom Hochgeladenen ab; die alte bleibt.": "The new file in the cloud differs from what was uploaded; the old one stays.",
  "Diese Datei ist keine Sicherung.": "This file is not a backup.",
  "In der Cloud liegt keine Buchhaltung.": "There is no accounting in the cloud.",
  "Diese Datei lässt sich nicht übernehmen.": "This file cannot be taken over.",
  "Datei ist bereit": "File is ready",
  "„{0}“ ist fertig erstellt.": "“{0}” has been created.",
  "Tippen Sie auf „Sichern“ und wählen Sie im Teilen-Menü „In Dateien sichern“.": "Tap “Save” and choose “Save to Files” in the share menu.",
  "Klicken Sie auf „Sichern“, um den Speicherort zu wählen.": "Click “Save” to choose the location.",
  "Sichern": "Save",
  "Dieses Gerät kann die Dateien nicht teilen.": "This device cannot share the files.",
  "Bitte tippen Sie noch einmal auf den Knopf.": "Please tap the button again.",
  "Kontovia-Export": "Kontovia-Export",
  "Der Browser hat die Bestätigung nicht zugelassen. Prüfen Sie, ob auf diesem Gerät eine Bildschirmsperre mit Fingerabdruck, Gesicht oder PIN eingerichtet ist, und versuchen Sie es noch einmal.": "The browser did not allow the confirmation. Check whether a screen lock with fingerprint, face or PIN is set up on this device, and try again.",
  "Die Bestätigung wurde abgebrochen.": "The confirmation was cancelled.",
  "Für dieses Gerät ist schon ein Zugang eingerichtet.": "Access is already set up for this device.",
  "Dieses Gerät oder dieser Browser unterstützt das nicht. Das Passwort funktioniert weiterhin.": "This device or browser does not support this. The password still works.",
  "Auf diesem Gerät ist keine Bildschirmsperre mit Fingerabdruck, Gesicht oder PIN eingerichtet. Richten Sie sie in den Einstellungen des Geräts ein und versuchen Sie es noch einmal.": "No screen lock with fingerprint, face or PIN is set up on this device. Set it up in the device settings and try again.",
  "Hier lässt sich das nicht einrichten. Öffnen Sie Kontovia über die gewohnte Internetadresse.": "This cannot be set up here. Open Kontovia via the usual web address.",
  "Die Bestätigung per Fingerabdruck oder Gesicht hat nicht geklappt. Das Passwort funktioniert weiterhin.": "The confirmation with fingerprint or face did not work. The password still works.",
  "Dieser Browser kann keine Anmeldung per Fingerabdruck oder Gesicht.": "This browser cannot sign in with fingerprint or face.",
  "Kontovia (Entsperren auf diesem Gerät)": "Kontovia (unlocking on this device)",
  "Dieses Gerät kann den Tresor nicht per Fingerabdruck oder Gesicht öffnen, weil es das nötige geheime Merkmal nicht herausgibt. Das Passwort funktioniert weiterhin.": "This device cannot open the vault with fingerprint or face because it does not release the required secret. The password still works.",
  "Dieses Gerät kann den Tresor nicht per Fingerabdruck oder Gesicht öffnen. Das Passwort funktioniert weiterhin.": "This device cannot open the vault with fingerprint or face. The password still works.",
  "Auf diesem Gerät ist keine Entsperrung per Fingerabdruck oder Gesicht eingerichtet.": "Unlocking with fingerprint or face is not set up on this device.",
  "Der gespeicherte Zugang passt nicht mehr. Bitte mit dem Passwort entsperren und neu einrichten.": "The stored access no longer fits. Please unlock with the password and set it up again.",
  "Unbekannter Ort einer Sicherung.": "Unknown backup location.",
  "Die Anmeldung bei Google gilt nicht mehr, etwa weil der Zugriff im Google-Konto entfernt wurde. Bitte neu anmelden; Ihre Daten bleiben dabei, wie sie sind.": "The Google sign-in is no longer valid, for example because access was removed in the Google account. Please sign in again; your data stays as it is.",
  "Es ist kein Firebase-Web-API-Schlüssel hinterlegt.": "No Firebase web API key is set.",
  "Es ist kein Firebase-Speicherort (Bucket) hinterlegt.": "No Firebase storage location (bucket) is set.",
  "Es ist keine Google-Client-ID hinterlegt.": "No Google client ID is set.",
  "Google hat die Anmeldung nicht bestätigt. Bitte erneut anmelden.": "Google did not confirm the sign-in. Please sign in again.",
  "Der Cloud-Speicher hat die Anmeldung nicht bestätigt. Bitte versuchen Sie es später noch einmal.": "The cloud storage did not confirm the sign-in. Please try again later.",
  "Es ist kein Konto verbunden.": "No account is connected.",
  "Die Sitzung konnte nicht erneuert werden. Bitte neu anmelden.": "The session could not be renewed. Please sign in again.",
  "Keine Kontokennung vorhanden.": "No account identifier available.",
  "?alt=media": "?alt=media",
  "Die Datei ließ sich nicht aus der Cloud laden (HTTP {0}).": "The file could not be loaded from the cloud (HTTP {0}).",
  "&pageToken=": "&pageToken=",
  "Beleg konnte nicht geladen werden (HTTP {0}).": "Receipt could not be loaded (HTTP {0}).",
  "Diese Sicherung bleibt.": "This backup is kept.",
  "Der Schlüssel ließ sich nicht lesen (HTTP {0}).": "The key could not be read (HTTP {0}).",
  "Ungültiger Name einer Kopplungsdatei.": "Invalid name of a pairing file.",
  "Die Kopplungsdatei ließ sich nicht lesen (HTTP {0}).": "The pairing file could not be read (HTTP {0}).",
  "eigener Verbrauch im Projekt": "own usage in the project",
  "token id_token": "token id_token",
  "Die Freigabe wurde bei Google abgebrochen.": "The approval was cancelled at Google.",
  "Die Antwort von Google ließ sich nicht bestätigen. Bitte erneut versuchen.": "Google's answer could not be confirmed. Please try again.",
  "Für Google Kalender ist kein Client hinterlegt.": "No client is set for Google Calendar.",
  "popup,width=520,height=680": "popup,width=520,height=680",
  "Der Browser hat das Fenster für Google blockiert. Bitte erlauben Sie Pop-ups für Kontovia und versuchen Sie es erneut.": "The browser blocked the window for Google. Please allow pop-ups for Kontovia and try again.",
  "Die Anmeldung bei Google hat zu lange gedauert. Bitte erneut versuchen.": "The Google sign-in took too long. Please try again.",
  "Der Browser erlaubt Kontovia gerade nicht, sich den Weg zu Google zu merken (privater Modus?). Bitte in einem normalen Fenster erneut versuchen.": "The browser currently does not allow Kontovia to remember the way to Google (private mode?). Please try again in a normal window.",
  "Der Zugriff auf den Kalender wurde im Google-Dialog nicht erlaubt. Bitte erneut verbinden und das Häkchen beim Kalender setzen.": "Access to the calendar was not allowed in the Google dialog. Please connect again and tick the calendar.",
  "Google hat den Zugriff auf den Kalender nicht angenommen. Bitte erneut verbinden.": "Google did not accept access to the calendar. Please connect again.",
  "Google Kalender ist auf diesem Gerät nicht verbunden.": "Google Calendar is not connected on this device.",
  "Bitte mit dem Google-Konto {0} bestätigen. Für ein anderes Konto Google Kalender erst trennen und neu verbinden.": "Please confirm with the Google account {0}. For a different account, disconnect Google Calendar first and connect it again.",
  "Der Kalenderabgleich wartet auf eine kurze Bestätigung bei Google.": "The calendar sync is waiting for a short confirmation at Google.",
  "Bearer": "Bearer",
  "Termine aus der Buchhaltung Kontovia. Änderungen hier kommen beim nächsten Abgleich in Kontovia an.": "Appointments from the Kontovia accounting. Changes here arrive in Kontovia at the next sync.",
  "Es ist noch kein Kontovia-Kalender angelegt. Bitte neu verbinden.": "No Kontovia calendar has been created yet. Please connect again.",
  "Der Kalender ist nicht mehr erreichbar.": "The calendar is no longer reachable.",
  "Ungültiger Auftrag.": "Invalid request.",
  "Nicht ausgeführt.": "Not performed.",
  "Google Kalender steht für Kontovia gerade nicht zur Verfügung. Bitte versuchen Sie es später noch einmal; bleibt es dabei, melden Sie es bitte dem Hersteller.": "Google Calendar is currently not available for Kontovia. Please try again later; if this persists, please report it to the vendor.",
  "Kontovia fehlt die Berechtigung für den Kalender. Bitte trennen und neu verbinden und dabei den Kalenderzugriff erlauben.": "Kontovia lacks permission for the calendar. Please disconnect, connect again and allow calendar access.",
  "Tippen Sie im Browser oben rechts auf das Menü (drei Punkte) und dann auf „App installieren“ oder „Zum Startbildschirm hinzufügen“. Danach startet Kontovia wie jede andere App und funktioniert auch ohne Netz.": "Tap the menu at the top right of the browser (three dots) and then “Install app” or “Add to Home screen”. Kontovia then starts like any other app and also works without a network.",
  "btn block mb8": "btn block mb8",
  "App installieren": "Install app",
  "Kontovia als App installieren": "Install Kontovia as an app",
  "Dann startet es wie jede andere App vom Startbildschirm und funktioniert auch ohne Netz. Hier tippen.": "Then it starts like any other app from the home screen and also works without a network. Tap here.",
  "Kontovia ist installiert": "Kontovia is installed",
  "Sie finden die App jetzt auf dem Startbildschirm.": "You now find the app on the home screen.",
  "SQLite format 30": "SQLite format 30",
  "Die Schlüsselableitung ist fehlgeschlagen.": "Key derivation failed.",
  "Die Datei hat ungewöhnliche Schlüsselparameter und wird nicht geöffnet.": "The file has unusual key parameters and will not be opened.",
  "Unbekanntes KDF:": "Unknown KDF:",
  "AES-GCM": "AES-GCM",
  "Datenblock ist beschädigt oder unvollständig.": "Data block is damaged or incomplete.",
  "Der Datenblock lässt sich nicht entschlüsseln (falscher Schlüssel oder verändert).": "The data block cannot be decrypted (wrong key or modified).",
  "Unbekanntes Dateiformat {0}.": "Unknown file format {0}.",
  "Keine gültige Kontovia-Datei.": "Not a valid Kontovia file.",
  "Keine gültige Kontovia-Datei (Signatur fehlt).": "Not a valid Kontovia file (signature missing).",
  "Dateiformat Version {0} wird von dieser Programmversion nicht unterstützt.": "File format version {0} is not supported by this program version.",
  "Datei ist beschädigt (Header).": "File is damaged (header).",
  "Datei ist beschädigt (Header nicht lesbar).": "File is damaged (header not readable).",
  "Das ist kein Abbild einer Datenbank.": "This is not a database image.",
  "Die Datei enthält keine lesbare Datenbank.": "The file contains no readable database.",
  "Der Verweis auf die Datenbank ist beschädigt.": "The reference to the database is damaged.",
  "Falsches Passwort oder beschädigte Datei.": "Wrong password or damaged file.",
  "Der Assistent ist abgestürzt.": "The assistant crashed.",
  "Dieses Modell kennt Kontovia nicht.": "Kontovia does not know this model.",
  "Es ist kein Modell gestartet.": "No model has been started.",
  "Dieses Konto gibt es auf diesem Gerät nicht (mehr).": "This account does not exist on this device (anymore).",
  "Es gibt kein anderes Konto, zu dem Kontovia zurückkehren könnte.": "There is no other account Kontovia could return to.",
  "Das offene Konto lässt sich nur über „Von diesem Gerät entfernen“ im Kontomenü entfernen.": "The open account can only be removed via “Remove from this device” in the account menu.",
  "P-256": "P-256",
  "Die Anfrage des Geräts ist unlesbar.": "The device's request is unreadable.",
  "|anfrage|{0}|{1}|": "|anfrage|{0}|{1}|",
  "|antwort|{0}|{1}|{2}|{3}|": "|antwort|{0}|{1}|{2}|{3}|",
  "Die Anfrage ist unlesbar.": "The request is unreadable.",
  "Die Anfrage passt nicht zu diesem Code.": "The request does not match this code.",
  "Im Moment wartet kein Gerät auf die Freigabe.": "No device is currently waiting for approval.",
  "Der Code ist abgelaufen. Bitte starten Sie noch einmal neu.": "The code has expired. Please start again.",
  "Bitte melden Sie sich zuerst bei Google an.": "Please sign in to Google first.",
  "Dieser Code wurde schon benutzt. Bitte zeigen Sie auf dem anderen Gerät einen neuen an.": "This code has already been used. Please show a new one on the other device.",
  "Das Verbinden wurde abgebrochen.": "Connecting was cancelled.",
  "Auf dem anderen Gerät wurde nichts bestätigt. Bitte starten Sie dort noch einmal neu.": "Nothing was confirmed on the other device. Please start again there.",
  "Die Antwort des anderen Geräts ist unlesbar.": "The other device's answer is unreadable.",
  "Der Code ist abgelaufen. Bitte zeigen Sie auf dem anderen Gerät einen neuen an.": "The code has expired. Please show a new one on the other device.",
  "Schlüssel": "Key",
  "Länge": "Length",
  "Die Antwort passt nicht zu diesem Code. Bitte zeigen Sie auf dem anderen Gerät einen neuen an.": "The answer does not match this code. Please show a new one on the other device.",
  "Die Freigabe wurde bei Microsoft abgebrochen.": "The approval was cancelled at Microsoft.",
  "Microsoft meldet:": "Microsoft reports:",
  "Die Antwort von Microsoft ließ sich nicht lesen. Bitte erneut versuchen.": "Microsoft's answer could not be read. Please try again.",
  "Für Microsoft ist in Kontovia noch nichts hinterlegt.": "Nothing is set up for Microsoft in Kontovia yet.",
  "Der Browser hat das Fenster für Microsoft blockiert. Bitte erlauben Sie Pop-ups für Kontovia und versuchen Sie es erneut.": "The browser blocked the window for Microsoft. Please allow pop-ups for Kontovia and try again.",
  "Die Anmeldung bei Microsoft hat zu lange gedauert. Bitte erneut versuchen.": "The Microsoft sign-in took too long. Please try again.",
  "Bitte eine Empfängeradresse eingeben.": "Please enter a recipient address.",
  "Unbekannter Anbieter.": "Unknown provider.",
  "Dieser Weg ist in Kontovia nicht eingerichtet.": "This method is not set up in Kontovia.",
  "Die E-Mail ist leer.": "The email is empty.",
  "Die E-Mail ist für Gmail zu groß (höchstens 25 MB).": "The email is too large for Gmail (at most 25 MB).",
  "Die E-Mail ist für Microsoft zu groß (mit Anhang höchstens etwa 3 MB). Bitte einen anderen Weg wählen.": "The email is too large for Microsoft (with attachment at most about 3 MB). Please choose another method.",
  "Das Senden wurde im Google-Fenster nicht erlaubt. Bitte erneut versuchen und das Häkchen bei „E-Mails senden“ setzen.": "Sending was not allowed in the Google window. Please try again and tick “Send emails”.",
  "Microsoft hat die Anmeldung nicht angenommen:": "Microsoft did not accept the sign-in:",
  "Die Antwort von Microsoft ließ sich nicht bestätigen. Bitte erneut versuchen.": "Microsoft's answer could not be confirmed. Please try again.",
  "Das Senden wurde bei Microsoft nicht erlaubt.": "Sending was not allowed at Microsoft.",
  "Die Freigabe für Gmail ist abgelaufen. Bitte noch einmal auf Senden klicken.": "The approval for Gmail has expired. Please click Send again.",
  "Der Versand über Gmail ist für Kontovia noch nicht freigeschaltet. Bitte einen anderen Weg wählen.": "Sending via Gmail is not yet enabled for Kontovia. Please choose another method.",
  "Google erlaubt Kontovia das Senden nicht. Bitte noch einmal auf Senden klicken und das Senden erlauben.": "Google does not allow Kontovia to send. Please click Send again and allow sending.",
  "Die E-Mail ist für Gmail zu groß. Bitte einen anderen Weg wählen.": "The email is too large for Gmail. Please choose another method.",
  "Gmail nimmt gerade keine weiteren E-Mails an. Bitte später erneut versuchen.": "Gmail is not accepting any more emails right now. Please try again later.",
  "Gmail hat die E-Mail nicht angenommen{0}.": "Gmail did not accept the email{0}.",
  "Die Freigabe für Microsoft ist abgelaufen. Bitte noch einmal auf Senden klicken.": "The approval for Microsoft has expired. Please click Send again.",
  "Microsoft erlaubt diesem Konto das Senden nicht. Bei Firmenkonten muss das oft die IT freigeben.": "Microsoft does not allow this account to send. For company accounts the IT department often has to enable this.",
  "Die E-Mail ist für Microsoft zu groß. Bitte einen anderen Weg wählen.": "The email is too large for Microsoft. Please choose another method.",
  "Microsoft nimmt gerade keine weiteren E-Mails an. Bitte später erneut versuchen.": "Microsoft is not accepting any more emails right now. Please try again later.",
  "Microsoft hat die E-Mail nicht angenommen:": "Microsoft did not accept the email:",
  "[data-view], #lockBtn, #updateBtn": "[data-view], #lockBtn, #updateBtn",
  "Schnellzugriff": "Quick access",
  "Ungültige Adresse.": "Invalid address.",
  "Nur verschlüsselte Verbindungen sind erlaubt.": "Only encrypted connections are allowed.",
  "Diese Gegenstelle ist nicht freigegeben:": "This endpoint is not approved:",
  "Keine Internetverbindung.": "No internet connection.",
  "Zeitüberschreitung bei der Verbindung.": "Connection timed out.",
  "Keine Verbindung zum Server.": "No connection to the server.",
  "Die Antwort ist unerwartet groß und wurde abgebrochen.": "The answer is unexpectedly large and was aborted.",
  "Ungültige Kennung der Rückmeldung.": "Invalid feedback identifier.",
  "Es ist kein Cloud-Speicher hinterlegt.": "No cloud storage is set.",
  "Der Server hat die Rückmeldung abgelehnt.": "The server rejected the feedback.",
  "Die Rückmeldung ist zu lang.": "The feedback is too long.",
  "Das Bildschirmfoto ist zu groß.": "The screenshot is too large.",
  "feedback/{0}.jpg": "feedback/{0}.jpg",
  "Ungültige Kennung.": "Invalid identifier.",
  "Das Foto konnte nicht geladen werden (HTTP {0}).": "The photo could not be loaded (HTTP {0}).",
  "feedback/{0}.": "feedback/{0}.",
  "scrypt: N muss eine Zweierpotenz sein.": "scrypt: N must be a power of two.",
  "scrypt: ungültige Parameter.": "scrypt: invalid parameters.",
  "scrypt: ungültige Schlüssellänge.": "scrypt: invalid key length.",
  "scrypt: Die Parameter verlangen mehr Speicher als erlaubt.": "scrypt: the parameters require more memory than allowed.",
  "Erlöse 19 % USt": "Revenue 19% VAT",
  "Erlöse 7 % USt": "Revenue 7% VAT",
  "Erlöse steuerfrei": "Tax-exempt revenue",
  "Erlöse als Kleinunternehmer (§ 19)": "Revenue as a small business (§ 19)",
  "Leistung ins Ausland (Reverse Charge)": "Service abroad (reverse charge)",
  "Zinserträge": "Interest income",
  "Verkauf von Anlagevermögen": "Sale of fixed assets",
  "Umsatzsteuer-Erstattung Finanzamt": "VAT refund from tax office",
  "Sonstige Betriebseinnahmen": "Other business income",
  "Privateinlage": "Private contribution",
  "Wareneinkauf / Material": "Purchase of goods / materials",
  "Fremdleistungen / Subunternehmer": "Third-party services / subcontractors",
  "Löhne und Gehälter": "Wages and salaries",
  "Sozialabgaben Arbeitgeber": "Employer social security contributions",
  "Geringwertige Wirtschaftsgüter (bis 800 €)": "Low-value assets (up to €800)",
  "Miete Betriebsräume": "Rent for business premises",
  "Nebenkosten, Strom, Heizung": "Utilities, electricity, heating",
  "Kfz-Kosten (laufend)": "Car costs (running)",
  "Kfz-Leasing": "Car leasing",
  "Reisekosten": "Travel costs",
  "Verpflegungsmehraufwand (Pauschale)": "Additional meal allowance (flat rate)",
  "Bewirtungskosten": "Entertainment expenses",
  "Geschenke an Geschäftsfreunde": "Gifts to business associates",
  "Werbung und Marketing": "Advertising and marketing",
  "Bürobedarf": "Office supplies",
  "Software, Lizenzen, Cloud-Dienste": "Software, licenses, cloud services",
  "Fortbildung und Fachliteratur": "Training and specialist literature",
};
