/** Wörterbuch Englisch, Teil t18. Quellen: web/seed.js, web/sperre.js, web/sql.js, web/tresor.js, web/updateinfo.js, web/weiterleitung.js. */

export default {
  "Rechts- und Steuerberatung": "Legal and tax advice",
  "Buchführungskosten": "Bookkeeping costs",
  "Beiträge, Gebühren, Abgaben": "Contributions, fees, levies",
  "Miete / Leasing bewegliche Wirtschaftsgüter": "Rent / leasing of movable assets",
  "Schuldzinsen": "Interest on debt",
  "Bankgebühren und Kontoführung": "Bank fees and account charges",
  "Gezahlte Vorsteuer": "Input VAT paid",
  "An Finanzamt gezahlte Umsatzsteuer": "VAT paid to the tax office",
  "Sonstige Betriebsausgaben": "Other business expenses",
  "Privatentnahme": "Private withdrawal",
  "Geschäftskonto": "Business account",
  "Bildschirmsperre nicht beobachtbar:": "Screen lock cannot be observed:",
  "Dieser Browser kann eine Bildschirmsperre nicht melden.": "This browser cannot report a screen lock.",
  "Der Browser hat die Erlaubnis nicht erteilt. Sie lässt sich in den Website-Einstellungen des Browsers nachträglich geben.": "The browser did not grant permission. It can be granted later in the browser's site settings.",
  "Die Datenbank meldet einen Fehler.": "The database reports an error.",
  "Das Rechenwerk der Datenbank ist ausgefallen:": "The database engine has failed:",
  "Die Datenbank ist geschlossen.": "The database is closed.",
  "Die Datenbank wurde geschlossen.": "The database was closed.",
  "Ungültige Angaben zum Konto.": "Invalid account details.",
  "kein OPFS": "no OPFS",
  "Unbekannter Auftrag an die Datenbank:": "Unknown request to the database:",
  "Ungültiger Ordner der Datenbank.": "Invalid database folder.",
  "Der Schlüssel passt nicht zu dieser Buchhaltung.": "The key does not match this accounting.",
  "Konto beschriften:": "Label account:",
  "Am Speicherort liegt bereits eine Buchhaltung.": "There is already an accounting at the storage location.",
  "Am Speicherort liegt keine Buchhaltung.": "There is no accounting at the storage location.",
  "Der Schlüssel passt nicht zu diesem Tresor.": "The key does not match this vault.",
  "Die Buchhaltung liegt im Datenspeicher dieses Browsers, und der ist gerade nicht erreichbar. Bitte die Seite neu laden. Hilft das nicht, holt „Aus der Cloud laden“ oder eine Sicherung den Stand zurück.": "The accounting is in this browser's data storage, which is currently not reachable. Please reload the page. If that does not help, “Load from the cloud” or a backup brings back the data.",
  "Die Datenbank dieser Buchhaltung ist leer. Holen Sie den Stand aus der Cloud oder aus einer Vollsicherung zurück.": "The database of this accounting is empty. Bring back the data from the cloud or from a full backup.",
  "Die Umstellung ist an einer Prüfung gescheitert ({0}). Ihre Daten sind unverändert; beim nächsten Öffnen versucht Kontovia es noch einmal.": "The conversion failed a check ({0}). Your data is unchanged; Kontovia will try again the next time it opens.",
  "Datenbank": "Database",
  "Der Verweis auf die Datenbank ließ sich nicht schreiben. Bitte noch einmal öffnen.": "The reference to the database could not be written. Please open it again.",
  "Die Umstellung ist an einer Prüfung gescheitert ({0}). Ihre Daten sind unverändert.": "The conversion failed a check ({0}). Your data is unchanged.",
  "Die Umstellung ist an einer Prüfung gescheitert (Abbild: {0}). Ihre Daten sind unverändert.": "The conversion failed a check (image: {0}). Your data is unchanged.",
  "Die umgestellte Datei ließ sich nicht schreiben. Bitte noch einmal öffnen.": "The converted file could not be written. Please open it again.",
  "Die Sicherung vor der Umstellung ließ sich nicht schreiben. Ihre Daten sind unverändert.": "The backup before the conversion could not be written. Your data is unchanged.",
  "Aufräumen der Datenbank:": "Database cleanup:",
  "-{0}.tresor": "-{0}.tresor",
  "Sicherung vor dem Eingriff:": "Backup before the intervention:",
  "kontovia-{0}.tresor": "kontovia-{0}.tresor",
  "Sicherung fehlgeschlagen:": "Backup failed:",
  "Diese Sicherung liegt nicht mehr auf diesem Gerät.": "This backup is no longer on this device.",
  "Diese Sicherung gehört zu einer anderen Buchhaltung (etwa vor einem „Cloud-Stand übernehmen“) und lässt sich hier nicht zurückholen.": "This backup belongs to a different accounting (for example before a “Take over cloud version”) and cannot be restored here.",
  "Kein Dateiinhalt übergeben.": "No file content provided.",
  "Die Datei ist leer.": "The file is empty.",
  "Die Datei ist zu groß (max. {0} MB).": "The file is too large (max. {0} MB).",
  "Der Beleg liegt auf diesem Gerät nicht vor. Ein Cloud-Abgleich holt ihn nach.": "The receipt is not available on this device. A cloud sync will fetch it.",
  "Aufräumen nach dem Umzug:": "Cleanup after the move:",
  "Die Tresordatei verweist auf den Speicher des Browsers und lässt sich so nicht verschieben.": "The vault file refers to the browser's storage and cannot be moved like this.",
  "Die Datei ist keine Kontovia-Vollsicherung.": "The file is not a Kontovia full backup.",
  "bestand-{0}-{1}.db": "bestand-{0}-{1}.db",
  "Der Update-Server hat keine gültige Versionsdatei geliefert.": "The update server did not deliver a valid version file.",
  "Die Versionsdatei enthält keine gültige Download-Adresse.": "The version file contains no valid download address.",
  "Die Versionsdatei enthält keine gültige Prüfsumme. Das Update wurde abgebrochen.": "The version file contains no valid checksum. The update was aborted.",
  "Kontovia-Setup.exe": "Kontovia-Setup.exe",
  "Für die Anmeldung per Weiterleitung ist kein Client hinterlegt.": "No client is set for sign-in via redirect.",
  "openid email profile": "openid email profile",
  "Die Antwort von Google passte nicht zur Anfrage. Bitte erneut anmelden.": "Google's answer did not match the request. Please sign in again.",
  "Die Anmeldung wurde bei Google abgebrochen.": "The sign-in was cancelled at Google.",
  "Die Anmeldung ließ sich nicht bestätigen. Bitte erneut anmelden.": "The sign-in could not be confirmed. Please sign in again.",
};
