/** Wörterbuch Englisch, Teil t19. Quellen: app.js, lib/assistentwerkzeuge.js, views/calendar.js, views/help.js, views/kontoimport.js, views/mahneinstellungen.js, views/master.js, views/rechnungen.js, views/rechnungseditor.js, views/rechnungsgestalter.js, views/settings.js, views/todos.js, views/transactions.js. */

export default {
  "zu kurz (mind. 10 Zeichen)": "too short (min. 10 characters)",
  "z. B. Musterbau GmbH oder Ihr Name": "e.g. Musterbau GmbH or your name",
  "z. B. \"gestern\"": "e.g. \"yesterday\"",
  "z. B. \"morgen\"": "e.g. \"tomorrow\"",
  "z. B. \"Montag\"": "e.g. \"Monday\"",
  "z. B. Steuerberater-Termin, Montage Kunde Meier": "e.g. tax advisor appointment, installation customer Meier",
  "eine Datei, die Ihre Steuerkanzlei direkt einliest.": "a file that your tax firm reads directly.",
  "ist eine Marke von The Document Foundation.": "is a trademark of The Document Foundation.",
  "z. B. Software-Abos": "e.g. software subscriptions",
  "z. B. Adobe": "e.g. Adobe",
  "z. B. 12,5": "e.g. 12.5",
  "z. Hd., Abteilung": "c/o, department",
  "z. B. Beratung": "e.g. consulting",
  "z. B. Beratung, Material, Wartung": "e.g. consulting, material, maintenance",
  "z. B. Monatliche Wartung": "e.g. monthly maintenance",
  "z. B. Website-Relaunch, Projekt Herbst": "e.g. website relaunch, autumn project",
  "z. Hd. Frau Beispiel": "Attn. Ms Example",
  "z. B. RE-": "e.g. RE-",
  "bis zum 10. des Folgemonats": "by the 10th of the following month",
  "z. B. Seiten, Belege, km": "e.g. pages, receipts, km",
  "z. B. Rechnung 2025-0042, Website-Relaunch": "e.g. invoice 2025-0042, website relaunch",
  "z. B. Schloss Elmau, Garmisch": "e.g. Schloss Elmau, Garmisch",
  "z. B. doppelt erfasst": "e.g. recorded twice",
};
