/** Wörterbuch Englisch, Teil t21. Quellen: app.js, lib/assistentfenster.js, lib/assistentmodelle.js, lib/aufgaben.js, lib/benutzer.js, lib/bewegung.js, lib/datenimport.js, lib/elster.js, lib/emailversand.js, lib/feedback.js, lib/fristen.js, lib/gcalsync.js, lib/girocode.js, lib/grafikhilfe.js, lib/hinweisblase.js, lib/ics.js, lib/kontoauszug.js, lib/mahnwesen.js, lib/pdf.js, lib/period.js, lib/popover.js, lib/rechnung.js, lib/rechnungsdruck.js, lib/seitenleiste.js, lib/store.js, lib/suche.js, lib/table.js, lib/ui.js, lib/util.js, lib/wiederkehrend.js, lib/xlsx.js, views/calendar.js, views/calendarsync.js, views/cloudpanel.js, views/dashboard.js, views/datenimport.js, views/erechnung.js, views/help.js, views/jahresvergleich.js, views/kontoimport.js, views/mahneinstellungen.js, views/mahnwesen.js, views/master.js, views/rechnungen.js, views/rechnungseditor.js, views/rechnungsgestalter.js, views/reports.js, views/settings.js, views/todos.js, views/transactions.js, web/ablage.js, web/aktualisierung.js, web/cloud.js, web/dateien.js, web/firebase.js, web/koppeln.js, web/rueckmeldung.js, web/seed.js, web/sql.js, web/tresor.js. */

export default {
  "{0} J": "{0} J",
  "{0}px": "{0}px",
  "etwa {0}": "about {0}",
  "as-karte as-karte-{0}": "as-karte as-karte-{0}",
  "ton-{0}": "ton-{0}",
  "{0} GB": "{0} GB",
  "{0} MB": "{0} MB",
  "noch {0}{1}": "{0}{1} left",
  "alle {0} {1}": "every {0} {1}",
  "{0} bearbeiten": "Edit {0}",
  "{0}px {1}": "{0}px {1}",
  "datev:{0}": "datev:{0}",
  "tabelle:{0}": "tabelle:{0}",
  "kz{0}": "kz{0}",
  "kontovia-{0}": "kontovia-{0}",
  "{0}x{1}": "{0}x{1}",
  "{0}T12:00:00": "{0}T12:00:00",
  "{0}T00:00:00Z": "{0}T00:00:00Z",
  "EUR{0}": "EUR{0}",
  "{0}://settings/system": "{0}://settings/system",
  "{0}://flags/#ignore-gpu-blocklist": "{0}://flags/#ignore-gpu-blocklist",
  "{0}://flags/#enable-unsafe-webgpu": "{0}://flags/#enable-unsafe-webgpu",
  "{0}://flags/#enable-vulkan": "{0}://flags/#enable-vulkan",
  "{0}://gpu": "{0}://gpu",
  "{0} kopieren": "Copy {0}",
  "{0}@kontovia": "{0}@kontovia",
  "GVC {0}": "GVC {0}",
  "{0} vom {1}": "{0} of {1}",
  "{0} {1} {2} {3} re": "{0} {1} {2} {3} re",
  "Q{0}": "Q{0}",
  "pop {0}": "pop {0}",
  "pos-{0}": "pos-{0}",
  "F{0}": "F{0}",
  "an {0}": "to {0}",
  "{0} bis {1}": "{0} to {1}",
  "vom {0}": "of {0}",
  "IBAN {0}": "IBAN {0}",
  "BIC {0}": "BIC {0}",
  "el:{0}": "el:{0}",
  "zeigen:{0}": "zeigen:{0}",
  "{0} einblenden": "Show {0}",
  "{0}.anlegen": "{0}.anlegen",
  "{0}.aendern": "{0}.aendern",
  "{0}.loeschen": "{0}.loeschen",
  "st{0}": "st{0}",
  "{0} K": "{0} K",
  "dt{0}": "dt{0}",
  "{0} von {1}": "{0} of {1}",
  "feld-{0}": "feld-{0}",
  "{0} B": "{0} B",
  "{0} KB": "{0} KB",
  "{0}T00:00:00.000Z": "{0}T00:00:00.000Z",
  "xl/{0}": "xl/{0}",
  "{0} ausgeblendet: {1}": "{0} hidden: {1}",
  "{0} erledigt": "{0} done",
  "bis {0}": "by {0}",
  "Google: abgeglichen {0}": "Google: synced {0}",
  "{0} .ics importieren": "Import {0} .ics",
  "{0} belegt": "{0} used",
  "verbunden{0}": "connected{0}",
  "{0} {1} offen": "{0} {1} open",
  "{0} ausblenden": "Hide {0}",
  "{0} {1} dabei neu angelegt.": "{0} {1} newly created in the process.",
  "je {0}": "per {0}",
  "datenimport-{0}": "datenimport-{0}",
  "{0} neu{1}": "{0} new{1}",
  "vom {0}{1}": "of {0}{1}",
  "hilfe-{0}": "hilfe-{0}",
  "{0} oder {1}": "{0} or {1}",
  "zu {0}": "to {0}",
  "y{0}": "y{0}",
  "{0} {1} nicht gebucht:": "{0} {1} not booked:",
  "frist{0}": "frist{0}",
  "gebuehr{0}": "gebuehr{0}",
  "{0} am {1}{2}": "{0} on {1}{2}",
  "{0} erstellen": "Create {0}",
  "dem {0}": "the {0}",
  "{0} erstellt": "{0} created",
  "AfA {0}": "Depreciation {0}",
  "{0} ausgestellt": "{0} issued",
  "bezahlt {0}": "paid {0}",
  "{0} {1} per E-Mail senden": "Send {0} {1} by email",
  "{0} {1} korrigieren": "Correct {0} {1}",
  "{0} {1} stornieren": "Reverse {0} {1}",
  "{0} je {1}{2}": "{0} per {1}{2}",
  "{0} mm": "{0} mm",
  "{0} ausstellen": "Issue {0}",
  "{0} {1} ausgestellt": "{0} {1} issued",
  "{0} anzeigen": "Show {0}",
  "e:{0}": "e:{0}",
  "{0} fett": "{0} bold",
  "{0} pt": "{0} pt",
  "guv-{0}": "guv-{0}",
  "{0} ohne Kategorie.": "{0} without a category.",
  "ab {0}": "from {0}",
  "erledigt {0}": "done {0}",
  "von {0}{1}": "of {0}{1}",
  "{0} offen": "{0} open",
  "{0} offen{1}": "{0} open{1}",
  "{0} privat": "{0} private",
  "bezahlt{0}": "paid{0}",
  "am {0}": "on {0}",
  "{0}-k-{1}": "{0}-k-{1}",
  "{0}.beleg": "{0}.beleg",
  "{0}/daten": "{0}/daten",
  "{0}/Kontovia": "{0}/Kontovia",
  "HTTP {0}": "HTTP {0}",
  "kontovia/attachment/{0}": "kontovia/attachment/{0}",
  "{0}.zip": "{0}.zip",
  "{0}/accounts:signInWithIdp?key={1}": "{0}/accounts:signInWithIdp?key={1}",
  "{0}/token?key={1}": "{0}/token?key={1}",
  "tresore/{0}": "tresore/{0}",
  "{0}/{1}/o/{2}{3}": "{0}/{1}/o/{2}{3}",
  "{0}/{1}/o?uploadType=media&name={2}": "{0}/{1}/o?uploadType=media&name={2}",
  "{0}/{1}/o?prefix={2}&maxResults=1000": "{0}/{1}/o?prefix={2}&maxResults=1000",
  "v2:{0}": "v2:{0}",
  "{0}/belege/": "{0}/belege/",
  "{0}/belege/{1}": "{0}/belege/{1}",
  "{0}/koppeln/{1}": "{0}/koppeln/{1}",
  "{0}/koppeln/": "{0}/koppeln/",
  "{0}/{1}/o?prefix={2}&maxResults=200": "{0}/{1}/o?prefix={2}&maxResults=200",
  "{0}/accounts:delete?key={1}": "{0}/accounts:delete?key={1}",
  "{0}#koppeln={1}": "{0}#koppeln={1}",
  "{0}/id": "{0}/id",
  "{0}/anfrage": "{0}/anfrage",
  "{0}/antwort": "{0}/antwort",
  "{0}.anfrage": "{0}.anfrage",
  "{0}.antwort": "{0}.antwort",
  "{0}/{1}/o?prefix={2}&maxResults=1000{3}": "{0}/{1}/o?prefix={2}&maxResults=1000{3}",
  "{0}/{1}/o/{2}?alt=media": "{0}/{1}/o/{2}?alt=media",
  "{0}/{1}/o/{2}": "{0}/{1}/o/{2}",
  "cat_{0}{1}": "cat_{0}{1}",
  "{0}-wal": "{0}-wal",
  "{0}-journal": "{0}-journal",
  "{0}{1}.tresor": "{0}{1}.tresor",
};
