/**
 * Wörterbuch Englisch, von Hand gepflegt: Texte, die scripts/sprache.js im
 * Quelltext nicht als Satz findet (Kürzel, Seitentitel aus dem Bau, zur
 * Laufzeit zusammengesetzte Wendungen). Gefunden beim Durchklicken auf Englisch.
 */

export default {
  "PLZ": "Postcode",
  // Versionshinweise 2.29
  "Kontovia auf Englisch": "Kontovia in English",
  "Neu: Kontovia gibt es jetzt auch auf Englisch. Umschalten unter Einstellungen › Darstellung oder unten auf dem Sperrbildschirm.": "New: Kontovia is now also available in English. Switch under Settings › Display or at the bottom of the lock screen.",
  "Auf Englisch erscheinen Zahlen und Datum in englischer Schreibweise, Berichte als PDF ebenfalls auf Englisch.": "In English, numbers and dates use English notation, and PDF reports are in English too.",
  "Eigene Texte wie Beschreibungen und Namen bleiben, wie Sie sie eingegeben haben. Rechnungen und Rechtstexte bleiben vorerst deutsch.": "Your own texts such as descriptions and names stay as you entered them. Invoices and legal texts remain in German for now.",
  "Kontovia: Buchhaltung im Browser, verschlüsselt und offline": "Kontovia: accounting in the browser, encrypted and offline",
  "Kontovia Buchhaltung": "Kontovia accounting",
  "Kontovia wird gestartet …": "Starting Kontovia …",
  "Einen Moment bitte.": "One moment please.",
  "Buchungen dieser Kategorie ansehen": "View transactions in this category",
  "USt": "VAT",
  "EÜR": "EÜR",
  "GuV": "P&L",
  "OPOS": "Open items",
  "Kz": "Box",
  "{0}. Quartal {1}": "Q{0} {1}",
  "{0}. Quartal": "Q{0}",
  "KW {0}": "wk {0}",
  "KW": "wk",
  // Einzelwörter (Zustände, Rhythmen), die der Leser als Bezeichner ansieht
  "offen": "open",
  "bezahlt": "paid",
  "storniert": "reversed",
  "privat": "private",
  "aktiviert": "capitalized",
  "erstellt": "created",
  "keines": "none",
  "keine": "none",
  "ausgestellt": "issued",
  "entwurf": "draft",
  "bald": "soon",
  "heute": "today",
  "morgen": "tomorrow",
  "gestern": "yesterday",
  "gespeichert": "saved",
  "gespeichert {0}": "saved {0}",
  "vereinnahmt": "collected",
  "vereinnahmt {0} €": "collected {0} €",
  "monatlich": "monthly",
  "täglich": "daily",
  "wöchentlich": "weekly",
  "einmalig": "once",
  "erledigt": "done",
  "fällig": "due",
  "überfällig": "overdue",
  "gesperrt": "locked",
  "verbunden": "connected",
  "getrennt": "disconnected",
  "aktiv": "active",
  "inaktiv": "inactive",
  "ja": "yes",
  "nein": "no",
  "psch.": "flat",
  "Std.": "hrs",
  "Stk.": "pcs.",
  "Pck.": "pk.",
  "bis {0}": "by {0}",
  "empfohlen": "recommended",
  "innergemeinschaftlich": "intra-community",
  "unbefristet": "open-ended",
  "beendet": "ended",
  "sicher": "certain",
  "wahrscheinlich": "likely",
  "unsicher": "uncertain",
  "nichts": "nothing",
  "anderen": "other",
  "sofort": "immediately",
  "degressiv": "declining balance",
  "linear": "straight-line",
  "{0} J.": "{0} yrs",
  "{0} und {1}": "{0} and {1}",
  "{0} oder {1}": "{0} or {1}",
  // Anzahl + Wort klein (die Einträge ohne Zahl sind Überschriften)
  "{0} Buchungen": "{0} transactions",
  "{0} Buchung": "{0} transaction",
  "{0} Termine": "{0} appointments",
  "{0} Termin": "{0} appointment",
  "{0} Aufgaben": "{0} tasks",
  "{0} Rechnungen": "{0} invoices",
  "{0} Rechnung": "{0} invoice",
  "{0} Belege": "{0} receipts",
  "{0} Beleg": "{0} receipt",
  "{0} Kontakte": "{0} contacts",
  "{0} Einträge": "{0} entries",
  "{0} Zeilen": "{0} rows",
  "{0} Dateien": "{0} files",
  "{0} Umsätze": "{0} transactions",
  "{0} Einnahmen offen": "{0} income items open",
  "{0} Einnahme offen": "{0} income item open",
  "{0} Ausgaben offen": "{0} expenses open",
  "{0} Ausgabe offen": "{0} expense open",
};
