/**
 * Wörterbuch Englisch, von Hand gepflegt: Texte, die scripts/sprache.js im
 * Quelltext nicht als Satz findet (Kürzel, Seitentitel aus dem Bau, zur
 * Laufzeit zusammengesetzte Wendungen). Gefunden beim Durchklicken auf Englisch.
 */

export default {
  "PLZ": "Postcode",
  // Gefunden beim Durchklicken (2.30)
  "{0} offene Aufgaben": "{0} open tasks",
  "{0} offene Aufgabe": "{0} open task",
  "nachrichtlich: Vorsteuer-Erstattungsanspruch": "memo: input VAT refund claim",
  "nie": "never",
  "Den darf der Browser bei Platzmangel löschen.": "The browser may delete it if space runs low.",
  ".ics importieren": "Import .ics",
  "als bezahlt": "as paid",
  "Kfz: Leasingkosten": "Car: leasing costs",
  // Beschriftungen mit Doppelpunkt, die der Teiltreffer nur halb übersetzt hat (Durchsicht 2.30.3)
  "Cloud: abgeglichen": "Cloud: synced",
  "Cloud: abgeglichen {0}": "Cloud: synced {0}",
  "Google: verbunden": "Google: connected",
  "Google: abgeglichen": "Google: synced",
  "Google: abgeglichen {0}": "Google: synced {0}",
  "Anleitung: Grafikchip freigeben": "Guide: enable the graphics chip",
  "Nachrichtlich: Privatvorgänge (nicht im Ergebnis enthalten)": "Memo: private items (not included in the result)",
  "Neu: Rechnungen schreiben": "New: writing invoices",
  "Korrektur: Stornos": "Correction: reversals",
  "Korrektur: EÜR-Zeilen": "Correction: EÜR lines",
  "Korrektur: Sonderzeichen": "Correction: special characters",
  "Suchen: Text, Rechnungsnummer, Kontakt …": "Search: text, invoice number, contact …",
  "Suchen: Text, Rechnungsnummer, Betrag …": "Search: text, invoice number, amount …",
  // Versionshinweise 2.30.3
  "Englisch noch sauberer": "English, polished",
  "Auf Englisch sind jetzt auch Stellen übersetzt, die vorher noch deutsch blieben, zum Beispiel in den Einstellungen und bei wiederkehrenden Buchungen.": "More places are now translated into English that used to stay German, for example in the settings and for recurring transactions.",
  "Hinweise zum Abgleich und die Suchfelder lesen sich auf Englisch natürlicher.": "Sync notices and the search fields read more naturally in English.",
  // Versionshinweise 2.30
  "Englisch für Rechnungen und Assistent": "English for invoices and the assistant",
  "Tarifseite: Fehler behoben": "Pricing page: fixes",
  "Der Rahmen um den empfohlenen Tarif läuft wieder flüssig.": "The border around the recommended plan runs smoothly again.",
  "Am Handy überlappen sich keine Inhalte mehr.": "On phones, content no longer overlaps.",
  "Zum Installieren gibt es jetzt Knöpfe für Windows, macOS, Android und iPhone.": "There are now install buttons for Windows, macOS, Android and iPhone.",
  "Tarifseite kürzer und ruhiger":"Shorter, calmer pricing page",
  "Die Seite mit den Tarifen ist kürzer geworden. Die Anmeldung öffnet sich in einem eigenen Fenster.": "The pricing page is shorter now. Sign-up opens in its own window.",
  "Am Handy lässt sich die Seite nicht mehr zur Seite schieben, und Knöpfe bleiben nach dem Antippen nicht mehr eingefärbt.": "On phones the page no longer slides sideways, and buttons no longer stay coloured after a tap.",
  "Die Vorschau der App ist übersichtlicher, Grafiken lassen sich nicht mehr markieren oder verschieben.": "The app preview is clearer, and graphics can no longer be selected or dragged.",
  "Dezente Bewegung beim Scrollen.": "Subtle motion while scrolling.",
  "Neu: Rechnungen, Mahnschreiben und E-Mails lassen sich auf Englisch schreiben. Die Sprache wählen Sie bei jeder Rechnung, für neue Rechnungen unter Rechnungen › Gestaltung.": "New: invoices, dunning letters and emails can be written in English. You choose the language for each invoice, and for new invoices under Invoices › Design.",
  "Der Assistent versteht jetzt auch englische Fragen und antwortet auf Englisch.": "The assistant now also understands English questions and answers in English.",
  "Die Seite mit den Tarifen gibt es auf Englisch, mit Umschalter oben.": "The pricing page is available in English, with a switch at the top.",
  "Auf Englisch steht bei Prozenten und Mengen jetzt überall der Punkt als Dezimalzeichen.": "In English, percentages and quantities now use the point as the decimal mark everywhere.",
  // Dokumente (Rechnung, Mahnschreiben) auf Englisch
  "Bankverbindung": "Bank details",
  "Mahngebühr": "Dunning fee",
  "Sprache der Rechnung": "Invoice language",
  "Sprache neuer Rechnungen": "Language of new invoices",
  "Jede Rechnung lässt sich beim Schreiben ändern.": "You can change each invoice when you write it.",
  "GF": "Managing director",
  // Zeiträume des Assistenten (assistentdeutung.js: zeitraumText)
  "Jahr {0}": "Year {0}",
  "gesamter Bestand": "entire record",
  // Versionshinweise 2.29
  "Kontovia auf Englisch": "Kontovia in English",
  "Neu: Kontovia gibt es jetzt auch auf Englisch. Umschalten unter Einstellungen › Darstellung oder unten auf dem Sperrbildschirm.": "New: Kontovia is now also available in English. Switch under Settings › Display or at the bottom of the lock screen.",
  "Auf Englisch erscheinen Zahlen und Datum in englischer Schreibweise, Berichte als PDF ebenfalls auf Englisch.": "In English, numbers and dates use English notation, and PDF reports are in English too.",
  "Eigene Texte wie Beschreibungen und Namen bleiben, wie Sie sie eingegeben haben. Rechnungen und Rechtstexte bleiben vorerst deutsch.": "Your own texts such as descriptions and names stay as you entered them. Invoices and legal texts remain in German for now.",
  "Kontovia: Buchhaltung im Browser, verschlüsselt und offline": "Kontovia: accounting in the browser, encrypted and offline",
  "Kontovia Buchhaltung": "Kontovia accounting",
  "Kontovia wird gestartet …": "Starting Kontovia …",
  "Einen Moment bitte.": "One moment please.",
  "Buchungen dieser Kategorie ansehen": "View transactions in this category",
  "USt": "VAT",
  "EÜR": "EÜR",
  "GuV": "P&L",
  "OPOS": "Open items",
  "Kz": "Box",
  "{0}. Quartal {1}": "Q{0} {1}",
  "{0}. Quartal": "Q{0}",
  "KW {0}": "wk {0}",
  "KW": "wk",
  // Einzelwörter (Zustände, Rhythmen), die der Leser als Bezeichner ansieht
  "offen": "open",
  "bezahlt": "paid",
  "storniert": "reversed",
  "privat": "private",
  "aktiviert": "capitalized",
  "erstellt": "created",
  "keines": "none",
  "keine": "none",
  "ausgestellt": "issued",
  "entwurf": "draft",
  "bald": "soon",
  "heute": "today",
  "morgen": "tomorrow",
  "gestern": "yesterday",
  "gespeichert": "saved",
  "gespeichert {0}": "saved {0}",
  "vereinnahmt": "collected",
  "vereinnahmt {0} €": "collected {0} €",
  "monatlich": "monthly",
  "täglich": "daily",
  "wöchentlich": "weekly",
  "einmalig": "once",
  "erledigt": "done",
  "fällig": "due",
  "überfällig": "overdue",
  "gesperrt": "locked",
  "verbunden": "connected",
  "getrennt": "disconnected",
  "aktiv": "active",
  "inaktiv": "inactive",
  "ja": "yes",
  "nein": "no",
  "psch.": "flat",
  "Std.": "hrs",
  "Stk.": "pcs.",
  "Pck.": "pk.",
  "bis {0}": "by {0}",
  "empfohlen": "recommended",
  "innergemeinschaftlich": "intra-community",
  "unbefristet": "open-ended",
  "beendet": "ended",
  "sicher": "certain",
  "wahrscheinlich": "likely",
  "unsicher": "uncertain",
  "nichts": "nothing",
  "anderen": "other",
  "sofort": "immediately",
  "degressiv": "declining balance",
  "linear": "straight-line",
  "{0} J.": "{0} yrs",
  "{0} und {1}": "{0} and {1}",
  "{0} oder {1}": "{0} or {1}",
  // Anzahl + Wort klein (die Einträge ohne Zahl sind Überschriften)
  "{0} Buchungen": "{0} transactions",
  "{0} Buchung": "{0} transaction",
  "{0} Termine": "{0} appointments",
  "{0} Termin": "{0} appointment",
  "{0} Aufgaben": "{0} tasks",
  "{0} Rechnungen": "{0} invoices",
  "{0} Rechnung": "{0} invoice",
  "{0} Belege": "{0} receipts",
  "{0} Beleg": "{0} receipt",
  "{0} Kontakte": "{0} contacts",
  "{0} Einträge": "{0} entries",
  "{0} Zeilen": "{0} rows",
  "{0} Dateien": "{0} files",
  "{0} Umsätze": "{0} transactions",
  "{0} Einnahmen offen": "{0} income items open",
  "{0} Einnahme offen": "{0} income item open",
  "{0} Ausgaben offen": "{0} expenses open",
  "{0} Ausgabe offen": "{0} expense open",
  // Ziele: Tageszähler (2.31)
  "Heute geschafft, gemessen am Tagesziel": "Done today, measured against the daily goal",
  "Ziele mit Tageszähler": "Goals with a daily counter",
  "Bei Zielen steht neben dem Balken jetzt der Fortschritt in Prozent.": "Goals now show their progress as a percentage next to the bar.",
  "Neu: „Heute 7 / 20“ zeigt, wie viel vom Tagesziel heute geschafft ist, und zählt beim Eintragen live mit.": "New: “Today 7 / 20” shows how much of the daily goal is done today and counts up live as you enter progress.",
  // Ratenzahlung und wiederkehrende Rechnungen (2.32)
  "(Rate {0}/{1})": "(instalment {0}/{1})",
  "{0} (Rate {1}/{2})": "{0} (instalment {1}/{2})",
  "Zahlbar in {0} Raten zu je {1} €, erste Rate am {2}, letzte Rate am {3}.": "Payable in {0} instalments of {1} € each, first instalment on {2}, last instalment on {3}.",
  "Zahlbar in {0} Raten zu je {1} €, die letzte Rate beträgt {2} €; erste Rate am {3}, letzte Rate am {4}.": "Payable in {0} instalments of {1} € each, the last instalment is {2} €; first instalment on {3}, last instalment on {4}.",
  "halbjährlich": "half-yearly",
  "re_w{0}_": "re_w{0}_",
  "re_w{0}_{1}": "re_w{0}_{1}",
  "Auch Rechnungen lassen sich wiederholen (beim Erstellen unter „Wiederholung“). Fällige Termine legt Kontovia als Rechnungsentwurf an; Sie prüfen ihn und stellen die Rechnung dann selbst aus.": "Invoices can repeat too (under “Repeat” when you create one). When a date is due, Kontovia creates an invoice draft; you check it and issue the invoice yourself.",
  "Zahlung in Raten": "Payment in instalments",
  "Rhythmus der Raten": "Instalment schedule",
  "Raten zu {0} €, die erste am {1}, die letzte am {2}. Jede wird eine eigene Buchung.": "instalments of {0} €, the first on {1}, the last on {2}. Each becomes its own transaction.",
  "{0} Raten zu {1} €, die erste am {2}, die letzte am {3}. Jede wird eine eigene Buchung.": "{0} instalments of {1} €, the first on {2}, the last on {3}. Each becomes its own transaction.",
  "Leer lassen für eine Zahlung auf einmal. Mit Raten wird jede Rate eine eigene Buchung mit eigener Fälligkeit.": "Leave empty to pay in one go. With instalments, each one becomes its own transaction with its own due date.",
  "Rechnung wiederholen": "Repeat invoice",
  "Oder nach so vielen Rechnungen (freiwillig)": "Or after this many invoices (optional)",
  "Diese Rechnung zählt mit.": "This invoice counts.",
  "Beim Ausstellen merkt sich Kontovia die Rechnung als Vorlage. Ist der nächste Termin erreicht, legt es einen Entwurf an, den Sie prüfen und selbst ausstellen. Nichts wird von allein verschickt.": "When you issue it, Kontovia remembers the invoice as a template. When the next date arrives, it creates a draft that you check and issue yourself. Nothing is sent automatically.",
  "{0} Wiederholung": "{0} Repeat",
  "für gleichbleibende Rechnungen, etwa Wartung oder Miete": "for invoices that stay the same, such as maintenance or rent",
  "Diese Rechnung gehört zu einer wiederkehrenden Rechnung ({0}). Den Turnus ändern Sie unter Stammdaten → Wiederkehrend.": "This invoice belongs to a recurring invoice ({0}). You change the schedule under Master data → Recurring.",
  "(je Rate eine Buchung{0})": "(one transaction per instalment{0})",
  "und Steuersatz": "and tax rate",
  "gilt für die erste Rate; leer lassen, wenn sie noch aussteht": "applies to the first instalment; leave empty if it is still open",
  "Oder nach so vielen Buchungen (freiwillig)": "Or after this many transactions (optional)",
  "Diese Buchung zählt mit.": "This transaction counts.",
  "Ratenzahlung": "Payment in instalments",
  "Das ist Rate {0} von {1}. Jede Rate hat ihre eigene Fälligkeit und wird einzeln als bezahlt eingetragen.": "This is instalment {0} of {1}. Each instalment has its own due date and is marked as paid on its own.",
  "In Raten aufteilen": "Split into instalments",
  "Für Anschaffungen auf Raten oder Rechnungen mit Zahlungsplan: Jede Rate wird eine eigene Buchung mit eigener Fälligkeit.": "For purchases on instalments or invoices with a payment plan: each instalment becomes its own transaction with its own due date.",
  "Die erste Rate ist zum Fälligkeitsdatum fällig, sonst zum Datum der Buchung.": "The first instalment is due on the due date, otherwise on the transaction date.",
  "Raten zu {0} €, die erste am {1}, die letzte am {2}.": "instalments of {0} €, the first on {1}, the last on {2}.",
  "{0} Raten zu {1} €, die erste am {2}, die letzte am {3}.": "{0} instalments of {1} €, the first on {2}, the last on {3}.",
  "Raten und Wiederholen lassen sich nicht verbinden. Wählen Sie eines davon.": "Instalments and repeating cannot be combined. Choose one of them.",
  "Eine bezahlte Buchung lässt sich nicht in Raten aufteilen. Nehmen Sie das Häkchen „bezahlt“ heraus; jede Rate tragen Sie einzeln ein.": "A paid transaction cannot be split into instalments. Untick “paid”; you enter each instalment's payment on its own.",
  "Eine Buchung mit Anlagegut lässt sich nicht in Raten aufteilen.": "A transaction linked to an asset cannot be split into instalments.",
  "Eine Anzahlung lässt sich nicht in Raten aufteilen.": "A deposit cannot be split into instalments.",
  "Rechnungsentwurf": "Invoice draft",
  "Eine Wiederholung ist": "One repeat is",
  "Wiederholungen sind": "repeats are",
  "{0} Wiederholungen sind": "{0} repeats are",
  "Angelegt wird, was angehakt ist. Jede ist eine eigene Buchung, die Sie danach wie jede andere ändern oder stornieren können. Ohne Häkchen lässt Kontovia eine Buchung für diesen Termin aus und bietet sie nicht noch einmal an. Belege hängen Sie an die einzelne Buchung an.{0}": "Whatever is ticked gets created. Each one is its own transaction that you can change or cancel afterwards like any other. Without a tick, Kontovia skips the transaction for that date and does not offer it again. You attach receipts to each transaction individually.{0}",
  "Eine wiederkehrende Rechnung wird als Entwurf angelegt: Sie prüfen sie unter Rechnungen und stellen sie dann aus.": "A recurring invoice is created as a draft: you check it under Invoices and then issue it.",
  "Eine Wiederholung anlegen": "Create one repeat",
  "Wiederholungen anlegen": "repeats",
  "{0} Wiederholungen anlegen": "Create {0} repeats",
  "Eine Wiederholung angelegt": "One repeat created",
  "Wiederholungen angelegt": "repeats created",
  "{0} Wiederholungen angelegt": "{0} repeats created",
  "Rechnungsentwürfe finden Sie unter Rechnungen.": "You will find invoice drafts under Invoices.",
  "nach {0} Mal": "after {0} times",
  "Beim Erfassen einer Buchung unter „Weitere Angaben → Wiederholen“ einen Turnus wählen, etwa für Miete, Telefon oder Software-Abos. Auch eine Rechnung lässt sich beim Erstellen wiederholen.": "When you enter a transaction, choose a schedule under “More details → Repeat”, for example for rent, phone or software subscriptions. An invoice can repeat too when you create it.",
  "Beim Erfassen unter {0} einen Turnus wählen. Sobald die nächste Buchung fällig ist, bietet Kontovia sie nach dem Entsperren zum Anlegen an. Jede wird eine gewöhnliche Buchung, an die Sie den Beleg hängen. Verwalten können Sie das unter {1}. Möglich sind wöchentlich bis jährlich, ein Enddatum oder eine Anzahl.": "When recording under {0}, choose an interval. As soon as the next transaction is due, Kontovia offers to create it after unlocking. Each becomes an ordinary transaction to which you attach the receipt. You can manage this under {1}. Weekly to yearly is possible, with an end date or a number of times.",
  "{0} Beim Erfassen unter {1} einen Turnus wählen. Sobald die nächste Buchung fällig ist, bietet Kontovia sie nach dem Entsperren zum Anlegen an. Jede wird eine gewöhnliche Buchung, an die Sie den Beleg hängen. Verwalten können Sie das unter {2}. Möglich sind wöchentlich bis jährlich, ein Enddatum oder eine Anzahl.": "{0} When recording under {1}, choose an interval. As soon as the next transaction is due, Kontovia offers to create it after unlocking. Each becomes an ordinary transaction to which you attach the receipt. You can manage this under {2}. Weekly to yearly is possible, with an end date or a number of times.",
  "Im Rechnungsformular unter {0} einen Turnus wählen. Beim Ausstellen merkt sich Kontovia die Rechnung. Zum nächsten Termin legt es einen Entwurf an, den Sie prüfen und selbst ausstellen. Nichts wird von allein verschickt.": "In the invoice form, choose an interval under {0}. When you issue it, Kontovia remembers the invoice. On the next date it creates a draft that you check and issue yourself. Nothing is sent automatically.",
  "{0} Im Rechnungsformular unter {1} einen Turnus wählen. Beim Ausstellen merkt sich Kontovia die Rechnung. Zum nächsten Termin legt es einen Entwurf an, den Sie prüfen und selbst ausstellen. Nichts wird von allein verschickt.": "{0} In the invoice form, choose an interval under {1}. When you issue it, Kontovia remembers the invoice. On the next date it creates a draft that you check and issue yourself. Nothing is sent automatically.",
  "Rechnungen wiederholen:": "Repeat invoices:",
  "Bei einer Rechnung unter {0}, bei einer Buchung unter {1}. Jede Rate wird eine eigene Buchung mit eigener Fälligkeit, die Sie einzeln als bezahlt eintragen. Das Mahnwesen und die offenen Posten behandeln jede Rate für sich.": "For an invoice under {0}, for a transaction under {1}. Each instalment becomes its own transaction with its own due date, which you mark as paid one by one. Reminders and open items treat each instalment separately.",
  "{0} Bei einer Rechnung unter {1}, bei einer Buchung unter {2}. Jede Rate wird eine eigene Buchung mit eigener Fälligkeit, die Sie einzeln als bezahlt eintragen. Das Mahnwesen und die offenen Posten behandeln jede Rate für sich.": "{0} For an invoice under {1}, for a transaction under {2}. Each instalment becomes its own transaction with its own due date, which you mark as paid one by one. Reminders and open items treat each instalment separately.",
  "Ratenzahlung:": "Payment in instalments:",
  "Zahlung → Zahlung in Raten": "Payment → Payment in instalments",
  "Weitere Angaben → In Raten aufteilen": "More details → Split into instalments",
  "Raten und wiederkehrende Rechnungen": "Instalments and recurring invoices",
  "Rechnungen und Buchungen lassen sich in Raten aufteilen. Jede Rate hat ihre eigene Fälligkeit und wird einzeln bezahlt.": "Invoices and transactions can be split into instalments. Each instalment has its own due date and is paid on its own.",
  "Rechnungen können sich wiederholen. Zum nächsten Termin legt Kontovia einen Entwurf an, den Sie prüfen und ausstellen.": "Invoices can repeat. On the next date Kontovia creates a draft that you check and issue.",
  "Wiederholungen gibt es jetzt auch wöchentlich und halbjährlich, mit Enddatum oder nach einer Anzahl.": "Repeats are now also available weekly and half-yearly, with an end date or after a number of times.",
  "Wiederkehrende Rechnung": "Recurring invoice",
  "Oder nach so vielen Malen (freiwillig)": "Or after this many times (optional)",
  "Die erste zählt mit.": "The first one counts.",
  "Nächste Rechnung am": "Next invoice on",
  "Eine Menge bis zu einem Tag, zum Beispiel 20 Seiten in 10 Tagen.": "An amount by a given day, for example 20 pages in 10 days.",
  "Kommt nach dem Abhaken von selbst wieder, etwa jeden Monat.": "Comes back by itself after you tick it off, for example every month.",
  "Die Unteraufgaben sind beim nächsten Mal wieder offen.": "The subtasks are open again next time.",
  "aktiv (fällige Rechnungen werden als Entwurf angeboten)": "active (due invoices are offered as drafts)",
  "Positionen, Kunde und Texte stammen aus der Rechnung, mit der die Wiederholung begann. Änderungen an den Beträgen nehmen Sie im Entwurf vor.": "Items, customer and texts come from the invoice the repeat started with. You change amounts in the draft.",
};
